Added workspacesInstanceCount plugin and spec
aquasecurity/cloudsploit pull request #1001
Opened 2021-11-28 13:35 UTC by m-nouman-suleman

## Task
https://scalock.atlassian.net/browse/SAAS-3111

2021-11-28 13:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1001) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1001) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=1001) it.</sub>

2021-12-21 12:13 UTC, AkhtarAmir requested changes

2021-12-21 12:13 UTC, AkhtarAmir commented on plugins/aws/workspaces/workspacesInstanceCount.js
> +        const RECOMMENDED_THRESHOLD = 50;
We should have a setting for this, default can be 50

2021-12-21 12:13 UTC, AkhtarAmir commented on plugins/aws/workspaces/workspacesInstanceCount.js
> +                                                i.e. ${RECOMMENDED_THRESHOLD} workspaces`);
```suggestion
                helpers.addResult(results, 2, `Workspaces instance count is greater than desired threshold of ${RECOMMENDED_THRESHOLD}`);
```

2021-12-21 12:13 UTC, AkhtarAmir commented on plugins/aws/workspaces/workspacesInstanceCount.js
> +                helpers.addResult(results, 0, 'Workspaces Instance count is within the recommended threshold');
```suggestion
                helpers.addResult(results, 0, 'Workspaces instance count is within desired threshold');
```

2021-12-21 12:13 UTC, AkhtarAmir commented on plugins/aws/workspaces/workspacesInstanceCount.js
> +            if (!listWorkspaces) {
```suggestion
            if (!listWorkspaces || listWorkspaces.err || !listWorkspaces.data) {
```

2021-12-21 12:13 UTC, AkhtarAmir commented on plugins/aws/workspaces/workspacesInstanceCount.js
> +
```suggestion
```

2021-12-21 13:31 UTC, AkhtarAmir requested changes

2021-12-21 13:31 UTC, AkhtarAmir commented on plugins/aws/workspaces/workspacesInstanceCount.js
> +            }
```suggestion
            if (listWorkspaces.err || !listWorkspaces.data) {
                helpers.addResult(results, 3,
                    'Unable to list Workspaces: ' + helpers.addError(listWorkspaces), region);
                return rcb();
            }
```

2021-12-24 13:48 UTC, AkhtarAmir requested changes

2021-12-24 13:48 UTC, AkhtarAmir commented on plugins/aws/workspaces/workspacesInstanceCount.js
> +        var workspace_instance_limit = settings.workspace_instance_limit || this.settings.workspace_instance_limit.default;
```suggestion
        var workspace_instance_limit = parseInt(settings.workspace_instance_limit || this.settings.workspace_instance_limit.default);
```

2021-12-24 13:48 UTC, AkhtarAmir commented on plugins/aws/workspaces/workspacesInstanceCount.js
> +            default: 50
Can you change the description and default value to be '50' because we always get string from fontend

2021-12-24 13:48 UTC, AkhtarAmir commented on plugins/aws/workspaces/workspacesInstanceCount.js
> +            default: 50
Also regex is missing

2021-12-24 13:48 UTC, AkhtarAmir commented on plugins/aws/workspaces/workspacesInstanceCount.js
> +                    i.e. ${workspace_instance_limit} workspaces`);
```suggestion
                helpers.addResult(results, 2, `Workspaces Instance count is ${instanceCount} of desired threshold ${workspace_instance_limit} workspaces`, 'global');
```

2021-12-24 13:48 UTC, AkhtarAmir commented on plugins/aws/workspaces/workspacesInstanceCount.js
> +                    i.e. ${workspace_instance_limit} workspaces`);
```suggestion
                helpers.addResult(results, 0, `Workspaces Instance count is ${instanceCount} of desired threshold ${workspace_instance_limit} workspaces`, 'global);
```

2021-12-24 13:48 UTC, AkhtarAmir commented on plugins/aws/workspaces/workspacesInstanceCount.js
> +                return callback(null, results, source);
```suggestion
                return rcb();
```

2021-12-28 09:07 UTC, AkhtarAmir commented on plugins/aws/workspaces/workspacesInstanceCount.js
> +            instanceCount += listWorkspaces.data.length;
```suggestion
            if (!listWorkspaces || listWorkspaces.err || !listWorkspaces.data) {
                helpers.addResult(results, 3,
                    'Unable to list Workspaces: ' + helpers.addError(listWorkspaces), region);
                return rcb();
            }
            
            if (!listWorkspaces.data.length) {
                helpers.addResult(results, 2,
                    'No WorkSpaces instances found', region);
                return rcb();
            }

            instanceCount += listWorkspaces.data.length;
```

2021-12-28 09:08 UTC, AkhtarAmir commented on plugins/aws/workspaces/workspacesInstanceCount.js
> +                    of ${workspace_instance_limit} workspaces.`, 'global');
```suggestion
                helpers.addResult(results, 2, `WorkSpaces Instance count is ${instanceCount} of desired threshold \
                    of ${workspace_instance_limit} workspaces`, 'global');
```

2021-12-28 09:09 UTC, AkhtarAmir commented on plugins/aws/workspaces/workspacesInstanceCount.js
> +                    of ${workspace_instance_limit} workspaces.`, 'global');
```suggestion
                helpers.addResult(results, 0, `WorkSpaces Instance count is ${instanceCount} of ${workspace_instance_limit} desired threshold`, 'global');
```

2021-12-28 09:09 UTC, AkhtarAmir commented on plugins/aws/workspaces/workspacesInstanceCount.js
> +                    of ${workspace_instance_limit} workspaces`, 'global');
```suggestion
                helpers.addResult(results, 2, `WorkSpaces Instance count is ${instanceCount} of ${workspace_instance_limit} desired threshold`, 'global');
```

2021-12-28 09:10 UTC, AkhtarAmir commented on plugins/aws/workspaces/workspacesInstanceCount.spec.js
> +                expect(results[0].message).to.include('Workspaces Instance count is 1 of desired threshold');
```suggestion
                expect(results[0].message).to.include('Workspaces Instance count is 1 of 10 desired threshold');
```

2021-12-28 09:10 UTC, AkhtarAmir commented on plugins/aws/workspaces/workspacesInstanceCount.spec.js
> +                expect(results[0].message).to.include('Workspaces Instance count is 3 of desired threshold');
```suggestion
                expect(results[0].message).to.include('WorkSpaces Instance count is 3 of 2 desired threshold');
```

2021-12-28 09:11 UTC, AkhtarAmir commented on plugins/aws/workspaces/workspacesInstanceCount.spec.js
> +            });
```suggestion
        it('should PASS if no WorkSpaces instances found', function (done) {
            const cache = createCache([]);
            workspacesInstanceCount.run(cache, {}, (err, results) => {
                expect(results.length).to.equal(2);
                expect(results[0].status).to.equal(0);
                done();
            });
```

2021-12-28 09:12 UTC, AkhtarAmir commented on plugins/aws/workspaces/workspacesInstanceCount.js
> +            name: 'Limit for the number of Workspace instances.',
```suggestion
            name: 'Limit for the number of WorkSpaces instances.',
```

2021-12-28 09:12 UTC, AkhtarAmir approved these changes

2021-12-28 09:21 UTC, AkhtarAmir commented on plugins/aws/workspaces/workspacesInstanceCount.js
> +                helpers.addResult(results, 2,
```suggestion
                helpers.addResult(results, 0,
```

2021-12-29 08:12 UTC, dipsubha06 approved these changes

2021-12-29 08:17 UTC, merged