SAAS-3138: Added ElastiCache Desired Node Type Plugin
aquasecurity/cloudsploit pull request #1005
Opened 2021-12-01 13:06 UTC by sadeed12345

2021-12-01 13:43 UTC, AkhtarAmir commented on plugins/aws/elasticache/elasticaheDesiredNodeType.js
> +    recommended_action: 'Enable Desired node type for ElastiCache clusters',
```suggestion
    recommended_action: 'Create ElastiCache clusters with desired node types',
```

2021-12-01 13:46 UTC, AkhtarAmir requested changes

2021-12-01 13:46 UTC, AkhtarAmir commented on plugins/aws/elasticache/elasticaheDesiredNodeType.js
> +        elasticache_desired_node_type: {
Create separate settings for redis and memcached clusters

2021-12-01 13:46 UTC, AkhtarAmir commented on collectors/aws/collector.js
> +    ElastiCache: {
Merge master into this branch

2022-01-26 13:33 UTC, AkhtarAmir commented on plugins/aws/elasticache/elasticaheDesiredNodeType.js
> +                        `cluster has desired node type: ${cluster.CacheNodeType} and engine: ${cluster.Engine} `,
```suggestion
                        `${cluster.Engine} Cluster has desired node type: ${cluster.CacheNodeType}`,
```

2022-01-26 13:33 UTC, AkhtarAmir commented on plugins/aws/elasticache/elasticaheDesiredNodeType.js
> +                        `cluster does not have desired node type: ${cluster.CacheNodeType} and engine: ${cluster.Engine}`,
```suggestion
                        `${cluster.Engine} cluster does not have desired node type: ${cluster.CacheNodeType}`,
```

2022-01-26 13:34 UTC, AkhtarAmir commented on plugins/aws/elasticache/elasticaheDesiredNodeType.js
> +                        `${cluster.Engine} Cluster has desired node type: ${cluster.CacheNodeType}`,
```suggestion
                        `${cluster.Engine} cluster has desired node type: ${cluster.CacheNodeType}`,
```

2022-01-26 13:39 UTC, AkhtarAmir approved these changes

2022-01-27 09:26 UTC, dipsubha06 commented on plugins/aws/elasticache/elasticaheDesiredNodeType.js
> +                if (!cluster.ARN) continue;
```suggestion
                if (!cluster.ARN || !cluster.Engine) continue;
```

2022-01-27 09:27 UTC, merged