SAAS-3133: Added MSK Encryption In Transit Plugin
aquasecurity/cloudsploit pull request #1006
Opened 2021-12-01 14:52 UTC by sadeed12345

2022-01-25 17:09 UTC, AkhtarAmir requested changes

2022-01-25 17:09 UTC, AkhtarAmir commented on plugins/aws/msk/mskClusterEncryptionInTransit.js
> +                if (cluster.EncryptionInfo &&
Let's discuss this tomorrow

2022-03-22 13:29 UTC, sadeed12345 commented on plugins/aws/msk/mskClusterEncryptionInTransit.js
> +    domain: 'Compute',
```suggestion
    domain: 'Compute',
    severity: 'Medium',
```

2022-03-31 11:10 UTC, AkhtarAmir requested changes

2022-03-31 11:10 UTC, AkhtarAmir commented on plugins/aws/msk/mskClusterEncryptionInTransit.js
> +    description: 'Ensure that your Amazon MSK clusters have encryption in-transit enabled.',
```suggestion
    description: 'Ensure that TLS encryption within the cluster feature is enabled for your Amazon MSK clusters.',
```

2022-03-31 11:10 UTC, AkhtarAmir commented on plugins/aws/msk/mskClusterEncryptionInTransit.js
> +    more_info: 'Amazon MSK in-transit encryption is an optional feature, it encrypts data in transit between the brokers of your MSK cluster. You can override this default at the time you create the
```suggestion
    more_info: 'Amazon MSK in-transit encryption is an optional feature which encrypts data in transit within your MSK cluster. You can override this default at the time you create the cluster.',
```

2022-03-31 11:10 UTC, AkhtarAmir commented on plugins/aws/msk/mskClusterEncryptionInTransit.js
> +    recommended_action: 'Enable in-transit encryption for MSK clusters',
```suggestion
    recommended_action: 'Enable TLS encryption within the cluster for all MSK clusters',
```

2022-03-31 11:10 UTC, AkhtarAmir commented on plugins/aws/msk/mskClusterEncryptionInTransit.js
> +                        'Cluster does not have in-transit encryption enabled', region, resource);
```suggestion
                        'TLS encryption within the cluster is not enabled', region, resource);
```

2022-03-31 11:10 UTC, AkhtarAmir commented on plugins/aws/msk/mskClusterEncryptionInTransit.js
> +                        'Cluster has in-transit encryption enabled', region, resource);
```suggestion
                        'TLS encryption within the cluster is enabled', region, resource);
```

2022-03-31 11:51 UTC, AkhtarAmir approved these changes

2022-03-31 11:51 UTC, merged