Added docdbClusterBackupRetention plugin and spec
aquasecurity/cloudsploit pull request #1010
Opened 2021-12-02 22:54 UTC by m-nouman-suleman

## Task
- https://scalock.atlassian.net/browse/SAAS-3181

2021-12-02 22:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1010) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1010) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=1010) it.</sub>

2021-12-21 12:01 UTC, AkhtarAmir requested changes

2021-12-21 12:01 UTC, AkhtarAmir commented on plugins/aws/documentDB/docdbClusterBackupRetention.js
> +        var RECOMMENDED_THRESHOLD = 7;
We should add a setting for this. Default can be 7. Regex should only allow 1-35

2021-12-24 13:18 UTC, AkhtarAmir approved these changes

2021-12-24 13:20 UTC, AkhtarAmir commented on plugins/aws/documentDB/docdbClusterBackupRetention.js
> +                sufficient backup retention period configured in order to restore your data in the event of failure.`,
```suggestion
    more_info: 'DocumentDB cluster provides feature to retain incremental backups between 1 and 35 allowing you to quickly restore to any point within the backup retention period. Ensure that you have sufficient backup retention period configured in order to restore your data in the event of failure.',
```

2021-12-24 13:21 UTC, AkhtarAmir commented on plugins/aws/documentDB/docdbClusterBackupRetention.js
> +        var doc_db_backup_retention_threshold = settings.doc_db_backup_retention_threshold || this.settings.doc_db_backup_retention_threshold.default;
```suggestion
        var doc_db_backup_retention_threshold = parseInt(settings.doc_db_backup_retention_threshold || this.settings.doc_db_backup_retention_threshold.default); 
```

2021-12-24 13:22 UTC, AkhtarAmir commented on plugins/aws/documentDB/docdbClusterBackupRetention.js
> +            name: 'Threshold for DocDB Cluster backup retention.',
```suggestion
            name: 'DocDB Cluster Backup Retention Threshold',
```

2021-12-24 13:26 UTC, AkhtarAmir commented on plugins/aws/documentDB/docdbClusterBackupRetention.js
> +                        which is greater than or equal to the recommended period of ${doc_db_backup_retention_threshold} days`,
```suggestion
                        `DocumentDB cluster has a backup retention period of ${cluster.BackupRetentionPeriod} of ${doc_db_backup_retention_threshold} days limit`,
```

2021-12-24 13:26 UTC, AkhtarAmir commented on plugins/aws/documentDB/docdbClusterBackupRetention.js
> +                        which is less than the recommended period of ${doc_db_backup_retention_threshold} days`,
```suggestion
                        `DocumentDB cluster has a backup retention period of ${cluster.BackupRetentionPeriod} of ${doc_db_backup_retention_threshold} days limit`,
```

2021-12-24 13:28 UTC, AkhtarAmir approved these changes

2021-12-24 13:29 UTC, AkhtarAmir commented on plugins/aws/documentDB/docdbClusterBackupRetention.spec.js
> +                expect(results[0].message).to.include('DocumentDB cluster has a backup retention period of 1 days');
```suggestion
                expect(results[0].message).to.include('DocumentDB cluster has a backup retention period of 1');
```

2021-12-24 13:29 UTC, AkhtarAmir commented on plugins/aws/documentDB/docdbClusterBackupRetention.spec.js
> +                expect(results[0].message).to.include('DocumentDB cluster has a backup retention period of 10 days');
```suggestion
                expect(results[0].message).to.include('DocumentDB cluster has a backup retention period of 10');
```

2021-12-24 13:30 UTC, AkhtarAmir approved these changes

2021-12-27 09:47 UTC, dipsubha06 commented on plugins/aws/documentDB/docdbClusterBackupRetention.js
> +            description: 'Plugin results will become aggregated once this value is breached',
```suggestion
            description: 'Desired number of days for DocumentDB cluster backup retention period.',
```

2021-12-27 09:48 UTC, dipsubha06 commented on plugins/aws/documentDB/docdbClusterBackupRetention.js
> +                if (cluster.BackupRetentionPeriod && cluster.BackupRetentionPeriod > doc_db_backup_retention_threshold) {
```suggestion
                if (cluster.BackupRetentionPeriod && cluster.BackupRetentionPeriod >=  doc_db_backup_retention_threshold) {
```

2021-12-27 09:50 UTC, dipsubha06 commented on plugins/aws/documentDB/docdbClusterBackupRetention.js
> +            name: 'DocDB Cluster Backup Retention Threshold',
```suggestion
            name: 'DocDB Cluster Minimum Backup Retention Period',
```

2021-12-27 09:52 UTC, dipsubha06 commented on plugins/aws/documentDB/docdbClusterBackupRetention.spec.js
> +            const cache = createCache(null, null, null, { message: "Unable to list DocumentDB Clusters encryption" });
```suggestion
            const cache = createCache(null,  { message: "Unable to list DocumentDB Clusters encryption" });
```

2021-12-27 09:52 UTC, dipsubha06 approved these changes

2021-12-27 09:53 UTC, merged