SAAS-2975: Added EMR Desired Instance Type Plugin
aquasecurity/cloudsploit pull request #1011
Opened 2021-12-03 13:35 UTC by sadeed12345

2021-12-03 14:11 UTC, sadeed12345 commented on plugins/aws/emr/emrDesiredInstanceType.js
> +                    // console.log(JSON.stringify(listInstanceGroups, null, 2));
```suggestion
```

2021-12-03 14:12 UTC, sadeed12345 commented on plugins/aws/emr/emrDesiredInstanceType.js
> +                // console.log(JSON.stringify(cache.emr, null ,2));
```suggestion
```

2021-12-03 14:12 UTC, sadeed12345 commented on plugins/aws/emr/emrDesiredInstanceType.js
> +        // console.log(JSON.stringify(cache, null, 2));
```suggestion
```

2022-01-25 17:11 UTC, AkhtarAmir requested changes

2022-01-25 17:11 UTC, AkhtarAmir commented on collectors/aws/collector.js
> +                    'RUNNING','TERMINATED_WITH_ERRORS', 'STARTING','TERMINATING'
Let's discuss about this tomorrow

2022-01-26 14:17 UTC, sadeed12345 commented on collectors/aws/collector.js
> +                    'RUNNING','TERMINATED_WITH_ERRORS', 'STARTING','TERMINATING'
```suggestion
                    'RUNNING'
```

2022-01-26 15:21 UTC, AkhtarAmir approved these changes

2022-01-27 09:34 UTC, dipsubha06 commented on plugins/aws/emr/emrDesiredInstanceType.js
> +    description: 'Ensure AWS Elastic MapReduce (EMR) clusters have the desired instance enabled.',
```suggestion
    description: 'Ensure AWS Elastic MapReduce (EMR) clusters are using desired instance type.
```

2022-01-27 09:40 UTC, dipsubha06 approved these changes

2022-01-27 09:40 UTC, merged