Added environmentPersistentLogs plugin and spec
aquasecurity/cloudsploit pull request #1015
Opened 2021-12-04 22:53 UTC by m-nouman-suleman

## Task
- https://scalock.atlassian.net/browse/SAAS-3114

2021-12-04 22:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1015) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1015) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=1015) it.</sub>

2021-12-21 11:57 UTC, AkhtarAmir requested changes

2021-12-21 11:57 UTC, AkhtarAmir commented on plugins/aws/elasticbeanstalk/environmentAccessLogs.js
> +                    helpers.addResult(results, 2, 'No environment configuration settings found', region, resource);
```suggestion
                    helpers.addResult(results, 2, 'Environment does not have any log configuration', region, resource);
```

2021-12-21 11:57 UTC, AkhtarAmir commented on plugins/aws/elasticbeanstalk/environmentAccessLogs.js
> +                        'Unable to query for environment configuration settings',
```suggestion
                        'Unable to query for environment configuration settings: ' + helpers.addError(describeConfigurationSettings),
```

2021-12-21 11:57 UTC, AkhtarAmir commented on plugins/aws/elasticbeanstalk/environmentAccessLogs.js
> +                    'Unable to query for application environments', region);
```suggestion
                    'Unable to query for application environments: ' + helpers.addError(describeEnvironments), region);
```

2021-12-24 13:10 UTC, AkhtarAmir commented on plugins/aws/elasticbeanstalk/environmentAccessLogs.js
> +                patterns and troubleshoot issues.`,
```suggestion
    more_info: 'Elastic Load Balancing provides access logs that capture detailed information about requests sent to your load balancer. Each log contains information such as the time the request was received, the client's IP address, latencies, request paths, and server responses. You can use these access logs to analyze traffic patterns and troubleshoot issues.',
```

2021-12-24 13:11 UTC, AkhtarAmir commented on plugins/aws/elasticbeanstalk/environmentAccessLogs.js
> +    more_info: 'Elastic Load Balancing provides access logs that capture detailed information about requests sent to your load balancer. Each log contains information such as the time the request was
```suggestion
    more_info: 'Elastic Load Balancing provides access logs that capture detailed information about requests sent to your load balancer. Each log contains information such as the time the request was received, the client\'s IP address, latencies, request paths, and server responses. You can use these access logs to analyze traffic patterns and troubleshoot issues.',
```

2021-12-24 13:12 UTC, AkhtarAmir commented on plugins/aws/elasticbeanstalk/environmentAccessLogs.js
> +                    'No application environments found', region);
```suggestion
                    'No ElasticBeanstalk applications found', region);
```

2021-12-24 13:12 UTC, AkhtarAmir commented on plugins/aws/elasticbeanstalk/environmentAccessLogs.js
> +                    'Unable to query for application environments: ' + helpers.addError(describeEnvironments), region);
```suggestion
                    'Unable to query for ElasticBeanstalk environments: ' + helpers.addError(describeEnvironments), region);
```

2021-12-24 13:12 UTC, AkhtarAmir commented on plugins/aws/elasticbeanstalk/environmentAccessLogs.js
> +
```suggestion
```

2021-12-24 13:13 UTC, AkhtarAmir commented on plugins/aws/elasticbeanstalk/environmentAccessLogs.js
> +                    'No ElasticBeanstalk applications found', region);
```suggestion
                    'No ElasticBeanstalk environments found', region);
```

2021-12-24 13:14 UTC, AkhtarAmir commented on plugins/aws/elasticbeanstalk/environmentAccessLogs.js
> +                        'Environment Access Logs for environment: ' + environment.EnvironmentName + ' are enabled',
```suggestion
                        'Access Logs for environment: ' + environment.EnvironmentName + ' are enabled',
```

2021-12-24 13:14 UTC, AkhtarAmir commented on plugins/aws/elasticbeanstalk/environmentAccessLogs.js
> +                        'Environment Access Logs for environment: ' + environment.EnvironmentName + ' are not enabled',
```suggestion
                        'Access Logs for environment: ' + environment.EnvironmentName + ' are not enabled',
```

2021-12-24 13:15 UTC, AkhtarAmir approved these changes

2021-12-27 10:04 UTC, dipsubha06 approved these changes

2021-12-27 10:04 UTC, merged