Added environmentPersistentLogs plugin and spec
aquasecurity/cloudsploit pull request #1017
Opened 2021-12-05 13:28 UTC by m-nouman-suleman

## Task
- https://scalock.atlassian.net/browse/SAAS-3113

2021-12-05 13:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1017) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1017) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=1017) it.</sub>

2021-12-21 11:51 UTC, AkhtarAmir requested changes

2021-12-21 11:51 UTC, AkhtarAmir commented on plugins/aws/elasticbeanstalk/environmentPersistentLogs.js
> +                        'Unable to query for environment configuration settings',
```suggestion
                        'Unable to query for environment configuration settings: ' + helpers.addError(describeConfigurationSettings),
```

2021-12-21 11:51 UTC, AkhtarAmir commented on plugins/aws/elasticbeanstalk/environmentPersistentLogs.js
> +                    'Unable to query for application environments', region);
```suggestion
                    'Unable to query for application environments: ' + helpers.addError(describeEnvironments), region);
```

2021-12-21 11:51 UTC, AkhtarAmir commented on plugins/aws/elasticbeanstalk/environmentPersistentLogs.js
> +                } else if (persistentLogs[0].Value === 'false' && persistentLogs[1].Value === 'false') {
```suggestion
                } else if (persistentLogs[0].Value === 'false' && persistentLogs[1] && persistentLogs[1].Value === 'false') {
```

2021-12-21 11:51 UTC, AkhtarAmir commented on plugins/aws/elasticbeanstalk/environmentPersistentLogs.js
> +                if (!persistentLogs || persistentLogs.length === 0) {
```suggestion
                if (!persistentLogs || !persistentLogs.length) {
```

2021-12-21 11:57 UTC, AkhtarAmir requested changes

2021-12-21 11:57 UTC, AkhtarAmir commented on plugins/aws/elasticbeanstalk/environmentPersistentLogs.js
> +                    helpers.addResult(results, 2, 'No environment configuration settings found', region, resource);
```suggestion
                    helpers.addResult(results, 2, 'Environment does not have any log configuration', region, resource);
```

2021-12-24 13:04 UTC, AkhtarAmir commented on plugins/aws/elasticbeanstalk/environmentPersistentLogs.js
> +                historical purposes or to track and analyze the EB application environment behavior for a long period of time.`,
```suggestion
    more_info: 'Elastic Beanstalk environement logs should be retained in order to keep the logging data for future audits, historical purposes or to track and analyze the EB application environment behavior for a long period of time.',
```

2021-12-24 13:05 UTC, AkhtarAmir commented on plugins/aws/elasticbeanstalk/environmentPersistentLogs.js
> +                    'Unable to query for application environments: ' + helpers.addError(describeEnvironments), region);
```suggestion
                    'Unable to query for ElasticBeanstalk environments: ' + helpers.addError(describeEnvironments), region);
```

2021-12-24 13:05 UTC, AkhtarAmir commented on plugins/aws/elasticbeanstalk/environmentPersistentLogs.js
> +                    'No application environments found', region);
```suggestion
                    'No ElasticBeanstalk environments found', region);
```

2021-12-24 13:08 UTC, AkhtarAmir approved these changes

2021-12-24 13:09 UTC, AkhtarAmir commented on plugins/aws/elasticbeanstalk/environmentPersistentLogs.js
> +    more_info: 'Elastic Beanstalk environement logs should be retained in order to keep the logging data for future audits, historical purposes or to track and analyze the EB application environment
```suggestion
    more_info: 'Elastic Beanstalk environment logs should be retained in order to keep the logging data for future audits, historical purposes or to track and analyze the EB application environment behavior for a long period of time.',
```

2021-12-27 10:05 UTC, AkhtarAmir requested changes

2021-12-27 10:05 UTC, AkhtarAmir commented on plugins/aws/elasticbeanstalk/environmentPersistentLogs.js
> +            rcb();
```suggestion
                }
                ecb();
            }, function() {
                rcb();
            });
```

2021-12-29 08:16 UTC, dipsubha06 approved these changes

2021-12-29 08:17 UTC, merged