SAAS-3380: Added GuardDuty Export Findings Encrypted Plugin
aquasecurity/cloudsploit pull request #1040
Opened 2021-12-16 17:32 UTC by sadeed12345

2021-12-17 12:51 UTC, sadeed12345 commented on plugins/aws/guardduty/exportedFindingsEncrypted.js
> +            name: 'Location GuardDuty Export Findings Desired Encryption Level',
```suggestion
            name: 'GuardDuty Export Findings Desired Encryption Level',
```

2021-12-22 11:11 UTC, AkhtarAmir commented on collectors/aws/collector.js
> +        },
```suggestion
        }
```

2021-12-22 11:37 UTC, AkhtarAmir requested changes

2021-12-22 11:37 UTC, AkhtarAmir commented on collectors/aws/guardduty/describePublishingDestination.js
> +        });
```suggestion
cb();
```

2021-12-22 11:37 UTC, AkhtarAmir commented on plugins/aws/guardduty/exportedFindingsEncrypted.js
> +    more_info: 'GuardDuty data, such as findings, is encrypted at rest using AWS owned customer master keys (CMK). To successfully configure findings export, you must first give GuardDuty permission
```suggestion
    more_info: 'GuardDuty data, such as findings, is encrypted at rest using AWS owned customer master keys (CMK). Additionally, you can use your use key (CMKs) in order to gain more control over data encryption/decryption process.',
```

2021-12-22 11:37 UTC, AkhtarAmir commented on plugins/aws/guardduty/exportedFindingsEncrypted.js
> +            regex: '^(awscmk|externalcmk|cloudhsm)$',
```suggestion
            regex: '^(awskms|awscmk|externalcmk|cloudhsm)$',
```

2021-12-22 11:37 UTC, AkhtarAmir commented on plugins/aws/guardduty/exportedFindingsEncrypted.js
> +                }
```suggestion
                } else currentEncryptionLevel = 2; //awskms
```

2021-12-22 11:37 UTC, AkhtarAmir commented on plugins/aws/guardduty/exportedFindingsEncrypted.js
> +                        `GuardDuty Export Findings is encrypted with ${currentEncryptionLevelString} \
```suggestion
                        `GuardDuty findings export is configured to use ${currentEncryptionLevelString} \
```

2021-12-22 11:37 UTC, AkhtarAmir commented on plugins/aws/guardduty/exportedFindingsEncrypted.js
> +                        `GuardDuty Export Findings is encrypted with ${currentEncryptionLevelString} \
```suggestion
                        `GuardDuty findings export is configured to use ${currentEncryptionLevelString} \
```

2021-12-22 11:37 UTC, AkhtarAmir commented on plugins/aws/guardduty/exportedFindingsEncrypted.js
> +
Add region loop

2021-12-22 11:37 UTC, AkhtarAmir commented on plugins/aws/guardduty/exportedFindingsEncrypted.js
> +            if (!listPublishingDestinations || listPublishingDestinations.err || !listPublishingDestinations.data) {
```suggestion
            if (!listPublishingDestinations || listPublishingDestinations.err || !listPublishingDestinations.data || !listPublishingDestinations.data.Destinations) {
```

2021-12-22 11:37 UTC, AkhtarAmir commented on plugins/aws/guardduty/exportedFindingsEncrypted.js
> +            if (!listPublishingDestinations.data.Destinations || !listPublishingDestinations.data.Destinations.length) {
```suggestion
            if (!listPublishingDestinations.data.Destinations.length) {
```

2021-12-22 11:37 UTC, AkhtarAmir commented on plugins/aws/guardduty/exportedFindingsEncrypted.js
> +
const resource = 'arn:' + awsOrGov + ':guardduty:' + region + ':' + accountId + ':detector/' + detectorId;

2021-12-22 11:37 UTC, AkhtarAmir commented on plugins/aws/guardduty/exportedFindingsEncrypted.js
> +                    'Unable to query for GuardDuty publishing destination lists: ' + detectorId + ': ' + helpers.addError(listPublishingDestinations), region);
```suggestion
                    'Unable to query for GuardDuty publishing destination lists: ' + helpers.addError(listPublishingDestinations), region, resource);
```

2021-12-22 11:37 UTC, AkhtarAmir commented on plugins/aws/guardduty/exportedFindingsEncrypted.js
> +                    'you need to configure exports for s3 bucket for enabling encryption: '  + helpers.addError(listPublishingDestinations), region);
```suggestion
                    'Guardduty findings export is not configured'), region, resource);
```

2021-12-22 11:37 UTC, AkhtarAmir commented on plugins/aws/guardduty/exportedFindingsEncrypted.js
> +                var resource = `arn:${awsOrGov}:guardduty:${region}:${accountId}:detector/${detectorId}/publishingDestination/${ destination.DestinationId}`;
```suggestion
                let resource = `arn:${awsOrGov}:guardduty:${region}:${accountId}:detector/${detectorId}/publishingDestination/${ destination.DestinationId}`;
```

2021-12-23 10:59 UTC, AkhtarAmir approved these changes

2021-12-23 15:45 UTC, AkhtarAmir commented on plugins/aws/guardduty/exportedFindingsEncrypted.spec.js
> +            const cache = createCache([listDetectors[0]], null, null, null, null, { message: "Unable to list KMS keys" });
```suggestion
            const cache = createCache([listDetectors[0]], null, null, null, null, null, { message: "Unable to list KMS keys" });
```

2021-12-23 15:46 UTC, AkhtarAmir commented on plugins/aws/guardduty/exportedFindingsEncrypted.spec.js
> +            const cache = createCache([listDetectors[0]], {}, describePublishingDestination[0], null, null, { message: 'Unable to query GuardDuty publishing destinations'});
```suggestion
            const cache = createCache([listDetectors[0]], {}, describePublishingDestination[0], null, null, null, null, { message: 'Unable to query GuardDuty publishing destinations'});
```

2021-12-23 15:50 UTC, merged