SAAS-3395: Added Lookout Vision Model Data Encrypted Plugin
aquasecurity/cloudsploit pull request #1043
Opened 2021-12-17 15:18 UTC by sadeed12345

2021-12-21 10:36 UTC, dipsubha06 commented on plugins/aws/lookout/modelDataEncrypted.js
> +                    return cb();
will it be return cb or continue here.

2021-12-21 11:07 UTC, sadeed12345 commented on plugins/aws/lookout/modelDataEncrypted.js
> +                    return cb();
```suggestion
                    continue;
```

2021-12-22 11:11 UTC, AkhtarAmir requested changes

2021-12-22 11:11 UTC, AkhtarAmir commented on collectors/aws/lookoutvision/describeModel.js
> +                collection.lookoutvision.describeModel[AWSConfig.region][model.ModelVersion].data = data;
```suggestion
                collection.lookoutvision.describeModel[AWSConfig.region][model.ModelArn].data = data;
```

2021-12-22 11:11 UTC, AkhtarAmir commented on helpers/aws/functions.js
> +function isRateError(err) {
remove

2021-12-22 11:11 UTC, AkhtarAmir commented on plugins/aws/lookout/modelDataEncrypted.js
> +    description: 'Ensure that LookoutVision model data is encrypted',
```suggestion
    description: 'Ensure that LookoutVision model data is encrypted using desired KMS encryption level',
```

2021-12-22 11:11 UTC, AkhtarAmir commented on plugins/aws/lookout/modelDataEncrypted.js
> +            name: 'LookoutVision Model Data Desired Encryption Level',
```suggestion
            name: 'LookoutVision Data Target Encryption Level',
```

2021-12-22 11:11 UTC, AkhtarAmir commented on plugins/aws/lookout/modelDataEncrypted.js
> +            // console.log(JSON.stringify(cache, null, 2));
```suggestion
```

2021-12-22 11:11 UTC, AkhtarAmir commented on plugins/aws/lookout/modelDataEncrypted.js
> +
```suggestion
```

2021-12-22 11:11 UTC, AkhtarAmir commented on plugins/aws/lookout/modelDataEncrypted.js
> +
Add loop

2021-12-23 09:45 UTC, sadeed12345 commented on collectors/aws/lookoutvision/describeModel.js
> +    }, function(){
```suggestion
            });
            cb();
        });
    }, function(){
```

2021-12-23 10:48 UTC, AkhtarAmir approved these changes

2021-12-23 15:13 UTC, dipsubha06 approved these changes

2021-12-23 15:28 UTC, dipsubha06 commented on helpers/aws/regions_china.js
> +    forecastservice: regions,
```suggestion
```

2021-12-23 15:29 UTC, dipsubha06 commented on helpers/aws/regions_gov.js
> +    forecastservice: regions,
```suggestion
```

2021-12-23 15:32 UTC, merged