Added ssmManagedInstances plugin and spec
aquasecurity/cloudsploit pull request #1045
Opened 2021-12-20 00:39 UTC by m-nouman-suleman

## Task
- https://scalock.atlassian.net/browse/SAAS-3375

2021-12-20 00:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1045) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1045) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=1045) it.</sub>

2021-12-21 09:16 UTC, AkhtarAmir commented on plugins/aws/ssm/ssmManagedInstances.js
> +    description: 'Ensure that all Amazon EC2 instances are managed by AWS Systems Manager (SSM)',
```suggestion
    description: 'Ensure that all Amazon EC2 instances are managed by AWS Systems Manager (SSM).',
```

2021-12-21 09:30 UTC, AkhtarAmir requested changes

2021-12-21 09:30 UTC, AkhtarAmir commented on plugins/aws/ssm/ssmManagedInstances.js
> +    more_info: 'Systems Manager simplifies AWS cloud resource management, shortens the time to detect and resolve operational problems, and makes it easy to operate and manage your instances securely
Rephrase

2021-12-21 09:30 UTC, AkhtarAmir commented on plugins/aws/ssm/ssmManagedInstances.js
> +
```suggestion

```

2021-12-21 09:30 UTC, AkhtarAmir commented on plugins/aws/ssm/ssmManagedInstances.js
> +            }
```suggestion
            }

            if (!describeInstances.data.length) {
                helpers.addResult(results, 0, 'No EC2 instances found', region);
                return rcb();
            }
```

2021-12-21 09:30 UTC, AkhtarAmir commented on plugins/aws/ssm/ssmManagedInstances.js
> +            }
```suggestion

            if (!describeInstanceInformation || describeInstanceInformation.err || !describeInstanceInformation.data) {
                helpers.addResult(results, 3,
                    'Unable to query for SSM instance information: ' + helpers.addError(describeInstanceInformation), region);
                return rcb();
            }
```

2021-12-21 09:30 UTC, AkhtarAmir commented on plugins/aws/ssm/ssmManagedInstances.spec.js
> +                    "Arn": "arn:aws:iam::101363889637:instance-profile/AmazonSSMRoleForInstancesQuickSetup",
```suggestion
                    "Arn": "arn:aws:iam::000011112222:instance-profile/AmazonSSMRoleForInstancesQuickSetup",
```

2021-12-21 09:30 UTC, AkhtarAmir commented on plugins/aws/ssm/ssmManagedInstances.js
> +                const arn = `arn:aws:ec2:${region}:${accountId}:instance/${instanceInfo.InstanceId}`;
Change aws partition

2021-12-24 15:32 UTC, AkhtarAmir requested changes

2021-12-24 15:32 UTC, AkhtarAmir commented on plugins/aws/ssm/ssmManagedInstances.js
> +            for (let instanceInfo of describeInstanceInformation.data) {
Loop ec2 instances instead

2021-12-28 08:44 UTC, AkhtarAmir commented on plugins/aws/ssm/ssmManagedInstances.js
> +            }
```suggestion
            if (!describeInstanceInformation || describeInstanceInformation.err || !describeInstanceInformation.data) {
                helpers.addResult(results, 3,
                    'Unable to query instance information: ' + helpers.addError(describeInstanceInformation), region);
                return rcb();
            }
```

2021-12-28 08:44 UTC, AkhtarAmir commented on plugins/aws/ssm/ssmManagedInstances.spec.js
> +        });
```suggestion
```

2021-12-28 08:49 UTC, AkhtarAmir commented on plugins/aws/ssm/ssmManagedInstances.js
> +                let instanceInfo = describeInstanceInformation.data.find((instanceInfo) => instanceInfo.InstanceId === ec2Instance.InstanceId);
```suggestion
                let instanceInfo = describeInstanceInformation.data.find((instanceInfo) => instanceInfo.InstanceId && instanceInfo.InstanceId === ec2Instance.InstanceId);
```

2021-12-28 08:49 UTC, AkhtarAmir approved these changes

2021-12-29 08:33 UTC, dipsubha06 approved these changes

2021-12-29 08:34 UTC, merged