SAAS-3405: Added Lex Audio Logs Encrypted Plugin
aquasecurity/cloudsploit pull request #1046
Opened 2021-12-21 11:39 UTC by sadeed12345

2021-12-22 10:59 UTC, AkhtarAmir requested changes

2021-12-22 10:59 UTC, AkhtarAmir commented on plugins/aws/lex/lexAudioLogsEncrypted.js
> +    description: 'Ensure that Amazon Lex audio logs are encrypted',
Ensure that Amazon Lex audio logs are encrypted using desired KMS encryption level.

2021-12-22 10:59 UTC, AkhtarAmir commented on plugins/aws/lex/lexAudioLogsEncrypted.js
> +    more_info: 'For audio logs you use default encryption on your S3 bucket or specify an AWS KMS key to encrypt your audio objects. Even if your S3 bucket uses default encryption you can still speci
```suggestion
    more_info: 'For audio logs you use default encryption on your S3 bucket or specify an AWS KMS key to encrypt your audio objects. Even if your S3 bucket uses default encryption you can still specify a different AWS KMS key to encrypt your audio objects for enhanced security.',
```

2021-12-22 10:59 UTC, AkhtarAmir commented on plugins/aws/lex/lexAudioLogsEncrypted.js
> +    recommended_action: 'Create Lex audio logs with customer-manager keys (CMKs) present in your account',
```suggestion
    recommended_action: 'Encrypt Lex audio logs with customer-manager keys (CMKs) present in your account',
```

2021-12-22 10:59 UTC, AkhtarAmir commented on plugins/aws/lex/lexAudioLogsEncrypted.js
> +            name: 'Lex Audio Logs Desired Encryption Level',
```suggestion
            name: 'Lex Audio Logs Target Encryption Level',
```

2021-12-22 10:59 UTC, AkhtarAmir commented on plugins/aws/lex/lexAudioLogsEncrypted.js
> +
```suggestion
```

2021-12-22 10:59 UTC, AkhtarAmir commented on plugins/aws/lex/lexAudioLogsEncrypted.js
> +
Add a loop for all lexv2models regions

2021-12-22 10:59 UTC, AkhtarAmir commented on plugins/aws/lex/lexAudioLogsEncrypted.js
> +                'Unable to query for  Lex bots: ' + helpers.addError(listBots));
Use string interpolation

2021-12-22 10:59 UTC, AkhtarAmir commented on plugins/aws/lex/lexAudioLogsEncrypted.js
> +        async.each(listBots.data, function(bot, cb){
Convert this to for loop

2021-12-22 10:59 UTC, AkhtarAmir commented on plugins/aws/lex/lexAudioLogsEncrypted.js
> +                // console.log(listBotAliases.data);
```suggestion
                ['lexmodelsv2', 'listBotAliases', region, bot.botId]);
```

2021-12-22 10:59 UTC, AkhtarAmir commented on plugins/aws/lex/lexAudioLogsEncrypted.js
> +            if (!listBotAliases || listBotAliases.err || !listBotAliases.data) {
```suggestion
            if (!listBotAliases || listBotAliases.err || !listBotAliases.data || !listBotAliases.data.botAliasSummaries) {
```

2021-12-22 10:59 UTC, AkhtarAmir commented on plugins/aws/lex/lexAudioLogsEncrypted.js
> +            if (!listBotAliases.data.botAliasSummaries || !listBotAliases.data.botAliasSummaries.length) {
```suggestion
            if (!listBotAliases.data.botAliasSummaries.length) {
```

2021-12-22 10:59 UTC, AkhtarAmir commented on plugins/aws/lex/lexAudioLogsEncrypted.js
> +                    'Unable to query for Lex bot aliases descriptions: '  + helpers.addError(listBotAliases), region);
Add PASS result with no bot aliases found

2021-12-22 10:59 UTC, AkhtarAmir commented on plugins/aws/lex/lexAudioLogsEncrypted.js
> +
```suggestion
```

2021-12-22 10:59 UTC, AkhtarAmir commented on plugins/aws/lex/lexAudioLogsEncrypted.js
> +                    // console.log(JSON.stringify(describeBotAlias , null, 2));
```suggestion
```

2021-12-22 10:59 UTC, AkhtarAmir commented on plugins/aws/lex/lexAudioLogsEncrypted.js
> +                        'Unable to get Lex bot aliases description: ' + alias.botAliasId + ': ' + helpers.addError(describeBotAlias), region, resource);
```suggestion
                        'Unable to query Lex bot alias: ' + helpers.addError(describeBotAlias), region, resource);
```

2021-12-22 10:59 UTC, AkhtarAmir commented on plugins/aws/lex/lexAudioLogsEncrypted.js
> +                        'Unable to get Lex conversation log settings: ' + alias.botAliasId + ': ' + helpers.addError(describeBotAlias), region, resource);
Bot alias does not have any audio logs configured

2021-12-22 10:59 UTC, AkhtarAmir commented on plugins/aws/lex/lexAudioLogsEncrypted.js
> +                if (describeBotAlias.data.conversationLogSettings  &&
Add login to loop describeBotAlias.data.conversationLogSettings.audioLogSettings

2021-12-22 10:59 UTC, AkhtarAmir commented on plugins/aws/lex/lexAudioLogsEncrypted.spec.js
> +                            "cloudWatchLogGroupArn": "arn:aws:logs:us-east-1:101363889637:log-group:mine1",
```suggestion
                            "cloudWatchLogGroupArn": "arn:aws:logs:us-east-1:000011112222:log-group:mine1",
```

2021-12-22 12:56 UTC, sadeed12345 commented on plugins/aws/lex/lexAudioLogsEncrypted.js
> +    description: 'Ensure that Amazon Lex audio logs are encrypted using desired KMS encryption leve',
```suggestion
    description: 'Ensure that Amazon Lex audio logs are encrypted using desired KMS encryption level',
```

2021-12-23 09:42 UTC, dipsubha06 commented on collectors/aws/collector.js
> +                        collectors[serviceLower][callKey](LocalAWSConfig, collection, retries, function() {
```suggestion
                        collectors[serviceLower][callKey](LocalAWSConfig, collection, function() {
```

2021-12-23 09:42 UTC, dipsubha06 commented on collectors/aws/collector.js
> +                                collectors[serviceLower][callKey](LocalAWSConfig, collection, retries, function() {
```suggestion
                                collectors[serviceLower][callKey](LocalAWSConfig, collection, function() {
```

2021-12-23 09:45 UTC, dipsubha06 commented on plugins/aws/lex/lexAudioLogsEncrypted.js
> +                helpers.addResult(results, 0, 'No  Lex bots found'),region;
```suggestion
                helpers.addResult(results, 0, 'No  Lex bots found',region);
```

2021-12-23 09:50 UTC, dipsubha06 approved these changes

2021-12-23 10:27 UTC, AkhtarAmir approved these changes

2021-12-23 15:02 UTC, merged