SAAS-3534: Added Firehose Encrypted Spec File
aquasecurity/cloudsploit pull request #1057
Opened 2021-12-27 16:27 UTC by sadeed12345

2021-12-28 09:42 UTC, sadeed12345 commented on plugins/aws/firehose/firehoseEncrypted.spec.js
> +
```suggestion
 
```

2022-01-24 15:49 UTC, AkhtarAmir commented on plugins/aws/firehose/firehoseEncrypted.js
> +                // console.log(JSON.stringify(describeDeliveryStream, null, 2));
```suggestion
```

2022-01-27 10:01 UTC, dipsubha06 commented on plugins/aws/firehose/firehoseEncrypted.spec.js
> +            const cache = createCache(null, null, { message: "Unable to Unable to query Firehose for delivery streams" });
Fix the error message

2022-01-27 10:03 UTC, dipsubha06 requested changes

2022-01-27 10:03 UTC, dipsubha06 commented on plugins/aws/firehose/firehoseEncrypted.spec.js
> +            const cache = createCache([listDeliveryStreams[0]], null, { message: "Unable to Unable to query Firehose for delivery streams" });
what is this test case for, as the above one also having same set of params to createcache? is this for describestreamerr, if so then fix the params order in the createcache call.

2022-01-27 10:03 UTC, AkhtarAmir commented on plugins/aws/firehose/firehoseEncrypted.spec.js
> +            firehoseEncrypted.run(cache, {}, (err, results) => {
```suggestion
        it('should UNKNOWN if unable to query Firehose for delivery streams', function (done) {
            const cache = createCache([listDeliveryStreams[0]], null, null, { message: "Unable to query Firehose for delivery streams" });
            firehoseEncrypted.run(cache, {}, (err, results) => {
```

2022-01-27 10:03 UTC, AkhtarAmir commented on plugins/aws/firehose/firehoseEncrypted.spec.js
> +            const cache = createCache([listDeliveryStreams[0]], null, { message: "Unable to Unable to query Firehose for delivery streams" });
```suggestion
            const cache = createCache([listDeliveryStreams[0]], null, { message: "Unable to query for firehose delivery streams" });
```

2022-04-13 13:16 UTC, merged