SAAS-3533: Added ELBV2 WAF Enabled Plugin
aquasecurity/cloudsploit pull request #1058
Opened 2021-12-28 13:09 UTC by sadeed12345

2022-01-24 15:55 UTC, AkhtarAmir commented on plugins/aws/elbv2/elbv2WafEnabled.js
> +        // console.log(JSON.stringify(cache, null, 2));
```suggestion
```

2022-01-24 15:55 UTC, AkhtarAmir commented on plugins/aws/elbv2/elbv2WafEnabled.js
> +                    // console.log(JSON.stringify(cache.wafregional, null, 2));
```suggestion
```

2022-01-24 15:56 UTC, AkhtarAmir commented on plugins/aws/elbv2/elbv2WafEnabled.js
>                          ['wafregional', 'listResourcesForWebACL', region, webACL.WebACLId]);
```suggestion
                        ['wafregional', 'listResourcesForWebACL', region, webACL.WebACLId]);

```

2022-01-24 15:57 UTC, AkhtarAmir commented on plugins/aws/elbv2/elbv2WafEnabled.spec.js
> +        "LoadBalancerArn": "arn:aws:elasticloadbalancing:us-east-1:101363889637:loadbalancer/app/sad-elb/0c48be96f812e564",
Can you remove account id from this?

2022-01-24 15:58 UTC, AkhtarAmir requested changes

2022-01-25 09:28 UTC, sadeed12345 commented on plugins/aws/elbv2/elbv2WafEnabled.spec.js
> +        "LoadBalancerArn": "arn:aws:elasticloadbalancing:us-east-1:101363889637:loadbalancer/app/sad-elb/0c48be96f812e564",
```suggestion
        "LoadBalancerArn": "arn:aws:elasticloadbalancing:us-east-1:000111222333:loadbalancer/app/sad-elb/0c48be96f812e564",
```

2022-01-26 15:27 UTC, AkhtarAmir approved these changes

2022-01-27 09:43 UTC, merged