SAAS-3542: Added SQS Encryption Enabled Plugin
aquasecurity/cloudsploit pull request #1059
Opened 2021-12-29 12:30 UTC by sadeed12345

2021-12-29 13:49 UTC, sadeed12345 commented on plugins/aws/sqs/sqsEncryptionEnabled.js
> +    description: 'Ensure SQS queues are encrypted with KMS Customer Master Keys (CMKs) instead of AWS managed-keys',
```suggestion
    description: 'Ensure SQS queues are encrypted using keys of desired encryption level',
```

2022-01-24 16:04 UTC, AkhtarAmir requested changes

2022-01-24 16:04 UTC, AkhtarAmir commented on plugins/aws/sqs/sqsEncryptionEnabled.js
> +                // arn:aws:sqs:us-east-1:101363889637:aaaa
```suggestion
```

2022-01-24 16:04 UTC, AkhtarAmir commented on plugins/aws/sqs/sqsEncryptionEnabled.spec.js
> +          "QueueArn": "arn:aws:sqs:us-east-1:101363889637:my-queue1",
Can you modify and remove account ids

2022-01-25 09:30 UTC, sadeed12345 commented on plugins/aws/sqs/sqsEncryptionEnabled.spec.js
> +          "QueueArn": "arn:aws:sqs:us-east-1:101363889637:my-queue1",
```suggestion
          "QueueArn": "arn:aws:sqs:us-east-1:000111222333:my-queue1",
```

2022-01-25 09:32 UTC, sadeed12345 commented on plugins/aws/sqs/sqsEncryptionEnabled.js
> +
```suggestion
```

2022-01-26 15:22 UTC, AkhtarAmir commented on plugins/aws/sqs/sqsEncryptionEnabled.js
> +            name: 'SQS QueuesTarget Encryption Level',
```suggestion
            name: 'SQS Queues Target Encryption Level',
```

2022-01-26 15:24 UTC, AkhtarAmir commented on plugins/aws/sqs/sqsEncryptionEnabled.js
> +
```suggestion
```

2022-01-26 15:25 UTC, AkhtarAmir approved these changes

2022-01-27 10:11 UTC, dipsubha06 commented on plugins/aws/sqs/sqsEncryptionEnabled.spec.js
> +        it('should UNKNOWN if unable to list SQS queues', function (done) {
Is it list queue error what we are checking or describe queue error

2022-01-27 10:12 UTC, dipsubha06 commented on plugins/aws/sqs/sqsEncryptionEnabled.spec.js
> +        it('should UNKNOWN if unable to list KMS keys', function (done) {
is it list keys error or describe keys error we are checking here

2022-01-27 10:12 UTC, dipsubha06 approved these changes

2022-01-31 12:47 UTC, merged