SAAS-3547: Added Kinesis Data Stream Encryption Enabled Plugin
aquasecurity/cloudsploit pull request #1060
Opened 2021-12-29 13:52 UTC by sadeed12345

2021-12-29 14:47 UTC, sadeed12345 commented on plugins/aws/kinesis/kinesisDataStreamsEncrypted.spec.js
> +            "StreamARN": "arn:aws:kinesis:us-east-1:101363889637:stream/mine2",
```suggestion
            "StreamARN": "arn:aws:kinesis:us-east-1:000011112222:stream/mine2",
```

2021-12-29 14:48 UTC, sadeed12345 commented on plugins/aws/kinesis/kinesisDataStreamsEncrypted.spec.js
> +            "KeyId": "arn:aws:kms:us-east-1:101363889637:key/ad013a33-b01d-4d88-ac97-127399c18b3e",
```suggestion
            "KeyId": "arn:aws:kms:us-east-1:000011112222:key/ad013a33-b01d-4d88-ac97-127399c18b3e",
```

2021-12-29 14:48 UTC, sadeed12345 commented on plugins/aws/kinesis/kinesisDataStreamsEncrypted.spec.js
> +            "StreamARN": "arn:aws:kinesis:us-east-1:101363889637:stream/mine3",
```suggestion
            "StreamARN": "arn:aws:kinesis:us-east-1:000011112222:stream/mine3",
```

2021-12-29 14:49 UTC, sadeed12345 commented on plugins/aws/kinesis/kinesisDataStreamsEncrypted.spec.js
> +            "StreamARN": "arn:aws:kinesis:us-east-1:101363889637:stream/mine1",
```suggestion
            "StreamARN": "arn:aws:kinesis:us-east-1:000011112222:stream/mine1",
```

2021-12-29 15:16 UTC, sadeed12345 commented on plugins/aws/kinesis/kinesisDataStreamsEncrypted.js
> +    description: 'Ensures Kinesis Streams are encrypted using keys of desired encryption level',
```suggestion
    description: 'Ensures Kinesis Streams are encrypted using AWS KMS of desired encryption level',
```

2022-01-24 16:53 UTC, AkhtarAmir requested changes

2022-01-24 16:53 UTC, AkhtarAmir commented on plugins/aws/kinesis/kinesisDataStreamsEncrypted.js
> +    description: 'Ensures Kinesis Streams are encrypted using AWS KMS of desired encryption level',
```suggestion
    description: 'Ensures Kinesis Streams are encrypted using AWS KMS key of desired encryption level.',
```

2022-01-24 16:53 UTC, AkhtarAmir commented on plugins/aws/kinesis/kinesisDataStreamsEncrypted.js
> +    more_info: 'Data sent to Kinesis Streams can be encrypted using KMS server-side encryption. Existing streams can be modified to add encryption with minimal overhead.'+
```suggestion
    more_info: 'Data sent to Kinesis Streams can be encrypted using KMS server-side encryption. Existing streams can be modified to add encryption with minimal overhead. '+ 
```

2022-01-24 16:53 UTC, AkhtarAmir commented on plugins/aws/kinesis/kinesisDataStreamsEncrypted.js
> +    recommended_action: 'Enable encryption using desired level for all Kinesis Streams.',
```suggestion
    recommended_action: 'Enable encryption using desired level for all Kinesis streams',
```

2022-01-24 16:53 UTC, AkhtarAmir commented on plugins/aws/kinesis/kinesisDataStreamsEncrypted.js
> +        , 'KMS:listAliases', 'STS:getCallerIdentity'],
```suggestion
    apis: ['Kinesis:listStreams', 'Kinesis:describeStream', 'KMS:listKeys', 'KMS:describeKey',
        'KMS:listAliases', 'STS:getCallerIdentity'],
```

2022-01-24 16:53 UTC, AkhtarAmir commented on plugins/aws/kinesis/kinesisDataStreamsEncrypted.js
> +                    'Unable to query for KMS aliases:' + helpers.addError(listAliases),
```suggestion
                    'Unable to query for KMS aliases: ' + helpers.addError(listAliases),
```

2022-01-24 16:53 UTC, AkhtarAmir commented on plugins/aws/kinesis/kinesisDataStreamsEncrypted.js
> +
```suggestion
```

2022-01-24 16:53 UTC, AkhtarAmir commented on plugins/aws/kinesis/kinesisDataStreamsEncrypted.js
> +                // arn:aws:kinesis:us-west-1:101363889637:stream/aaaa
```suggestion
```

2022-01-24 16:53 UTC, AkhtarAmir commented on plugins/aws/kinesis/kinesisDataStreamsEncrypted.js
> +                if (describeStream.err || !describeStream.data) {
```suggestion
                if (!describeStream || describeStream.err || !describeStream.data || !describeStream.data.StreamDescription) {
```

2022-01-24 16:53 UTC, AkhtarAmir commented on plugins/aws/kinesis/kinesisDataStreamsEncrypted.js
> +                        region);
```suggestion
                        region, resource);
```

2022-01-24 16:53 UTC, AkhtarAmir commented on plugins/aws/kinesis/kinesisDataStreamsEncrypted.js
> +
```suggestion
```

2022-01-24 16:53 UTC, AkhtarAmir commented on plugins/aws/kinesis/kinesisDataStreamsEncrypted.js
> +                } else currentEncryptionLevel = 2; //awskms
They don't have default encryption so we should remove this

2022-01-24 16:53 UTC, AkhtarAmir commented on plugins/aws/kinesis/kinesisDataStreamsEncrypted.js
> +                } else currentEncryptionLevel = 2; //awskms
```suggestion
```

2022-01-24 16:53 UTC, AkhtarAmir commented on plugins/aws/kinesis/kinesisDataStreamsEncrypted.js
> +                if (describeStream.data.StreamDescription.KeyId) {
```suggestion
```

2022-01-25 16:06 UTC, AkhtarAmir approved these changes

2022-01-25 16:06 UTC, AkhtarAmir commented on plugins/aws/kinesis/kinesisDataStreamsEncrypted.js
> +    description: 'Ensures Kinesis Streams are encrypted using AWS KMS key of desired encryption level.',
```suggestion
    description: 'Ensures Kinesis data streams are encrypted using AWS KMS key of desired encryption level.',
```

2022-01-31 12:52 UTC, merged