SAAS-3549: Added Firehose Delivery Stream Encryption Enabled Plugin
aquasecurity/cloudsploit pull request #1061
Opened 2021-12-29 15:20 UTC by sadeed12345

2022-01-25 10:28 UTC, sadeed12345 commented on plugins/aws/firehose/deliveryStreamEncrypted.js
> +    description: 'Ensures Firehose Delivery Stream are encrypted using AWS KMS of desired encryption level',
```suggestion
    description: 'Ensures Firehose Delivery Stream are encrypted using AWS KMS key of desired encryption level',
```

2022-01-25 10:28 UTC, sadeed12345 commented on plugins/aws/firehose/deliveryStreamEncrypted.js
> +    more_info: 'Data sent through Firehose Delivery Streams can be encrypted using KMS server-side encryption. Existing delivery streams can be modified to add encryption with minimal overhead.'+
```suggestion
    more_info: 'Data sent through Firehose delivery streams can be encrypted using KMS server-side encryption. Existing delivery streams can be modified to add encryption with minimal overhead.'+
```

2022-01-25 10:29 UTC, sadeed12345 commented on plugins/aws/firehose/deliveryStreamEncrypted.js
> +                // arn:aws:firehose:us-east-1:101363889637:deliverystream/123
```suggestion
```

2022-01-25 16:03 UTC, AkhtarAmir requested changes

2022-01-25 16:03 UTC, AkhtarAmir commented on plugins/aws/firehose/deliveryStreamEncrypted.js
> +    description: 'Ensures Firehose Delivery Stream are encrypted using AWS KMS key of desired encryption level',
```suggestion
    description: 'Ensures Firehose delivery stream are encrypted using AWS KMS key of desired encryption level.',
```

2022-01-25 16:03 UTC, AkhtarAmir commented on plugins/aws/firehose/deliveryStreamEncrypted.js
> +            name: 'Firehose delivery stream Target Encryption Level',
```suggestion
            name: 'Firehose Delivery Stream Target Encryption Level',
```

2022-01-25 16:03 UTC, AkhtarAmir commented on plugins/aws/firehose/deliveryStreamEncrypted.js
> +    more_info: 'Data sent through Firehose delivery streams can be encrypted using KMS server-side encryption. Existing delivery streams can be modified to add encryption with minimal overhead.'+
```suggestion
    more_info: 'Data sent through Firehose delivery streams can be encrypted using KMS server-side encryption. Existing delivery streams can be modified to add encryption with minimal overhead. '+
```

2022-01-25 16:04 UTC, AkhtarAmir approved these changes

2022-01-31 12:59 UTC, dipsubha06 approved these changes

2022-01-31 18:03 UTC, merged