SAAS-3765: Added SNS Appropriate Subscribers Plugin
aquasecurity/cloudsploit pull request #1089
Opened 2022-01-11 10:02 UTC by sadeed12345

2022-01-11 10:02 UTC, sadeed12345 commented on plugins/aws/sns/snsAppropriateSubscribers.js
> +            default: 'sadeed1999@gmail.com',
```suggestion
            default: '',
```

2022-01-20 10:57 UTC, sadeed12345 commented on plugins/aws/sns/snsAppropriateSubscribers.js
> +
```suggestion
```

2022-01-31 12:20 UTC, AkhtarAmir commented on collectors/aws/collector.js
> +            },
```suggestion
            }
```

2022-01-31 12:22 UTC, AkhtarAmir commented on plugins/aws/sns/snsAppropriateSubscribers.js
> +    description: 'Ensure that all your Amazon SNS subscriptions are inspected for appropriate subscribers',
```suggestion
    description: 'Ensure that Amazon SNS subscriptions are valid and there are no unwanted subscribers.',
```

2022-01-31 12:25 UTC, AkhtarAmir commented on plugins/aws/sns/snsAppropriateSubscribers.js
> +    recommended_action: 'Ensure that no unwanted subscribers are using the subscriptions periodically.',
```suggestion
    recommended_action: 'Check for unwanted SNS subscriptions periodically',
```

2022-01-31 12:35 UTC, AkhtarAmir requested changes

2022-01-31 12:35 UTC, AkhtarAmir commented on plugins/aws/sns/snsAppropriateSubscribers.js
> +
Make this opt-in plugin

2022-01-31 12:35 UTC, AkhtarAmir commented on plugins/aws/sns/snsAppropriateSubscribers.js
> +                if (subscriber.Endpoint == config.sns_unwanted_subscribers_endpoint){
Check if config includes endpoint

2022-01-31 12:35 UTC, AkhtarAmir commented on plugins/aws/sns/snsAppropriateSubscribers.js
> +            description: 'endpoint for SNS subscrptions that are unwanted',
```suggestion
            description: 'Comma-separated list of subscription endpoint i.e. xyz@aquasec.com',
```

2022-01-31 12:35 UTC, AkhtarAmir commented on plugins/aws/sns/snsAppropriateSubscribers.js
> +                        'SNS subscriber is unwanted for topic', region, resource);
```suggestion
                        'SNS subscription is an unwanted subscription', region, resource);
```

2022-01-31 12:35 UTC, AkhtarAmir commented on plugins/aws/sns/snsAppropriateSubscribers.js
> +                        'SNS subscriber is appropriate for topic', region, resource);
```suggestion
                        'SNS subscription is not an unwanted subscription', region, resource);
```

2022-02-02 11:24 UTC, sadeed12345 commented on plugins/aws/sns/snsAppropriateSubscribers.js
> +        console.log(JSON.stringify(cache, null, 2))
```suggestion
```

2022-02-04 11:43 UTC, AkhtarAmir commented on plugins/aws/sns/snsAppropriateSubscribers.js
> +                }
```suggestion
```

2022-02-04 11:45 UTC, AkhtarAmir requested changes

2022-02-04 11:45 UTC, AkhtarAmir commented on plugins/aws/sns/snsAppropriateSubscribers.js
> +                if ((config.sns_unwanted_subscribers_endpoint.toLowerCase()).includes(endpoint)){
```suggestion
                if (subscriber.Endpoint && config.sns_unwanted_subscribers_endpoint.toLowerCase().includes(subscriber.Endpoint.toLowerCase())){
```

2022-02-04 11:45 UTC, AkhtarAmir commented on plugins/aws/sns/snsAppropriateSubscribers.js
> +            default: 'sadeed1999@gmail.com',
```suggestion
            default: '',
```

2022-02-14 10:52 UTC, AkhtarAmir approved these changes

2022-03-18 11:45 UTC, AkhtarAmir commented on plugins/aws/sns/snsValidSubscribers.spec.js
> +            snsValidSubscribers.run(cache, { sns_unwanted_subscribers: 'sadeed1999@gmail.com' }, (err, results) => {
```suggestion
        it('should PASS if SNS subscription is wanted', function (done) {
            const cache = createCache([listSubscriptions[0]]);
            snsValidSubscribers.run(cache, { sns_unwanted_subscribers: 'xyz@aquasec.com' }, (err, results) => {
```

2022-03-18 11:45 UTC, AkhtarAmir commented on plugins/aws/sns/snsValidSubscribers.spec.js
> +        it('should FAIL if SNS subscriber is unwanted for topic', function (done) {
```suggestion
        it('should FAIL if SNS subscription is unwanted', function (done) {
```

2022-03-18 11:46 UTC, AkhtarAmir commented on plugins/aws/sns/snsValidSubscribers.spec.js
> +            snsValidSubscribers.run(cache, { sns_unwanted_subscribers: 'sadeed1999@gmail.com' }, (err, results) => {
```suggestion
            snsValidSubscribers.run(cache, { sns_unwanted_subscribers: 'xyz@aquasec.com' }, (err, results) => {
```

2022-03-18 11:46 UTC, AkhtarAmir commented on plugins/aws/sns/snsValidSubscribers.spec.js
> +            snsValidSubscribers.run(cache, { sns_unwanted_subscribers: 'sadeed1999@gmail.com' }, (err, results) => {
```suggestion
            snsValidSubscribers.run(cache, { sns_unwanted_subscribers: 'xyz@aquasec.com' }, (err, results) => {
```

2022-03-18 11:46 UTC, AkhtarAmir commented on plugins/aws/sns/snsValidSubscribers.spec.js
> +            snsValidSubscribers.run(cache, { sns_unwanted_subscribers: 'sadeed1999@gmail.com' }, (err, results) => {
```suggestion
            snsValidSubscribers.run(cache, { sns_unwanted_subscribers: 'xyz@aquasec.com' }, (err, results) => {
```

2022-03-19 20:24 UTC, AkhtarAmir commented on plugins/aws/sns/snsValidSubscribers.js
> +                        'SNS subscription is not an unwanted subscription', region, resource);
```suggestion
                        'SNS subscription is a wanted subscription', region, resource);
```

2022-03-19 20:24 UTC, AkhtarAmir commented on plugins/aws/sns/snsValidSubscribers.spec.js
> +                expect(results[0].message).to.include('SNS subscription is not an unwanted subscription');
```suggestion
                expect(results[0].message).to.include('SNS subscription is a wanted subscription');
```

2022-03-19 20:27 UTC, AkhtarAmir commented on plugins/aws/sns/snsValidSubscribers.spec.js
> +        "Endpoint": "makhtar.pucit@gmail.com",
```suggestion
        "Endpoint": "xyz@aquasec.com",
```

2022-03-19 20:28 UTC, AkhtarAmir commented on plugins/aws/sns/snsValidSubscribers.spec.js
> +        "Endpoint": "sadeed1999@gmail.com",
```suggestion
        "Endpoint": "xxz@aquasec.com",
```

2022-03-19 20:32 UTC, AkhtarAmir commented on plugins/aws/sns/snsValidSubscribers.spec.js
> +            const cache = createCache([listSubscriptions[0]]);
```suggestion
            const cache = createCache([listSubscriptions[1]]);
```

2022-03-19 20:32 UTC, AkhtarAmir commented on plugins/aws/sns/snsValidSubscribers.spec.js
> +            const cache = createCache([listSubscriptions[1]]);
```suggestion
            const cache = createCache([listSubscriptions[2]]);
```

2022-03-19 20:35 UTC, AkhtarAmir commented on plugins/aws/sns/snsValidSubscribers.js
> +                let resource = subscriber.SubscriptionArn;
```suggestion
            for (let subscriber of listSubscriptions.data) {
                if (!subscriber.SubscriptionArn) continue;

                let resource = subscriber.SubscriptionArn;
```

2022-03-19 20:36 UTC, AkhtarAmir commented on plugins/aws/sns/snsValidSubscribers.spec.js
> +            const cache = createCache([listSubscriptions[2]]);
```suggestion
            const cache = createCache([listSubscriptions[0]]);
```

2022-03-19 20:37 UTC, merged