SAAS-3780: Added Enable Access Logging For App Mesh Virtual Gateways Plugin
aquasecurity/cloudsploit pull request #1090
Opened 2022-01-11 15:34 UTC by sadeed12345

2022-01-11 15:38 UTC, sadeed12345 commented on plugins/aws/appmesh/enableAccessLogging.js
> +                        'Unable to query for AppMesh virtual gateways: ' + helpers.addError(listVirtualGateways),
```suggestion
                        'Unable to query for App Mesh virtual gateways: ' + helpers.addError(listVirtualGateways),
```

2022-01-31 13:06 UTC, AkhtarAmir commented on helpers/aws/regions.js
> +    ],
```suggestion
        'ap-southeast-1', 'ap-southeast-2', 'ap-south-1', 'sa-east-1', 'ap-east-1', 'me-south-1']
```

2022-01-31 13:07 UTC, AkhtarAmir commented on plugins/aws/appmesh/enableAccessLogging.js
> +    title: 'Enable Access Logging for App Mesh Virtual Gateways',
```suggestion
    title: 'App Mesh Virtual Gateway Access Logging',
```

2022-01-31 13:07 UTC, AkhtarAmir commented on plugins/aws/appmesh/enableAccessLogging.js
> +    description: 'Ensure that your Amazon App Mesh virtual gateways have access logging enabled and configured for all.',
```suggestion
    description: 'Ensure that your Amazon App Mesh virtual gateways have access logging enabled.',
```

2022-01-31 13:08 UTC, AkhtarAmir commented on plugins/aws/appmesh/enableAccessLogging.js
> +    more_info: 'The Amazon App Mesh virtual gateways Access Logging feature provide evidence for security audits and investigations, it also lets you keep an eye on application mesh user access and h
```suggestion
    more_info: 'The Amazon App Mesh virtual gateways Access Logging feature provide evidence for security audits and investigations as well as let\'s you keep an eye on application mesh user access and helps you meet compliance regulations. ',
```

2022-01-31 13:09 UTC, AkhtarAmir commented on plugins/aws/appmesh/enableAccessLogging.js
> +    recommended_action: 'Enable the feature, configure the file path to write access logs, within the virtual gateway configuration settings.',
```suggestion
    recommended_action: 'Modify App Mesh virtual gateways to configure access logging feature',
```

2022-01-31 13:10 UTC, AkhtarAmir commented on plugins/aws/appmesh/enableAccessLogging.js
> +
```suggestion
    run: function(cache, settings, callback) {
        var results = [];
        var source = {};
        var region = helpers.regions(settings);
```

2022-01-31 13:11 UTC, AkhtarAmir commented on plugins/aws/appmesh/enableAccessLogging.js
> +                    if (!gateway.arn) continue;
```suggestion
                    if (!gateway.arn || gateway.virtualGatewayName) continue;
```

2022-01-31 13:11 UTC, AkhtarAmir commented on plugins/aws/appmesh/enableAccessLogging.js
> +                            'Unable to query AppMesh virtual gateway description: ' + helpers.addError(describeVirtualGateway), region, resource);
```suggestion
                            'Unable to describe AppMesh virtual gateway: ' + helpers.addError(describeVirtualGateway), region, resource);
```

2022-01-31 13:14 UTC, AkhtarAmir commented on plugins/aws/appmesh/enableAccessLogging.js
> +                        continue;
```suggestion
                    if (describeVirtualGateway.data.virtualGateway &&
                        describeVirtualGateway.data.virtualGateway.spec &&
                        describeVirtualGateway.data.virtualGateway.spec.logging &&
                        describeVirtualGateway.data.virtualGateway.spec.logging.accessLog &&
                        describeVirtualGateway.data.virtualGateway.spec.logging.accessLog.file &&
                        describeVirtualGateway.data.virtualGateway.spec.logging.accessLog.file.path &&
                        describeVirtualGateway.data.virtualGateway.spec.logging.accessLog.file.path.length) {
                        helpers.addResult(results, 0,
                            'App Mesh virtual gateway has access logging enabled',
                            region, resource);
                        continue;         
                    } else {
                        helpers.addResult(results, 2,
                            'App Mesh virtual gateway does not have access logging enabled',
                            region, resource);
                        continue;
```

2022-01-31 13:15 UTC, AkhtarAmir commented on plugins/aws/appmesh/enableAccessLogging.spec.js
> +                expect(results[0].message).to.include('access logging is enabled and configured for Amazon App Mesh virtual gateways');
```suggestion
                expect(results[0].message).to.include('App Mesh virtual gateway has access logging enabled');
```

2022-01-31 13:16 UTC, AkhtarAmir commented on plugins/aws/appmesh/enableAccessLogging.spec.js
> +                expect(results[0].message).to.include('access logging is not enabled for Amazon App Mesh virtual gateways');
```suggestion
                expect(results[0].message).to.include('App Mesh virtual gateway does not have access logging enabled');
```

2022-01-31 13:19 UTC, AkhtarAmir requested changes

2022-01-31 13:19 UTC, AkhtarAmir commented on plugins/aws/appmesh/enableAccessLogging.spec.js
> +
In below tests, order doesn't seem right. Also add check for message

2022-01-31 13:19 UTC, AkhtarAmir commented on plugins/aws/appmesh/enableAccessLogging.js
> +
Change plugin file name to 'appmeshVGAccessLogging'

2022-02-04 11:47 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshVGAccessLogging.js
> +                    'Unable to query for App Meshes: ' + helpers.addError(listMeshes),region);
```suggestion
                    'Unable to query for App Mesh meshes: ' + helpers.addError(listMeshes),region);
```

2022-02-04 11:47 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshVGAccessLogging.js
> +                helpers.addResult(results, 0, 'No App Meshes found', region);
```suggestion
                helpers.addResult(results, 0, 'No App Mesh meshes found', region);
```

2022-02-04 11:47 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshVGAccessLogging.js
> +                            'Unable to describe AppMesh virtual gateway: ' + helpers.addError(describeVirtualGateway), region, resource);
```suggestion
                            'Unable to describe App Mesh virtual gateway: ' + helpers.addError(describeVirtualGateway), region, resource);
```

2022-02-04 11:48 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshVGAccessLogging.js
> +                        'No AppMesh virtual gateways found', region, resource);
```suggestion
                        'No App Mesh virtual gateways found', region, resource);
```

2022-02-04 11:48 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshVGAccessLogging.js
> +                if (!listVirtualGateways.data.virtualGateways ) {
```suggestion
                if (!listVirtualGateways.data.virtualGateways) {
```

2022-02-04 11:48 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshVGAccessLogging.spec.js
> +                expect(results[0].message).to.include('No App Meshes found');
```suggestion
                expect(results[0].message).to.include('No App Mesh meshes found');
```

2022-02-04 11:49 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshVGAccessLogging.spec.js
> +        it('should UNKNOWN if unable to query for App Meshes', function (done) {
```suggestion
        it('should UNKNOWN if unable to query for App Mesh meshes', function (done) {
```

2022-02-04 11:49 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshVGAccessLogging.spec.js
> +                expect(results[0].message).to.include('Unable to query for App Meshes');
```suggestion
                expect(results[0].message).to.include('Unable to query for App Mesh meshes');
```

2022-02-04 11:49 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshVGAccessLogging.spec.js
> +        it('should UNKNOWN if unable to query for AppMesh virtual gateways', function (done) {
```suggestion
        it('should UNKNOWN if unable to query for App Mesh virtual gateways', function (done) {
```

2022-02-04 11:50 UTC, AkhtarAmir approved these changes

2022-02-14 11:00 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshVGAccessLogging.js
> +    more_info: 'The Amazon App Mesh virtual gateways Access Logging feature provide evidence for security audits and investigations as well as let\'s you keep an eye on application mesh user access a
```suggestion
    more_info: 'Amazon App Mesh virtual gateways Access Logging feature provide evidence for security audits and investigations as well as let\'s you keep an eye on application mesh user access and helps you meet compliance regulations. ',
```

2022-02-14 11:04 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshVGAccessLogging.js
> +    recommended_action: 'Modify App Mesh virtual gateways to configure access logging feature',
```suggestion
    recommended_action: 'To enable access logging, modify virtual gateway configuration settings and configure the file path to write access logs to.',
```

2022-02-14 11:05 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshVGAccessLogging.js
> +                if (!mesh.arn) continue;
```suggestion
                if (!mesh.arn || !mesh.meshName) continue;
```

2022-02-14 11:08 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshVGAccessLogging.js
> +                    if (!gateway.arn) continue;
```suggestion
                    if (!gateway.arn || gateway.virtualGatewayName) continue;
```

2022-02-14 11:10 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshVGAccessLogging.spec.js
> +
```suggestion
```

2022-02-14 11:11 UTC, AkhtarAmir approved these changes

2022-03-16 11:08 UTC, AkhtarAmir approved these changes

2022-03-16 11:55 UTC, merged