SAAS-3837: Added AWS Config Delivery Failing Plugin
aquasecurity/cloudsploit pull request #1104
Opened 2022-01-19 11:00 UTC by sadeed12345

2022-01-20 07:34 UTC, m-nouman-suleman commented on plugins/aws/configservice/configDeliveryFailing.js
> +                if (record.lastStatus.toUpperCase()=='SUCCESS') {
```suggestion
                if (record.lastStatus.toUpperCase() === 'SUCCESS') {
```

2022-01-20 07:35 UTC, m-nouman-suleman commented on plugins/aws/configservice/configDeliveryFailing.spec.js
> +                    data: status                },
```suggestion
                    data: status
                },
```

2022-01-20 07:39 UTC, m-nouman-suleman commented on plugins/aws/configservice/configDeliveryFailing.js
> +            rcb();
```suggestion

            rcb();
```

2022-01-20 07:47 UTC, m-nouman-suleman commented on plugins/aws/configservice/configDeliveryFailing.js
> +    link: 'https://docs.aws.amazon.com/config/latest/developerguide/stop-start-recorder.html',
Please make sure this is the right link provided

2022-01-20 07:49 UTC, m-nouman-suleman commented on plugins/aws/configservice/configDeliveryFailing.js
> +        async.each(regions.configservice, function(region, rcb){
```suggestion
        
        async.each(regions.configservice, function(region, rcb){
```

2022-02-03 11:53 UTC, AkhtarAmir commented on plugins/aws/configservice/configDeliveryFailing.js
> +
Add separate check for length

2022-02-03 11:54 UTC, AkhtarAmir commented on plugins/aws/configservice/configDeliveryFailing.js
> +        'Sometimes you lose the ability to audit the configuration changes made within your AWS account this happen when AWS Config is not able to deliver log files to its recipient due to delivery e
```suggestion
```

2022-02-03 11:55 UTC, AkhtarAmir commented on plugins/aws/configservice/configDeliveryFailing.js
> +                        'The AWS Config service succeeded in delivering the last log file to the designated recipient.',
```suggestion
                        'AWS Config service is successfully delivering log files to the designated recipient',
```

2022-02-03 11:56 UTC, AkhtarAmir commented on plugins/aws/configservice/configDeliveryFailing.js
> +                        'The AWS Config service failed to deliver the last log file to the designated recipient.',
```suggestion
                        'AWS Config service is not delivering log files to the designated recipient successfully',
```

2022-02-03 11:57 UTC, AkhtarAmir requested changes

2022-02-03 11:57 UTC, AkhtarAmir commented on plugins/aws/configservice/configDeliveryFailing.js
> +
Add check for length

2022-02-14 14:28 UTC, AkhtarAmir commented on plugins/aws/configservice/configDeliveryFailing.js
> +    recommended_action: 'Enable AWS Config log files to be delivered without any failures to designated S3 bucket, So that user could save logging data for auditing.',
```suggestion
    recommended_action: 'Configure AWS Config log files to be delivered without any failures to designated S3 bucket.',
```

2022-03-19 20:50 UTC, AkhtarAmir approved these changes

2022-03-19 20:51 UTC, merged