SAAS-3847: Added AWS Backup Compliant Lifecycle Configured Plugin
aquasecurity/cloudsploit pull request #1109
Opened 2022-01-21 12:51 UTC by sadeed12345

2022-02-03 12:32 UTC, sadeed12345 commented on plugins/aws/backup/compliantLifecyleConfigured.js
> +                        'there is no lifecycle configuration enabled for the selected Amazon Backup plan', region, resource);
```suggestion
                        'No lifecycle configuration enabled for the selected Amazon Backup plan', region, resource);
```

2022-02-04 11:34 UTC, sadeed12345 commented on plugins/aws/backup/compliantLifecyleConfigured.js
> +    description: 'Ensure that a compliant lifecycle configuration is enabled for your Amazon Backup plans in order to meet compliance requirements when it comes to security and cost optimization.',
```suggestion
    description: 'Ensure that a compliant lifecycle configuration is enabled for your Amazon Backup plans in order to meet compliance requirements when it comes to security and cost optimization. ',
```

2022-02-04 11:36 UTC, sadeed12345 commented on plugins/aws/backup/compliantLifecyleConfigured.spec.js
> +            const cache = createCache([listBackupPlans[0]], null, { message: "Unable to get Backup plan description" });
```suggestion
            const cache = createCache([listBackupPlans[0]], null, null, { message: "Unable to get Backup plan description" });
```

2022-02-04 16:05 UTC, sadeed12345 commented on plugins/aws/backup/compliantLifecyleConfigured.js
> +
```suggestion
```

2022-03-02 12:41 UTC, sadeed12345 commented on plugins/aws/backup/compliantLifecyleConfigured.js
> +                    'Unable to query Backup plans: ' + helpers.addError(listBackupPlans), region);
```suggestion
                    'Unable to list Backup plans: ' + helpers.addError(listBackupPlans), region);
```

2022-03-02 12:42 UTC, sadeed12345 commented on plugins/aws/backup/compliantLifecyleConfigured.spec.js
> +        it('should UNKNOWN if Unable to query Backup plans', function (done) {
```suggestion
        it('should UNKNOWN if Unable to list Backup plans', function (done) {
```

2022-03-02 12:42 UTC, sadeed12345 commented on plugins/aws/backup/compliantLifecyleConfigured.spec.js
> +            const cache = createCache(null, null, { message: "Unable to query Backup plans" });
```suggestion
            const cache = createCache(null, null, { message: "Unable to list Backup plans" });
```

2022-03-02 12:47 UTC, sadeed12345 commented on plugins/aws/backup/compliantLifecyleConfigured.spec.js
> +                expect(results[0].message).to.include('Unable to query Backup plans')
```suggestion
                expect(results[0].message).to.include('Unable to list Backup plans')
```

2022-03-14 13:21 UTC, sadeed12345 commented on plugins/aws/backup/compliantLifecyleConfigured.js
> +    title: 'Backup Vault Encrypted',
```suggestion
    title: 'AWS Backup Compliant Lifecycle Configured',
```

2022-03-16 08:29 UTC, AkhtarAmir commented on plugins/aws/backup/compliantLifecyleConfigured.js
> +        'DeleteAfterDays specifies the number of days after creation that a recovery point is deleted. MoveToColdStorageAfterDays Specifies the number of days after creation that a recovery point is
```suggestion

```

2022-03-16 08:29 UTC, AkhtarAmir commented on plugins/aws/backup/compliantLifecyleConfigured.js
> +    more_info: 'The AWS Backup lifecycle configuration contains an array of Transition objects specifying how long in days before a recovery point transitions to cold storage or is deleted.'+
```suggestion
    more_info: 'The AWS Backup lifecycle configuration contains an array of transition objects specifying how long in days before a recovery point transitions to cold storage or is deleted.'+ 
```

2022-03-16 08:30 UTC, AkhtarAmir commented on plugins/aws/backup/compliantLifecyleConfigured.js
> +    description: 'Ensure that a compliant lifecycle configuration is enabled for your Amazon Backup plans in order to meet compliance requirements when it comes to security and cost optimization. ',
```suggestion
    description: 'Ensure that a compliant lifecycle configuration is enabled for your Amazon Backup plans in order to meet compliance requirements when it comes to security and cost optimization.',
```

2022-03-16 08:30 UTC, AkhtarAmir commented on plugins/aws/backup/compliantLifecyleConfigured.js
> +    recommended_action: 'Enable compliant lifecycle configuration for your Amazon Backup plans in order to meet compliance requirements',
```suggestion
    recommended_action: 'Enable compliant lifecycle configuration for your Amazon Backup plans',
```

2022-03-16 08:33 UTC, AkhtarAmir requested changes

2022-03-16 08:33 UTC, AkhtarAmir commented on plugins/aws/backup/compliantLifecyleConfigured.js
> +                getBackupPlan.data.BackupPlan.Rules[0].Lifecycle &&
What is the length of getBackupPlan.data.BackupPlan.Rules is more than 1?

2022-03-19 20:59 UTC, AkhtarAmir approved these changes

2022-03-19 21:02 UTC, merged