SAAS-4125: Added App Mesh TLS Required Plugin
aquasecurity/cloudsploit pull request #1159
Opened 2022-02-24 16:58 UTC by sadeed12345

2022-02-25 10:34 UTC, sadeed12345 commented on plugins/aws/appmesh/appmeshTLSRequired.js
> +                            `App Mesh vitual gateway listeners ${tlsEnabled ? 'restrict ' : 'does not restrict '} TLS enabled connections`,
```suggestion
                            `App Mesh virtual gateway listeners ${tlsEnabled ? 'restrict ' : 'does not restrict '} TLS enabled connections`,
```

2022-03-04 12:41 UTC, AkhtarAmir requested changes

2022-03-04 12:41 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshTLSRequired.js
> +    more_info: 'In App Mesh, Transport Layer Security (TLS) encrypts communication between the Envoy proxies deployed on compute resources that are represented in App Mesh by mesh endpoints. An objec
Make it more meaningful

2022-03-04 12:41 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshTLSRequired.js
> +                if (!mesh.meshName) continue;
```suggestion
                if (!mesh.meshName || !mesh.arn) continue;
```

2022-03-04 12:41 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshTLSRequired.js
> +                if (!mesh.arn) continue;
```suggestion
```

2022-03-04 12:41 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshTLSRequired.js
> +                            'Unable to App Mesh virtual gateways: ' + helpers.addError(describeVirtualGateway), region, gatewayArn);
```suggestion
                            'Unable to describe App Mesh virtual gateway: ' + helpers.addError(describeVirtualGateway), region, gatewayArn);
```

2022-03-04 12:41 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshTLSRequired.js
> +                    if (!gateway.arn) continue;
```suggestion
                    if (!gateway.virtualGatewayName || !gateway.arn) continue;
```

2022-03-04 12:41 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshTLSRequired.js
> +                        !describeVirtualGateway.data) {
```suggestion
                        !describeVirtualGateway.data || describeVirtualGateway.data.virtualGateway) {
```

2022-03-04 12:41 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshTLSRequired.js
> +                    if (!virtual.spec.listeners.length) {
```suggestion
                    if (!describeVirtualGateway.data.virtualGateway.spec ||
                        !describeVirtualGateway.data.virtualGateway.spec.listeners ||
                        !describeVirtualGateway.data.virtualGateway.spec.listeners.length) {
```

2022-03-04 12:41 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshTLSRequired.js
> +                        const tlsEnabled = virtual.spec.listeners.every(listener => listener.tls && listener.tls.mode && listener.tls.mode.toUpperCase() === 'STRICT');
```suggestion
                        const tlsEnabled = describeVirtualGateway.data.virtualGateway.spec.listeners.every(listener => listener.tls && listener.tls.mode && listener.tls.mode.toUpperCase() === 'STRICT');
```

2022-03-04 12:41 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshTLSRequired.spec.js
> +                done();we
```suggestion
                done();
```

2022-03-04 12:41 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshTLSRequired.spec.js
> +
Add message check

2022-03-04 16:17 UTC, sadeed12345 commented on plugins/aws/appmesh/appmeshTLSRequired.js
> +    more_info: 'In App Mesh, Transport Layer Security (TLS) encrypts communication between the Envoy proxies deployed on compute resources that are represented in App Mesh by mesh endpoints.',
```suggestion
    more_info: 'In App Mesh, Transport Layer Security (TLS) encrypts communication between the Envoy proxies deployed on compute resources that are represented in App Mesh by mesh endpoints, such as Virtual nodes and Virtual gateways. The proxy negotiates and terminates TLS.',
```

2022-03-16 09:36 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshTLSRequired.js
> +    description: 'Ensure that AWS App Mesh virtual gateways Listener only accepts connections with TLS enabled.',
```suggestion
    description: 'Ensure that AWS App Mesh virtual gateway listeners only accepts TLS enabled connections.',
```

2022-03-16 09:37 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshTLSRequired.js
> +    more_info: 'In App Mesh, Transport Layer Security (TLS) encrypts communication between the Envoy proxies deployed on compute resources that are represented in App Mesh by mesh endpoints, such as
```suggestion
    more_info: 'In App Mesh, Transport Layer Security (TLS) encrypts communication between the envoy proxies deployed on compute resources that are represented in App Mesh by mesh endpoints, such as Virtual nodes and Virtual gateways.',
```

2022-03-16 09:38 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshTLSRequired.js
> +    recommended_action: 'Restrict TLS enabled connections to AWS App Mesh virtual gateways Listeners in your account',
```suggestion
    recommended_action: 'Restrict AWS App Mesh virtual gateway listeners to accept only TLS enabled connections.',
```

2022-03-16 09:41 UTC, AkhtarAmir approved these changes

2022-03-16 09:41 UTC, merged