SAAS-4146: Added VPC Flow Logs Metric Alarm Plugin
aquasecurity/cloudsploit pull request #1162
Opened 2022-03-01 15:35 UTC by sadeed12345

2022-03-02 10:22 UTC, sadeed12345 commented on plugins/aws/cloudwatch/vpcFlowLogsMetricAlarm.js
> +                    'CloudWatch alarms are configured for the VPC Flow Logs', region);
```suggestion
                    'CloudWatch alarms are configured for the VPC Flow Logs', 
                    region);
```
```suggestion
                    'CloudWatch alarms are configured for the VPC Flow Logs', region);
```

2022-03-02 10:23 UTC, sadeed12345 commented on plugins/aws/cloudwatch/vpcFlowLogsMetricAlarm.js
> +
```suggestion
```

2022-03-02 10:24 UTC, sadeed12345 commented on plugins/aws/cloudwatch/vpcFlowLogsMetricAlarm.js
> +
```suggestion
                    'CloudWatch alarms are not configured for the VPC Flow Logs', 
                    region);
```

2022-03-04 12:18 UTC, AkhtarAmir commented on collectors/aws/collector.js
> +        },
```suggestion
        }
```

2022-03-04 12:19 UTC, AkhtarAmir commented on plugins/aws/cloudwatch/vpcFlowLogsMetricAlarm.js
> +    description: 'Ensures metric filters are setup for alarms by CloudWatch to detect any changes from VPC.',
```suggestion
    description: 'Ensures metric filters are setup for alarms by CloudWatch to detect any changes from VPC flow logs.',
```

2022-03-04 12:21 UTC, AkhtarAmir commented on plugins/aws/cloudwatch/vpcFlowLogsMetricAlarm.js
> +            name: 'CloudWatch VPC flow log group name',
```suggestion
            name: 'CloudWatch VPC Flow Log Group Name',
```

2022-03-04 12:24 UTC, AkhtarAmir commented on plugins/aws/cloudwatch/vpcFlowLogsMetricAlarm.js
> +
```suggestion
            let cwVpcLogGroup = describeMetricFilters.data.find(metrics => metrics.logGroupName === config.vpc_flow_log_group);
            if (!cwVpcLogGroup) {
                helpers.addResult(results, 2,
                    'Unable to locate the specified log group', region);
                return rcb();
            }

```

2022-03-04 12:25 UTC, AkhtarAmir commented on plugins/aws/cloudwatch/vpcFlowLogsMetricAlarm.js
> +            let alarms =  describeAlarms.data.find(alarm => alarm.MetricName === filters.metricTransformations[0].metricName);
```suggestion
            let alarms =  describeAlarms.data.find(alarm => cwVpcLogGroup.metricTransformations && cwVpcLogGroup.metricTransformations.length && cwVpcLogGroup.metricTransformations[0].metricName && alarm.MetricName === cwVpcLogGroup.metricTransformations[0].metricName);
```

2022-03-04 12:26 UTC, AkhtarAmir commented on plugins/aws/cloudwatch/vpcFlowLogsMetricAlarm.js
> +                    'CloudWatch alarms are configured for the VPC Flow Logs',
```suggestion
                    'CloudWatch alarm is configured for the VPC Flow Logs', 
```

2022-03-04 12:26 UTC, AkhtarAmir commented on plugins/aws/cloudwatch/vpcFlowLogsMetricAlarm.js
> +                    'CloudWatch alarms are not configured for the VPC Flow Logs',
```suggestion
                    'CloudWatch alarm is not configured for the VPC Flow Logs', 
```

2022-03-04 12:29 UTC, AkhtarAmir requested changes

2022-03-04 12:29 UTC, AkhtarAmir commented on plugins/aws/cloudwatch/vpcFlowLogsMetricAlarm.js
> +    recommended_action: '1. Create a log group in CloudWatch logs; 2. Create a metric filter for log group with Namespace=LogMetrics and metric Threshold=1; 3.Create CloudWatch alarm for the metric f
Check these steps carefully

2022-03-04 12:29 UTC, AkhtarAmir commented on plugins/aws/cloudwatch/vpcFlowLogsMetricAlarm.js
> +            description: 'Log group name for VPC to detect the log group being used by CLoudWatch logs',
```suggestion
            description: 'Existing CloudWatch log group name created to log VPC flow logs',
```

2022-03-04 12:29 UTC, AkhtarAmir commented on plugins/aws/cloudwatch/vpcFlowLogsMetricAlarm.spec.js
> +                expect(results[0].status).to.equal(0);
Add messages check in tests

2022-03-04 16:19 UTC, sadeed12345 commented on plugins/aws/cloudwatch/vpcFlowLogsMetricAlarm.js
> +    recommended_action: '1. Create a log group in CloudWatch logs; 2. Create a metric filter for log group with Namespace=LogMetrics, metric Threshold=1 and check for logGroupName of desired type; 3.
```suggestion
    recommended_action: '1. Create a log group in CloudWatch logs; 2. Create a metric filter for log group with Namespace=LogMetrics, metric Threshold=1 and check for logGroupName; 3.Create CloudWatch alarm for the metric filter',
```

2022-03-24 10:12 UTC, sadeed12345 commented on plugins/aws/cloudwatch/vpcFlowLogsMetricAlarm.js
> +    severity: 'Low',
```suggestion
    severity: 'LOW',
```

2022-03-31 09:45 UTC, merged