SAAS-4491: Added Enhanced Metadata Collection Enabled Plugin
aquasecurity/cloudsploit pull request #1187
Opened 2022-03-22 15:57 UTC by sadeed12345

2022-03-24 10:10 UTC, sadeed12345 commented on plugins/aws/imagebuilder/enhancedMetadataEnabled.js
> +    domain: 'compute',
```suggestion
    domain: 'compute',
    severity: 'LOW'
```
```suggestion
    domain: 'compute',
```

2022-03-24 10:10 UTC, sadeed12345 commented on plugins/aws/imagebuilder/enhancedMetadataEnabled.js
> +    domain: 'compute',
```suggestion
    domain: 'compute',
    severity: 'LOW'
```
```suggestion
    domain: 'compute',
```

2022-03-24 10:27 UTC, sadeed12345 commented on plugins/aws/imagebuilder/enhancedMetadataEnabled.js
> +    severity: 'LOW'
```suggestion
```

2022-03-24 10:27 UTC, sadeed12345 commented on plugins/aws/imagebuilder/enhancedMetadataEnabled.js
> +    severity: 'LOW'
```suggestion
    severity: 'LOW',
```

2022-05-16 17:21 UTC, AkhtarAmir requested changes

2022-05-16 17:21 UTC, AkhtarAmir commented on plugins/aws/imagebuilder/enhancedMetadataEnabled.js
> +    more_info: 'Image Builder is a fully managed AWS service that makes it easier to automate the creation, management, and deployment of customized, secure, and up-to-date server images that are pre
```suggestion
    more_info: 'EC2 Image Builder is a fully managed AWS service that makes it easier to automate the creation, management, and deployment of customized, secure, and up-to-date server images that are pre-installed and pre-configured with software and settings to meet specific IT standards.',
```

2022-05-16 17:21 UTC, AkhtarAmir commented on plugins/aws/imagebuilder/enhancedMetadataEnabled.spec.js
> +                expect(results[0].message).to.include('No image pipeline list found')
```suggestion
                expect(results[0].message).to.include('No Image Builder image pipelines found')
```

2022-05-16 17:30 UTC, AkhtarAmir approved these changes

2022-06-26 18:47 UTC, merged