SAAS-4494: Added Image Recipe storage volumes encrypted Plugin
aquasecurity/cloudsploit pull request #1191
Opened 2022-03-24 09:28 UTC by sadeed12345

2022-03-24 10:08 UTC, sadeed12345 commented on plugins/aws/imagebuilder/imgRcpStrgVlmEncrypted.js
> +    domain: 'compute',
```suggestion
    domain: 'compute',
    severity: 'LOW'
```

2022-05-16 16:58 UTC, sadeed12345 commented on plugins/aws/imagebuilder/imgRcpStrgVlmEncrypted.js
> +
```suggestion
```

2022-05-16 17:36 UTC, AkhtarAmir requested changes

2022-05-16 17:36 UTC, AkhtarAmir commented on plugins/aws/imagebuilder/imgRcpStrgVlmEncrypted.js
> +    apis: ['Imagebuilder:listImageRecipes', 'Imagebuilder:getImageRecipe'],
Add setting for aws-amanged or cmk level

2022-05-16 17:36 UTC, AkhtarAmir commented on plugins/aws/imagebuilder/imgRcpStrgVlmEncrypted.js
> +    more_info: 'EC2 Image Builder is a fully managed AWS service that makes it easier to automate the creation, management, and deployment of customized, secure, and up-to-date server images that are
Let's make this description more specific to encryption

2022-05-16 17:36 UTC, AkhtarAmir commented on exports.js
> +        'imgRcpStrgVlmEncrypted'        : require(__dirname + '/plugins/aws/imagebuilder/imgRcpStrgVlmEncrypted.js'),
```suggestion
        'imageRecipeVolumeEncrypted'    : require(__dirname + '/plugins/aws/imagebuilder/imgRcpStrgVlmEncrypted.js'),
```

2022-07-29 07:13 UTC, AkhtarAmir commented on plugins/aws/imagebuilder/imageRecipeVolumeEncrypted.js
> +    severity: 'LOW',
```suggestion
    severity: 'MEDIUM',
```

2022-07-29 07:14 UTC, AkhtarAmir commented on plugins/aws/imagebuilder/imageRecipeVolumeEncrypted.js
> +            default: ''
```suggestion
            default: 'awscmk'
```

2022-07-29 12:33 UTC, AkhtarAmir approved these changes

2022-07-29 12:34 UTC, AkhtarAmir approved these changes

2022-07-29 12:39 UTC, merged