SAAS-4562: Added Infrastructure Configuration Notification Enabled Plugin
aquasecurity/cloudsploit pull request #1192
Opened 2022-03-24 16:29 UTC by sadeed12345

2022-05-16 17:08 UTC, sadeed12345 commented on plugins/aws/imagebuilder/infraConfigNotificationEnabled.js
> +
```suggestion
```

2022-05-16 17:45 UTC, AkhtarAmir requested changes

2022-05-16 17:45 UTC, AkhtarAmir commented on helpers/aws/regions.js
> +    imagebuilder: regions
Add new regions

2022-05-16 17:45 UTC, AkhtarAmir commented on plugins/aws/imagebuilder/infraConfigNotificationEnabled.js
> +    domain: 'compute',
```suggestion
    domain: 'Compute',
```

2022-05-16 17:45 UTC, AkhtarAmir commented on plugins/aws/imagebuilder/infraConfigNotificationEnabled.js
> +    description: 'Ensure that Imagebuilder infrastructure configuration have sns notifications enabled.',
```suggestion
    description: 'Ensure that Image Builder infrastructure configurations have SNS notifications enabled.',
```

2022-05-16 17:45 UTC, AkhtarAmir commented on plugins/aws/imagebuilder/infraConfigNotificationEnabled.js
> +    recommended_action: 'Enable sns notification in Imagebuilder infrastructure configurations to get notified of any changes in the service',
```suggestion
    recommended_action: 'Enable SNS notification in EC2 Image Builder infrastructure configurations to get notified of any changes in the service.',
```

2022-05-16 17:45 UTC, AkhtarAmir commented on plugins/aws/imagebuilder/infraConfigNotificationEnabled.js
> +
```suggestion
```

2022-05-16 17:45 UTC, AkhtarAmir commented on plugins/aws/imagebuilder/infraConfigNotificationEnabled.js
> +                        'Imagebuilder has infrastructure configuration notifications enabled',
```suggestion
                        'Infrastructure configuration has SNS notifications enabled',
```

2022-05-16 17:45 UTC, AkhtarAmir commented on plugins/aws/imagebuilder/infraConfigNotificationEnabled.js
> +                        'Imagebuilder does not have infrastructure configuration notifications enabled',
```suggestion
                        'Infrastructure configuration does not have SNS notifications enabled',
```

2022-07-29 12:16 UTC, AkhtarAmir commented on helpers/aws/regions_china.js
> +    imagebuilder: regions
```suggestion
    imagebuilder: regions,
```

2022-07-29 12:16 UTC, AkhtarAmir commented on helpers/aws/regions_gov.js
> +    imagebuilder: regions
```suggestion
    imagebuilder: regions,
```

2022-07-29 12:26 UTC, AkhtarAmir approved these changes

2022-07-29 12:33 UTC, merged