SAAS-5417: Added enableWDATPIntegration plugin and spec
aquasecurity/cloudsploit pull request #1252
Opened 2022-05-15 13:52 UTC by m-nouman-suleman

## Task
- https://scalock.atlassian.net/browse/SAAS-5414

2022-05-18 09:50 UTC, AkhtarAmir requested changes

2022-05-18 09:50 UTC, AkhtarAmir commented on plugins/azure/defender/enableWDATPIntegration.js
> +    domain: 'Security',
```suggestion
    domain: 'Management and Governance',
```

2022-05-18 09:50 UTC, AkhtarAmir commented on plugins/azure/defender/enableWDATPIntegration.js
> +            const wdatpIntegration = defenderSettings.data.find((settings) => settings.name.toLowerCase() === 'wdatp');
```suggestion
            const wdatpIntegration = defenderSettings.data.find((settings) => settings.name && settings.name.toLowerCase() === 'wdatp');
```

2022-05-20 16:30 UTC, m-nouman-suleman commented on plugins/azure/defender/enableWDATPIntegration.js
> +    description: 'Ensures that Microsoft Defender for Endpoint integration is enabled for Microsoft Defender for Cloud.',
```suggestion
    description: 'Ensures that Endpoint integration is enabled for Microsoft Defender for Cloud.',
```

2022-05-23 11:44 UTC, AkhtarAmir approved these changes

2022-05-23 12:31 UTC, AkhtarAmir commented on plugins/azure/defender/enableEndpointIntegration.js
> +    more_info: 'WDATP integration brings comprehensive Endpoint Detection and Response (EDR) capabilities within Microsoft Defender for Cloud. This integration helps to spot abnormalities, detect and
```suggestion
    more_info: 'Window Defender ATP integration brings comprehensive Endpoint Detection and Response (EDR) capabilities within Microsoft Defender for Cloud. This integration helps to spot abnormalities, detect and respond to advanced attacks on Windows server endpoints monitored by Microsoft Defender for Cloud. Windows Defender ATP in Microsoft Defender for Cloud supports detection on Windows Server 2016, 2012 R2, and 2008 R2 SP1 operating systems in a Standard service subscription.',
```

2022-05-23 12:41 UTC, AkhtarAmir approved these changes

2022-05-23 12:42 UTC, merged