AWS Plugin to ensure ecs container insights are enabled
aquasecurity/cloudsploit pull request #1390
Opened 2022-09-20 19:32 UTC by abdullahaslam306

2022-09-20 19:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1390) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1390) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=1390) it.</sub>

2022-09-20 19:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1390) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1390) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=1390) it.</sub>

2022-09-21 07:53 UTC, AkhtarAmir commented on plugins/aws/ecs/ecsContainerInsightsEnabled.js
> +      'Ensure that ECS clusters have CloudWatch Container Insights feature enabled.',
```suggestion
    description: 'Ensure that ECS clusters have CloudWatch Container Insights feature enabled.',
```

2022-09-21 09:29 UTC, AkhtarAmir requested changes

2022-09-21 09:29 UTC, AkhtarAmir commented on plugins/aws/ecs/ecsContainerInsightsEnabled.js
> +                    var clsuterARN = listClusters.data[c];
```suggestion
                for (var clusterARN of listClusters.data) {
```

2022-09-21 09:29 UTC, AkhtarAmir commented on plugins/aws/ecs/ecsContainerInsightsEnabled.js
> +                                            helpers.addResult(
use a flag like inightsEnabled and set it inside loop and add result outside the loop. Just to make sure we don't generate multiple results for same resource

2022-09-21 09:29 UTC, AkhtarAmir commented on plugins/aws/ecs/ecsContainerInsightsEnabled.spec.js
> +describe('ECSContainerInsightsEnabled', function () {
write 1 test per each result

2022-09-21 15:13 UTC, AkhtarAmir requested changes

2022-09-21 15:13 UTC, AkhtarAmir commented on plugins/aws/ecs/ecsContainerInsightsEnabled.js
> +                             if(containerInsightsEnabled){
indentation seems off

2022-09-21 15:13 UTC, AkhtarAmir commented on plugins/aws/ecs/ecsContainerInsightsEnabled.js
> +                                    'ECS cluster container Insights is enabled', region, clusterARN);
```suggestion
                                    'ECS cluster has container Insights enabled', region, clusterARN);
```

2022-09-21 15:13 UTC, AkhtarAmir commented on plugins/aws/ecs/ecsContainerInsightsEnabled.js
> +                                                'ECS cluster container insights  not enabled',region, clusterARN);
```suggestion
                                                'ECS cluster does not have container insights enabled',region, clusterARN);
```

2022-10-04 11:14 UTC, alphadev4 commented on exports.js
> +        'ecsContainerInsightsEnabled'    : require(__dirname + '/plugins/aws/ecs/ecsContainerInsightsEnabled.js'),
```suggestion
        'ecsContainerInsightsEnabled'   : require(__dirname + '/plugins/aws/ecs/ecsContainerInsightsEnabled.js'),
```

2022-10-04 11:15 UTC, alphadev4 commented on plugins/aws/ecs/ecsContainerInsightsEnabled.js
> +                    ['ecs', 'describeCluster', region, clusterARN ]);
```suggestion
                    ['ecs', 'describeCluster', region, clusterARN]);
```

2022-10-04 11:17 UTC, alphadev4 commented on plugins/aws/ecs/ecsContainerInsightsEnabled.js
> +                ) {
```suggestion
                if (describeCluster.data.clusters && describeCluster.data.clusters.length) {   
```

2022-10-04 11:20 UTC, alphadev4 commented on plugins/aws/ecs/ecsContainerInsightsEnabled.js
> +                        let containerInsightsEnabled = false;
```suggestion
                    for (var index in describeCluster.data.clusters) {
                        let containerInsightsEnabled = false;
```

2022-10-04 11:23 UTC, alphadev4 commented on plugins/aws/ecs/ecsContainerInsightsEnabled.js
> +                        if (cluster.settings.length > 0){
```suggestion
                        const cluster = describeCluster.data.clusters[index];
                        
                        if (cluster.settings.length > 0) { 
```

2022-10-04 11:24 UTC, alphadev4 commented on plugins/aws/ecs/ecsContainerInsightsEnabled.js
> +                        if (containerInsightsEnabled){
```suggestion
                        if (containerInsightsEnabled) {
```

2022-10-04 11:25 UTC, alphadev4 commented on plugins/aws/ecs/ecsContainerInsightsEnabled.spec.js
> +        });
```suggestion
        });
        
```

2022-10-04 11:26 UTC, alphadev4 approved these changes

2022-10-04 11:28 UTC, alphadev4 commented on plugins/aws/ecs/ecsContainerInsightsEnabled.spec.js
> +            );
```suggestion
            const cache = createCache([], {});
```

2022-10-07 16:26 UTC, AkhtarAmir commented on plugins/aws/ecs/ecsContainerInsightsEnabled.js
> +                if (!describeCluster || describeCluster.err ||!describeCluster.data) {
```suggestion
                if (!describeCluster || describeCluster.err ||!describeCluster.data ||
                    describeCluster.data.clusters || describeCluster.data.clusters.length) {
```

2022-10-07 16:32 UTC, AkhtarAmir commented on plugins/aws/ecs/ecsContainerInsightsEnabled.js
> +            }
```suggestion
                const cluster = describeCluster.data.clusters[0];
                let containerInsightsEnabled = (cluster.settings && cluster.settings.length) ? cluster.settings.find(item => item.name == 'containerInsights' && item.value == ''enabled) : false;

                if (containerInsightsEnabled) {
                    helpers.addResult(results, 0,
                        'ECS cluster has container Insights enabled', region, clusterARN);
                } else {
                    helpers.addResult(results, 2,
                         'ECS cluster does not have container insights enabled', region, clusterARN);
                }             
            }
```

2022-10-07 16:34 UTC, AkhtarAmir commented on plugins/aws/ecs/ecsContainerInsightsEnabled.spec.js
> +                expect(results[0].message).to.include('ECS cluster has container Insights enabled');
```suggestion
                expect(results[0].message).to.include('ECS cluster has container insights enabled');
```

2022-10-07 16:34 UTC, AkhtarAmir commented on plugins/aws/ecs/ecsContainerInsightsEnabled.js
> +                let containerInsightsEnabled = (cluster.settings && cluster.settings.length) ? cluster.settings.find(item => item.name == 'containerInsights' && item.value == ''enabled) : false;
```suggestion
                let containerInsightsEnabled = (cluster.settings && cluster.settings.length) ? cluster.settings.find(item => item.name == 'containerInsights' && item.value == 'enabled') : false;
```

2022-10-07 16:36 UTC, AkhtarAmir approved these changes

2022-10-07 16:36 UTC, AkhtarAmir commented on plugins/aws/ecs/ecsContainerInsightsEnabled.js
> +                         'ECS cluster does not have container insights enabled', region, clusterARN);
```suggestion
                        'ECS cluster does not have container insights enabled', region, clusterARN);
```

2022-10-07 16:38 UTC, AkhtarAmir commented on plugins/aws/ecs/ecsContainerInsightsEnabled.js
> +                    describeCluster.data.clusters || describeCluster.data.clusters.length) {
```suggestion
                    !describeCluster.data.clusters || !describeCluster.data.clusters.length) {
```

2022-10-07 16:43 UTC, merged