Ensure that IAM Users have tags
aquasecurity/cloudsploit pull request #1396
Opened 2022-09-26 11:20 UTC by abdullahaslam306

2022-10-03 09:24 UTC, AkhtarAmir commented on exports.js
> +        'iamUsersHasTags'               : require(__dirname + '/plugins/aws/iam/iamUsersHasTags.js'),
```suggestion
        'iamUserHasTags'                : require(__dirname + '/plugins/aws/iam/iamUserHasTags.js'),
```

2022-10-03 09:25 UTC, AkhtarAmir requested changes

2022-10-03 09:25 UTC, AkhtarAmir commented on exports.js
> +        'iamUsersHasTags'               : require(__dirname + '/plugins/aws/iam/iamUsersHasTags.js'),
```suggestion
        'iamUserHasTags'                : require(__dirname + '/plugins/aws/iam/iamUserHasTags.js'),
```

2022-10-03 09:25 UTC, AkhtarAmir commented on plugins/aws/iam/iamUsersHasTags.js
> +    title: 'IAM Users Has Tags',
```suggestion
    title: 'IAM User Has Tags',
```

2022-10-03 09:25 UTC, AkhtarAmir commented on plugins/aws/iam/iamUsersHasTags.js
> +
Also need to change file name

2022-10-04 10:55 UTC, alphadev4 commented on exports.js
> +        'iamUserHasTags'               : require(__dirname + '/plugins/aws/iam/iamUserHasTags.js'),
```suggestion
        'iamUserHasTags'                : require(__dirname + '/plugins/aws/iam/iamUserHasTags.js'),
```

2022-10-04 10:56 UTC, alphadev4 commented on plugins/aws/iam/iamUserHasTags.js
> +
```suggestion
```

2022-10-04 11:06 UTC, alphadev4 commented on plugins/aws/iam/iamUserHasTags.js
> +                helpers.addResult(results, 0, 'IAM User have Tags specified', 'global', user.Arn);
```suggestion
                helpers.addResult(results, 0, 'IAM User has tags', 'global', user.Arn);
```

2022-10-04 11:06 UTC, alphadev4 commented on plugins/aws/iam/iamUserHasTags.js
> +
```suggestion
```

2022-10-04 11:09 UTC, alphadev4 commented on plugins/aws/iam/iamUserHasTags.js
> +        for (var user of listUsers.data) {
```suggestion

        for (var user of listUsers.data) {
```

2022-10-04 11:11 UTC, alphadev4 approved these changes

2022-10-04 13:51 UTC, AkhtarAmir approved these changes

2022-10-04 13:53 UTC, merged