plugin iam role has tags complete
aquasecurity/cloudsploit pull request #1399
Opened 2022-09-26 19:19 UTC by abdullahaslam306

2022-10-03 09:23 UTC, AkhtarAmir requested changes

2022-10-03 09:23 UTC, AkhtarAmir commented on exports.js
> +        'iamRolesHasTags'              : require(__dirname + '/plugins/aws/iam/iamRolesHasTags.js'),
```suggestion
        'iamRoleHasTags'               : require(__dirname + '/plugins/aws/iam/iamRoleHasTags.js'),
```

2022-10-03 09:23 UTC, AkhtarAmir commented on plugins/aws/iam/iamRolesHasTags.js
> +
You will have to change file name as well

2022-10-04 10:44 UTC, AkhtarAmir commented on exports.js
> +        'iamRoleHasTags'              : require(__dirname + '/plugins/aws/iam/iamRoleHasTags.js'),
```suggestion
        'iamRoleHasTags'                : require(__dirname + '/plugins/aws/iam/iamRoleHasTags.js'),
```

2022-10-04 10:44 UTC, AkhtarAmir commented on exports.js
> +
```suggestion
```

2022-10-04 10:45 UTC, alphadev4 commented on plugins/aws/iam/iamRoleHasTags.js
> +
```suggestion
```

2022-10-04 10:45 UTC, alphadev4 commented on plugins/aws/iam/iamRoleHasTags.js
> +
```suggestion
```

2022-10-04 10:47 UTC, alphadev4 commented on plugins/aws/iam/iamRoleHasTags.js
> +
```suggestion
```

2022-10-04 10:48 UTC, alphadev4 commented on plugins/aws/iam/iamRoleHasTags.js
> +        for (var role of listRoles.data){
```suggestion
        for (var role of listRoles.data) {
```

2022-10-04 10:52 UTC, alphadev4 approved these changes

2022-10-04 13:46 UTC, AkhtarAmir commented on plugins/aws/iam/iamRoleHasTags.js
> +            if (!Tags.length) {
```suggestion
            if (!Tags || !Tags.length) {
```

2022-10-04 13:47 UTC, AkhtarAmir approved these changes

2022-10-04 13:50 UTC, merged