plugin dev  for cloudtrail tags check
aquasecurity/cloudsploit pull request #1420
Opened 2022-10-15 12:34 UTC by abdullahaslam306

2022-10-24 08:45 UTC, alphadev4 commented on plugins/aws/cloudtrail/cloudtrailHasTags.js
> +    recommended_action: 'Modify  cloudtrail and tags',
```suggestion
    recommended_action: 'Modify  cloudtrail and add tags',
```

2022-10-24 08:45 UTC, alphadev4 commented on plugins/aws/cloudtrail/cloudtrailHasTags.js
> +
```suggestion
```

2022-10-24 08:59 UTC, alphadev4 commented on plugins/aws/cloudtrail/cloudtrailHasTags.js
> +                helpers.addResult(results, 0, 'CloudTrail is not enabled', region);
```suggestion
                helpers.addResult(results, 0, 'No cloud trails found', region);
```

2022-10-24 08:59 UTC, alphadev4 commented on plugins/aws/cloudtrail/cloudtrailHasTags.js
> +                    helpers.addResult(results, 2, 'Cloudtrail does not have tags associated.', region, trail.TrailARNs);
```suggestion
                    helpers.addResult(results, 2, 'Cloudtrail does not have tags associated', region, trail.TrailARNs);
```

2022-10-24 09:03 UTC, alphadev4 requested changes

2022-10-24 09:19 UTC, alphadev4 commented on plugins/aws/cloudtrail/cloudtrailHasTags.js
> +                    helpers.addResult(results, 0, 'Cloudtrail have tags associated.', region, trail.TrailARNs) ;
No full stops at the end of results

2022-10-24 09:22 UTC, alphadev4 commented on plugins/aws/cloudtrail/cloudtrailHasTags.spec.js
> +            expect(results[0].status).to.equal(0);
```suggestion
            expect(results[0].status).to.equal(0);
            expect(results[0].message).to.include('Cloudtrail has tags');
```

2022-10-24 09:25 UTC, alphadev4 requested changes

2022-10-24 09:25 UTC, alphadev4 commented on plugins/aws/cloudtrail/cloudtrailHasTags.spec.js
> +            expect(results[0].status).to.equal(0);
```suggestion
            expect(results[0].status).to.equal(0);
            expect(results[0].message).to.include('Cloudtrail has tags');
```

2022-10-24 09:25 UTC, alphadev4 commented on plugins/aws/cloudtrail/cloudtrailHasTags.spec.js
> +            expect(results[0].status).to.equal(0);
Make sure to include message check in all the spec files

2022-10-24 09:25 UTC, alphadev4 commented on plugins/aws/cloudtrail/cloudtrailHasTags.js
> +                    helpers.addResult(results, 0, 'Cloudtrail have tags associated.', region, trail.TrailARNs) ;
```suggestion
                    helpers.addResult(results, 0, 'Cloudtrail has tags', region, trail.TrailARNs) ;
```

2022-10-24 09:25 UTC, alphadev4 commented on plugins/aws/cloudtrail/cloudtrailHasTags.js
> +                    helpers.addResult(results, 0, 'Cloudtrail have tags associated.', region, trail.TrailARNs) ;
no full stop at the end of results

2022-10-24 09:25 UTC, alphadev4 commented on plugins/aws/cloudtrail/cloudtrailHasTags.js
> +                    helpers.addResult(results, 2, 'Cloudtrail does not have tags associated.', region, trail.TrailARNs);
```suggestion
                    helpers.addResult(results, 2, 'Cloudtrail does not have tags', region, trail.TrailARNs);
```

2022-10-27 07:48 UTC, alphadev4 approved these changes

2022-10-31 09:43 UTC, AkhtarAmir commented on plugins/aws/cloudtrail/cloudtrailHasTags.js
> +    description: 'Ensure that Cloudtrail have tags',
```suggestion
    description: 'Ensure that AWS CloudTrail trails have tags associated.',
```

2022-10-31 09:44 UTC, AkhtarAmir commented on plugins/aws/cloudtrail/cloudtrailHasTags.js
> +    recommended_action: 'Modify  cloudtrail and add tags',
```suggestion
    recommended_action: 'Modify CloudTrail trails and add tags.',
```

2022-10-31 09:44 UTC, AkhtarAmir commented on plugins/aws/cloudtrail/cloudtrailHasTags.js
> +                    `Unable to query for trails: ${helpers.addError(describeTrails)}`, region);
```suggestion
                    `Unable to query for CloudTrail trails: ${helpers.addError(describeTrails)}`, region);
```

2022-10-31 09:45 UTC, AkhtarAmir commented on plugins/aws/cloudtrail/cloudtrailHasTags.js
> +            for (let trail of describeTrails.data){
```suggestion
            }

            for (let trail of describeTrails.data){
```

2022-10-31 09:45 UTC, AkhtarAmir commented on plugins/aws/cloudtrail/cloudtrailHasTags.js
> +                if (!trail.TrailARN) return rcb();
```suggestion
                if (!trail.TrailARN) continue;
```

2022-10-31 09:46 UTC, AkhtarAmir commented on plugins/aws/cloudtrail/cloudtrailHasTags.js
> +                    return rcb();
```suggestion
                    continue;
```

2022-10-31 09:46 UTC, AkhtarAmir commented on plugins/aws/cloudtrail/cloudtrailHasTags.js
> +                    helpers.addResult(results, 0, 'Cloudtrail has tags', region, trail.TrailARNs) ;
```suggestion
                    helpers.addResult(results, 0, 'Cloudtrail has tags', region, trail.TrailARNs);
```

2022-10-31 09:49 UTC, AkhtarAmir commented on plugins/aws/cloudtrail/cloudtrailHasTags.js
> +                !listTags.data.ResourceTagList[0].TagsList ||
```suggestion
                    !listTags.data.ResourceTagList[0].TagsList || 
```

2022-10-31 09:50 UTC, AkhtarAmir commented on plugins/aws/cloudtrail/cloudtrailHasTags.js
> +                !listTags.data.ResourceTagList[0].TagsList.length){
```suggestion
                    !listTags.data.ResourceTagList[0].TagsList.length){
```

2022-10-31 09:51 UTC, AkhtarAmir commented on plugins/aws/cloudtrail/cloudtrailHasTags.js
> +                    helpers.addResult(results, 2, 'Cloudtrail does not have tags', region, trail.TrailARNs);
```suggestion
                    helpers.addResult(results, 2, 'CloudTrail trail does not have tags', region, trail.TrailARN);
```

2022-10-31 09:53 UTC, AkhtarAmir commented on plugins/aws/cloudtrail/cloudtrailHasTags.js
> +                    !listTags.data.ResourceTagList[0].TagsList ||
```suggestion
                if (!listTags.data.ResourceTagList[0].TagsList || 
```

2022-10-31 09:53 UTC, AkhtarAmir commented on plugins/aws/cloudtrail/cloudtrailHasTags.js
> +                if (listTags.err || !listTags.data) {
```suggestion
                if (listTags.err || !listTags.data || !listTags.data.ResourceTagList || !listTags.data.ResourceTagList.length) {
```

2022-10-31 09:53 UTC, AkhtarAmir commented on plugins/aws/cloudtrail/cloudtrailHasTags.js
> +                    helpers.addResult(results, 0, 'Cloudtrail has tags', region, trail.TrailARNs);
```suggestion
                    helpers.addResult(results, 0, 'CloudTrail trail has tags', region, trail.TrailARN);
```

2022-10-31 09:54 UTC, AkhtarAmir commented on plugins/aws/cloudtrail/cloudtrailHasTags.spec.js
> +                expect(results[0].message).to.include('Unable to query for trails');
```suggestion
                expect(results[0].message).to.include('Unable to query for CloudTrail trails');
```

2022-10-31 09:55 UTC, AkhtarAmir commented on plugins/aws/cloudtrail/cloudtrailHasTags.js
> +                        `Unable to query for listTags api: ${helpers.addError(listTags)}`, region);
```suggestion
                        `Unable to list trail tags: ${helpers.addError(listTags)}`, region);
```

2022-10-31 09:55 UTC, AkhtarAmir commented on plugins/aws/cloudtrail/cloudtrailHasTags.spec.js
> +            expect(results[0].message).to.include('Unable to query for listTags api');
```suggestion
            expect(results[0].message).to.include('Unable to list trail tags');
```

2022-10-31 09:55 UTC, AkhtarAmir commented on plugins/aws/cloudtrail/cloudtrailHasTags.spec.js
> +            expect(results[0].message).to.include('Cloudtrail does not have tags');
```suggestion
            expect(results[0].message).to.include('CloudTrail trail does not have tags');
```

2022-10-31 09:55 UTC, AkhtarAmir commented on plugins/aws/cloudtrail/cloudtrailHasTags.spec.js
> +            expect(results[0].message).to.include('Cloudtrail has tags');
```suggestion
            expect(results[0].message).to.include('CloudTrail trail has tags');
```

2022-10-31 11:11 UTC, merged