Feature/saas 9663 aws ensure ebs volumes have tags
aquasecurity/cloudsploit pull request #1422
Opened 2022-10-15 15:03 UTC by abdullahaslam306

2022-10-24 08:15 UTC, alphadev4 commented on plugins/aws/ec2/ebsVolumeHasTags.js
> +    description: 'Ensure that EBS Volumes have tags',
```suggestion
    description: 'Ensure that EBS Volumes have tags associated.',
```

2022-10-24 08:15 UTC, alphadev4 commented on plugins/aws/ec2/ebsVolumeHasTags.js
> +    title: 'EBS Volumes have tags',
```suggestion
    title: 'EBS Volume has tags',
```

2022-10-24 08:18 UTC, alphadev4 commented on plugins/aws/ec2/ebsVolumeHasTags.js
> +                    helpers.addResult(results, 0, 'EBS volume have tags.', region, volumeArn);
```suggestion
                    helpers.addResult(results, 0, 'EBS volume has tags.', region, volumeArn);
```

2022-10-24 08:20 UTC, alphadev4 commented on plugins/aws/ec2/ebsVolumeHasTags.spec.js
> +
```suggestion
```

2022-10-24 08:21 UTC, alphadev4 approved these changes

2022-10-24 09:07 UTC, alphadev4 requested changes

2022-10-24 09:07 UTC, alphadev4 commented on plugins/aws/ec2/ebsVolumeHasTags.js
> +                    helpers.addResult(results, 2, 'EBS volume have no tags associated.', region, volumeArn);
```suggestion
                    helpers.addResult(results, 2, 'EBS volume does not have tags', region, volumeArn);
```

2022-10-24 09:07 UTC, alphadev4 commented on plugins/aws/ec2/ebsVolumeHasTags.js
> +                    helpers.addResult(results, 0, 'EBS volume has tags.', region, volumeArn);
```suggestion
                    helpers.addResult(results, 0, 'EBS volume has tags', region, volumeArn);
```

2022-10-27 07:50 UTC, alphadev4 approved these changes

2022-10-27 09:20 UTC, alphadev4 commented on plugins/aws/ec2/ebsVolumeHasTags.js
> +            for (let volume of describeVolumes.data) {
```suggestion
            for (let volume of describeVolumes.data) {
                  if (!volume.VolumeId) continue;
```

2022-10-31 11:18 UTC, AkhtarAmir commented on plugins/aws/ec2/ebsVolumeHasTags.js
> +                var volumeArn = 'arn:' + awsOrGov + ':ec2:' + region + ':' + accountId + ':volume/' + volume.VolumeId;
```suggestion

                var volumeArn = 'arn:' + awsOrGov + ':ec2:' + region + ':' + accountId + ':volume/' + volume.VolumeId;
```

2022-10-31 11:21 UTC, AkhtarAmir approved these changes

2022-10-31 11:25 UTC, merged