Feature/saas 9815 aws ensure that cognito have m
aquasecurity/cloudsploit pull request #1429
Opened 2022-10-23 19:30 UTC by abdullahaslam306

2022-10-27 08:00 UTC, alphadev4 commented on plugins/aws/cognito/cognitoMFAEnabled.js
> +                    return rcb();
```suggestion
                   continue;
```

2022-10-27 08:02 UTC, alphadev4 commented on plugins/aws/cognito/cognitoMFAEnabled.js
> +                    return rcb();
use continue in for loop

2022-10-27 09:11 UTC, alphadev4 requested changes

2022-10-27 09:11 UTC, alphadev4 commented on plugins/aws/cognito/cognitoMFAEnabled.js
> +            for (let userPool of userPools.data) {
```suggestion
            for (let userPool of userPools.data) {
                  if (!userPool.Id) continue;
```

2022-10-27 09:11 UTC, alphadev4 commented on plugins/aws/cognito/cognitoMFAEnabled.js
> +            for (let userPool of userPools.data) {
add this check to make sure userPool.Id is present

2022-10-27 09:11 UTC, alphadev4 commented on plugins/aws/cognito/cognitoMFAEnabled.js
> +                    return rcb();
use continue in for loop

2022-10-27 09:11 UTC, alphadev4 commented on plugins/aws/cognito/cognitoMFAEnabled.spec.js
> +      Arn: 'arn:aws:cognito-idp:us-east-1:10136388154:userpool/us-east-1_cbDh8sCFGH',
```suggestion
      Arn: 'arn:aws:cognito-idp:us-east-1:1111222222222:userpool/us-east-1_cbDh8sCFGH',
```

2022-10-27 09:11 UTC, alphadev4 commented on plugins/aws/cognito/cognitoMFAEnabled.spec.js
> +      Arn: 'arn:aws:cognito-idp:us-east-1:10136388154:userpool/us-east-1_cbDh8sCFGH',
dummy id

2022-10-27 09:11 UTC, alphadev4 commented on plugins/aws/cognito/cognitoMFAEnabled.js
> +
-

2022-10-31 07:56 UTC, alphadev4 commented on plugins/aws/cognito/cognitoMFAEnabled.js
> +
```suggestion
```

2022-10-31 07:58 UTC, alphadev4 commented on plugins/aws/cognito/cognitoMFAEnabled.js
> +                    helpers.addResult(results, 2, 'MFA not enabled for cognito', region, describeUserPool.data.Arn);
```suggestion
                    helpers.addResult(results, 2, 'Cognito does not have MFA enabled', region, describeUserPool.data.Arn);
```

2022-10-31 07:59 UTC, alphadev4 commented on plugins/aws/cognito/cognitoMFAEnabled.js
> +
```suggestion
```

2022-10-31 08:00 UTC, alphadev4 approved these changes

2022-11-01 10:27 UTC, alphadev4 commented on plugins/aws/cognito/cognitoMFAEnabled.js
> +    recommended_action: '1. Enter the Cognito service. 2. Enter user pools and enable MFA from signin experience ',
```suggestion
    recommended_action: '1. Enter the Cognito service. 2. Enter user pools and enable MFA from sign in experience',
```

2022-11-01 10:28 UTC, alphadev4 approved these changes

2022-11-01 11:17 UTC, AkhtarAmir commented on plugins/aws/cognito/cognitoMFAEnabled.js
> +    category: 'CognitoIdentityServiceProvider',
```suggestion
    title: 'Cognito User Pool MFA enabled',
    category: 'Cognito',
```

2022-11-01 11:17 UTC, AkhtarAmir commented on plugins/aws/cognito/cognitoMFAEnabled.js
> +    description: 'Ensure that cognito user pool has MFA enabled.',
```suggestion
    description: 'Ensure that Cognito user pool has MFA enabled.',
```

2022-11-01 11:18 UTC, AkhtarAmir commented on plugins/aws/cognito/cognitoMFAEnabled.js
> +    recommended_action: '1. Enter the Cognito service. 2. Enter user pools and enable MFA from sign in experience',
```suggestion
    recommended_action: '1. Enter the Cognito service. 2. Enter user pools and enable MFA from sign in experience.',
```

2022-11-01 11:20 UTC, AkhtarAmir commented on plugins/aws/cognito/cognitoMFAEnabled.js
> +                helpers.addResult(results, 3,  'Unable to query api: ' + helpers.addError(userPools), region);
```suggestion
                helpers.addResult(results, 3,  'Unable to query Cognito user pools: ' + helpers.addError(userPools), region);
```

2022-11-01 11:20 UTC, AkhtarAmir commented on plugins/aws/cognito/cognitoMFAEnabled.js
> +                helpers.addResult(results, 0, 'No User pool found', region);
```suggestion
                helpers.addResult(results, 0, 'No Cognito user pools found', region);
```

2022-11-01 11:21 UTC, AkhtarAmir commented on plugins/aws/cognito/cognitoMFAEnabled.js
> +                if (!describeUserPool || describeUserPool.err || !describeUserPool.data || !describeUserPool.data.UserPool){
```suggestion
                    ['cognitoidentityserviceprovider', 'describeUserPool', region, userPool.Id]);

                if (!describeUserPool || describeUserPool.err || !describeUserPool.data || !describeUserPool.data.UserPool){
```

2022-11-01 11:24 UTC, AkhtarAmir commented on plugins/aws/cognito/cognitoMFAEnabled.js
> +            for (let userPool of userPools.data) {
```suggestion
            }

            if (!userPools.data.length){
                helpers.addResult(results, 0, 'No Cognito user pools found', region);
                return rcb();
            }

            for (let userPool of userPools.data) {
```

2022-11-01 11:26 UTC, AkhtarAmir commented on plugins/aws/cognito/cognitoMFAEnabled.spec.js
> +                expect(results[0].message).to.include('Unable to query api:');
```suggestion
                expect(results[0].message).to.include('Unable to query Cognito user pools:');
```

2022-11-01 11:26 UTC, AkhtarAmir commented on plugins/aws/cognito/cognitoMFAEnabled.spec.js
> +                expect(results[0].message).to.include('No User pool found');
```suggestion
                expect(results[0].message).to.include('No Cognito user pool found');
```

2022-11-01 11:26 UTC, AkhtarAmir commented on plugins/aws/cognito/cognitoMFAEnabled.spec.js
> +                expect(results[0].message).to.include('Unable to query for Cognito');
```suggestion
                expect(results[0].message).to.include('Unable to describe Cognito user pool');
```

2022-11-01 11:27 UTC, AkhtarAmir commented on plugins/aws/cognito/cognitoMFAEnabled.js
> +                    helpers.addResult(results, 0, 'Cognito has MFA enabled', region, describeUserPool.data.Arn);
```suggestion
                    helpers.addResult(results, 0, 'User pool has MFA enabled', region, describeUserPool.data.Arn);
```

2022-11-01 11:27 UTC, AkhtarAmir commented on plugins/aws/cognito/cognitoMFAEnabled.js
> +                    helpers.addResult(results, 2, 'Cognito does not have MFA enabled', region, describeUserPool.data.Arn);
```suggestion
                    helpers.addResult(results, 2, 'User pool does not have MFA enabled', region, describeUserPool.data.Arn);
```

2022-11-01 11:27 UTC, AkhtarAmir commented on plugins/aws/cognito/cognitoMFAEnabled.spec.js
> +                expect(results[0].message).to.include('Cognito has MFA enabled');
```suggestion
                expect(results[0].message).to.include('User pool has MFA enabled');
```

2022-11-01 11:28 UTC, AkhtarAmir commented on plugins/aws/cognito/cognitoMFAEnabled.spec.js
> +                    expect(results[0].message).to.include('Cognito does not have MFA enabled');
```suggestion
                    expect(results[0].message).to.include('User pool does not have MFA enabled');
```

2022-11-01 11:29 UTC, AkhtarAmir requested changes

2022-11-01 11:29 UTC, AkhtarAmir commented on plugins/aws/cognito/cognitoMFAEnabled.js
> +                        'Unable to describe Cognito user pool: ' + helpers.addError(describeUserPool), region);
Where is resource? You need to create ARN above. Also use that ARN for messages below

2022-11-01 12:06 UTC, AkhtarAmir commented on helpers/aws/api_multipart.js
> +
```suggestion
```

2022-11-01 12:07 UTC, AkhtarAmir commented on helpers/aws/regions.js
> +
```suggestion
```

2022-11-01 12:08 UTC, AkhtarAmir approved these changes

2022-11-01 12:10 UTC, AkhtarAmir commented on plugins/aws/cognito/cognitoMFAEnabled.js
> +    domain: 'Identity Service Provider',
```suggestion
    domain: 'Identity and Access Management',
```

2022-11-01 12:10 UTC, AkhtarAmir approved these changes

2022-11-01 12:11 UTC, merged