plugin vm has tags
aquasecurity/cloudsploit pull request #1476
Opened 2022-12-10 21:18 UTC by abdullahaslam306

2022-12-14 14:03 UTC, alphadev4 commented on plugins/azure/virtualmachines/vmHasTags.js
> +    description: 'Ensures that Azure virtual machine have tags associated.',
```suggestion
    description: 'Ensures that Azure virtual machines have tags associated.',
```

2022-12-14 14:07 UTC, alphadev4 commented on plugins/azure/virtualmachines/vmHasTags.js
> +            var virtualMachines = helpers.addSource(cache, source, ['virtualMachines', 'listAll', location]);
```suggestion
            var virtualMachines = helpers.addSource(cache, source,
                   ['virtualMachines', 'listAll', location]);
```

2022-12-14 14:07 UTC, alphadev4 commented on plugins/azure/virtualmachines/vmHasTags.js
> +            var virtualMachines = helpers.addSource(cache, source, ['virtualMachines', 'listAll', location]);
```suggestion
            var virtualMachines = helpers.addSource(cache, source,
                ['virtualMachines', 'listAll', location]);
```

2022-12-14 14:11 UTC, alphadev4 commented on plugins/azure/virtualmachines/vmHasTags.js
> +                const virtualMachineData = helpers.addSource(cache, source, ['virtualMachines', 'get', location, virtualMachine.id]);
```suggestion
                const virtualMachineData = helpers.addSource(cache, source,
                    ['virtualMachines', 'get', location, virtualMachine.id]);
```

2022-12-14 14:24 UTC, alphadev4 commented on plugins/azure/virtualmachines/vmHasTags.js
> +                    helpers.addResult(results, 0, 'Virtual Machine has tags associated', location, virtualMachine.id);
```suggestion
                    helpers.addResult(results, 0, 'Virtual Machine has tags', location, virtualMachine.id);
```

2022-12-14 14:24 UTC, alphadev4 commented on plugins/azure/virtualmachines/vmHasTags.js
> +                    helpers.addResult(results, 2, 'Virtual Machine does not have tags associated', location, virtualMachine.id);
```suggestion
                    helpers.addResult(results, 2, 'Virtual Machine does not have tags', location, virtualMachine.id);
```

2022-12-14 14:25 UTC, alphadev4 commented on plugins/azure/virtualmachines/vmHasTags.spec.js
> +                expect(results[0].message).to.include('Virtual Machine does not have tags associated');
```suggestion
                expect(results[0].message).to.include('Virtual Machine does not have tags');
```

2022-12-14 14:25 UTC, alphadev4 commented on plugins/azure/virtualmachines/vmHasTags.spec.js
> +                expect(results[0].message).to.include('Virtual Machine has tags associated');
```suggestion
                expect(results[0].message).to.include('Virtual Machine has tags');
```

2022-12-26 14:41 UTC, alphadev4 commented on plugins/azure/virtualmachines/vmHasTags.js
> +    recommended_action: 'Modify virtual machine and add tags',
```suggestion
    recommended_action: 'Modify affected virtual machine and add tags',
```

2023-01-02 08:25 UTC, alphadev4 commented on plugins/azure/virtualmachines/vmHasTags.js
> +    recommended_action: 'Modify affected virtual machine and add tags',
```suggestion
    recommended_action: 'Modify affected virtual machine and add tags.',
```

2023-01-03 09:24 UTC, AkhtarAmir requested changes

2023-01-03 09:24 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/vmHasTags.js
> +                const virtualMachineData = helpers.addSource(cache, source, ['virtualMachines', 'get', location, virtualMachine.id]);
if not virtualMachine.id check

2023-01-03 09:24 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/vmHasTags.js
> +                if (!virtualMachineData || !virtualMachineData.data || !virtualMachineData.data.name || virtualMachineData.err) {
```suggestion
                if (!virtualMachineData || !virtualMachineData.data || virtualMachineData.err) {
```

2023-01-03 09:40 UTC, AkhtarAmir approved these changes

2023-01-03 10:50 UTC, merged