mysql server has tags
aquasecurity/cloudsploit pull request #1482
Opened 2022-12-11 19:17 UTC by abdullahaslam306

2022-12-26 14:55 UTC, alphadev4 commented on plugins/azure/keyvaults/keyVaultHasTags.js
> +    title: 'KeyVault Has Tags',
```suggestion
    title: 'Key Vault Has Tags',
```

2022-12-27 11:14 UTC, alphadev4 commented on plugins/azure/mysqlserver/mysqlServerHasTags.js
> +    description: 'Ensures that Azure MySQL Server Has Tags',
```suggestion
    description: 'Ensure that Azure MySQL servers have tags associated.',
```

2022-12-28 14:35 UTC, alphadev4 commented on plugins/azure/mysqlserver/mysqlServerHasTags.js
> +    recommended_action: 'Modify MySQL server and add tags',
```suggestion
    recommended_action: 'Modify MySQL server and add tags.',
```

2023-01-03 09:06 UTC, AkhtarAmir commented on plugins/azure/keyvaults/keyVaultHasTags.js
> +
Can you remove this file?

2023-01-03 09:07 UTC, AkhtarAmir requested changes

2023-01-03 09:07 UTC, AkhtarAmir commented on plugins/azure/keyvaults/keyVaultHasTags.js
> +
Can you remove this file?

2023-02-01 13:47 UTC, AkhtarAmir approved these changes

2023-02-01 13:48 UTC, merged