SAAS-12945/iam-policies-plugins
aquasecurity/cloudsploit pull request #1521
Opened 2023-01-24 17:38 UTC by alphadev4

2023-02-01 18:22 UTC, AkhtarAmir commented on plugins/aws/lambda/lambdaOldRuntimes.js
> +            default: 30
lets keep this 0

2023-02-08 08:10 UTC, alphadev4 commented on plugins/aws/lambda/lambdaOldRuntimes.js
> +            default: 30
ok

2023-02-08 11:08 UTC, AkhtarAmir requested changes

2023-02-08 11:08 UTC, AkhtarAmir commented on plugins/aws/iam/iamRolePolicies.js
> +            description: 'Resource specific wildcards in attached policies (inline and managed) which matches this regex. '+
can we make this more descriptive? like:
input to flag resources based on regex. All policy resource which not pass this regex will be flagged.

2023-02-08 12:06 UTC, AkhtarAmir commented on plugins/aws/lambda/lambdaOldRuntimes.js
> +            lambda_runtime_fail: settings.lambda_runtime_fail || this.settings.lambda_runtime_fail.default
```suggestion
            lambda_runtime_fail: parseInt(settings.lambda_runtime_fail || this.settings.lambda_runtime_fail.default)
```

2023-02-08 12:58 UTC, AkhtarAmir commented on plugins/aws/iam/iamRolePolicies.js
> +            name: 'Resource Specific Wildcards',
```suggestion
            name: 'IAM Policy Resource Specific Wildcards',
```

2023-02-08 13:03 UTC, AkhtarAmir commented on plugins/aws/iam/iamRolePolicies.js
> +                'If iam_policy_resource_specific_wildcards is set to default value, PASS result will be generated.',
```suggestion
            description: 'Allows policy resources to flag based on regular expression. All the resources in IAM policy, inline or managed, will be tested against this regex and if they don't pass the regex, they will be flagged by the plugin.',
```

2023-02-08 13:05 UTC, AkhtarAmir commented on plugins/aws/iam/iamRolePolicies.js
> +            config.iam_policy_resource_specific_wildcards.length) ? new RegExp(config.iam_policy_resource_specific_wildcards) : false;
```suggestion
        var allowedRegex = RegExp(config.iam_policy_resource_specific_wildcards);
```

2023-02-08 13:05 UTC, AkhtarAmir commented on plugins/aws/iam/iamRolePolicies.js
> +                            addRoleFailures(roleFailures, statements, 'managed', config.ignore_service_specific_wildcards, allowRegex);
```suggestion
                            addRoleFailures(roleFailures, statements, 'managed', config.ignore_service_specific_wildcards, allowedRegex);
```

2023-02-08 13:05 UTC, AkhtarAmir commented on plugins/aws/iam/iamRolePolicies.js
> +                        addRoleFailures(roleFailures, statements, 'inline', config.ignore_service_specific_wildcards, allowRegex);
```suggestion
                        addRoleFailures(roleFailures, statements, 'inline', config.ignore_service_specific_wildcards, allowedRegex);
```

2023-02-08 13:07 UTC, AkhtarAmir commented on plugins/aws/iam/iamRolePolicies.js
> +            } else if (regResource && statement.Resource && statement.Resource.length) {
```suggestion
            }
            if (regResource && statement.Resource && statement.Resource.length) {
```

2023-02-08 13:09 UTC, AkhtarAmir commented on plugins/aws/iam/iamRolePolicies.js
> +                if (wildcards.length) failMsg = `Role ${policyType} policy allows resource wildcards: ${wildcards.join(', ')}`;
```suggestion
                if (wildcards.length) failMsg = `Role ${policyType} policy does not match provided regex: ${wildcards.join(', ')}`;
```

2023-02-08 13:20 UTC, alphadev4 commented on plugins/aws/iam/iamRolePolicies.spec.js
> +            iamRolePolicies.run(cache, { ignore_service_specific_wildcards: 'true', resource_specific_wildcards: 'true' }, (err, results) => {
```suggestion
            iamRolePolicies.run(cache, {resource_specific_wildcards: 'true' }, (err, results) => {
```

2023-02-08 13:20 UTC, alphadev4 commented on plugins/aws/iam/iamRolePolicies.spec.js
> +            iamRolePolicies.run(cache,{ ignore_service_specific_wildcards: 'true',iam_policy_resource_specific_wildcards: '^[a-z]+:[a-z]+:[a-z0-9]+:::[a-z]+$'}, (err, results) => {
```suggestion
            iamRolePolicies.run(cache, {iam_policy_resource_specific_wildcards: '^[a-z]+:[a-z]+:[a-z0-9]+:::[a-z]+$'}, (err, results) => {
```

2023-02-08 13:21 UTC, alphadev4 commented on plugins/aws/iam/rolePolicyUnusedServices.js
> +            default: '^.*$',
```suggestion
        whitelist_unused_actions_for_resources: {
            name: 'Whitelist Unused Actions For Resources',
            description: 'A comma-separated list indicating which actions for specific service should be ignored i.e. Ignore the following actions ec2:CancelReservedInstancesListing, ec2:AcceptVpcPeeringConnection for ec2 Service',
            regex: '.*$',
            default: ''
        },
        iam_policy_resource_specific_wildcards: {
            name: 'IAM Policy Resource Specific Wildcards',
            description: 'Allows policy resources to flag based on regular expression. All the resources in IAM policy, inline or managed, will be tested against this regex and if they don\'t pass the regex, they will be flagged by the plugin.',
            regex: '^.*$',
            default: '^.*$',
```

2023-02-08 13:23 UTC, alphadev4 commented on plugins/aws/iam/rolePolicyUnusedServices.js
> +            config.iam_policy_resource_specific_wildcards.length) ? new RegExp(config.iam_policy_resource_specific_wildcards) : false;
```suggestion
        var allowedRegex = new RegExp(config.iam_policy_resource_specific_wildcards);
```

2023-02-08 13:23 UTC, alphadev4 commented on plugins/aws/iam/rolePolicyUnusedServices.js
> +                                addRoleFailures(roleFailures, statements, 'managed', config.ignore_service_specific_wildcards, allowRegex);
```suggestion
                                addRoleFailures(roleFailures, statements, 'managed', config.ignore_service_specific_wildcards, allowedRegex);
```

2023-02-08 13:23 UTC, alphadev4 commented on plugins/aws/iam/rolePolicyUnusedServices.js
> +                            addRoleFailures(roleFailures, statements, 'inline', config.ignore_service_specific_wildcards, allowRegex);
```suggestion
                            addRoleFailures(roleFailures, statements, 'inline', config.ignore_service_specific_wildcards, allowedRegex);
```

2023-02-08 13:23 UTC, alphadev4 commented on plugins/aws/iam/rolePolicyUnusedServices.js
> +            } else if (regResource && statement.Resource && statement.Resource.length) {
```suggestion
            }
            if (statement.Resource && statement.Resource.length) {
```

2023-02-08 13:27 UTC, alphadev4 commented on plugins/aws/iam/iamRolePolicies.spec.js
> +                expect(results[0].message).to.include('policy allows resource wildcards:');
```suggestion
                expect(results[0].message).to.include('policy does not match provided regex');
```

2023-02-08 13:28 UTC, alphadev4 commented on plugins/aws/iam/rolePolicyUnusedServices.spec.js
> +            rolePolicyUnusedServices.run(cache,{ ignore_service_specific_wildcards: 'true',iam_policy_resource_specific_wildcards: '^[a-z]+:[a-z]+:[a-z0-9]+:::[a-z]+$'}, (err, results) => {
```suggestion
            rolePolicyUnusedServices.run(cache, {iam_policy_resource_specific_wildcards: '^[a-z]+:[a-z]+:[a-z0-9]+:::[a-z]+$'}, (err, results) => {
```

2023-02-08 13:30 UTC, alphadev4 commented on plugins/aws/iam/iamRolePolicies.js
> +
```suggestion
```

2023-02-08 13:35 UTC, alphadev4 commented on plugins/aws/iam/rolePolicyUnusedServices.js
> +            } else if (statement.Resource && statement.Resource.indexOf('*') > -1){
```suggestion
            } else if (statement.Resource && statement.Resource == '*'){
```

2023-02-08 14:25 UTC, merged