Feature/saas 12636 azure ensure waf policy for application gateway is set to prevention mode
aquasecurity/cloudsploit pull request #1539
Opened 2023-01-30 19:17 UTC by abdullahaslam306

2023-01-31 09:20 UTC, AkhtarAmir commented on plugins/azure/applicationGateway/agPreventionModeEnabled.js
> +    description: 'Ensure that WAF policy for Microsoft Azure Application gateway is set to Prevention mode',
```suggestion
    description: 'Ensure that WAF policy for Microsoft Azure Application gateway is set to Prevention mode.',
```

2023-01-31 09:24 UTC, AkhtarAmir requested changes

2023-01-31 09:24 UTC, AkhtarAmir commented on plugins/azure/applicationGateway/agPreventionModeEnabled.js
> +                if (!appGateway.id || !appGateway.sku.tier === 'WAF_v2') continue;
Is it not supported for v2? If not, then add a result saying 'Prevention mode is not supported for WAF_v2'

2023-01-31 18:16 UTC, abdullahaslam306 commented on plugins/azure/applicationGateway/agPreventionModeEnabled.js
> +                if (!appGateway.id || !appGateway.sku.tier === 'WAF_v2') continue;
It is only available for WAFV2 I have added message in case of other standard

2023-02-01 12:36 UTC, AkhtarAmir approved these changes

2023-02-01 12:37 UTC, AkhtarAmir commented on plugins/azure/applicationGateway/agPreventionModeEnabled.js
> +                if (appGateway.webApplicationFirewallConfiguration && appGateway.webApplicationFirewallConfiguration.firewallMode.toLowerCase() === 'prevention') {
```suggestion
                if (appGateway.webApplicationFirewallConfiguration && appGateway.webApplicationFirewallConfiguration.firewallMode && appGateway.webApplicationFirewallConfiguration.firewallMode.toLowerCase() === 'prevention') {
```

2023-02-01 12:44 UTC, merged