deafult security group ec2
aquasecurity/cloudsploit pull request #1551
Opened 2023-02-15 19:08 UTC by abdullahaslam306

2023-02-28 18:24 UTC, alphadev4 commented on plugins/aws/ec2/ec2AssociatedWithDefaultSG.js
> +    title: 'EC2 Associated With Default Security Group',
```suggestion
    title: 'Default Security Group In Use',
```

2023-02-28 18:24 UTC, alphadev4 commented on plugins/aws/ec2/ec2AssociatedWithDefaultSG.js
> +    title: 'EC2 Associated With Default Security Group',
the name should be this i think, so does the file name

2023-02-28 18:37 UTC, alphadev4 commented on plugins/aws/ec2/ec2AssociatedWithDefaultSG.js
> +    more_info: 'The default security group is often used for resources launched without a defined security group. For this reason, default security groups should not be associated with ec2 instances.
```suggestion
    more_info: 'The default security group allows all traffic inbound and outbound, which can make your resources vulnerable to attacks. Ensure that the Amazon EC2 instances are not associated with the default security groups.',
```

2023-02-28 19:03 UTC, alphadev4 commented on plugins/aws/ec2/ec2AssociatedWithDefaultSG.js
> +                    }
The loop here will probably result in duplicates in case we have multiple security groups attached to an instance

2023-02-28 19:05 UTC, alphadev4 commented on plugins/aws/ec2/ec2AssociatedWithDefaultSG.js
> +    more_info: 'The default security group is often used for resources launched without a defined security group. For this reason, default security groups should not be associated with ec2 instances.
more_info

2023-02-28 19:06 UTC, alphadev4 commented on plugins/aws/ec2/ec2AssociatedWithDefaultSG.js
> +    title: 'EC2 Associated With Default Security Group',
the name should be this and so does the file name

2023-02-28 19:10 UTC, alphadev4 requested changes

2023-02-28 19:10 UTC, alphadev4 commented on plugins/aws/ec2/ec2AssociatedWithDefaultSG.js
> +    title: 'EC2 Associated With Default Security Group',
```suggestion
    title: 'Default Security Group In Use',
```

2023-02-28 19:10 UTC, alphadev4 commented on plugins/aws/ec2/ec2AssociatedWithDefaultSG.js
> +    title: 'EC2 Associated With Default Security Group',
the name should be this and so does the file name

2023-02-28 19:10 UTC, alphadev4 commented on plugins/aws/ec2/ec2AssociatedWithDefaultSG.js
> +    more_info: 'The default security group is often used for resources launched without a defined security group. For this reason, default security groups should not be associated with ec2 instances.
```suggestion
    more_info: 'The default security group allows all traffic inbound and outbound, which can make your resources vulnerable to attacks. Ensure that the Amazon EC2 instances are not associated with the default security groups.',
```

2023-02-28 19:10 UTC, alphadev4 commented on plugins/aws/ec2/ec2AssociatedWithDefaultSG.js
> +    more_info: 'The default security group is often used for resources launched without a defined security group. For this reason, default security groups should not be associated with ec2 instances.
more info

2023-02-28 19:10 UTC, alphadev4 commented on plugins/aws/ec2/ec2AssociatedWithDefaultSG.js
> +                    }
```suggestion
                    const defaultSecurityGroup = SecurityGroups.find(sg => sg.GroupName === 'default');
                    if (defaultSecurityGroup) {
                        helpers.addResult(results, 2, 'EC2 instance is associated with default security group', region, arn);
                    } else {
                        helpers.addResult(results, 0, 'EC2 instance is not associated with default security group', region, arn);
                    }
```

2023-02-28 19:10 UTC, alphadev4 commented on plugins/aws/ec2/ec2AssociatedWithDefaultSG.js
> +                    }
The loop here will probably result in duplicates in case we have multiple security groups attached to an instance

2023-03-06 07:14 UTC, alphadev4 commented on plugins/aws/ec2/defaultSecurityGroupInUse.spec.js
> +
```suggestion
         it('should PASS if EC2 is not associated with default security group', function (done) {
             const cache = createCache([describeInstances[0]]);
             ec2AssociatedWithDefaultSG.run(cache, {}, (err, results) => {
                 expect(results.length).to.equal(1);
                 expect(results[0].status).to.equal(0);
                 expect(results[0].region).to.equal('us-east-1')
                 expect(results[0].message).to.include('EC2 instance is not associated with default security group');
                 done();
             });
         });

         it('should FAIL if EC2 is associated with default security group', function (done) {
             const cache = createCache([describeInstances[1]]);
             ec2AssociatedWithDefaultSG.run(cache, {}, (err, results) => {
                 expect(results.length).to.equal(1);
                 expect(results[0].status).to.equal(2);
                 expect(results[0].region).to.equal('us-east-1')
                 expect(results[0].message).to.include('EC2 instance is associated with default security group');
                 done();
             });
         });

```

2023-03-06 07:36 UTC, alphadev4 commented on plugins/aws/ec2/defaultSecurityGroupInUse.js
> +                    const defaultSecurityGroup = SecurityGroups? SecurityGroups.find(sg => sg.GroupName === 'default'): false;
```suggestion
                    const defaultSecurityGroup = SecurityGroups? SecurityGroups.find(sg => sg.GroupName.toLowerCase() === 'default'): false;
```

2023-03-06 08:51 UTC, alphadev4 commented on plugins/aws/ec2/defaultSecurityGroupInUse.js
> +                    const defaultSecurityGroup = SecurityGroups? SecurityGroups.find(sg => sg.GroupName.toLowerCase() == 'default'): false;
```suggestion
                    const defaultSecurityGroup = SecurityGroups.find(sg => sg.GroupName.toLowerCase() == 'default');
```

2023-03-06 08:54 UTC, alphadev4 commented on plugins/aws/ec2/defaultSecurityGroupInUse.js
> +                    const defaultSecurityGroup = SecurityGroups.find(sg => sg.GroupName.toLowerCase() == 'default');
```suggestion
                    if (!instance.InstanceId) continue;
                    const { SecurityGroups } = instance;
                    const arn = `arn:aws:ec2:${region}:${OwnerId}:instance/${instance.InstanceId}`;
                    const defaultSecurityGroup =  SecurityGroups.find(sg => sg.GroupName.toLowerCase() == 'default');
```

2023-03-06 08:55 UTC, alphadev4 commented on plugins/aws/ec2/defaultSecurityGroupInUse.js
> +                    const defaultSecurityGroup = SecurityGroups.find(sg => sg.GroupName.toLowerCase() == 'default');
```suggestion
                     if (!instance.InstanceId) continue;
                    const arn = `arn:aws:ec2:${region}:${OwnerId}:instance/${instance.InstanceId}`;
                    const defaultSecurityGroup =  instance.SecurityGroups.find(sg => sg.GroupName.toLowerCase() == 'default');
```

2023-03-06 10:45 UTC, alphadev4 commented on plugins/aws/ec2/defaultSecurityGroupInUse.js
> +                    const defaultSecurityGroup = SecurityGroups.find(sg => sg.GroupName.toLowerCase() == 'default');
```suggestion
                    const { InstanceId } = instance;
                    const arn = `arn:aws:ec2:${region}:${OwnerId}:instance/${InstanceId}`;
                    const defaultSecurityGroup = (instance.SecurityGroups && instance.SecurityGroups.length) ? SecurityGroups.find(sg => sg.GroupName.toLowerCase() == 'default'): false;
```

2023-03-06 10:46 UTC, alphadev4 commented on plugins/aws/ec2/defaultSecurityGroupInUse.js
> +                    const defaultSecurityGroup = (instance.SecurityGroups && instance.SecurityGroups.length) ? SecurityGroups.find(sg => sg.GroupName.toLowerCase() == 'default'): false;
```suggestion
                    const { InstanceId } = instance;
                    const arn = `arn:aws:ec2:${region}:${OwnerId}:instance/${InstanceId}`;
                    const defaultSecurityGroup = (instance.SecurityGroups && instance.SecurityGroups.length) ? isntance.SecurityGroups.find(sg => sg.GroupName.toLowerCase() == 'default'): false;
```

2023-03-06 10:47 UTC, alphadev4 commented on plugins/aws/ec2/defaultSecurityGroupInUse.js
> +                    const defaultSecurityGroup = (instance.SecurityGroups && instance.SecurityGroups.length) ? isntance.SecurityGroups.find(sg => sg.GroupName.toLowerCase() == 'default'): false;
```suggestion
                    const defaultSecurityGroup = (instance.SecurityGroups && instance.SecurityGroups.length) ? instance.SecurityGroups.find(sg => sg.GroupName.toLowerCase() == 'default'): false;
```

2023-03-06 10:50 UTC, alphadev4 commented on plugins/aws/ec2/defaultSecurityGroupInUse.spec.js
> +        //  });
```suggestion
          it('should PASS if EC2 is not associated with default security group', function (done) {
              const cache = createCache([describeInstances[0]]);
              ec2AssociatedWithDefaultSG.run(cache, {}, (err, results) => {
                  expect(results.length).to.equal(1);
                  expect(results[0].status).to.equal(0);
                  expect(results[0].region).to.equal('us-east-1')
                  expect(results[0].message).to.include('EC2 instance is not associated with default security group');
                  done();
              });
          });

          it('should FAIL if EC2 is associated with default security group', function (done) {
              const cache = createCache([describeInstances[1]]);
              ec2AssociatedWithDefaultSG.run(cache, {}, (err, results) => {
                  expect(results.length).to.equal(1);
                  expect(results[0].status).to.equal(2);
                  expect(results[0].region).to.equal('us-east-1')
                  expect(results[0].message).to.include('EC2 instance is associated with default security group');
                  done();
              });
          });
```

2023-03-06 11:24 UTC, AkhtarAmir commented on plugins/aws/ec2/defaultSecurityGroupInUse.spec.js
> +              });
```suggestion
          // it('should FAIL if EC2 is associated with default security group', function (done) {
          //    const cache = createCache([describeInstances[1]]);
          //    ec2AssociatedWithDefaultSG.run(cache, {}, (err, results) => {
          //        expect(results.length).to.equal(1);
          //        expect(results[0].status).to.equal(2);
          //        expect(results[0].region).to.equal('us-east-1')
          //        expect(results[0].message).to.include('EC2 instance is associated with default security group');
          //        done();
          //    });
```

2023-03-06 11:24 UTC, AkhtarAmir commented on plugins/aws/ec2/defaultSecurityGroupInUse.spec.js
> +          });
```suggestion
          // });
```

2023-03-06 14:41 UTC, AkhtarAmir approved these changes

2023-03-06 14:43 UTC, AkhtarAmir approved these changes

2023-03-06 14:45 UTC, merged