es domain awareness
aquasecurity/cloudsploit pull request #1571
Opened 2023-02-28 12:04 UTC by abdullahaslam306

2023-02-28 21:03 UTC, alphadev4 commented on plugins/aws/es/esZoneAwarenessEnabled.js
> +            async.each(listDomainNames.data, function(domain, dcb){
```suggestion
           listDomainNames.data.forEach(function(domain){
```

2023-02-28 21:03 UTC, alphadev4 commented on plugins/aws/es/esZoneAwarenessEnabled.js
> +                    return dcb();
```suggestion
                    continue;
```

2023-02-28 21:05 UTC, alphadev4 commented on plugins/aws/es/esZoneAwarenessEnabled.js
> +            }, function(){
```suggestion
                });
```

2023-02-28 21:06 UTC, alphadev4 commented on plugins/aws/es/esZoneAwarenessEnabled.js
> +                });
```suggestion
              });
```

2023-02-28 21:07 UTC, alphadev4 commented on plugins/aws/es/esZoneAwarenessEnabled.js
> +            });
```suggestion
```

2023-02-28 21:08 UTC, alphadev4 commented on plugins/aws/es/esZoneAwarenessEnabled.js
> +                rcb();
```suggestion
            rcb();
```

2023-02-28 21:11 UTC, alphadev4 commented on plugins/aws/es/esZoneAwarenessEnabled.js
> +           listDomainNames.data.forEach(function(domain){
```suggestion
           for(var domain of listDomainNames.domain) {
```

2023-02-28 21:12 UTC, alphadev4 commented on plugins/aws/es/esZoneAwarenessEnabled.js
> +              });
```suggestion
              };
```

2023-02-28 21:12 UTC, alphadev4 commented on plugins/aws/es/esZoneAwarenessEnabled.js
> +                var describeElasticsearchDomain = helpers.addSource(cache, source,
```suggestion
                if (!domain.DomainName) continue;
                var describeElasticsearchDomain = helpers.addSource(cache, source,
```

2023-02-28 21:14 UTC, alphadev4 commented on plugins/aws/es/esZoneAwarenessEnabled.js
> +           for (var domain of listDomainNames.domain) {
```suggestion
            for (var domain of listDomainNames.domain) {
```

2023-02-28 21:14 UTC, alphadev4 commented on plugins/aws/es/esZoneAwarenessEnabled.js
> +              };
```suggestion
            };
```

2023-02-28 21:18 UTC, alphadev4 commented on plugins/aws/es/esZoneAwarenessEnabled.js
> +            for (var domain of listDomainNames.domain) {
```suggestion
            for (var domain of listDomainNames.data) {
```

2023-02-28 21:23 UTC, alphadev4 approved these changes

2023-06-15 13:07 UTC, AkhtarAmir commented on plugins/aws/es/esZoneAwarenessEnabled.js
> +
```suggestion
```

2023-06-15 13:09 UTC, AkhtarAmir commented on plugins/aws/es/esZoneAwarenessEnabled.js
> +                var describeElasticsearchDomain = helpers.addSource(cache, source,
```suggestion
                if (!domain.DomainName) continue;

                const resource = `arn:${awsOrGov}:es:${region}:${accountId}:domain/${domain.DomainName}`;

                var describeElasticsearchDomain = helpers.addSource(cache, source,
```

2023-06-15 13:09 UTC, AkhtarAmir commented on plugins/aws/es/esZoneAwarenessEnabled.js
> +        var regions = helpers.regions(settings);
```suggestion
        var regions = helpers.regions(settings);

        var accountId =  helpers.addSource(cache, source, ['sts', 'getCallerIdentity', accRegion, 'data']);
        var awsOrGov = helpers.defaultPartition(settings);
```

2023-06-15 13:10 UTC, AkhtarAmir commented on plugins/aws/es/esZoneAwarenessEnabled.js
> +
```suggestion
                        `Unable to query for ES domain config: ${helpers.addError(describeElasticsearchDomain)}`, region, resource);
                    continue;
                }

```

2023-06-15 13:11 UTC, AkhtarAmir commented on plugins/aws/es/esZoneAwarenessEnabled.js
> +                describeElasticsearchDomain.data.DomainStatus.ElasticsearchClusterConfig.ZoneAwarenessEnabled === true) {
```suggestion
      describeElasticsearchDomain.data.DomainStatus.ElasticsearchClusterConfig.ZoneAwarenessEnabled) {
```

2023-06-15 13:18 UTC, AkhtarAmir requested changes

2023-08-03 11:38 UTC, AkhtarAmir commented on plugins/aws/opensearch/opensearchZoneAwarenessEnabled.js
> +    description: 'Ensure that OpenSearch domains have zone awareness enabled',
```suggestion
    description: 'Ensure that OpenSearch domains have zone awareness enabled.',
```

2023-08-03 11:39 UTC, AkhtarAmir approved these changes

2023-08-03 13:20 UTC, merged