elbv2 cross zone enabled
aquasecurity/cloudsploit pull request #1590
Opened 2023-03-29 22:02 UTC by abdullahaslam306

2023-04-04 12:01 UTC, AkhtarAmir requested changes

2023-04-04 12:01 UTC, AkhtarAmir commented on plugins/aws/elbv2/elbv2crosszoneLoadBalancing.js
> +                elbv2Attributes.data.Attributes.forEach(attribute => {
do attributes.find and move helpers.addResult outside loop

2023-04-04 12:01 UTC, AkhtarAmir commented on plugins/aws/elbv2/elbv2crosszoneLoadBalancing.js
> +                if (!found) {
what is this for?

2023-04-05 10:12 UTC, alphadev4 commented on plugins/aws/elbv2/elbv2crosszoneLoadBalancing.js
> +                let found = elbv2Attributes.data.Attributes.find(attr => attr.Key === 'load_balancing.cross_zone.enabled' && attr.Value === 'true');
```suggestion
                let found = elbv2Attributes.data.Attributes.find(attr => attr.Key && attr.Key === 'load_balancing.cross_zone.enabled' && attr.Value && attr.Value === 'true');
```

2023-04-05 10:12 UTC, alphadev4 approved these changes

2023-04-05 10:49 UTC, AkhtarAmir commented on plugins/aws/elbv2/elbv2crosszoneLoadBalancing.spec.js
> +                done();
```suggestion
                expect(results[0].status).to.equal(0);
                expect(results[0].message).to.include('has cross-zone load balancing enabled');
                done();
```

2023-04-05 10:49 UTC, AkhtarAmir commented on plugins/aws/elbv2/elbv2crosszoneLoadBalancing.spec.js
> +                expect(results[0].status).to.equal(2);
```suggestion
                expect(results[0].status).to.equal(2);
                expect(results[0].message).to.include('does not have cross-zone load balancing enabled');
```

2023-04-05 10:49 UTC, AkhtarAmir approved these changes

2023-04-05 10:51 UTC, merged