Feature/saas 15348 azure ensure that enable infrastructure encryption for each storage account in azure storage is set to enabled
aquasecurity/cloudsploit pull request #1613
Opened 2023-05-01 15:45 UTC by abdullahaslam306

2023-06-05 14:54 UTC, mehakseedat63 requested changes

2023-06-05 14:54 UTC, mehakseedat63 commented on exports.js
> +        'infrastructureEncryptionEnabled': require(__dirname + '/plugins/azure/storageaccounts/infrastructureEncryptionEnabled.js'),
change plugin name to infrastructureEncryption
```suggestion
        'infrastructureEncryptionEnabled': require(__dirname + '/plugins/azure/storageaccounts/infrastructureEncryptionEnabled.js'),
```

2023-06-05 14:54 UTC, mehakseedat63 commented on plugins/azure/storageaccounts/infrastructureEncryptionEnabled.js
> +    description: 'Ensure that Azure Storage Accounts have Infrastructure Encryption Enabled.',
```suggestion
    description: 'Ensure that Azure Storage Accounts have infrastructure encryption enabled',
```

2023-06-05 14:54 UTC, mehakseedat63 commented on plugins/azure/storageaccounts/infrastructureEncryptionEnabled.js
> +                    helpers.addResult(results, 0, 'Storage Account have infrastructure encryption enabled', location, account.id);
```suggestion
                    helpers.addResult(results, 0, 'Storage Account has infrastructure encryption enabled', location, account.id);
```

2023-06-05 14:54 UTC, mehakseedat63 commented on plugins/azure/storageaccounts/infrastructureEncryptionEnabled.js
> +                    helpers.addResult(results, 2, 'Storage Account does have infrastructure encryption enabled', location, account.id);
```suggestion
                    helpers.addResult(results, 2, 'Storage Account does not have infrastructure encryption enabled', location, account.id);
```

2023-06-06 21:55 UTC, mehakseedat63 approved these changes

2023-06-14 10:47 UTC, AkhtarAmir commented on plugins/azure/storageaccounts/infrastructureEncryption.js
> +                if (!account.id) continue;
```suggestion
            }

            for (let account of storageAccount.data) {
                if (!account.id) continue;
```

2023-06-14 10:49 UTC, merged