Feature/ saas 15343 azure ensure an azure bastion host exists
aquasecurity/cloudsploit pull request #1614
Opened 2023-05-01 15:47 UTC by abdullahaslam306

2023-06-05 19:02 UTC, mehakseedat63 approved these changes

2023-06-13 18:12 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/bastionHostExist.js
> +    description: 'Ensure that Azure Bastion Host exists.',
```suggestion
    description: 'Ensure that there is at least one Bastion host in Azure subscription.',
```

2023-06-13 18:17 UTC, AkhtarAmir requested changes

2023-06-13 18:17 UTC, AkhtarAmir commented on exports.js
> +        'bastionHostExist'              : require(__dirname + '/plugins/azure/virtualmachines/bastionHostExist.js'),
```suggestion
        'bastionHostExists'              : require(__dirname + '/plugins/azure/virtualmachines/bastionHostExists.js'),
```

2023-06-13 18:17 UTC, AkhtarAmir commented on helpers/azure/api.js
> +    bastionHost: {
```suggestion
    bastionHosts: {
```

2023-06-13 18:17 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/bastionHostExist.js
> +                    helpers.addResult(results, 0, 'Azure bastion host exists', location, bastionHost.data[0].id);
```suggestion
                    helpers.addResult(results, 0, 'Azure bastion host exists', location);
```

2023-06-15 13:23 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/bastionHostExists.js
> +    category: 'Virtual Machines',
```suggestion
    category: 'Bastion Hosts',
```

2023-06-15 13:24 UTC, AkhtarAmir commented on exports.js
> +        'bastionHostExists'              : require(__dirname + '/plugins/azure/virtualmachines/bastionHostExists.js'),
```suggestion
        'bastionHostExists'              : require(__dirname + '/plugins/azure/bastion/bastionHostExists.js'),
```

2023-06-15 13:25 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/bastionHostExists.js
> +    category: 'Bastion Hosts',
```suggestion
    category: 'Bastion',
```

2023-06-15 13:29 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/bastionHostExists.js
> +                }
```suggestion
                if (bastionHost.data.length) {
                    helpers.addResult(results, 0, `There are ${bastionHost.data.length} Bastion hosts`, location);
                } else {
                    helpers.addResult(results, 2, 'No Bastion hosts found', location);
                }
```

2023-06-16 09:27 UTC, AkhtarAmir approved these changes

2023-06-16 09:41 UTC, AkhtarAmir commented on plugins/azure/bastion/bastionHostExists.js
> +                if (!bastionHost) return rcb();
```suggestion
            if (!bastionHost) return rcb();
```

2023-06-16 09:41 UTC, AkhtarAmir commented on plugins/azure/bastion/bastionHostExists.js
> +                if (bastionHost.err || !bastionHost.data) {
```suggestion
            if (bastionHost.err || !bastionHost.data) {
```

2023-06-16 09:41 UTC, AkhtarAmir commented on plugins/azure/bastion/bastionHostExists.js
> +                    helpers.addResult(results, 3, 'Unable to query for bastion host: ' + helpers.addError(bastionHost), location);
```suggestion
                helpers.addResult(results, 3, 'Unable to query for bastion host: ' + helpers.addError(bastionHost), location);
```

2023-06-16 09:42 UTC, AkhtarAmir commented on plugins/azure/bastion/bastionHostExists.js
> +                    return rcb();
```suggestion
                return rcb();
```

2023-06-16 09:42 UTC, AkhtarAmir commented on plugins/azure/bastion/bastionHostExists.js
> +                }
```suggestion
            }
```

2023-06-16 09:42 UTC, AkhtarAmir commented on plugins/azure/bastion/bastionHostExists.js
> +                if (bastionHost.data.length) {
```suggestion
            if (bastionHost.data.length) {
```

2023-06-16 09:42 UTC, AkhtarAmir commented on plugins/azure/bastion/bastionHostExists.js
> +                    helpers.addResult(results, 0, `There are ${bastionHost.data.length} Bastion hosts`, location);
```suggestion
                helpers.addResult(results, 0, `There are ${bastionHost.data.length} Bastion hosts`, location);
```

2023-06-16 09:43 UTC, AkhtarAmir commented on plugins/azure/bastion/bastionHostExists.js
> +                } else {
```suggestion
            } else {
```

2023-06-16 09:43 UTC, AkhtarAmir commented on plugins/azure/bastion/bastionHostExists.js
> +                    helpers.addResult(results, 2, 'No Bastion hosts found', location);
```suggestion
                helpers.addResult(results, 2, 'No Bastion hosts found', location);
```

2023-06-16 09:43 UTC, AkhtarAmir commented on plugins/azure/bastion/bastionHostExists.js
> +                }
```suggestion
            }
```

2023-06-16 09:44 UTC, AkhtarAmir commented on plugins/azure/bastion/bastionHostExists.js
> +
```suggestion
```

2023-06-16 09:45 UTC, AkhtarAmir commented on plugins/azure/bastion/bastionHostExists.js
> +                    ['bastionHosts', 'listAll', location]);
```suggestion
                ['bastionHosts', 'listAll', location]);
```

2023-06-16 09:47 UTC, merged