Feature/saas 15381 ensure that SKU basic consumption is not used on artifacts that need to be monitored
aquasecurity/cloudsploit pull request #1615
Opened 2023-05-01 16:09 UTC by abdullahaslam306

2023-06-05 19:01 UTC, mehakseedat63 requested changes

2023-06-05 19:01 UTC, mehakseedat63 commented on exports.js
> +        'resourceAppropriateSKU'        : require(__dirname + '/plugins/azure/monitor/monitorResourceSku.js'),
```suggestion
        'monitorResourceSKU'        : require(__dirname + '/plugins/azure/monitor/monitorResourceSku.js'),    
```

2023-06-05 19:01 UTC, mehakseedat63 commented on plugins/azure/monitor/monitorResourceSku.js
> +    description: 'Ensure that Basic or Consumption SKUs are not used on Artifacts that need to be Monitored.',
```suggestion
    description: 'Ensure that basic or consumption SKUs are not used on artifacts that need to be monitored',
```

2023-06-15 10:36 UTC, AkhtarAmir commented on plugins/azure/monitor/monitorResourceSku.js
> +    category: 'Monitor',
```suggestion
    category: 'Resources',
```

2023-06-15 10:36 UTC, AkhtarAmir commented on plugins/azure/monitor/monitorResourceSku.js
> +    domain: 'Management and Governance',
```suggestion
    domain: 'Application Integration',
```

2023-06-15 10:38 UTC, AkhtarAmir commented on plugins/azure/monitor/monitorResourceSku.js
> +                helpers.addResult(results, 0, 'No existing resource found', location);
```suggestion
                helpers.addResult(results, 0, 'No existing resources found', location);
```

2023-06-15 10:38 UTC, AkhtarAmir commented on plugins/azure/monitor/monitorResourceSku.js
> +
```suggestion
```

2023-06-15 10:39 UTC, AkhtarAmir commented on plugins/azure/monitor/monitorResourceSku.spec.js
> +                expect(results[0].message).to.include('Unable to query for resources:');
```suggestion
                expect(results[0].message).to.include('Unable to query for Resources:');
```

2023-06-15 10:39 UTC, AkhtarAmir commented on plugins/azure/monitor/monitorResourceSku.js
> +                    helpers.addResult(results, 2, `Azure Resource is using ${resource.sku.name} SKU`, location, resource.id);
```suggestion
                    helpers.addResult(results, 2, `Resource is using ${resource.sku.name} SKU`, location, resource.id);
```

2023-06-15 10:40 UTC, AkhtarAmir commented on plugins/azure/monitor/monitorResourceSku.js
> +                    helpers.addResult(results, 2, `Azure Resource is using ${resource.sku.name} SKU`, location, resource.id);
```suggestion
                    helpers.addResult(results, 2, `Resource is using ${resource.sku.name} SKU`, location, resource.id);
```

2023-06-15 10:40 UTC, AkhtarAmir commented on plugins/azure/monitor/monitorResourceSku.js
> +                    helpers.addResult(results, 0, `Azure Resource is using ${resource.sku.name} SKU`, location, resource.id);
```suggestion
                    helpers.addResult(results, 0, `Resource is using ${resource.sku.name} SKU`, location, resource.id);
```

2023-06-15 10:40 UTC, AkhtarAmir commented on plugins/azure/monitor/monitorResourceSku.spec.js
> +                expect(results[0].message).to.include('No existing resource found');
```suggestion
                expect(results[0].message).to.include('No existing Resources found');
```

2023-06-15 10:41 UTC, AkhtarAmir commented on plugins/azure/monitor/monitorResourceSku.spec.js
> +                expect(results[0].message).to.include('Azure Resource is using Standard_LRS');
```suggestion
                expect(results[0].message).to.include('Resource is using Standard_LRS');
```

2023-06-15 10:41 UTC, AkhtarAmir commented on plugins/azure/monitor/monitorResourceSku.spec.js
> +                expect(results[0].message).to.include('Azure Resource is using BASIC');
```suggestion
                expect(results[0].message).to.include('Resource is using BASIC');
```

2023-06-15 10:42 UTC, AkhtarAmir commented on plugins/azure/monitor/monitorResourceSku.js
> +            }
```suggestion
            if (!resources.data.length){
                helpers.addResult(results, 0, 'No existing Resources found', location);
                return rcb();
            }
```

2023-06-15 10:42 UTC, AkhtarAmir commented on plugins/azure/monitor/monitorResourceSku.js
> +                if (resource.sku && (resource.sku.name.toLowerCase() === 'basic' ||resource.sku.name.toLowerCase() === 'consumption')){
```suggestion
                if (resource.sku && resource.sku.name && (resource.sku.name.toLowerCase() === 'basic' ||resource.sku.name.toLowerCase() === 'consumption')){
```

2023-06-15 10:43 UTC, AkhtarAmir approved these changes

2023-06-15 10:48 UTC, mehakseedat63 approved these changes

2023-06-15 10:51 UTC, merged