storage account private endpoint
aquasecurity/cloudsploit pull request #1618
Opened 2023-05-01 17:02 UTC by abdullahaslam306

2023-06-05 11:14 UTC, mehakseedat63 requested changes

2023-06-05 11:14 UTC, mehakseedat63 commented on plugins/azure/storageaccounts/storageAccountPrivateEndpoint.js
> +    description: 'Ensure that Azure Storage Accounts are Accessible only through Private Endpoints.',
```suggestion
    description: 'Ensure that Azure Storage accounts are accessible only through private endpoints',
```

2023-06-15 09:19 UTC, AkhtarAmir commented on plugins/azure/storageaccounts/storageAccountPrivateEndpoint.js
> +            }
```suggestion
            }

            for (let account of storageAccount.data) {
                if (!account.id) continue;

                if (account.privateEndpointConnections && account.privateEndpointConnections.length){
                    helpers.addResult(results, 0, 'Private endpoints are configured for the storage account', location, account.id);
                } else {
                    helpers.addResult(results, 2, 'Private endpoints are not configured for the storage account', location, account.id);
                }
            }
```

2023-06-15 09:19 UTC, AkhtarAmir commented on plugins/azure/storageaccounts/storageAccountPrivateEndpoint.spec.js
> +                expect(results[0].message).to.include('Private Endpoints are configured for the storage account');
```suggestion
                expect(results[0].message).to.include('Private endpoints are configured for the storage account');
```

2023-06-15 09:19 UTC, AkhtarAmir commented on plugins/azure/storageaccounts/storageAccountPrivateEndpoint.spec.js
> +                expect(results[0].message).to.include('Private Endpoints are not configured for the storage account');
```suggestion
                expect(results[0].message).to.include('Private endpoints are not configured for the storage account');
```

2023-06-15 09:20 UTC, AkhtarAmir approved these changes

2023-06-15 09:29 UTC, mehakseedat63 approved these changes

2023-06-15 09:29 UTC, merged