plugin/opensearchVersionCheck
aquasecurity/cloudsploit pull request #1624
Opened 2023-05-19 11:16 UTC by fatima99s

2023-05-19 11:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1624) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1624) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=1624) it.</sub>

2023-05-19 11:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1624) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1624) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=1624) it.</sub>

2023-05-22 07:37 UTC, alphadev4 commented on exports.js
> +
```suggestion
```

2023-05-22 07:38 UTC, alphadev4 commented on plugins/aws/opensearch/opensearchVersion.js
> +    description: 'Checks if OpenSearch domains are running the latest  Engine version',
```suggestion
    description: 'Checks if OpenSearch domains are running the latest engine version',
```

2023-05-22 07:45 UTC, alphadev4 commented on plugins/aws/opensearch/opensearchVersion.js
> +    link: 'https://docs.aws.amazon.com/opensearch-service/latest/developerguide/features-by-version.html',
```suggestion
    link: 'https://docs.aws.amazon.com/opensearch-service/latest/developerguide/what-is.html',
```

2023-05-22 08:04 UTC, alphadev4 commented on plugins/aws/opensearch/opensearchVersion.js
> +    recommended_action: 'Ensure each OpenSearch domain is running the latest service software and update out-of-date domains.',
```suggestion
    recommended_action: 'Update OpenSearch domain to set to latest engine version.',
```

2023-05-22 08:05 UTC, alphadev4 commented on plugins/aws/opensearch/opensearchVersion.js
> +    link: 'https://docs.aws.amazon.com/opensearch-service/latest/developerguide/features-by-version.html',
link should be relevant

2023-05-22 08:05 UTC, alphadev4 commented on plugins/aws/opensearch/opensearchVersion.js
> +    recommended_action: 'Ensure each OpenSearch domain is running the latest service software and update out-of-date domains.',
Recommended action should contain the recommended step to remediate.

2023-05-22 08:06 UTC, alphadev4 commented on plugins/aws/opensearch/opensearchVersion.js
> +
avoid extra spaces

2023-06-05 18:56 UTC, mehakseedat63 requested changes

2023-06-05 18:56 UTC, mehakseedat63 commented on plugins/aws/opensearch/opensearchVersion.js
> +                    if (currentVersion.includes('Elasticsearch')) {
This check can be simplified by doing something like
```suggestion
                    if ((currentVersion.includes('Elasticsearch') && currentVersion.includes('7.10')) || (currentVersion.includes('OpenSearch') && currentVersion.includes('2.5'))) {
```

2023-06-05 21:45 UTC, mehakseedat63 requested changes
Fix linting issues

2023-06-06 09:32 UTC, mehakseedat63 approved these changes

2023-06-06 09:32 UTC, mehakseedat63 approved these changes

2023-06-13 21:45 UTC, merged