Rds default user name
aquasecurity/cloudsploit pull request #1625
Opened 2023-05-22 09:26 UTC by fatima99s

2023-05-22 09:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1625) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1625) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=1625) it.</sub>

2023-05-23 07:21 UTC, alphadev4 commented on plugins/aws/rds/rdsDefaultUserName.js
> +    title: 'RDS Instance Should Not Have Default Username',
```suggestion
    title: 'RDS Default Username',
```

2023-05-23 17:48 UTC, alphadev4 commented on plugins/aws/rds/rdsDefaultUserName.js
> +    description: 'Ensures RDS instance doest not have a default master username.',
```suggestion
    description: 'Ensures RDS instance does not have default master username.',
```

2023-05-23 18:07 UTC, alphadev4 commented on plugins/aws/rds/rdsDefaultUserName.js
> +                if (!instance.DBInstanceArn||!instance.MasterUsername) return;
```suggestion
                if (!instance.DBInstanceArn || !instance.MasterUsername) return;
```

2023-05-23 18:07 UTC, alphadev4 commented on plugins/aws/rds/rdsDefaultUserName.js
> +                    helpers.addResult(results, 2, 'RDS instance have a default master username',
```suggestion
                    helpers.addResult(results, 2, 'RDS instance has a default master username',
```

2023-05-23 18:08 UTC, alphadev4 commented on plugins/aws/rds/rdsDefaultUserName.spec.js
> +                expect(results[0].message).includes('RDS instance have a default master username');
```suggestion
                expect(results[0].message).includes('RDS instance has a default master username');
```

2023-05-30 08:56 UTC, alphadev4 commented on plugins/aws/rds/rdsDefaultUserName.js
> +                }else{
```suggestion
                } else {
```

2023-05-30 08:59 UTC, alphadev4 commented on plugins/aws/rds/rdsDefaultUserName.js
> +            describeDBInstances.data.forEach(instance=>{
```suggestion
            describeDBInstances.data.forEach(instance => {
```

2023-05-30 09:01 UTC, alphadev4 commented on plugins/aws/rds/rdsDefaultUserName.js
> +                    region, instance.DBInstanceArn);
```suggestion
                        region, instance.DBInstanceArn);
```

2023-05-30 09:01 UTC, alphadev4 commented on plugins/aws/rds/rdsDefaultUserName.js
> +                    region, instance.DBInstanceArn);
```suggestion
                        region, instance.DBInstanceArn);
```

2023-06-05 18:01 UTC, mehakseedat63 approved these changes

2023-06-13 21:44 UTC, mehakseedat63 requested changes
Resolve merge conflicts

2023-06-14 10:12 UTC, closed without merging