Apigateway authorization
aquasecurity/cloudsploit pull request #1627
Opened 2023-05-24 13:50 UTC by fatima99s

2023-05-30 08:37 UTC, alphadev4 commented on plugins/aws/apigateway/apigatewayAuthorization.js
> +    description: 'Ensures that Amazon API Gateway APIs are using authorizer.',
```suggestion
    description: 'Ensures that Amazon API Gateway APIs are using authorizer',
```

2023-05-30 08:49 UTC, alphadev4 requested changes

2023-05-30 08:49 UTC, alphadev4 commented on plugins/aws/apigateway/apigatewayAuthorization.js
> +                if (!api.id) return cb();
we cannot use return cb() inside the foreach loop , use retun statement instead

2023-06-14 10:48 UTC, mehakseedat63 requested changes
Fix linting issues

2023-06-14 10:48 UTC, mehakseedat63 commented on plugins/aws/apigateway/apigatewayAuthorization.js
> +                        return cb();
this should be just return
```suggestion
                        return;
```

2023-06-14 10:50 UTC, alphadev4 approved these changes

2023-06-14 12:22 UTC, mehakseedat63 commented on plugins/aws/apigateway/apigatewayAuthorization.js
> +                    return ;
```suggestion
                    return;
```

2023-06-14 12:23 UTC, mehakseedat63 approved these changes

2023-06-14 12:24 UTC, merged