acr public access
aquasecurity/cloudsploit pull request #1628
Opened 2023-05-24 19:19 UTC by abdullahaslam306

2023-06-05 11:08 UTC, mehakseedat63 requested changes

2023-06-05 11:08 UTC, mehakseedat63 commented on plugins/azure/containerregistry/acrPublicAccess.js
> +    more_info: 'Azure Container Registries should be not be publicly accessible to prevent unauthorized actions.',
```suggestion
    more_info: 'Azure Container registries should be not be publicly accessible to prevent unauthorized actions.',
```

2023-06-05 11:08 UTC, mehakseedat63 commented on plugins/azure/containerregistry/acrPublicAccess.js
> +    description: 'Ensures that Azure Container Registries are not Publicly Accessible.',
```suggestion
    description: 'Ensures that Azure Container registries are not publicly accessible',
```

2023-06-15 09:07 UTC, AkhtarAmir commented on plugins/azure/containerregistry/acrPublicAccess.js
> +    description: 'Ensures that Azure Container registries are not publicly accessible',
```suggestion
    description: 'Ensures that Azure Container registries are not publicly accessible.',
```

2023-06-15 09:08 UTC, AkhtarAmir commented on plugins/azure/containerregistry/acrPublicAccess.js
> +
```suggestion
```

2023-06-15 09:08 UTC, AkhtarAmir commented on plugins/azure/containerregistry/acrPublicAccess.js
> +                helpers.addResult(results, 0, 'No existing container registries found', location);
```suggestion
                helpers.addResult(results, 0, 'No existing Container registries found', location);
```

2023-06-15 09:09 UTC, AkhtarAmir commented on plugins/azure/containerregistry/acrPublicAccess.js
> +                    helpers.addResult(results, 2, 'Container Registry is publicly accessible', location, registry.id);
```suggestion
                    helpers.addResult(results, 2, 'Container registry is publicly accessible', location, registry.id);
```

2023-06-15 09:09 UTC, AkhtarAmir commented on plugins/azure/containerregistry/acrPublicAccess.js
> +                    helpers.addResult(results, 0, 'Container Registry is not publicly accessible', location, registry.id);
```suggestion
                    helpers.addResult(results, 0, 'Container registry is not publicly accessible', location, registry.id);
```

2023-06-15 09:10 UTC, AkhtarAmir commented on plugins/azure/containerregistry/acrPublicAccess.spec.js
> +                expect(results[0].message).to.include('No existing container registries found');
```suggestion
                expect(results[0].message).to.include('No existing Container registries found');
```

2023-06-15 09:10 UTC, AkhtarAmir commented on plugins/azure/containerregistry/acrPublicAccess.spec.js
> +                expect(results[0].message).to.include('Container Registry is publicly accessible');
```suggestion
                expect(results[0].message).to.include('Container registry is publicly accessible');
```

2023-06-15 09:10 UTC, AkhtarAmir commented on plugins/azure/containerregistry/acrPublicAccess.spec.js
> +                expect(results[0].message).to.include('Container Registry is not publicly accessibl');
```suggestion
                expect(results[0].message).to.include('Container registry is not publicly accessibl');
```

2023-06-15 09:11 UTC, AkhtarAmir commented on plugins/azure/containerregistry/acrPublicAccess.js
> +            for (let registry of registries.data){
```suggestion
            }

            for (let registry of registries.data){
```

2023-06-15 09:11 UTC, AkhtarAmir approved these changes

2023-06-15 09:11 UTC, AkhtarAmir approved these changes

2023-06-15 09:12 UTC, mehakseedat63 approved these changes

2023-06-15 09:13 UTC, merged