plugin for elb Unhealthy Instances
aquasecurity/cloudsploit pull request #1634
Opened 2023-05-26 11:31 UTC by fatima99s

2023-05-26 12:07 UTC, fatima99s commented on exports.js
> +};
```suggestion
};

```

2023-05-29 17:41 UTC, alphadev4 commented on plugins/aws/elb/elbUnhealthyInstances.js
> +    description: 'Detects ELBs that have unhealthy instances attached',
```suggestion
    description: 'Ensures that AWS ELBs have healthy instances attached',
```

2023-05-29 17:50 UTC, alphadev4 commented on plugins/aws/elb/elbUnhealthyInstances.js
> +    more_info: 'ELBs should have healthy instances attached to ensure proper load balancing and availability. Unhealthy instances can indicate issues with the backend server resources.',
```suggestion
    more_info: 'ELBs should have healthy instances attached to ensure proper load balancing and availability. The status of the instances that are healthy should be InService.',
```

2023-05-29 17:53 UTC, alphadev4 commented on plugins/aws/elb/elbUnhealthyInstances.js
> +    link: 'https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-healthchecks.html',
```suggestion
    link: 'https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-healthchecks.html#check-instance-health',
```

2023-05-29 18:08 UTC, alphadev4 requested changes

2023-06-13 21:58 UTC, mehakseedat63 requested changes

2023-06-13 21:58 UTC, mehakseedat63 commented on plugins/aws/elb/elbUnhealthyInstances.js
> +                    helpers.addResult(results, 0, `ELB does not have unhealthy instance`, region, elbArn);
```suggestion
                    helpers.addResult(results, 0, 'ELB does not have unhealthy instance', region, elbArn);
```

2023-06-13 22:00 UTC, mehakseedat63 approved these changes

2023-06-13 22:01 UTC, mehakseedat63 requested changes
Fix the failing test

2023-06-14 10:00 UTC, mehakseedat63 approved these changes

2023-06-14 10:45 UTC, alphadev4 approved these changes

2023-06-14 12:24 UTC, merged