Feature/saas 16593 azure azure recovery services vaults should use customer managed keys for encrypting backup data
aquasecurity/cloudsploit pull request #1636
Opened 2023-05-29 20:19 UTC by abdullahaslam306

2023-05-31 09:26 UTC, alphadev4 commented on exports.js
> +        'rsvCmkEncryption'             : require(__dirname + '/plugins/azure/recoveryService/rsvCmkEncryption.js')
```suggestion
        'rsvCmkEncryption'              : require(__dirname + '/plugins/azure/recoveryService/rsvCmkEncryption.js')
```

2023-06-04 13:44 UTC, AkhtarAmir requested changes

2023-06-04 13:44 UTC, AkhtarAmir commented on plugins/azure/recoveryService/rsvCmkEncryption.js
> +    more_info: 'A customer-managed key gives you the ownership to bring your own key in Azure Key Vault. When you enable a customer-managed key, you can manage its rotations, control the access and p
```suggestion
    more_info: 'A customer-managed key gives you the ownership to bring your own key in Azure Key Vault. When you enable a customer-managed key, you can manage its rotations, control the access and permissions to use it, and audit its use.',
```

2023-06-14 08:46 UTC, AkhtarAmir commented on exports.js
> +        'recoveryVaultByokEncrypted'              : require(__dirname + '/plugins/azure/recoveryService/recoveryVaultByokEncrypted.js')
```suggestion
        'recoveryVaultByokEncrypted'     : require(__dirname + '/plugins/azure/recoveryService/recoveryVaultByokEncrypted.js')
```

2023-06-14 08:47 UTC, AkhtarAmir commented on exports.js
> +        'recoveryVaultByokEncrypted'     : require(__dirname + '/plugins/azure/recoveryService/recoveryVaultByokEncrypted.js')
```suggestion
        'recoveryVaultByokEncrypted'    : require(__dirname + '/plugins/azure/recoveryService/recoveryVaultByokEncrypted.js')
```

2023-06-14 08:48 UTC, AkhtarAmir commented on plugins/azure/recoveryService/recoveryVaultByokEncrypted.js
> +                    'Unable to query for list Recovery Service vaults: ' + helpers.addError(serviceVaults), location);
```suggestion
                    'Unable to list Recovery Service vaults: ' + helpers.addError(serviceVaults), location);
```

2023-06-14 08:48 UTC, AkhtarAmir commented on plugins/azure/recoveryService/recoveryVaultByokEncrypted.spec.js
> +                expect(results[0].message).to.include('Unable to query for list Recovery Service vaults:');
```suggestion
                expect(results[0].message).to.include('Unable to list Recovery Service Vaults:');
```

2023-06-14 08:49 UTC, AkhtarAmir commented on plugins/azure/recoveryService/recoveryVaultByokEncrypted.js
> +            rcb();
```suggestion
            }

            rcb();
```

2023-06-14 08:51 UTC, AkhtarAmir approved these changes

2023-06-14 08:55 UTC, merged