plugin for rds instance using order generation of ec2
aquasecurity/cloudsploit pull request #1639
Opened 2023-05-31 10:43 UTC by fatima99s

2023-06-05 16:45 UTC, mehakseedat63 approved these changes

2023-06-05 16:47 UTC, mehakseedat63 requested changes
Fix linting issues

2023-06-05 17:28 UTC, fatima99s commented on plugins/aws/rds/rdsInstanceGeneration.js
> +}
};

2023-06-05 17:29 UTC, mehakseedat63 commented on plugins/aws/rds/rdsInstanceGeneration.js
> +}
```suggestion
};
```

2023-06-05 17:29 UTC, fatima99s commented on plugins/aws/rds/rdsInstanceGeneration.js
> +}
};

2023-06-05 17:30 UTC, mehakseedat63 approved these changes

2023-06-13 21:38 UTC, mehakseedat63 approved these changes

2023-06-13 21:38 UTC, merged