plugin to check if ec2 instance have exceeded the alarm threshold for…
aquasecurity/cloudsploit pull request #1646
Opened 2023-06-09 12:01 UTC by fatima99s

… cpu utilization

2023-06-13 19:25 UTC, mehakseedat63 requested changes

2023-06-13 19:25 UTC, mehakseedat63 commented on plugins/aws/ec2/overutilizedEC2Instance.js
> +    description: 'Identify EC2 instances that have exceeded the alarm threshold for CPU utilization.',
Change it to something like
```suggestion
    description: 'Ensure EC2 instances do not exceed the alarm threshold for CPU utilization.',
```

2023-06-13 19:25 UTC, mehakseedat63 commented on plugins/aws/ec2/overutilizedEC2Instance.js
> +        var cpuThreshold = 90;
This should be a user input

2023-06-13 19:25 UTC, mehakseedat63 commented on plugins/aws/ec2/overutilizedEC2Instance.js
> +                                `CPU threshold exceeded - Current CPU utilization: ${cpuUtilization}%`, region, resource);
Can we change this to something like
```suggestion
                                `EC2 instance has current CPU utilization of ${cpuUtilization}% which exceeds the CPU threshold`, region, resource);
```

2023-06-13 19:25 UTC, mehakseedat63 commented on plugins/aws/ec2/overutilizedEC2Instance.js
> +                                `CPU threshold not exceeded - Current CPU utilization: ${cpuUtilization}%`, region, resource);
something like
```suggestion
                                `EC2 instance has current CPU utilization of ${cpuUtilization}% which does not exceed the CPU threshold`, region, resource);
```

2023-06-13 19:25 UTC, mehakseedat63 commented on plugins/aws/ec2/overutilizedEC2Instance.js
> +    description: 'Identify EC2 instances that have exceeded the alarm threshold for CPU utilization.',
Change this to something like
```suggestion
    description: 'Ensure EC2 instances do not exceed the alarm threshold for CPU utilization.',
```

2023-06-13 19:25 UTC, mehakseedat63 commented on plugins/aws/ec2/overutilizedEC2Instance.js
> +        var cpuThreshold = 90;
This should be a user input

2023-06-13 19:25 UTC, mehakseedat63 commented on plugins/aws/ec2/overutilizedEC2Instance.js
> +                                `CPU threshold exceeded - Current CPU utilization: ${cpuUtilization}%`, region, resource);
can we change this to something like
```suggestion
                                `EC2 instance has current CPU utilization of ${cpuUtilization}% which exceeds the CPU threshold`, region, resource);
```

2023-06-13 19:25 UTC, mehakseedat63 commented on plugins/aws/ec2/overutilizedEC2Instance.js
> +                                `CPU threshold not exceeded - Current CPU utilization: ${cpuUtilization}%`, region, resource);
change this to something like
```suggestion
                                `EC2 instance has current CPU utilization of ${cpuUtilization}% which does not exceed the CPU threshold`, region, resource);
```

2023-06-13 19:58 UTC, fatima99s commented on plugins/aws/ec2/overutilizedEC2Instance.js
> +        var cpuThreshold = 90;
do i need to write settings for this?

2023-06-14 08:50 UTC, mehakseedat63 commented on plugins/aws/ec2/overutilizedEC2Instance.js
> +        var cpuThreshold = 90;
yes

2023-06-15 09:35 UTC, mehakseedat63 requested changes

2023-06-15 09:35 UTC, mehakseedat63 commented on plugins/aws/ec2/overutilizedEC2Instance.js
> +    link: 'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-cloudwatch.html',
```suggestion
    link: 'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/viewing_metrics_with_cloudwatch.html#ec2-cloudwatch-metrics',
```

2023-06-15 09:37 UTC, mehakseedat63 approved these changes

2023-06-15 09:38 UTC, merged