rdsPublicSubnets
aquasecurity/cloudsploit pull request #1696
Opened 2023-08-24 12:16 UTC by fatima99s

2023-09-04 12:21 UTC, mehakseedat63 requested changes

2023-09-04 12:21 UTC, mehakseedat63 commented on plugins/aws/rds/rdsPublicSubnet.js
> +                    helpers.addResult(results, 2, 'RDS instance has public subnets', region, dbResource);
```suggestion
                    helpers.addResult(results, 2, 'RDS instance is in a public subnet', region, dbResource);
```

2023-09-04 14:04 UTC, mehakseedat63 approved these changes

2023-09-05 08:34 UTC, AkhtarAmir commented on plugins/aws/rds/rdsPublicSubnet.js
> +    description: 'Ensures RDS is not deployed on public subnet.',
```suggestion
    description: 'Ensures RDS database instances are not deployed in public subnet.',
```

2023-09-05 08:36 UTC, AkhtarAmir commented on plugins/aws/rds/rdsPublicSubnet.js
> +                const allPrivate = subnetsData.every(subnet => privateSubnets.includes(subnet.SubnetIdentifier));
```suggestion

                const dbResource = instance.DBInstanceArn;
                const subnetsData = instance.DBSubnetGroup.Subnets;
                const allPrivate = subnetsData.every(subnet => privateSubnets.includes(subnet.SubnetIdentifier));
```

2023-09-05 08:37 UTC, AkhtarAmir commented on plugins/aws/rds/rdsPublicSubnet.js
> +            rcb();
```suggestion
            });

            rcb();
```

2023-09-05 16:09 UTC, merged