defaultrdsport
aquasecurity/cloudsploit pull request #1697
Opened 2023-08-24 12:18 UTC by fatima99s

2023-09-04 12:18 UTC, mehakseedat63 requested changes

2023-09-04 12:18 UTC, mehakseedat63 commented on plugins/aws/rds/rdsDefaultPort.js
> +                    helpers.addResult(results, 2, 'RDS instance has default port',
```suggestion
                    helpers.addResult(results, 2, 'RDS instance is running on default port',
```

2023-09-04 12:18 UTC, mehakseedat63 commented on plugins/aws/rds/rdsDefaultPort.js
> +                    helpers.addResult(results, 0, 'RDS instance does not have default port',
```suggestion
                    helpers.addResult(results, 0, 'RDS instance is not running on default port',
```

2023-09-04 12:18 UTC, mehakseedat63 commented on plugins/aws/rds/rdsDefaultPort.js
> +                    !(instance.Endpoint && instance.Endpoint.Port)) continue;
Why can't we make it one check?

2023-09-04 14:07 UTC, mehakseedat63 requested changes

2023-09-04 14:07 UTC, mehakseedat63 commented on plugins/aws/rds/rdsDefaultPort.js
> +    more_info: 'Running RDS instances on default ports represent a potential security concern. Moving RDS instances ports to non-default ports will add an extra layer of security, protecting publicly
```suggestion
    more_info: 'Running RDS instances on default ports represent a potential security concern. Moving RDS instances ports to non-default ports will add an extra layer of security, protecting publicly accessible AWS RDS databases from brute force and dictionary attacks.',
```


rephrase this

2023-09-04 14:45 UTC, mehakseedat63 approved these changes

2023-09-04 14:50 UTC, mehakseedat63 requested changes

2023-09-05 08:32 UTC, AkhtarAmir requested changes

2023-09-05 08:32 UTC, AkhtarAmir commented on plugins/aws/rds/rdsDefaultPort.js
> +            { 'engine': 'oracle-ee', 'port': 1521 },
Why do we need redundancy? We can have just 1 value for oracle databases. Same goes for sqlserver

2023-09-05 12:17 UTC, AkhtarAmir approved these changes

2023-09-05 12:18 UTC, mehakseedat63 approved these changes

2023-09-05 16:06 UTC, merged