AWS - Idle rds instance
aquasecurity/cloudsploit pull request #1699
Opened 2023-08-25 08:31 UTC by fatima99s

2023-09-04 11:21 UTC, mehakseedat63 requested changes

2023-09-04 14:10 UTC, mehakseedat63 approved these changes

2023-09-04 14:11 UTC, mehakseedat63 commented on plugins/aws/rds/idleRDSInstance.js
> +            description: 'Return a failing result when consumed RDS instance write IOPS threshold equal to or less than this percentage',
```suggestion
            description: 'Return a failing result when consumed RDS instance cpu threshold is equal to or less than this percentage',
            regex: '^(100|[1-9][0-9]?)$', 
            default: '1.0'
        },
        rds_idle_instance_readIOPS_percentage: {
            name: 'RDS Idle Instance Average Read IOPS Percentage',
            description: 'Return a failing result when consumed RDS instance read IOPS threshold is equal to or less than this percentage',
            regex: '^(100|[1-9][0-9]?)$', 
            default: '20'
        },
        rds_idle_instance_writeIOPS_percentage: {
            name: 'RDS Idle Instance Average Write IOPS Percentage',
            description: 'Return a failing result when consumed RDS instance write IOPS threshold is equal to or less than this percentage',
```

2023-09-04 14:12 UTC, mehakseedat63 requested changes

2023-09-04 14:12 UTC, mehakseedat63 commented on plugins/aws/rds/idleRDSInstance.js
> +            description: 'Return a failing result when consumed RDS instance write IOPS threshold equal to or less than this percentage',
```suggestion
            name: 'RDS Idle Instance Average CPU Usage Percentage',
            description: 'Return a failing result when consumed RDS instance cpu threshold is equal to or less than this percentage',
            regex: '^(100|[1-9][0-9]?)$', 
            default: '1.0'
        },
        rds_idle_instance_readIOPS_percentage: {
            name: 'RDS Idle Instance Average Read IOPS Percentage',
            description: 'Return a failing result when consumed RDS instance read IOPS threshold is equal to or less than this percentage',
            regex: '^(100|[1-9][0-9]?)$', 
            default: '20'
        },
        rds_idle_instance_writeIOPS_percentage: {
            name: 'RDS Idle Instance Average Write IOPS Percentage',
            description: 'Return a failing result when consumed RDS instance write IOPS threshold is equal to or less than this percentage',
```

2023-09-04 14:15 UTC, mehakseedat63 approved these changes

2023-09-05 08:28 UTC, AkhtarAmir requested changes

2023-09-05 08:28 UTC, AkhtarAmir commented on plugins/aws/rds/idleRDSInstance.js
> +                if (!getRdsWriteIOPSMetricStatistics.data.Datapoints.length) {
This is not right. This will produce multiple results for same resource.

2023-09-05 08:28 UTC, AkhtarAmir commented on plugins/aws/rds/idleRDSInstance.js
> +    description: 'Ensure there are no RDS instances with CPU utilization below defined threshold within last 7 days.',
```suggestion
    description: 'Ensure there are no RDS instances with CPU utilization below any of the defined thresholds within last 7 days.',
```

2023-09-05 12:22 UTC, AkhtarAmir requested changes

2023-09-05 12:22 UTC, AkhtarAmir commented on plugins/aws/rds/idleRDSInstance.js
> +                if (!getRdsReadIOPSMetricStatistics.data.Datapoints.length) {
Even if they are not available, we can check other datapoints. We should return only when all 3 datapoints are not available.

2023-09-05 16:10 UTC, AkhtarAmir commented on plugins/aws/rds/idleRDSInstance.js
> +    description: 'Ensure there are no RDS instances with CPU utilization below any of the defined thresholds within last 7 days.',
```suggestion
    description: 'Ensure there are no RDS instances with CPU utilization below all of the defined thresholds within last 7 days.',
```

2023-09-05 16:13 UTC, AkhtarAmir approved these changes

2023-09-05 17:33 UTC, merged