Feature/app mesh vg health checks
aquasecurity/cloudsploit pull request #1702
Opened 2023-08-25 13:38 UTC by muzzamilinovaqo

2023-08-25 13:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1702) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1702) before we can accept your contribution.<br/><hr/>**muzzamilinovaqo** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=1702) it.</sub>

2023-09-04 10:36 UTC, mehakseedat63 requested changes

2023-09-04 10:36 UTC, mehakseedat63 commented on plugins/aws/appmesh/appmeshVGHealthChecks.js
> +                }
```suggestion
                if (!listVirtualGateways.data.virtualGateways || !listVirtualGateways.data.virtualGateways.length) {
                    helpers.addResult(results, 0,
                        'No App Mesh virtual gateways found', region, resource);
                    continue;
                }
```

virtualGateways has an empty array if there are no gateways

2023-09-04 10:36 UTC, mehakseedat63 commented on plugins/aws/appmesh/appmeshVGHealthChecks.js
> +                                listener.healthCheck.timeoutMillis && listener.healthCheck.unhealthyThreshold;
```suggestion
                            return listener.healthCheck && Object.keys(listener.healthCheck).length;
```

maybe we should just check if healthCheck exists and not each field specifically

2023-09-05 13:38 UTC, AkhtarAmir requested changes

2023-09-05 13:38 UTC, AkhtarAmir commented on plugins/aws/appmesh/appmeshVGHealthChecks.js
> +                        !describeVirtualGateway.data.virtualGateway.spec.listeners) {
We should have a separate check for length of listeners and if length is 0 then return a passing result

2023-09-05 13:40 UTC, mehakseedat63 requested changes

2023-09-05 13:40 UTC, mehakseedat63 commented on plugins/aws/appmesh/appmeshVGHealthChecks.js
> +                        continue;
There should be a separate check to see if there are no listeners, and it should pass with 'No listeners found'

2023-09-05 17:46 UTC, mehakseedat63 approved these changes

2023-09-05 17:47 UTC, merged