added tiggers for E
aquasecurity/cloudsploit pull request #1717
Opened 2023-09-14 10:35 UTC by fatima99s

2023-09-14 12:53 UTC, muzzamilinovaqo commented on plugins/aws/ec2/allowedCustomPorts.js
> +    realtime_triggers: ['ec2:AuthorizeSecurityGroupIngress', 'ec2:ModifySecurityGroupRules'],
```suggestion
    realtime_triggers: ['ec2:CreateSecurityGroup,ec2:AuthorizeSecurityGroupIngress', 'ec2:ModifySecurityGroupRules'],
```

2023-09-18 14:43 UTC, muzzamilinovaqo commented on plugins/aws/emr/emrClusterLogging.js
> +    realtime_triggers: ['emr:CreateCluster'],
```suggestion
    realtime_triggers: ['emr:CreateCluster','emr:TerminateJobFlows'],
```

2023-09-18 14:43 UTC, muzzamilinovaqo commented on plugins/aws/emr/emrEncryptionAtRest.js
> +    realtime_triggers: ['emr:CreateCluster', 'emr:CreateSecurityConfiguration'],
```suggestion
    realtime_triggers: ['emr:CreateCluster', 'emr:CreateSecurityConfiguration','emr:DeleteSecurityConfiguration'],
```

2023-09-18 14:43 UTC, muzzamilinovaqo commented on plugins/aws/emr/emrEncryptionInTransit.js
> +    realtime_triggers: ['emr:CreateCluster', 'emr:CreateSecurityConfiguration'],
```suggestion
    realtime_triggers: ['emr:CreateCluster', 'emr:CreateSecurityConfiguration','emr: DeleteSecurityConfiguration'],
```

2023-09-18 14:43 UTC, muzzamilinovaqo commented on plugins/aws/eventbridge/eventBusCrossAccountAccess.js
> +    realtime_triggers: ['eventbridge:CreateEventBus'],
```suggestion
    realtime_triggers: ['eventbridge:CreateEventBus','eventbridge:PutPermission'],
```

2023-09-18 14:43 UTC, muzzamilinovaqo commented on plugins/aws/eventbridge/eventBusPublicAccess.js
> +    realtime_triggers: ['eventbridge:CreateEventBus', 'eventbridge:PutRule', 'eventbridge:PutTarget'],
```suggestion
    realtime_triggers: ['eventbridge:CreateEventBus','eventbridge:PutPermission', 'eventbridge:PutRule', 'eventbridge:PutTarget'],
```

2023-12-27 03:12 UTC, mehakseedat63 requested changes
need to verify elasticloadbalancing events

2023-12-27 03:12 UTC, mehakseedat63 commented on plugins/aws/eventbridge/eventsInUse.js
> +    realtime_triggers: ['eventbridge:PutRules', 'eventbridge:EnableRule', 'eventbridge:DeleteRule'],
```suggestion
    realtime_triggers: ['eventbridge:PutRule', 'eventbridge:EnableRule', 'eventbridge:DeleteRule'],
```

2023-12-27 03:12 UTC, mehakseedat63 commented on plugins/aws/elb/elbHttpsOnly.js
> +    realtime_triggers: ['elb:CreateLoadBalancerListeners','elb:CreateLoadBalancer', 'elb:DeleteLoadBalancer', 'elb:DeleteLoadBalancerListeners'],
```suggestion
    realtime_triggers: ['elb:CreateLoadBalancerListeners','elb:CreateLoadBalancer', 'elb:DeleteLoadBalancer', 'elb:DeleteLoadBalancerListeners'],
```
```suggestion
    realtime_triggers: ['elb:CreateLoadBalancerListeners','elb:CreateLoadBalancer', 'elb:DeleteLoadBalancer', 'elb:DeleteLoadBalancerListeners'],
```
why did we change it from 'elasticloadbalancing' to 'elb'?

2023-12-27 07:58 UTC, mehakseedat63 approved these changes

2024-01-01 22:13 UTC, merged