L m n o tiggers
aquasecurity/cloudsploit pull request #1719
Opened 2023-09-14 11:38 UTC by fatima99s

2023-09-14 13:22 UTC, AkhtarAmir requested changes

2023-09-14 13:22 UTC, AkhtarAmir commented on plugins/aws/msk/mskClusterEncryptionAtRest.js
> +    realtime_triggers: ['kafka:CreateCluster'],
KMS events?

2023-09-14 13:22 UTC, AkhtarAmir commented on plugins/aws/msk/mskClusterUnauthAccess.js
> +    realtime_triggers: ['kafka:CreateCluster','kafka:UpdateClusterConfiguration'],
```suggestion
    realtime_triggers: ['kafka:CreateCluster','kafka:UpdateSecurity'],
```

2023-09-14 13:22 UTC, AkhtarAmir commented on plugins/aws/mwaa/environmentDataEncrypted.js
> +    realtime_triggers: ['mwaa:CreateEnvironment'],
KMS events?

2023-09-14 13:22 UTC, AkhtarAmir commented on plugins/aws/neptune/neptuneDBInstanceEncrypted.js
> +    realtime_triggers: ['neptune:CreateDBCluster'],
KMS events

2023-09-14 13:22 UTC, AkhtarAmir commented on plugins/aws/neptune/neptuneDBInstanceEncrypted.js
> +    realtime_triggers: ['neptune:CreateDBCluster'],
Update event?

2023-09-14 13:22 UTC, AkhtarAmir commented on plugins/aws/openSearchServerless/opensearchCollectionCmkEncrypted.js
> +    realtime_triggers: ['opensearchserverless:CreateCollection'],
KMS events?

2023-09-14 13:22 UTC, AkhtarAmir commented on plugins/aws/openSearchServerless/opensearchCollectionPublicAccess.js
> +    realtime_triggers: ['opensearchserverless:CreateCollection', 'opensearchserverless:CreateSecurityPolicy', 'opensearchserverless:UpdateSecurityPolicy','opensearchserverless:DeleteSecurityPolicy'],
Why CreateSecurityPolicy

2023-12-26 09:02 UTC, alphadev4 approved these changes

2023-12-27 07:24 UTC, merged