added tiggers for p,q,r,w
aquasecurity/cloudsploit pull request #1720
Opened 2023-09-14 12:04 UTC by fatima99s

2023-09-18 13:22 UTC, AkhtarAmir requested changes

2023-09-18 13:22 UTC, AkhtarAmir commented on plugins/aws/redshift/auditLoggingEnabled.js
> +    realtime_triggers: ['redshift:CreateCluster', 'redshift:EditLogging'],
restoreFromClusterSnapshot

2023-09-18 13:22 UTC, AkhtarAmir commented on plugins/aws/route53/domainAutoRenew.js
> +    realtime_triggers: ['route53domains:RegisterDomain','route53domains:EnableAutoRenew'],
DisableDomainAutoRenew

2023-09-18 13:22 UTC, AkhtarAmir commented on plugins/aws/route53/domainTransferLock.js
> +    realtime_triggers: ['route53domains:RegisterDomain', 'route53Domain:EnableDomainTransferLock'],
disableDomainTransferLock

2023-09-18 13:27 UTC, fatima99s commented on plugins/aws/rds/rdsCmkEncryptionEnabled.js
> +    realtime_triggers: ['rds:CreateDBInstance', 'rds:RestoreDBInstanceFromDBSnapshot'],
we cant add the cmk encryption by modifying the db-instance

2023-09-25 09:24 UTC, AkhtarAmir approved these changes

2023-12-26 09:02 UTC, alphadev4 approved these changes

2023-12-27 02:36 UTC, merged