added tiggers for s annd t
aquasecurity/cloudsploit pull request #1721
Opened 2023-09-14 12:29 UTC by fatima99s

2023-09-14 14:31 UTC, AkhtarAmir requested changes

2023-09-14 14:31 UTC, AkhtarAmir commented on plugins/aws/s3/bucketEnforceEncryption.js
> +    realtime_triggers: ['s3:CreateBucket' , 's3:PutBucketPolicy'],
delete bucket policy?

2023-09-14 14:31 UTC, AkhtarAmir commented on plugins/aws/s3/bucketLifecycleConfiguration.js
> +    realtime_triggers: ['s3:CreateBucket', 's3:PutBucketLifeCycleConfiguration'],
deleteBucketLifecycle

2023-09-14 14:31 UTC, AkhtarAmir commented on plugins/aws/s3/bucketPolicyCloudFrontOac.js
> +    realtime_triggers: ['s3:CreateBucket', 'cloudfront:CreateDistribution', 'cloudfront:UpdateDistribution', 's3:PutBucketPolicy', 's3:DeleteBucketPolicy'],
```suggestion
    realtime_triggers: ['s3:CreateBucket', 's3:PutBucketPolicy', 's3:DeleteBucketPolicy'],
```

2023-09-14 14:31 UTC, AkhtarAmir commented on plugins/aws/s3/bucketPolicyCloudFrontOai.js
> +    realtime_triggers: ['s3:CreateBucket', 'cloudfront:CreateDistribution', 'cloudfront:UpdateDistribution', 's3:PutBucketPolicy', 's3:DeleteBucketPolicy'],
```suggestion
    realtime_triggers: ['s3:CreateBucket', 's3:PutBucketPolicy', 's3:DeleteBucketPolicy'],
```

2023-09-14 14:31 UTC, AkhtarAmir commented on plugins/aws/s3/bucketSecureTransportEnabled.js
> +    realtime_triggers: ['s3:CreateBucket', 's3:PutBucketPolicy'],
delete bucket policy

2023-09-14 14:31 UTC, AkhtarAmir commented on plugins/aws/s3/objectLevelReadEventLogging.js
> +    realtime_triggers: ['s3:CreateBucket', 'cloudtrail:CreateTrail', 'cloudtrail:PutEventSelectors', 'cloudtrail:PutInsightSelectors'],
What about update bucket

2023-09-14 14:31 UTC, AkhtarAmir commented on plugins/aws/s3/objectLevelWriteEventLogging.js
> +    realtime_triggers: ['s3:CreateBucket', 'cloudtrail:CreateTrail', 'cloudtrail:PutEventSelectors', 'cloudtrail:PutInsightSelectors'],
What about update bucket

2023-09-25 09:22 UTC, AkhtarAmir approved these changes

2023-11-17 09:33 UTC, AkhtarAmir approved these changes

2023-11-20 12:33 UTC, mehakseedat63 approved these changes

2023-11-20 12:34 UTC, merged