SAAS-20313/afd-detection-mode
aquasecurity/cloudsploit pull request #1742
Opened 2023-11-23 13:21 UTC by alphadev4

2023-11-29 12:58 UTC, alphadev4 commented on plugins/azure/frontdoor/frontDoorWafDetectionMode.js
> +    more_info: 'Azure Web Application Firewall (WAF) on Azure Front Door provides centralized protection of your web applications from common exploits and vulnerabilities. Web applications are increa
```suggestion
    more_info: 'Web Application Firewall (WAF) on Front Door provides centralized protection of your web applications from common exploits and vulnerabilities. Web applications are increasingly targeted by malicious attacks that exploit commonly known vulnerabilities. It monitors and logs the request and its matched WAF rule to WAF logs.',
```

2023-11-30 22:16 UTC, mehakseedat63 approved these changes

2023-11-30 22:16 UTC, mehakseedat63 commented
Fix failing test

2023-11-30 22:17 UTC, mehakseedat63 requested changes
Fix failing test

2023-12-04 17:50 UTC, mehakseedat63 approved these changes

2023-12-05 14:51 UTC, alphadev4 commented on exports.js
> +        'namespaceEncryptionAtRest'    : require(__dirname + '/plugins/azure/servicebus/namespaceEncryptionAtRest.js'),
```suggestion
        'namespaceEncryptionAtRest'     : require(__dirname + '/plugins/azure/servicebus/namespaceEncryptionAtRest.js'),
```

2023-12-05 15:03 UTC, merged