SAAS-20313/Front-Door-WAF-Logs-Enabled
aquasecurity/cloudsploit pull request #1747
Opened 2023-11-27 11:25 UTC by alphadev4

2023-11-27 11:25 UTC, alphadev4 commented on exports.js
> +};
```suggestion
};

```

2023-12-04 16:09 UTC, mehakseedat63 requested changes

2023-12-04 16:09 UTC, mehakseedat63 commented on plugins/azure/applicationGateway/agAccessLogsEnabled.js
> +    description: 'Ensures that Application Gateway Access Log is enabled.',
```suggestion
    description: 'Ensures that Application Gateway access logs are enabled.',
```

2023-12-04 16:09 UTC, mehakseedat63 commented on plugins/azure/applicationGateway/agAccessLogsEnabled.js
> +    recommended_action: 'Ensure that diagnostic setting for Application Gateway Access Log is enabled.',
```suggestion
    recommended_action: 'Ensure that diagnostic setting for Application Gateway access logs is enabled.',
```

2023-12-04 16:09 UTC, mehakseedat63 commented on plugins/azure/applicationGateway/agAccessLogsEnabled.js
> +                    helpers.addResult(results, 2, 'No existing Application Gateway diagnostics settings found', location, appGateway.id);
```suggestion
                } else if (!diagnosticSettings.data.length) {
                    helpers.addResult(results, 2, 'No existing Application Gateway diagnostics settings found', location, appGateway.id);
```
I think not found means that it's not enabled so we don't have to add this

2023-12-04 16:09 UTC, mehakseedat63 commented on plugins/azure/applicationGateway/agFirewallLogsEnabled.js
> +    description: 'Ensures that Application Gateway Firewall Log is enabled.',
```suggestion
    description: 'Ensures that Application Gateway Firewall logs are enabled.',
```

2023-12-04 16:09 UTC, mehakseedat63 commented on plugins/azure/applicationGateway/agFirewallLogsEnabled.js
> +    recommended_action: 'Ensure that diagnostic setting for Application Gateway Firewall Log is enabled.',
```suggestion
    recommended_action: 'Ensure that diagnostic setting for Application Gateway Firewall logs is enabled.',
```

2023-12-04 16:09 UTC, mehakseedat63 commented on plugins/azure/frontdoor/wafLogsEnabled.js
> +    description: 'Ensures that Azure Front Door WAF Log is enabled.',
```suggestion
    description: 'Ensures that Azure Front Door WAF logs are enabled.',
```

2023-12-04 16:09 UTC, mehakseedat63 commented on plugins/azure/frontdoor/wafLogsEnabled.js
> +    recommended_action: 'Ensure that diagnostic setting for Front Door WAF Log is enabled.',
```suggestion
    recommended_action: 'Ensure that diagnostic setting for Front Door WAF logs is enabled.',
```

2023-12-04 16:09 UTC, mehakseedat63 commented on plugins/azure/frontdoor/wafLogsEnabled.js
> +    link: 'https://learn.microsoft.com/en-us/azure/frontdoor/standard-premium/how-to-logs',
```suggestion
    link: 'https://learn.microsoft.com/en-us/azure/web-application-firewall/afds/waf-front-door-monitor?pivots=front-door-standard-premium',
```

2023-12-04 16:14 UTC, mehakseedat63 requested changes

2023-12-04 17:43 UTC, alphadev4 commented on helpers/azure/functions.js
> +    remediateOpenPortsHelper: remediateOpenPortsHelper,
```suggestion
    remediateOpenPortsHelper: remediateOpenPortsHelper
```

2023-12-04 17:51 UTC, mehakseedat63 approved these changes

2023-12-05 15:21 UTC, merged