added sql db diagnostic logging enabled
aquasecurity/cloudsploit pull request #1752
Opened 2023-11-28 10:00 UTC by muzzamilinovaqo

2023-11-28 10:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1752) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1752) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=1752) it.</sub>

2023-12-04 09:29 UTC, fatima99s commented on plugins/azure/sqldatabases/dbDiagnosticLoggingEnabled.js
> +    description: 'Enable diagnostic logging for enhanced monitoring and troubleshooting.',
Ensures diagnostic logging is enabled for SQL Databases.

2023-12-04 09:30 UTC, fatima99s commented on plugins/azure/sqldatabases/dbDiagnosticLoggingEnabled.js
> +    description: 'Enable diagnostic logging for enhanced monitoring and troubleshooting.',
```suggestion
    description: 'Ensures diagnostic logging is enabled for SQL Databases.',
```

2023-12-04 11:45 UTC, fatima99s commented on plugins/azure/sqldatabases/dbDiagnosticLoggingEnabled.js
> +                                    helpers.addResult(results, 2, 'diagnostic settings not configured for SQL database', location, database.id);
```suggestion
                                    helpers.addResult(results, 2, 'Diagnostic settings not configured for SQL database', location, database.id);
```

2023-12-04 11:45 UTC, fatima99s commented on plugins/azure/sqldatabases/dbDiagnosticLoggingEnabled.js
> +                                            helpers.addResult(results, 2, 'diagnostic settings are not configured with minimum requirements', location, settings.id);
```suggestion
                                            helpers.addResult(results, 2, 'Diagnostic settings are not configured with minimum requirements', location, settings.id);
```

2023-12-04 11:46 UTC, fatima99s commented on plugins/azure/sqldatabases/dbDiagnosticLoggingEnabled.js
> +                                                'diagnostic settings are configured with minimum requirements', location, settings.id);
```suggestion
                                                'Diagnostic settings are configured with minimum requirements', location, settings.id);
```

2023-12-05 13:16 UTC, mehakseedat63 requested changes
We don't need to look for specific settings, should pass if any kind of diagnostic logs are enabled. Look at other diagnostic logging plugins for reference.

2023-12-05 14:03 UTC, muzzamilinovaqo commented
> We don't need to look for specific settings, should pass if any kind of diagnostic logs are enabled. Look at other diagnostic logging plugins for reference.

The requirement is to have at least the mention settings enabled.

2023-12-05 16:36 UTC, alphadev4 commented on exports.js
> +        'frontDoorMinimumTlsVersion'    : require(__dirname + '/plugins/azure/frontdoor/frontDoorMinimumTlsVersion.js'),
```suggestion
        'frontDoorMinimumTlsVersion'    : require(__dirname + '/plugins/azure/frontdoor/frontDoorMinimumTlsVersion.js')
```

2023-12-05 16:40 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbDiagnosticLoggingEnabled.js
> +    title: 'Database Diagnostic Logging Enabled',
```suggestion
    title: 'SQL Diagnostic Logging Enabled',
```

2023-12-05 16:44 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbDiagnosticLoggingEnabled.js
> +    link: 'https://docs.microsoft.com/en-us/azure/sql-database/sql-database-monitoring-with-dmvs?tabs=sql-insights',
```suggestion
    link: 'https://learn.microsoft.com/en-us/azure/azure-sql/database/monitoring-sql-database-azure-monitor?view=azuresql',
```

2023-12-05 16:45 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbDiagnosticLoggingEnabled.js
> +    description: 'Ensure diagnostic logging is enabled for SQL databases.',
```suggestion
    description: 'Ensures diagnostic logging is enabled for SQL databases.',
```

2023-12-05 16:46 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbDiagnosticLoggingEnabled.js
> +    more_info: 'Enabling diagnostic logging provides valuable insights into SQL database performance and helps identify issues.',
```suggestion
    more_info: 'Enabling diagnostic logging provides valuable insights into SQL database that helps to monitor resources for their availability, performance, and operation.',
```

2023-12-05 16:48 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbDiagnosticLoggingEnabled.js
> +                                helpers.addResult(results, 3, 'Unable to query diagnostic settings: ' + helpers.addError(diagnosticSettings), location, database.id);
```suggestion
                                helpers.addResult(results, 3, 'Unable to query SQL database diagnostic settings: ' + helpers.addError(diagnosticSettings), location, database.id);
```

2023-12-05 16:52 UTC, alphadev4 commented
> > We don't need to look for specific settings, should pass if any kind of diagnostic logs are enabled. Look at other diagnostic logging plugins for reference.
> 
> The requirement is to have at least the mention settings enabled.

We still cannot produce results based on settings.id ? We should filter out the missing settings from recommended settings and then produce the result accordingly

2024-01-28 21:28 UTC, mehakseedat63 requested changes

2024-01-28 21:28 UTC, mehakseedat63 commented on plugins/azure/sqldatabases/dbDiagnosticLoggingEnabled.js
> +                            helpers.addResult(results, 2, `SQL database does not have diagnostic logs enabled ${missingConfig.length ? `for following: ${missingConfig}` : ''}`, location, database.id)
```suggestion
                            helpers.addResult(results, 2, `SQL database does not have diagnostic logs enabled ${missingConfig.length ? `for following: ${missingConfig,join(','}` : ''}`, location, database.id);
```

2024-01-28 21:30 UTC, mehakseedat63 requested changes

2024-01-28 21:30 UTC, mehakseedat63 commented on plugins/azure/sqldatabases/dbDiagnosticLoggingEnabled.js
> +    title: 'Database Diagnostic Logging Enabled',
```suggestion
    title: 'SQL Database Diagnostic Logging Enabled',
```

2024-01-28 21:30 UTC, mehakseedat63 commented on plugins/azure/sqldatabases/dbDiagnosticLoggingEnabled.js
> +    recommended_action: 'Enable diagnostic logging for SQL databases with the minimum required data recording settings: SQLInsights, Errors, Timeouts, Blocks, Deadlocks, Basic, InstanceAndAppAdvanced
```suggestion
    recommended_action: 'Enable diagnostic logging for all SQL databases.',
```

2024-01-28 21:30 UTC, mehakseedat63 commented on plugins/azure/sqldatabases/dbDiagnosticLoggingEnabled.js
> +        diagnostic_logs: {
```suggestion
        sqldb_diagnostic_logs: {
```
should make sure that this setting name is unique in all diagnostic log plugins

2024-02-19 00:57 UTC, merged