added sql db ledgerDigestStorageEnabled
aquasecurity/cloudsploit pull request #1753
Opened 2023-11-28 10:17 UTC by muzzamilinovaqo

2023-11-28 10:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1753) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1753) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=1753) it.</sub>

2023-12-05 15:40 UTC, alphadev4 commented on exports.js
> +        'frontDoorMinimumTlsVersion'    : require(__dirname + '/plugins/azure/frontdoor/frontDoorMinimumTlsVersion.js'),
```suggestion
        'frontDoorMinimumTlsVersion'    : require(__dirname + '/plugins/azure/frontdoor/frontDoorMinimumTlsVersion.js')
```

2023-12-05 15:46 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbLedgerDigestStorageEnabled.js
> +    link: 'https://docs.microsoft.com/en-us/azure/sql-database/sql-database-ledger-overview',
```suggestion
    link: 'https://learn.microsoft.com/en-us/sql/relational-databases/security/ledger/ledger-overview?view=sql-server-ver16',
```

2023-12-05 16:01 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbLedgerDigestStorageEnabled.js
> +                        databases.data.forEach(database=> {
```suggestion
                        databases.data.forEach(database => {
```

2023-12-05 16:02 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbLedgerDigestStorageEnabled.js
> +                                helpers.addResult(results, 3, 'Unable to query for Azure ledger: ' + helpers.addError(ledgerDigestUploads), location, database.id);
```suggestion
                                helpers.addResult(results, 3, 'Unable to query for Legder Digest Uploads for SQL servers: ' + helpers.addError(ledgerDigestUploads), location, database.id);
```

2023-12-05 16:05 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbLedgerDigestStorageEnabled.js
> +                                    helpers.addResult(results, 0, 'Automatic Ledger digest storage is enabled for SQL database', location, database.id);
```suggestion
                                    helpers.addResult(results, 0, 'Ledger automatic digest storage is enabled for SQL database', location, database.id);
```

2023-12-05 16:05 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbLedgerDigestStorageEnabled.js
> +                                    helpers.addResult(results, 2, 'Automatic Ledger digest storage is not enabled for SQL database', location, database.id);
```suggestion
                                    helpers.addResult(results, 2, 'Ledger automatic digest storage is not enabled for SQL database', location, database.id);
```

2023-12-05 16:06 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbLedgerDigestStorageEnabled.spec.js
> +                expect(results[0].message).to.include('Automatic Ledger digest storage is enabled for SQL database');
```suggestion
                expect(results[0].message).to.include('Ledger automatic digest storage is enabled for SQL database');
```

2023-12-05 16:06 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbLedgerDigestStorageEnabled.spec.js
> +                expect(results[0].message).to.include('Automatic Ledger digest storage is not enabled for SQL database');
```suggestion
                expect(results[0].message).to.include('Ledger automatic digest storage is not enabled for SQL database');
```

2023-12-05 16:07 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbLedgerDigestStorageEnabled.spec.js
> +                expect(results[0].message).to.include('Unable to query for Azure ledger');
```suggestion
                expect(results[0].message).to.include('Unable to query for Legder Digest Uploads for SQL database:');
```

2023-12-05 16:14 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbLedgerDigestStorageEnabled.js
> +    more_info: 'Configuring automatic Ledger digest storage allows for the generation and storage of digests for later verification.',
```suggestion
    more_info: 'Configuring Ledger automatic digest storage allows the generation and storage of digests for later verification. Automatic database digests are generated on a predefined interval of 30 seconds and uploaded to the selected storage service.',
```

2023-12-05 16:19 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbLedgerDigestStorageEnabled.js
> +    recommended_action: 'Configure an Azure Storage account or Azure Confidential Ledger for automatic Ledger digest storage. ',
```suggestion
    recommended_action: 'Modify SQL database ledger and add storage account for automatic digest storage.',
```

2023-12-06 08:14 UTC, muzzamilinovaqo commented on plugins/azure/sqldatabases/dbLedgerDigestStorageEnabled.js
> +    title: 'Ledger Digest Storage Enabled',
it's a feature of ledger that's why. Let me know if you still want me to change it.

2023-12-06 12:22 UTC, mehakseedat63 requested changes

2023-12-06 12:25 UTC, mehakseedat63 approved these changes

2023-12-06 12:25 UTC, merged