added sql db syncGroupPrivateLink
aquasecurity/cloudsploit pull request #1754
Opened 2023-11-28 10:18 UTC by muzzamilinovaqo

2023-11-28 10:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1754) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1754) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=1754) it.</sub>

2023-11-28 10:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1754) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1754) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=1754) it.</sub>

2023-12-04 11:51 UTC, fatima99s commented on plugins/azure/sqldatabases/dbSyncGroupPrivateLink.js
> +    title: 'Private Link Enabled for SQL Databases',
```suggestion
    title: 'SQL Databases Private Link Enabled',
```

2023-12-06 09:17 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbSyncGroupPrivateLink.js
> +    description: 'Ensures SQL Database sync groups use private link when SQL DB sync with others databases.',
```suggestion
    description: 'Ensures SQL Database sync groups are configured to use private link.',
```

2023-12-06 09:17 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbSyncGroupPrivateLink.js
> +    link: 'https://learn.microsoft.com/en-us/azure/private-link/private-link-overview',
```suggestion
    link: 'https://learn.microsoft.com/en-us/azure/azure-sql/database/sql-data-sync-data-sql-server-sql-database?view=azuresql',
```

2023-12-06 09:24 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbSyncGroupPrivateLink.js
> +    more_info: 'Private Link is the way to create Sync groups using secure connection with databases sitting behind a firewall. SQL Data Sync Private Link is Microsoft-managed endpoint and internally
```suggestion
    more_info: 'Private link feature allows you to choose a service managed private endpoint to establish a secure connection between the sync service and your member/hub databases during the data synchronization process. A service managed private endpoint is a private IP address within a specific virtual network and subnet.',
```

2023-12-06 09:26 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbSyncGroupPrivateLink.js
> +    apis: ['servers:listSql','databases:listByServer','syncGroups:list'],
```suggestion
    apis: ['servers:listSql', 'databases:listByServer', 'syncGroups:list'],
```

2023-12-06 09:26 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbSyncGroupPrivateLink.js
> +                        databases.data.forEach(database=> {
```suggestion
                        databases.data.forEach(database => {
```

2023-12-06 09:33 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbSyncGroupPrivateLink.js
> +                                    'No Database sync group found for SQL database', location, database.id);
```suggestion
                                    'No sync groups found for SQL database', location, database.id);
```

2023-12-06 09:36 UTC, alphadev4 requested changes

2023-12-06 09:36 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbSyncGroupPrivateLink.js
> +                                }
Again the result should be SQL Based instead of syncGroup based

2023-12-06 11:13 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbSyncGroupPrivateLink.js
> +                                    helpers.addResult(results, 2, `Database is not configured to use private link in following sync groups: ${missingPrivateConfigGrps.join(', ')} `, location, databas
```suggestion
                                    helpers.addResult(results, 2, `SQL Database following sync groups are not configured to use private link: ${missingPrivateConfigGrps.join(', ')} `, location, database.id);
```

2023-12-06 11:13 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbSyncGroupPrivateLink.js
> +                                    helpers.addResult(results, 0, 'Database sync groups are configured to use private link', location, database.id);
```suggestion
                                    helpers.addResult(results, 0, 'SQL Database sync groups are configured to use private link', location, database.id);
```

2023-12-06 11:13 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbSyncGroupPrivateLink.spec.js
> +                expect(results[0].message).to.include('Database is not configured to use private link in following sync groups:');
```suggestion
                expect(results[0].message).to.include('SQL Database following sync groups are not configured to use private link:');
```

2023-12-06 11:13 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbSyncGroupPrivateLink.spec.js
> +                expect(results[0].message).to.include('Database sync groups are configured to use private link');
```suggestion
                expect(results[0].message).to.include('SQL Database sync groups are configured to use private link');
```

2023-12-06 11:14 UTC, alphadev4 approved these changes

2023-12-06 12:20 UTC, mehakseedat63 requested changes

2023-12-06 12:20 UTC, mehakseedat63 commented on plugins/azure/sqldatabases/dbSyncGroupPrivateLink.js
> +                                var missingPrivateConfigGrps = syncGroups.data.filter((e) => !e.usePrivateLinkConnection).map((e)=>e.name);
```suggestion
                                var missingPrivateConfigGrps = syncGroups.data.filter((e) => !e.usePrivateLinkConnection).map((e) => e.name);
```

2023-12-06 12:20 UTC, mehakseedat63 commented on plugins/azure/sqldatabases/dbSyncGroupPrivateLink.js
> +                                    helpers.addResult(results, 2, `SQL Database following sync groups are not configured to use private link: ${missingPrivateConfigGrps.join(', ')} `, location, datab
```suggestion
                                    helpers.addResult(results, 2, `Following SQL Database sync groups are not configured to use private link: ${missingPrivateConfigGrps.join(', ')} `, location, database.id);
```

2023-12-06 12:20 UTC, mehakseedat63 commented on plugins/azure/sqldatabases/dbSyncGroupPrivateLink.js
> +                                    helpers.addResult(results, 0, 'SQL Database sync groups are configured to use private link', location, database.id);
```suggestion
                                    helpers.addResult(results, 0, 'All SQL Database sync groups are configured to use private link', location, database.id);
```

2023-12-06 12:25 UTC, mehakseedat63 approved these changes

2023-12-06 12:34 UTC, merged