added sql db enableSecureEnclaves
aquasecurity/cloudsploit pull request #1756
Opened 2023-11-28 10:24 UTC by muzzamilinovaqo

2023-11-28 10:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1756) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1756) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=1756) it.</sub>

2023-12-04 12:00 UTC, fatima99s commented on plugins/azure/sqldatabases/dbEnableSecureEnclaves.js
> +    link: 'https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-enclaves-security-features?view=sql-server-ver15',
```suggestion
    link: 'https://learn.microsoft.com/en-us/azure/azure-sql/database/always-encrypted-enclaves-enable?view=azuresql&tabs=IntelSGXenclaves',
```

2023-12-05 15:38 UTC, mehakseedat63 requested changes

2023-12-05 15:38 UTC, mehakseedat63 commented on plugins/azure/sqldatabases/dbEnableSecureEnclaves.js
> +    description: 'Ensure Always Encrypted with secure enclaves is enabled at the database level.',
```suggestion
    description: 'Ensure secure enclaves encryption is enabled for SQL databases.',
```

2023-12-05 15:38 UTC, mehakseedat63 commented on plugins/azure/sqldatabases/dbEnableSecureEnclaves.js
> +    more_info: 'Always Encrypted protects the data by encrypting it on the client side and never allowing the data or the corresponding cryptographic keys to appear in plaintext inside the Database E
```suggestion
    more_info: 'Secure enclaves encryption protects the data by encrypting it on the client side and never allowing the data or the corresponding cryptographic keys to appear in plaintext inside the Database Engine. As a result, the functionality on encrypted columns inside the database is severely restricted.',
```

2023-12-05 15:38 UTC, mehakseedat63 commented on plugins/azure/sqldatabases/dbEnableSecureEnclaves.js
> +    recommended_action: 'Enable Always Encrypted with secure enclaves for the SQL database.',
```suggestion
    recommended_action: 'Enable secure enclaves encryption for all SQL databases.',
```

2023-12-05 15:38 UTC, mehakseedat63 commented on plugins/azure/sqldatabases/dbEnableSecureEnclaves.js
> +                                helpers.addResult(results, 2, 'Always Encrypted with secure enclaves is disabled for SQL database', location, database.id);
```suggestion
                                helpers.addResult(results, 2, 'Secure enclaves encryption is disabled for SQL database', location, database.id);
```

2023-12-05 15:38 UTC, mehakseedat63 commented on plugins/azure/sqldatabases/dbEnableSecureEnclaves.js
> +                                helpers.addResult(results, 0, 'Always Encrypted with secure enclaves is enabled for SQL database', location, database.id);
```suggestion
                                helpers.addResult(results, 0, 'Secure enclaves encryption is enabled for SQL database', location, database.id);
```

2023-12-05 15:38 UTC, mehakseedat63 commented on plugins/azure/sqldatabases/dbEnableSecureEnclaves.spec.js
> +                expect(results[0].message).to.include('Always Encrypted with secure enclaves is enabled for SQL database');
```suggestion
                expect(results[0].message).to.include('Secure enclaves encryption is enabled for SQL database');
```

2023-12-05 15:38 UTC, mehakseedat63 commented on plugins/azure/sqldatabases/dbEnableSecureEnclaves.spec.js
> +                expect(results[0].message).to.include('Always Encrypted with secure enclaves is disabled for SQL database');
```suggestion
                expect(results[0].message).to.include('Secure enclaves encryption is disabled for SQL database');
```

2023-12-06 08:41 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbEnableSecureEnclaves.js
> +                        databases.data.forEach(database=> {
```suggestion
                        databases.data.forEach(database => {
```

2023-12-06 08:41 UTC, alphadev4 commented on plugins/azure/sqldatabases/dbEnableSecureEnclaves.js
> +
```suggestion
```

2023-12-06 08:47 UTC, alphadev4 approved these changes

2023-12-06 12:04 UTC, mehakseedat63 approved these changes

2023-12-06 12:04 UTC, merged