Feature/saas 20307/sql db ledger enabled
aquasecurity/cloudsploit pull request #1757
Opened 2023-11-28 10:25 UTC by muzzamilinovaqo

2023-11-28 10:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1757) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=1757) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=1757) it.</sub>

2023-12-04 12:03 UTC, fatima99s commented on plugins/azure/sqldatabases/dbLedgerEnabled.js
> +    link: 'https://docs.microsoft.com/en-us/azure/sql-database/sql-database-ledger-overview',
```suggestion
    link: 'https://learn.microsoft.com/en-us/sql/relational-databases/security/ledger/ledger-overview?view=sql-server-ver16',
```

2023-12-04 12:03 UTC, fatima99s commented on plugins/azure/sqldatabases/dbLedgerEnabled.js
> +                                helpers.addResult(results, 2, 'Azure ledger is disabled for SQL database', location, database.id);
```suggestion
                                helpers.addResult(results, 2, 'Azure ledger is not enabled for SQL database', location, database.id);
```

2023-12-05 14:18 UTC, alphadev4 commented on exports.js
> +        'frontDoorMinimumTlsVersion'    : require(__dirname + '/plugins/azure/frontdoor/frontDoorMinimumTlsVersion.js'),
```suggestion
        'frontDoorMinimumTlsVersion'    : require(__dirname + '/plugins/azure/frontdoor/frontDoorMinimumTlsVersion.js')
```

2023-12-05 15:27 UTC, mehakseedat63 requested changes

2023-12-05 15:27 UTC, mehakseedat63 commented on plugins/azure/sqldatabases/dbLedgerEnabled.js
> +    description: 'Ensure ledger is enabled to protect the integrity of data for SQL databases.',
```suggestion
    description: 'Ensure ledger is enabled for SQL databases.',
```

2023-12-05 15:27 UTC, mehakseedat63 commented on plugins/azure/sqldatabases/dbLedgerEnabled.js
> +    recommended_action: 'Enable Azure ledger for all future tables in the SQL database to enhance data integrity.',
```suggestion
    recommended_action: 'Enable Azure ledger for all SQL databases.',
```

2023-12-05 15:27 UTC, mehakseedat63 commented on plugins/azure/sqldatabases/dbLedgerEnabled.js
> +                        });
```suggestion
                        databases.data.forEach(database => {
                          
                            if (database.isLedgerOn) {
                                helpers.addResult(results, 0, 'Ledger is enabled for SQL database', location, database.id);
                            } else {
                                helpers.addResult(results, 2, 'Ledger is not enabled for SQL database', location, database.id);
                            }
                                
                        });
```

2023-12-05 15:27 UTC, mehakseedat63 approved these changes

2023-12-06 12:12 UTC, merged