added azure vm plugin vmVTPMEnabled
aquasecurity/cloudsploit pull request #1769
Opened 2023-11-30 10:26 UTC by muzzamilinovaqo

2023-12-04 15:21 UTC, mehakseedat63 requested changes

2023-12-04 17:53 UTC, mehakseedat63 approved these changes

2023-12-04 17:58 UTC, mehakseedat63 requested changes

2023-12-04 17:58 UTC, mehakseedat63 commented on plugins/azure/virtualmachines/vmVTPMEnabled.js
> +    more_info: 'vTPM is TPM2.0 compliant and enhances security by validating VM boot integrity and providing a secure storage mechanism for keys and secrets.',
```suggestion
    more_info: 'vTPM is TPM2.0 compliant and enhances security by validating VM boot integrity and providing a secure storage mechanism for keys and secrets.',
```
add a little more info in here

2023-12-05 09:53 UTC, mehakseedat63 approved these changes

2023-12-06 08:35 UTC, alphadev4 commented on plugins/azure/virtualmachines/vmVTPMEnabled.js
> +    description: 'Ensure Virtual Trusted Platform Module (vTPM) is enabled for Azure virtual machines (VM).',
```suggestion
    description: 'Ensure that Virtual Trusted Platform Module (vTPM) is enabled for Azure virtual machines.',
```

2023-12-06 08:37 UTC, alphadev4 commented on plugins/azure/virtualmachines/vmVTPMEnabled.js
> +                    helpers.addResult(results, 0, 'vTPM is enabled for Azure Virtual Machine', location, virtualMachine.id);
```suggestion
                    helpers.addResult(results, 0, 'vTPM is enabled for virtual machine', location, virtualMachine.id);
```

2023-12-06 08:38 UTC, alphadev4 commented on plugins/azure/virtualmachines/vmVTPMEnabled.js
> +                    helpers.addResult(results, 2, 'vTPM is not enabled for Azure Virtual Machine', location, virtualMachine.id);
```suggestion
                    helpers.addResult(results, 2, 'vTPM is not enabled for virtual machine', location, virtualMachine.id);
```

2023-12-06 08:38 UTC, alphadev4 commented on plugins/azure/virtualmachines/vmVTPMEnabled.spec.js
> +                expect(results[0].message).to.include('vTPM is not enabled for Azure Virtual Machine');
```suggestion
                expect(results[0].message).to.include('vTPM is not enabled for virtual machine');
```

2023-12-06 08:38 UTC, alphadev4 commented on plugins/azure/virtualmachines/vmVTPMEnabled.spec.js
> +                expect(results[0].message).to.include('vTPM is enabled for Azure Virtual Machine');
```suggestion
                expect(results[0].message).to.include('vTPM is enabled for virtual machine');
```

2023-12-06 08:39 UTC, alphadev4 approved these changes

2023-12-06 11:12 UTC, merged