SAAS-20297/ag-ssl-policy
aquasecurity/cloudsploit pull request #1770
Opened 2023-11-30 10:53 UTC by alphadev4

2023-11-30 10:54 UTC, alphadev4 commented on plugins/azure/applicationGateway/agSslPolicy.js
> +    recommended_action: 'Modify Application Gateway with latest SSL policy which supports minimum TLS version',
```suggestion
    recommended_action: 'Modify Application Gateway with latest SSL policy which supports minimum TLS version.',
```

2023-11-30 10:59 UTC, alphadev4 commented on plugins/azure/applicationGateway/agSslPolicy.spec.js
> +                expect(results[0].message).to.include('SSL policy  which supports TLSV1_2');
```suggestion
                expect(results[0].message).to.include('SSL policy which supports TLSV1_2');
```

2023-11-30 21:36 UTC, mehakseedat63 requested changes

2023-12-01 10:43 UTC, alphadev4 commented on plugins/azure/applicationGateway/agSslPolicy.js
> +                    (sslPolicy.policyType == 'Custom' && sslPolicy.minProtocolVersion && sslPolicy.minProtocolVersion.toLowerCase() == 'tlsv1_2')) {
but right in here we are checking the minimum tls version so should we add the check for tlsv1_3, if yes then should the message be like it is using latest TLS version?

2023-12-01 12:12 UTC, mehakseedat63 commented on plugins/azure/applicationGateway/agSslPolicy.js
> +                    (sslPolicy.policyType == 'Custom' && sslPolicy.minProtocolVersion && sslPolicy.minProtocolVersion.toLowerCase() == 'tlsv1_2')) {
Yes, this will fail in case of TLSV1_3, it should pass for v1_2 or higher. Update the messages accordingly

2023-12-04 15:56 UTC, mehakseedat63 requested changes

2023-12-04 15:56 UTC, mehakseedat63 commented on plugins/azure/applicationGateway/agSslPolicy.js
> +
```suggestion
                } else {
                    helpers.addResult(results, 2, 'Application Gateway is using SSL policy which does not support latest TLS version', location, appGateway.id);
                } 
            }

```
Duplicate code, maybe we can just set found to true or false inside the first if and then produce pass or fail results based off it outside the if?

2023-12-04 17:47 UTC, mehakseedat63 approved these changes

2023-12-05 15:21 UTC, merged