added azure vm plugin diskDeleteConfig
aquasecurity/cloudsploit pull request #1772
Opened 2023-11-30 14:13 UTC by muzzamilinovaqo

2023-12-04 12:21 UTC, fatima99s commented on plugins/azure/virtualmachines/vmDiskDeleteConfig.js
> +    title: 'Azure VM"s Automatic Disks Delete Enabled',
```suggestion
    title: 'Azure VM's Automatic Disks Delete Enabled',
```

2023-12-04 12:23 UTC, fatima99s commented on plugins/azure/virtualmachines/vmDiskDeleteConfig.js
> +    link: 'https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/disk-delete',
https://learn.microsoft.com/en-us/azure/virtual-machines/delete?tabs=portal2%2Ccli3%2Cportal4%2Cportal5

2023-12-05 09:56 UTC, mehakseedat63 requested changes

2023-12-05 09:59 UTC, mehakseedat63 reviewed
Fix failing test

2023-12-06 10:39 UTC, mehakseedat63 approved these changes

2023-12-06 10:39 UTC, merged