content key policy exists
aquasecurity/cloudsploit pull request #1777
Opened 2023-12-01 09:14 UTC by abdullahaslam306

2023-12-05 08:27 UTC, alphadev4 commented on plugins/azure/mediaServices/amsContentKeyPolicy.js
> +    title: 'Media Services Content Key Policy Exists',
```suggestion
    title: 'Media Services Content Key Policy',
```

2023-12-05 08:28 UTC, alphadev4 commented on plugins/azure/mediaServices/amsContentKeyPolicy.js
> +    recommended_action: 'Modify media service account and add a content key policy.',
```suggestion
    recommended_action: 'Modify media service account and add content key policy.',
```

2023-12-05 08:31 UTC, alphadev4 commented on plugins/azure/mediaServices/amsContentKeyPolicy.js
> +                    helpers.addResult(results, 3, `Unable to query for Content Key Policy: ${helpers.addError(listContentKeyPolicies)}`,
```suggestion
                    helpers.addResult(results, 3, `Unable to query Content Key Policy for Media service account: ${helpers.addError(listContentKeyPolicies)}`,
```

2023-12-05 08:33 UTC, alphadev4 commented on plugins/azure/mediaServices/amsContentKeyPolicy.js
> +                    helpers.addResult(results, 2, 'Azure Media Service does not have content key policy configured', location, mediaService.id);
```suggestion
                    helpers.addResult(results, 2, 'Media Service account does not have content key policy configured', location, mediaService.id);
```

2023-12-05 08:34 UTC, alphadev4 commented on plugins/azure/mediaServices/amsContentKeyPolicy.spec.js
> +                expect(results[0].message).to.include('Unable to query for Content Key Policy');
```suggestion
                expect(results[0].message).to.include('Unable to query Content Key Policy for Media service account:');
```

2023-12-05 08:34 UTC, alphadev4 commented on plugins/azure/mediaServices/amsContentKeyPolicy.spec.js
> +                expect(results[0].message).to.include('Azure Media Service has content key policy configured');
```suggestion
                expect(results[0].message).to.include('Media Service account has content key policy configured');
```

2023-12-05 08:34 UTC, alphadev4 commented on plugins/azure/mediaServices/amsContentKeyPolicy.spec.js
> +                expect(results[0].message).to.include('Azure Media Service does not have content key policy configured');
```suggestion
                expect(results[0].message).to.include('Media Service account does not have content key policy configured');
```

2023-12-05 08:37 UTC, alphadev4 commented on plugins/azure/mediaServices/amsContentKeyPolicy.js
> +    recommended_action: 'Modify media service account and add content key policy.',
```suggestion
    recommended_action: 'Modify Media Service account and add content key policy.',
```

2023-12-05 08:38 UTC, alphadev4 approved these changes

2023-12-05 19:02 UTC, mehakseedat63 requested changes

2023-12-05 19:02 UTC, mehakseedat63 commented on plugins/azure/mediaServices/amsContentKeyPolicy.js
> +                if (listContentKeyPolicies.data.length > 0) {
```suggestion
                if (listContentKeyPolicies.data.length) {
```
don't need to check for > 0

2023-12-06 10:01 UTC, mehakseedat63 approved these changes

2024-01-02 06:24 UTC, merged