storage account managed identity enabled
aquasecurity/cloudsploit pull request #1779
Opened 2023-12-01 09:14 UTC by abdullahaslam306

2023-12-04 19:02 UTC, alphadev4 commented on plugins/azure/mediaServices/amsStorageAccountIdentityEnabled.js
> +    recommended_action: 'Modify the media service\'s storage account settings and enable managed identity.',
```suggestion
    recommended_action: 'Modify Media Service storage account settings and enable managed identity.',
```

2023-12-04 19:03 UTC, alphadev4 commented on plugins/azure/mediaServices/amsStorageAccountIdentityEnabled.js
> +    description: 'Ensure that Azure Media Services have managed identity enabled for Storage Account authentication.',
```suggestion
    description: 'Ensures that Azure Media Services have managed identity enabled for Storage Account authentication.',
```

2023-12-04 19:03 UTC, alphadev4 approved these changes

2023-12-04 19:13 UTC, alphadev4 commented on plugins/azure/mediaServices/amsStorageAccountIdentityEnabled.js
> +    description: 'Ensures that Azure Media Services have managed identity enabled for Storage Account authentication.',
```suggestion
    description: 'Ensures that Azure Media Service accounts have managed identity enabled for Storage Account authentication.',
```

2023-12-05 18:44 UTC, mehakseedat63 requested changes

2023-12-05 18:44 UTC, mehakseedat63 commented on exports.js
> +        'amsStorageAccountIdentityEnabled': require(__dirname + '/plugins/azure/mediaServices/amsStorageAccountIdentityEnabled.js')
```suggestion
        'amsStorageAccountIdentity': require(__dirname + '/plugins/azure/mediaServices/amsStorageAccountIdentityEnabled.js')
```
Filename could just be amsStorageAccountIdentity

2023-12-06 12:05 UTC, merged