Feature/azure ams diagnostic logs
aquasecurity/cloudsploit pull request #1781
Opened 2023-12-01 09:14 UTC by abdullahaslam306

2023-12-04 08:49 UTC, alphadev4 requested changes

2023-12-04 18:50 UTC, alphadev4 commented on plugins/azure/mediaServices/amsDiagnosticLogsEnabled.js
> +                }
```suggestion
```

2023-12-04 18:52 UTC, alphadev4 commented on plugins/azure/mediaServices/amsDiagnosticLogsEnabled.js
> +    description: 'Ensure that Microsoft Azure Media Services have diagnostic logs enabled.',
```suggestion
    description: 'Ensures that Azure Media Services have diagnostic logs enabled.',
```

2023-12-04 18:53 UTC, alphadev4 commented on plugins/azure/mediaServices/amsDiagnosticLogsEnabled.js
> +    recommended_action: 'Modify the media service settings and enable diagnostic logs.',
```suggestion
    recommended_action: 'Modify Media Service settings and enable diagnostic logs.',
```

2023-12-04 18:53 UTC, alphadev4 approved these changes

2023-12-05 18:41 UTC, mehakseedat63 approved these changes

2023-12-06 09:48 UTC, merged