vmss health https enabled
aquasecurity/cloudsploit pull request #1806
Opened 2023-12-23 08:09 UTC by abdullahaslam306

2023-12-28 17:51 UTC, alphadev4 commented on plugins/azure/virtualmachinescaleset/healthMonitoringHttpsEnabled.js
> +                const hasHTTPSProtocol = scaleSetExtensions.some((extension) => (
i think we should only check for httpsProtocol if healthMonitoringEnabled flag is true.

2023-12-28 18:09 UTC, alphadev4 requested changes

2023-12-28 18:09 UTC, alphadev4 commented on plugins/azure/virtualmachinescaleset/healthMonitoringHttpsEnabled.js
> +                        'Virtual Machine Scale Set has health monitoring disabled', location, virtualMachineScaleSet.id);
if no extension is found then message should be Virtual Machine Scale Set has health monitoring disabled, with fail result

2023-12-28 18:09 UTC, alphadev4 commented on plugins/azure/virtualmachinescaleset/healthMonitoringHttpsEnabled.spec.js
> +    {
update the tests accordingly

2023-12-28 18:09 UTC, alphadev4 commented on plugins/azure/virtualmachinescaleset/healthMonitoringHttpsEnabled.js
> +    more_info: 'Scale set health monitoring feature reports on VM health from inside the scale set instance and can be configured to probe on an application endpoint and update the status of the appl
```suggestion
    more_info: 'Enabling Application Health Extension in Virtual Machine Scale Set instance reports on application health from inside based on HTTPS responses received from the application. This allows to initiate repairs on unhealthy instances and to determine if an instance is eligible for upgrade operations.',
```

2024-01-01 11:51 UTC, alphadev4 commented on exports.js
> +        'healthMonitoringExtensionHttps'  : require(__dirname + '/plugins/azure/virtualmachinescaleset/healthMonitoringExtensionHttps.js')
```suggestion
        'healthMonitoringExtensionHttps' : require(__dirname + '/plugins/azure/virtualmachinescaleset/healthMonitoringExtensionHttps.js')
```

2024-01-01 11:52 UTC, alphadev4 commented on exports.js
> +        'healthMonitoringExtensionHttps' : require(__dirname + '/plugins/azure/virtualmachinescaleset/healthMonitoringExtensionHttps.js')
```suggestion
        'healthMonitoringExtensionHttps': require(__dirname + '/plugins/azure/virtualmachinescaleset/healthMonitoringExtensionHttps.js')
```

2024-01-01 11:59 UTC, alphadev4 commented on plugins/azure/virtualmachinescaleset/healthMonitoringExtensionHttps.js
> +
```suggestion
                    ? scaleSetExtensions.some((extension) => (
                        extension.properties && extension.properties.type && 
                        (extension.properties.type === 'ApplicationHealthWindows' || extension.properties.type === 'ApplicationHealthLinux'))
                    ) : false;

```

2024-01-01 12:01 UTC, alphadev4 commented on plugins/azure/virtualmachinescaleset/healthMonitoringExtensionHttps.js
> +
```suggestion

```

2024-01-31 10:58 UTC, alphadev4 commented on exports.js
>          'automationAcctManagedIdentity' : require(__dirname + '/plugins/azure/automationAccounts/automationAcctManagedIdentity.js'),
```suggestion
        'automationAcctManagedIdentity' : require(__dirname + '/plugins/azure/automationAccounts/automationAcctManagedIdentity.js'),

```

2024-01-31 10:59 UTC, alphadev4 approved these changes

2024-03-05 05:10 UTC, mehakseedat63 approved these changes

2024-03-05 06:30 UTC, merged