flexibleServerVersion
aquasecurity/cloudsploit pull request #1814
Opened 2023-12-26 09:04 UTC by fatima99s

2023-12-28 04:55 UTC, mehakseedat63 requested changes

2023-12-28 04:55 UTC, mehakseedat63 commented on plugins/azure/postgresqlserver/flexibleServerVersion.js
> +    more_info: 'The latest version of PostgreSQL for flexible servers will give access to new software features, resolve reported bugs through security patches, and improve compatibility with other a
```suggestion
    more_info: 'Using the latest version of PostgreSQL for flexible servers will give access to new software features, resolve reported bugs through security patches, and improve compatibility with other applications and services.',
```

2023-12-28 04:55 UTC, mehakseedat63 commented on plugins/azure/postgresqlserver/flexibleServerVersion.js
> +    recommended_action: 'Upgrade the version of PostgreSQL flexible server to the latest available version..',
```suggestion
    recommended_action: 'Upgrade the version of PostgreSQL flexible server to the latest available version.',
```

2023-12-28 04:55 UTC, mehakseedat63 commented on plugins/azure/postgresqlserver/flexibleServerVersion.js
> +    },
```suggestion
    settings: {
        server_desired_version: {
            name: 'Postgresql Flexible Server Desired Version',
            description: 'Desire Postgresql Flexible Server Version ',
            regex: '^[0-9]+$',
            default: '11'
        }
    },
```
this shouldn't be a setting, we should find the minimum version which should be used and check against it. This is one of those periodic refactoring plugins where we keep checking for deprecated and outdated versions and update them accordingly (also add it to the periodic refactoring sheet).

2023-12-29 08:07 UTC, alphadev4 commented on plugins/azure/postgresqlserver/flexibleServerVersion.js
> +                        'Postgresql flexible server has the latest server version', location, flexibleServer.id);
```suggestion
                        'Postgresql flexible server has the latest postgresql version', location, flexibleServer.id);
```

2023-12-29 08:09 UTC, alphadev4 commented on plugins/azure/postgresqlserver/flexibleServerVersion.js
> +                        'Postgresql flexible server does not the latest server version', location, flexibleServer.id);
```suggestion
                        'PostgreSQL flexible server does not the latest server version', location, flexibleServer.id);
```

2023-12-29 08:09 UTC, alphadev4 commented on plugins/azure/postgresqlserver/flexibleServerVersion.spec.js
> +                expect(results[0].message).to.include('Postgresql flexible server does not the latest server version');
```suggestion
                expect(results[0].message).to.include('PostgreSQL flexible server does not the latest server version');
```

2023-12-29 08:09 UTC, alphadev4 commented on plugins/azure/postgresqlserver/flexibleServerVersion.spec.js
> +                expect(results[0].message).to.include('Postgresql flexible server has the latest server version');
```suggestion
                expect(results[0].message).to.include('PostgreSQL flexible server has the latest server version');
```

2023-12-29 08:14 UTC, alphadev4 commented on plugins/azure/postgresqlserver/flexibleServerVersion.js
> +                let version = parseFloat(flexibleServer.version);
```suggestion
                If (!flexibleServer.id || !flexibleServer.version) return;
                
                let version = parseFloat(flexibleServer.version);
```

2023-12-29 08:14 UTC, alphadev4 approved these changes

2023-12-29 08:17 UTC, alphadev4 commented on plugins/azure/postgresqlserver/flexibleServerVersion.js
> +                If (!flexibleServer.id || !flexibleServer.version) return;
```suggestion
                if(!flexibleServer.id || !flexibleServer.version) return;
```

2023-12-29 08:30 UTC, alphadev4 commented on plugins/azure/postgresqlserver/flexibleServerVersion.js
> +                if (!flexibleServer.id || !flexibleServer.version) return;
```suggestion
                if (!flexibleServer.id || !flexibleServer.version) continue;
```

2024-01-02 06:59 UTC, mehakseedat63 approved these changes

2024-01-02 08:11 UTC, merged