Azure/acr content trust
aquasecurity/cloudsploit pull request #1815
Opened 2023-12-26 10:07 UTC by alphadev4

2023-12-26 11:24 UTC, alphadev4 commented on plugins/azure/containerregistry/acrContentTrustEnabled.js
> +                    helpers.addResult(results, 0, 'Content trsut is enabled for container registry', location, registry.id);
```suggestion
                    helpers.addResult(results, 0, 'Content trust is enabled for container registry', location, registry.id);
```

2023-12-26 11:24 UTC, alphadev4 commented on plugins/azure/containerregistry/acrContentTrustEnabled.js
> +                    helpers.addResult(results, 2, 'Content trsut is not enabled for container registry', location, registry.id);
```suggestion
                    helpers.addResult(results, 2, 'Content trust is not enabled for container registry', location, registry.id);
```

2023-12-26 11:24 UTC, alphadev4 commented on plugins/azure/containerregistry/acrContentTrustEnabled.spec.js
> +                expect(results[0].message).to.include('Content trsut is not enabled for container registry');
```suggestion
                expect(results[0].message).to.include('Content trust is not enabled for container registry');
```

2023-12-26 11:24 UTC, alphadev4 commented on plugins/azure/containerregistry/acrContentTrustEnabled.spec.js
> +                expect(results[0].message).to.include('Content trsut is enabled for container registry');
```suggestion
                expect(results[0].message).to.include('Content trust is enabled for container registry');
```

2023-12-28 04:51 UTC, mehakseedat63 requested changes

2023-12-28 04:51 UTC, mehakseedat63 commented on plugins/azure/containerregistry/acrContentTrustEnabled.js
> +    more_info: 'Content trust allows you to sign the images you push to your registry. Consumers of your images (people or systems pulling images from your registry) can configure their clients to pu
```suggestion
    more_info: 'Content trust allows you to sign the images you push to your registry. Consumers of your images (people or systems pulling images from your registry) can configure their clients to pull only signed images which enhances container image security by ensuring the integrity and authenticity of images and safeguards against unauthorized or tampered content.',
```

2023-12-28 04:51 UTC, mehakseedat63 commented on plugins/azure/containerregistry/acrContentTrustEnabled.js
> +                if (!registry.id || (registry.sku && registry.sku.tier && registry.sku.tier!= 'Premium')) continue;
```suggestion
                if (!registry.id || (registry.sku && registry.sku.tier && registry.sku.tier!= 'Premium')) continue;
```
maybe add a pass result for non-premium registries that says 'is not a premium registry'

2023-12-28 04:51 UTC, mehakseedat63 commented on plugins/azure/containerregistry/acrContentTrustEnabled.spec.js
> +
add a test case for non-premium registries too

2024-01-01 22:09 UTC, mehakseedat63 approved these changes

2024-01-02 07:05 UTC, merged