enableDefenderForPostgresql
aquasecurity/cloudsploit pull request #1822
Opened 2023-12-26 17:36 UTC by fatima99s

2023-12-28 04:41 UTC, mehakseedat63 requested changes

2023-12-28 04:41 UTC, mehakseedat63 commented on plugins/azure/defender/enableDefenderForPostgresql.js
> +            helpers.checkMicrosoftDefender(pricings, 'opensourcerelationaldatabases', 'PostgreSQL Flexible Servers', results, location);
```suggestion
            helpers.checkMicrosoftDefender(pricings, 'opensourcerelationaldatabases', 'PostgreSQL Flexible Servers', results, location);
```
this plan is for multiple types of databases, we should remove PostgreSQL Flexible Server from the title and make this plugin generic for open source relational databases

2023-12-29 08:06 UTC, alphadev4 commented on exports.js
> +
```suggestion

```

2023-12-29 08:20 UTC, alphadev4 commented on plugins/azure/defender/enableDefenderForOSRD.js
> +    more_info: 'Enabling Defender for Cloud on Open Source Relational Databases allows detection of unusual database access, query patterns, and suspicious activities, enhancing overall security.',
```suggestion
    more_info: 'Enabling Defender for Cloud on Open Source Relational Databases allows detection of unusual database access, query patterns, and suspicious activities, enhancing overall security. This plan brings threat protections for PostgreSQL, MySQL and MariaDB  Azure Databases.'
```

2023-12-29 08:22 UTC, alphadev4 approved these changes

2024-01-02 07:00 UTC, mehakseedat63 approved these changes

2024-01-02 08:11 UTC, alphadev4 commented on helpers/azure/functions.js
> +
```suggestion
   
```

2024-01-02 08:13 UTC, merged