flexibleServerPrivateDnsZone
aquasecurity/cloudsploit pull request #1826
Opened 2023-12-27 10:09 UTC by fatima99s

2023-12-28 04:26 UTC, mehakseedat63 requested changes

2023-12-28 04:26 UTC, mehakseedat63 commented on plugins/azure/postgresqlserver/flexibleServerPrivateDns.js
> +    description: 'Ensure that PostgreSQL flexible servers has Private DNS Zone integrated.',
```suggestion
    description: 'Ensure that PostgreSQL flexible servers have private DNS zone integrated.',
```

2023-12-28 04:26 UTC, mehakseedat63 commented on plugins/azure/postgresqlserver/flexibleServerPrivateDns.js
> +    more_info: 'Integrate Private DNS Zones with PostgreSQL flexible servers to enhance DNS service reliability and security within your Azure virtual network, ensuring seamless DNS resolution and st
```suggestion
    more_info: 'Integrating Private DNS Zones with PostgreSQL flexible servers enhances DNS service reliability and security within your Azure virtual network, ensuring seamless DNS resolution and streamlined domain management.',
```

2023-12-28 04:26 UTC, mehakseedat63 commented on plugins/azure/postgresqlserver/flexibleServerPrivateDns.js
> +    recommended_action: 'Ensures Vnet and Private DNS Zone (private access) is integrated for PostgreSQL flexible server.',
```suggestion
    recommended_action: 'Ensure Vnet and Private DNS Zone (private access) is integrated for PostgreSQL flexible server.',
```

2023-12-28 04:26 UTC, mehakseedat63 commented on plugins/azure/postgresqlserver/flexibleServerPrivateDns.js
> +                    helpers.addResult(results, 0, 'PostgreSQL flexible server has Private DNS Zone integrated', location, flexibleServer.id);
```suggestion
                    helpers.addResult(results, 0, 'PostgreSQL flexible server has private DNS zone integrated', location, flexibleServer.id);
```

2023-12-28 04:26 UTC, mehakseedat63 commented on plugins/azure/postgresqlserver/flexibleServerPrivateDns.js
> +                    helpers.addResult(results, 2, 'PostgreSQL flexible server does not have Private DNS Zone integrated', location, flexibleServer.id);
```suggestion
                    helpers.addResult(results, 2, 'PostgreSQL flexible server does not have private DNS zone integrated', location, flexibleServer.id);
```

2023-12-28 04:26 UTC, mehakseedat63 commented on plugins/azure/postgresqlserver/flexibleServerPrivateDns.spec.js
> +        "delegatedSubnetResourceId" : "/subscriptions/26a1a07e-06dd-4892-92c9-e4996b0fc546/resourceGroups/cloudsploit-dev/providers/Microsoft.Network/virtualNetworks/omer-virtual-network-test/subnets
```suggestion
        "delegatedSubnetResourceId" : "/subscriptions/26a1a07e-06dd-4892-92c9-e4996b0fc546/resourceGroups/cloudsploit-dev/providers/Microsoft.Network/virtualNetworks/omer-virtual-network-test/subnets/default",
```
change subscription id to a random value

2023-12-28 04:29 UTC, mehakseedat63 requested changes

2023-12-28 04:29 UTC, mehakseedat63 commented on plugins/azure/postgresqlserver/flexibleServerPrivateDns.js
> +    link: 'https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-networking-private',
```suggestion
    link: 'https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-networking-private',
```
this is the same as vnet integration, can we add a link that mentions private dns zones?

2023-12-29 08:35 UTC, alphadev4 approved these changes

2024-01-02 07:00 UTC, mehakseedat63 approved these changes

2024-01-02 08:15 UTC, merged