Azure/app configuration diagnostic logs
aquasecurity/cloudsploit pull request #1827
Opened 2023-12-27 10:54 UTC by alphadev4

2023-12-28 04:17 UTC, mehakseedat63 requested changes

2023-12-28 04:17 UTC, mehakseedat63 commented on plugins/azure/appConfigurations/appConfigurationDiagnosticLogs.js
> +    more_info: 'Enabling diagnostic logging for  for App Configuration helps with performance monitoring, troubleshooting, and security optimization.',
```suggestion
    more_info: 'Enabling diagnostic logging for App Configuration helps with performance monitoring, troubleshooting, and security optimization.',
```

2023-12-28 04:17 UTC, mehakseedat63 commented on plugins/azure/appConfigurations/appConfigurationDiagnosticLogs.js
> +    recommended_action: 'Enable diagnostic logging for all App Configuration.',
```suggestion
    recommended_action: 'Enable diagnostic logging for all App Configurations.',
```

2024-01-01 21:59 UTC, mehakseedat63 approved these changes

2024-01-02 08:02 UTC, alphadev4 commented on exports.js
> +        'appConfigManagedIdentity'      : require(__dirname + '/plugins/azure/appConfigurations/appConfigManagedIdentity.js'),
```suggestion
```

2024-01-02 08:02 UTC, alphadev4 commented on exports.js
> +         'amsContentKeyPolicy'           : require(__dirname + '/plugins/azure/mediaServices/amsContentKeyPolicy.js'),
```suggestion
        'amsContentKeyPolicy'           : require(__dirname + '/plugins/azure/mediaServices/amsContentKeyPolicy.js'),
```

2024-01-02 08:03 UTC, merged