Azure/app configuration public access
aquasecurity/cloudsploit pull request #1828
Opened 2023-12-27 11:16 UTC by alphadev4

2023-12-28 04:11 UTC, mehakseedat63 requested changes

2023-12-28 04:11 UTC, mehakseedat63 commented on exports.js
> +        'appConfigurationManagedIdentity': require(__dirname + '/plugins/azure/appConfigurations/appConfigurationManagedIdentity.js'),
```suggestion
        'appConfigurationManagedIdentity': require(__dirname + '/plugins/azure/appConfigurations/appConfigurationManagedIdentity.js'),
```
can we change it to appConfigManagedIdentity?

2023-12-28 04:11 UTC, mehakseedat63 commented on plugins/azure/appConfigurations/appConfigurationManagedIdentity.js
> +    link: 'https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-integrate-azure-managed-service-identity?tabs=core6x&pivots=framework-dotnet',
```suggestion
    link: 'https://learn.microsoft.com/en-us/azure/azure-app-configuration/overview-managed-identity',
```

2023-12-28 04:11 UTC, mehakseedat63 commented on plugins/azure/appConfigurations/appConfigurationManagedIdentity.js
> +                if (identityType && (identityType.includes('systemassigned') || identityType.includes('userassigned'))) {
```suggestion
                if (identityType && (identityType.toLowerCase().includes('systemassigned') || identityType.toLowerCase().includes('userassigned'))) {
```
is it necessary to check for identity type?

2023-12-28 04:11 UTC, mehakseedat63 commented on plugins/azure/appConfigurations/appConfigurationManagedIdentity.spec.js
> +        "id": "/subscriptions/26a1a07e-06dd-4892-92c9-e4996b0fc546/resourceGroups/meerab-rg/providers/Microsoft.AppConfiguration/configurationStores/meerab-test-rg",
```suggestion
        "id": "/subscriptions/26a1a07e-06dd-4892-92c9-e4996b0fc546/resourceGroups/meerab-rg/providers/Microsoft.AppConfiguration/configurationStores/meerab-test-rg",
```
change subscription id to some random value

2023-12-28 04:11 UTC, mehakseedat63 commented on plugins/azure/appConfigurations/appConfigurationManagedIdentity.spec.js
> +        "id": "/subscriptions/26a1a07e-06dd-4892-92c9-e4996b0fc546/resourceGroups/meerab-rg/providers/Microsoft.AppConfiguration/configurationStores/meerab-test-rg",
```suggestion
        "id": "/subscriptions/26a1a07e-06dd-4892-92c9-e4996b0fc546/resourceGroups/meerab-rg/providers/Microsoft.AppConfiguration/configurationStores/meerab-test-rg",
```
change subscription id to a random value

2023-12-28 04:11 UTC, mehakseedat63 commented on plugins/azure/appConfigurations/appConfigurationManagedIdentity.spec.js
> +              }
```suggestion
            "principalId": "dc03d47d-e6df-491f-aebe-50a93412a890",
            "tenantId": "d207c7bd-fcb1-4dd3-855a-cfd2f9b651e8",
            "userAssignedIdentities": {
              "/subscriptions/26a1a07e-06dd-4892-92c9-e4996b0fc546/resourcegroups/meerab-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/testmeerab": {
                "PrincipalId": "1d34c2cd-bd53-487d-b3a9-6064465497c9",
                "ClientId": "2071caa1-3668-4de3-babc-155cfe3e38e5"
              }
```
make sure we're using dummy values here

2023-12-28 04:16 UTC, mehakseedat63 requested changes

2023-12-28 04:16 UTC, mehakseedat63 commented on plugins/azure/appConfigurations/appConfigurationPublicAccess.spec.js
> +        "id": "/subscriptions/26a1a07e-06dd-4892-92c9-e4996b0fc546/resourceGroups/meerab-rg/providers/Microsoft.AppConfiguration/configurationStores/meerab-test-rg",
```suggestion
        "id": "/subscriptions/26a1a07e-06dd-4892-92c9-e4996b0fc546/resourceGroups/meerab-rg/providers/Microsoft.AppConfiguration/configurationStores/meerab-test-rg",
```
change these

2023-12-28 08:19 UTC, alphadev4 commented on exports.js
> +        'appConfigManagedIdentity'      : require(__dirname + '/plugins/azure/appConfigurations/appConfigurationManagedIdentity.js'),
```suggestion
        'appConfigManagedIdentity'      : require(__dirname + '/plugins/azure/appConfigurations/appConfigManagedIdentity.js'),
```

2024-01-01 21:47 UTC, mehakseedat63 approved these changes

2024-01-01 21:59 UTC, mehakseedat63 approved these changes

2024-01-02 08:07 UTC, alphadev4 commented on exports.js
> +        'appConfigurationPublicAccess'  : require(__dirname + '/plugins/azure/appConfigurations/appConfigurationPublicAccess.js'),
```suggestion
        'appConfigurationDiagnosticLogs'  : require(__dirname + '/plugins/azure/appConfigurations/appConfigurationDiagnosticLogs.js'),
         'appConfigurationPublicAccess'  : require(__dirname + '/plugins/azure/appConfigurations/appConfigurationPublicAccess.js'),
```

2024-01-02 08:07 UTC, alphadev4 commented on exports.js
> +         'appConfigurationPublicAccess'  : require(__dirname + '/plugins/azure/appConfigurations/appConfigurationPublicAccess.js'),
```suggestion
        'appConfigurationDiagnosticLogs' : require(__dirname + '/plugins/azure/appConfigurations/appConfigurationDiagnosticLogs.js'),
        'appConfigurationPublicAccess'  : require(__dirname + '/plugins/azure/appConfigurations/appConfigurationPublicAccess.js'),
```

2024-01-02 08:08 UTC, alphadev4 commented on exports.js
> +        'appConfigurationDiagnosticLogs' : require(__dirname + '/plugins/azure/appConfigurations/appConfigurationDiagnosticLogs.js'),
```suggestion
        'appConfigurationDiagnosticLogs': require(__dirname + '/plugins/azure/appConfigurations/appConfigurationDiagnosticLogs.js'),
```

2024-01-02 08:09 UTC, merged