updated category for ML & AI
aquasecurity/cloudsploit pull request #1888
Opened 2024-01-30 14:12 UTC by fatima99s

2024-01-30 18:30 UTC, mehakseedat63 requested changes

2024-01-30 18:30 UTC, mehakseedat63 commented on plugins/aws/sagemaker/notebookDirectInternetAccess.js
> +    category: 'SML & AI',
```suggestion
    category: 'ML & AI',
```

2024-02-07 08:20 UTC, alphadev4 approved these changes

2024-02-07 08:23 UTC, mehakseedat63 approved these changes

2024-02-07 08:23 UTC, merged