postgresqlAdvanceThreadProtection
aquasecurity/cloudsploit pull request #1898
Opened 2024-02-01 06:23 UTC by fatima99s

2024-02-01 10:22 UTC, mehakseedat63 requested changes

2024-02-01 10:22 UTC, mehakseedat63 commented on plugins/azure/postgresqlserver/flexibleServerATP.js
> +    recommended_action: 'Ensure Defender is enabled for PostgreSQL Flexible Server',
<img width="1124" alt="Screenshot 2024-02-01 at 3 20 36 PM" src="https://github.com/aquasecurity/cloudsploit/assets/87388442/8292f93d-dada-45a9-b5cd-1067c3876402">
I don't see ATP for flexible servers, can only see defender which is enabled at subscription level and falls under "open source relational databases" category, please verify this.

2024-02-01 10:51 UTC, fatima99s commented on plugins/azure/postgresqlserver/flexibleServerATP.js
> +    recommended_action: 'Ensure Defender is enabled for PostgreSQL Flexible Server',
we can enable the defender for postgres flexible server at resource level unlike other services if the defender is enable its enabled for all resources of that service , for postgres we can enable defender for one server and disable for others.

2024-02-01 11:41 UTC, mehakseedat63 requested changes

2024-02-01 11:41 UTC, mehakseedat63 commented on plugins/azure/postgresqlserver/flexibleServerATP.js
> +    description: 'Ensures Defender is enabled for Advanced Threat Protection on PostgreSQL flexible servers.',
```suggestion
    description: 'Ensures Advanced Threat Protection is enabled on PostgreSQL flexible servers.',
```

2024-02-01 11:41 UTC, mehakseedat63 commented on plugins/azure/postgresqlserver/flexibleServerATP.js
> +    recommended_action: 'Ensure Defender is enabled for PostgreSQL Flexible Server.',
change the wording for Advanced Threat protection and not defender

2024-02-19 00:35 UTC, mehakseedat63 requested changes

2024-02-19 00:35 UTC, mehakseedat63 commented on plugins/azure/postgresqlserver/flexibleServerATP.js
> +                                'Advanced Threat Protection for the PostgreSQL flexible server is enabled', location, server.id);
```suggestion
                                'Advanced Threat Protection is enabled for PostgreSQL flexible server', location, server.id);
```

2024-02-19 00:35 UTC, mehakseedat63 commented on plugins/azure/postgresqlserver/flexibleServerATP.js
> +                                'Advanced Threat Protection for the PostgreSQL flexible server is disabled', location, server.id);
```suggestion
                                'Advanced Threat Protection is disabled for PostgreSQL flexible server', location, server.id);
```

2024-02-19 00:35 UTC, mehakseedat63 commented on plugins/azure/postgresqlserver/flexibleServerATP.spec.js
> +                expect(results[0].message).to.include('Advanced Threat Protection for the PostgreSQL flexible server is disabled');
```suggestion
                expect(results[0].message).to.include('Advanced Threat Protection is disabled for PostgreSQL flexible server');
```

2024-02-19 00:35 UTC, mehakseedat63 commented on plugins/azure/postgresqlserver/flexibleServerATP.spec.js
> +                expect(results[0].message).to.include('Advanced Threat Protection for the PostgreSQL flexible server is enabled');
```suggestion
                expect(results[0].message).to.include('Advanced Threat Protection is enabled for PostgreSQL flexible server');
```

2024-02-19 00:37 UTC, mehakseedat63 approved these changes

2024-02-19 00:38 UTC, merged