added settings for vpn check for network gateways
aquasecurity/cloudsploit pull request #1904
Opened 2024-02-07 13:21 UTC by muzzamilinovaqo

2024-02-18 17:48 UTC, mehakseedat63 requested changes

2024-02-18 17:48 UTC, mehakseedat63 commented on plugins/azure/virtualnetworks/noNetworkGatewaysInUse.js
> +            regex: '^.*$',
```suggestion
            regex: '^.*$',
```
regex should only allow vpn, expressroute and * as values

2024-02-18 17:48 UTC, mehakseedat63 commented on plugins/azure/virtualnetworks/noNetworkGatewaysInUse.js
> +            default: '*',
```suggestion
            default: '*',
```
don't think we need * we can just leave blank for any type

2024-02-18 17:48 UTC, mehakseedat63 commented on plugins/azure/virtualnetworks/noNetworkGatewaysInUse.js
> +                            helpers.addResult(results, 2, `Virtual network is using ${config} network gateways: ${restrictGateways.join(',')}`, location, virtualNetwork.id);
```suggestion
                            helpers.addResult(results, 2, `Virtual network is using following ${config} network gateways: ${restrictGateways.join(',')}`, location, virtualNetwork.id);
```

2024-02-18 17:48 UTC, mehakseedat63 commented on plugins/azure/virtualnetworks/noNetworkGatewaysInUse.js
> +                            helpers.addResult(results, 0, `Virtual network is not using ${config} network gateways`, location, virtualNetwork.id);
```suggestion
                            helpers.addResult(results, 0, `Virtual network is not using any ${config} network gateways`, location, virtualNetwork.id);
```

2024-02-19 12:59 UTC, alphadev4 commented on plugins/azure/virtualnetworks/noNetworkGatewaysInUse.js
> +                        gatewaysList.push({id:virtualNetworkGateway.id, name: virtualNetworkGateway.name, gatewayType: virtualNetworkGateway.gatewayType});
```suggestion
                        gatewaysList.push({id:virtualNetworkGateway.id, name: virtualNetworkGateway.name, gatewayType: virtualNetworkGateway.gatewayType? virtualNetworkGateway.gatewayType: ''});
```

2024-02-19 13:07 UTC, alphadev4 approved these changes

2024-02-19 13:09 UTC, mehakseedat63 approved these changes

2024-02-19 13:10 UTC, mehakseedat63 approved these changes

2024-02-19 13:10 UTC, merged