Create azure app service plugin nodeJsVersion that checks if nodeJs version is latest or not
aquasecurity/cloudsploit pull request #1929
Opened 2024-02-27 12:11 UTC by muzzamilinovaqo

2024-02-28 06:45 UTC, fatima99s requested changes

2024-02-28 06:45 UTC, fatima99s commented on plugins/azure/appservice/nodeJsVersion.js
> +    description: 'Ensures the latest version of NodeJs is installed for all App Services',
```suggestion
    description: 'Ensures the latest version of Node.js is installed for all App Services',
```

2024-02-28 06:45 UTC, fatima99s commented on plugins/azure/appservice/nodeJsVersion.js
> +    title: 'NodeJs Version',
```suggestion
    title: 'Node.js Version',
```

2024-02-28 06:45 UTC, fatima99s commented on plugins/azure/appservice/nodeJsVersion.js
> +            regex: '[0-9.]{1,2}-lts'
```suggestion
            regex: '[0-9.]{1,2}'
```

2024-02-28 06:45 UTC, fatima99s commented on plugins/azure/appservice/nodeJsVersion.js
> +            regex: '[0-9.]{1,2}-lts'
handle the -lts logic in code

2024-02-28 06:45 UTC, fatima99s commented on plugins/azure/appservice/nodeJsVersion.js
> +                } else {
add the logic for if the app is on windows platform

2024-02-28 06:45 UTC, fatima99s commented on plugins/azure/appservice/nodeJsVersion.js
> +                        console.log(webConfigs.data[0].linuxFxVersion);
```suggestion
 
```

2024-03-04 18:03 UTC, alphadev4 commented on plugins/azure/appservice/nodeJsVersion.js
> +    recommended_action: 'Select the latest version of Node.js for all Node.js-based App Services',
```suggestion
    recommended_action: 'Select the latest version of Node for all Node.js based App Services',
```

2024-03-04 18:04 UTC, alphadev4 commented on plugins/azure/appservice/nodeJsVersion.js
> +    recommended_action: 'Select the latest version of Node for all Node.js based App Services',
```suggestion
    recommended_action: 'Select the latest version of Node for all Node.js based App Services.',
```

2024-03-05 06:31 UTC, alphadev4 approved these changes

2024-03-05 06:33 UTC, merged