aws cloudformation deletion policy
aquasecurity/cloudsploit pull request #1965
Opened 2024-03-26 08:59 UTC by muzzamilinovaqo

2024-03-28 07:32 UTC, fatima99s requested changes

2024-03-28 07:32 UTC, fatima99s commented on plugins/aws/cloudformation/cloudformationDeletionPolicy.js
> +    title: 'CloudFormation Deletion Policy in Use',
```suggestion
    title: 'CloudFormation Deletion Policy In Use',
```

2024-03-28 07:32 UTC, fatima99s commented on plugins/aws/cloudformation/cloudformationDeletionPolicy.js
> +    description: 'Ensures that a deletion policy is used for Amazon CloudFormation stacks.',
```suggestion
    description: 'Ensures that deletion policy is used for Amazon CloudFormation stacks.',
```

2024-03-28 07:32 UTC, fatima99s commented on plugins/aws/cloudformation/cloudformationDeletionPolicy.js
> +    more_info: 'AWS Cloudformation stacks should have a deletion policy, implemented with the DeletionPolicy attribute in order preserve or backup AWS resources when the stacks are deleted.',
make it more descriptive

2024-03-28 07:32 UTC, fatima99s commented on plugins/aws/cloudformation/cloudformationDeletionPolicy.js
> +    recommended_action: 'Enable Deletion Policy attribute in the AWS Cloudformation stack.',
```suggestion
    recommended_action: 'Enable deletion policy attribute in the AWS Cloudformation stack.',
```

2024-03-28 07:32 UTC, fatima99s commented on plugins/aws/cloudformation/cloudformationDeletionPolicy.js
> +                if (!stack.StackId) return;
```suggestion
                if (!stack.StackId) return;
                
```

2024-03-28 07:32 UTC, fatima99s commented on plugins/aws/cloudformation/cloudformationDeletionPolicy.js
> +                if (templates && templates.data && templates.data.TemplateBody) {
add the checks if (templates.err || !templates || !templates.data) {
helpers.addResult(results, 3,
                        `Unable to query for CloudFormation stack template: ${helpers.addError(templates)}`, region, resource);

2024-03-28 07:32 UTC, fatima99s commented on plugins/aws/cloudformation/cloudformationDeletionPolicy.js
> +                            `Deletion Policy is used for CloudFormation stack "${stack.StackName}"`,
```suggestion
                            "Deletion Policy is used for CloudFormation stack ",
```

2024-03-28 07:32 UTC, fatima99s commented on plugins/aws/cloudformation/cloudformationDeletionPolicy.js
> +                        helpers.addResult(results, 2, `Deletion Policy is not used for CloudFormation stack "${stack.StackName}"`,
```suggestion
                        helpers.addResult(results, 2, "Deletion Policy is not used for CloudFormation stack ",
```

2024-04-16 12:07 UTC, alphadev4 commented on plugins/aws/cloudformation/cloudformationDeletionPolicy.js
> +    more_info: 'CloudFormation deletes the resource and all its content during stack deletion. With the DeletionPolicy attribute you can preserve, backup a resource when its stack is deleted. A Delet
```suggestion
    more_info: 'DeletionPolicy attribute allows to preserve and backup a resource when its stack is deleted. By default, AWS CloudFormation deletes the resource and all its content if a resource has no DeletionPolicy attribute in a template.',
```

2024-04-16 12:21 UTC, alphadev4 commented on plugins/aws/cloudformation/cloudformationDeletionPolicy.js
> +    description: 'Ensures that deletion policy is used for Amazon CloudFormation stacks.',
```suggestion
    description: 'Ensures that deletion policy is used for Amazon CloudFormation stacks.',
```

2024-04-16 12:22 UTC, alphadev4 commented on plugins/aws/cloudformation/cloudformationDeletionPolicy.js
> +    recommended_action: 'Enable deletion policy attribute in the AWS Cloudformation stack.',
```suggestion
    recommended_action: 'Add DeletionPolicy attribute in the AWS Cloudformation stack template.',
```

2024-04-16 12:42 UTC, alphadev4 requested changes

2024-04-16 12:42 UTC, alphadev4 commented on plugins/aws/cloudformation/cloudformationDeletionPolicy.js
> +                if (!stack.StackId) return;
```suggestion
                if (!stack.StackName) continue;
```

2024-04-16 12:42 UTC, alphadev4 commented on plugins/aws/cloudformation/cloudformationDeletionPolicy.js
> +                    return rcb();
should not use return rcb() inside the for loop

2024-04-16 12:42 UTC, alphadev4 commented on plugins/aws/cloudformation/cloudformationDeletionPolicy.js
> +                if (templates && templates.data && templates.data.TemplateBody) {
```suggestion
                if (templates.data.TemplateBody) {
```

2024-04-16 12:42 UTC, alphadev4 commented on plugins/aws/cloudformation/cloudformationDeletionPolicy.js
> +                            'Deletion Policy is used for CloudFormation stack ',
```suggestion
                            'Deletion Policy is used for CloudFormation stack',
```

2024-04-18 19:33 UTC, alphadev4 approved these changes

2024-04-22 12:38 UTC, merged