dynamodb deletion protection enabled
aquasecurity/cloudsploit pull request #1966
Opened 2024-03-26 09:05 UTC by muzzamilinovaqo

2024-03-28 07:38 UTC, fatima99s requested changes

2024-03-28 07:38 UTC, fatima99s commented on plugins/aws/dynamodb/dynamoDeletionProtection.js
> +    more_info: 'With Deletion Protection safety feature enabled, you have the guarantee that your Amazon DynamoDB tables can\'t be accidentally deleted and make sure that your data remains safe. Dele
```suggestion
    more_info: 'Enabling the Deletion Protection safety feature ensures that Amazon DynamoDB tables cannot be accidentally deleted, thereby safeguarding your data and preventing any deletions via the AWS Management Console by users. ',
```

2024-03-28 10:33 UTC, alphadev4 commented on plugins/aws/dynamodb/dynamoDeletionProtection.js
> +    description: 'Ensures that your Amazon DynamoDB tables have Deletion Protection feature enabled.',
```suggestion
    description: 'Ensures that DynamoDB tables have deletion protection feature enabled.',
```

2024-03-28 10:38 UTC, alphadev4 commented on plugins/aws/dynamodb/dynamoDeletionProtection.js
> +    more_info: 'Enabling the Deletion Protection safety feature ensures that Amazon DynamoDB tables cannot be accidentally deleted, thereby safeguarding your data and preventing any deletions via the
```suggestion
    more_info: 'Enabling deletion protection feature ensures the prevention of accidental deletion of DynamoDB tables during regular maintenance operations, thereby safeguarding your data.',
```

2024-03-28 10:39 UTC, alphadev4 commented on plugins/aws/dynamodb/dynamoDeletionProtection.js
> +    link: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-deletion-protection.html',
```suggestion
    link: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/WorkingWithTables.Basics.html#WorkingWithTables.Basics.DeletionProtection',
```

2024-03-28 10:42 UTC, alphadev4 commented on plugins/aws/dynamodb/dynamoDeletionProtection.js
> +    apis: ['DynamoDB:listTables', 'DynamoDB:describeTable'],
```suggestion
    apis: ['DynamoDB:listTables', 'DynamoDB:describeTable', 'sts:getCallerIdentity'],
```

2024-03-28 10:46 UTC, alphadev4 commented on plugins/aws/dynamodb/dynamoDeletionProtection.spec.js
> +                expect(results[0].message).to.include('DynamoDB table "test-table" has deletion protection enabled');
```suggestion
                expect(results[0].region).to.include('us-east-1')
                expect(results[0].message).to.include('DynamoDB table "test-table" has deletion protection enabled');
```

2024-03-28 10:46 UTC, alphadev4 commented on plugins/aws/dynamodb/dynamoDeletionProtection.spec.js
> +                expect(results[0].status).to.equal(0);
```suggestion
                expect(results[0].status).to.equal(0);
                expect(results[0].region).to.include('us-east-1')
```

2024-04-02 09:04 UTC, alphadev4 approved these changes

2024-04-02 09:11 UTC, merged