lambda code signing config enabled
aquasecurity/cloudsploit pull request #1967
Opened 2024-03-26 09:10 UTC by muzzamilinovaqo

2024-03-28 07:47 UTC, fatima99s requested changes

2024-03-28 07:47 UTC, fatima99s commented on exports.js
> +};
remove  extra line

2024-03-28 07:47 UTC, fatima99s commented on plugins/aws/lambda/lambdaCodeSigningEnabled.js
> +                if (!lambdaFunc.FunctionName) continue;
```suggestion

                if (!lambdaFunc.FunctionName) continue;
```

2024-03-28 07:47 UTC, fatima99s commented on plugins/aws/lambda/lambdaCodeSigningEnabled.js
> +                var resource = lambdaFunc.FunctionName;
```suggestion
                var resource = lambdaFunc.FunctionArn;
```

2024-03-28 07:47 UTC, fatima99s commented on plugins/aws/lambda/lambdaCodeSigningEnabled.js
> +                var codeSigningConfig = helpers.addSource(cache, source, ['lambda', 'getFunctionCodeSigningConfig', region, resource]);
```suggestion
                var codeSigningConfig = helpers.addSource(cache, source, ['lambda', 'getFunctionCodeSigningConfig', region,lambdaFunc.FunctionName]);
```

2024-03-28 07:47 UTC, fatima99s commented on plugins/aws/lambda/lambdaCodeSigningEnabled.js
> +                if (codeSigningConfig && codeSigningConfig.data && codeSigningConfig.data.CodeSigningConfigArn) {
add checks for error and null data

2024-03-28 07:47 UTC, fatima99s commented on plugins/aws/lambda/lambdaCodeSigningEnabled.js
> +                    helpers.addResult(results, 0, 'Code signing config is enabled for Lambda Function', region,resource);
```suggestion
                    helpers.addResult(results, 0, ' Lambda Function has code signing config enabled ', region,resource);
```

2024-03-28 07:47 UTC, fatima99s commented on plugins/aws/lambda/lambdaCodeSigningEnabled.js
> +                    helpers.addResult(results, 2, 'Code signing config is not enabled for Lambda Function', region,resource);
```suggestion
                    helpers.addResult(results, 2, 'Lambda Function does not have code signing config enabled', region,resource);
```

2024-04-16 12:58 UTC, alphadev4 commented on plugins/aws/lambda/lambdaCodeSigningEnabled.js
> +    more_info: 'Code Signing ensures that the function code has been signed by an approved (trusted) source, has not been altered since signing, and that the code signature has not expired or been re
```suggestion
    more_info: 'Code signing for AWS Lambda helps to ensure that only trusted code runs in Lambda functions. When you enable code signing for a function, Lambda checks every code deployment and verifies that the code package is signed by a trusted source.',
```

2024-04-16 12:59 UTC, alphadev4 commented on plugins/aws/lambda/lambdaCodeSigningEnabled.js
> +    recommended_action: 'Modify Lambda function configurations and enable code signing',
```suggestion
    recommended_action: 'Modify Lambda function configurations and enable code signing.',
```

2024-04-16 18:06 UTC, alphadev4 commented on plugins/aws/lambda/lambdaCodeSigningEnabled.js
> +                if (!lambdaFunc.FunctionName) continue;
```suggestion
                if (!lambdaFunc.FunctionName) continue;
```

2024-04-16 18:09 UTC, alphadev4 commented on plugins/aws/lambda/lambdaCodeSigningEnabled.js
> +                var codeSigningConfig = helpers.addSource(cache, source, ['lambda', 'getFunctionCodeSigningConfig', region,lambdaFunc.FunctionName]);
```suggestion
                var codeSigningConfig = helpers.addSource(cache, source, 
                      ['lambda', 'getFunctionCodeSigningConfig', region, lambdaFunc.FunctionName]);
```

2024-04-16 18:14 UTC, alphadev4 commented on plugins/aws/lambda/lambdaCodeSigningEnabled.js
> +                        `Unable to query for Lambda function Code Signing Config: ${helpers.addError(codeSigningConfig)}`, region, resource);
```suggestion
                        `Unable to query for Lambda function code signing config: ${helpers.addError(codeSigningConfig)}`, region, resource);
```

2024-04-16 18:22 UTC, alphadev4 requested changes

2024-04-16 18:22 UTC, alphadev4 commented on plugins/aws/lambda/lambdaCodeSigningEnabled.js
> +                    return rcb();
should use continue instead of rcb() inside for loop

2024-04-16 18:22 UTC, alphadev4 commented on plugins/aws/lambda/lambdaCodeSigningEnabled.js
> +                    helpers.addResult(results, 0, ' Lambda Function has code signing config enabled ', region,resource);
```suggestion
                    helpers.addResult(results, 0, 'Lambda function has code signing config enabled', region, resource);
```

2024-04-16 18:22 UTC, alphadev4 commented on plugins/aws/lambda/lambdaCodeSigningEnabled.js
> +                    helpers.addResult(results, 2, 'Lambda Function does not have code signing config enabled', region,resource);
```suggestion
                    helpers.addResult(results, 2, 'Lambda Function does not have code signing config enabled', region, resource);
```

2024-04-16 18:22 UTC, alphadev4 commented on plugins/aws/lambda/lambdaCodeSigningEnabled.spec.js
> +                expect(results[0].status).to.equal(0);
test cases are missing the message and region checks

2024-04-18 19:19 UTC, alphadev4 commented on plugins/aws/lambda/lambdaCodeSigningEnabled.js
> +    description: 'Ensure that AWS Lambda functions are configured to use the Code Signing feature.',
```suggestion
    description: 'Ensure that AWS Lambda functions are configured to use the code signing feature.',
```

2024-04-18 19:20 UTC, alphadev4 commented on plugins/aws/lambda/lambdaCodeSigningEnabled.js
> +    more_info: 'Code signing for AWS Lambda helps to ensure that only trusted code runs in Lambda functions. When you enable code signing for a function, Lambda checks every code deployment and verif
```suggestion
    more_info: 'Code signing for AWS Lambda helps to ensure that only trusted code runs in Lambda functions. Enabling code signing for a function, ensures that lambda checks every code deployment and verifies that the code package is signed by a trusted source.',
```

2024-04-18 19:22 UTC, alphadev4 commented on plugins/aws/lambda/lambdaCodeSigningEnabled.js
> +                if (codeSigningConfig && codeSigningConfig.data && codeSigningConfig.data.CodeSigningConfigArn) {
```suggestion
                if (codeSigningConfig.data.CodeSigningConfigArn) {
```

2024-04-18 19:24 UTC, alphadev4 commented on plugins/aws/lambda/lambdaCodeSigningEnabled.js
> +                    helpers.addResult(results, 0, 'Lambda function has code signing config enabled', region, resource);
```suggestion
                    helpers.addResult(results, 0, 'Lambda function has code signing feature enabled', region, resource);
```

2024-04-18 19:24 UTC, alphadev4 commented on plugins/aws/lambda/lambdaCodeSigningEnabled.js
> +                    helpers.addResult(results, 2, 'Lambda Function does not have code signing config enabled', region, resource);
```suggestion
                    helpers.addResult(results, 2, 'Lambda function does not have code signing feature enabled', region, resource);
```

2024-04-18 19:24 UTC, alphadev4 commented on plugins/aws/lambda/lambdaCodeSigningEnabled.spec.js
> +                expect(results[0].message).to.include('Lambda Function does not have code signing config enabled')
```suggestion
                expect(results[0].message).to.include('Lambda function does not have code signing feature enabled')
```

2024-04-18 19:24 UTC, alphadev4 commented on plugins/aws/lambda/lambdaCodeSigningEnabled.spec.js
> +                expect(results[0].message).to.include('Lambda function has code signing config enabled')
```suggestion
                expect(results[0].message).to.include('Lambda function has code signing feature enabled')
```

2024-04-18 19:27 UTC, alphadev4 approved these changes

2024-04-22 12:56 UTC, alphadev4 approved these changes

2024-04-22 12:56 UTC, merged