aws lambda dead letter queue
aquasecurity/cloudsploit pull request #1968
Opened 2024-03-26 09:53 UTC by muzzamilinovaqo

2024-03-28 07:59 UTC, fatima99s requested changes

2024-03-28 07:59 UTC, fatima99s commented on plugins/aws/lambda/lambdaDeadLetterQueue.js
> +            for (var lambdaFunc of listFunctions.data) {
update the same as Lambda Code Signing Enabled plugin

2024-03-28 07:59 UTC, fatima99s commented on plugins/aws/lambda/lambdaDeadLetterQueue.js
> +                    helpers.addResult(results, 0, 'Lambda function has Dead Letter Queue configured', region, resource);
```suggestion
                    helpers.addResult(results, 0, 'Lambda function has dead letter queue configured', region, resource);
```

2024-03-28 07:59 UTC, fatima99s commented on plugins/aws/lambda/lambdaDeadLetterQueue.js
> +                    helpers.addResult(results, 2, 'Lambda function does not have Dead Letter Queue configured', region, resource);
```suggestion
                    helpers.addResult(results, 2, 'Lambda function does not have dead letter queue configured', region, resource);
```

2024-04-17 08:52 UTC, fatima99s commented on exports.js
```suggestion


```

2024-04-17 08:52 UTC, fatima99s commented on exports.js
> +};
remove extra line

2024-04-17 09:10 UTC, fatima99s commented on plugins/aws/lambda/lambdaDeadLetterQueue.js
> +    link: 'https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-deadletterqueue.html',
https://docs.aws.amazon.com/lambda/latest/dg/invocation-async.html#invocation-dlq

2024-04-17 09:23 UTC, fatima99s commented on plugins/aws/lambda/lambdaDeadLetterQueue.js
> +    more_info: 'Dead Letter Queues (DLQs) for your Amazon Lambda functions can make your serverless application more resilient by capturing and storing unprocessed events from asynchronous invocation
```suggestion
    more_info: 'Dead Letter Queues (DLQs) are used to store discarded events for further processing, providing a version-specific configuration locked in at publishing, offering a reliable fallback mechanism for failed event processing. They are essential for preserving failed events, aiding in debugging and analysis of processing errors.',
```

2024-04-17 09:50 UTC, fatima99s requested changes

2024-04-17 09:50 UTC, fatima99s commented on plugins/aws/lambda/lambdaDeadLetterQueue.js
> +                        `Unable to query for Lambda function Config: ${helpers.addError(functionConfig)}`, region, resource);
```suggestion
                        `Unable to query for Lambda function config: ${helpers.addError(functionConfig)}`, region, resource);
```

2024-04-17 09:56 UTC, fatima99s commented on plugins/aws/lambda/lambdaDeadLetterQueue.js
> +    recommended_action: 'Modify Lambda function configurations and enable dead letter queue',
```suggestion
    recommended_action: 'Modify Lambda function configurations and enable dead letter queue.',
```

2024-04-17 09:57 UTC, fatima99s requested changes

2024-04-17 09:57 UTC, fatima99s commented on plugins/aws/lambda/lambdaDeadLetterQueue.js
> +                    return rcb();
use contine instead of rcb()

2024-04-18 17:07 UTC, alphadev4 commented on plugins/aws/lambda/lambdaDeadLetterQueue.js
> +    link: 'https://docs.aws.amazon.com/lambda/latest/dg/invocation-async.html#invocation-dlq',
```suggestion
    more_info: 'Configuring Dead Letter Queues (DLQs) with lambda functions helps to store discarded events and isolate messages that can\'t be processed correctly. It helps to configure an alarm for any messages moved to a dead-letter queue. They are essential in preserving failed events,debugging and determining why their processing didn\'t succeed. ',
    link: 'https://docs.aws.amazon.com/lambda/latest/dg/invocation-async.html#invocation-dlq',
```

2024-04-18 17:09 UTC, alphadev4 commented on plugins/aws/lambda/lambdaDeadLetterQueue.js
> +    more_info: 'Configuring Dead Letter Queues (DLQs) with lambda functions helps to store discarded events and isolate messages that can\'t be processed correctly. It helps to configure an alarm for
```suggestion
    more_info: 'Configuring Dead Letter Queues (DLQs) with lambda functions helps to store discarded events and isolate messages that can\'t be processed correctly. It helps to configure an alarm for any messages moved to a dead-letter queue. They are essential in preserving failed events,debugging and determining why their processing didn\'t succeed.',
```

2024-04-18 17:12 UTC, alphadev4 approved these changes

2024-04-22 12:57 UTC, alphadev4 approved these changes

2024-04-22 13:01 UTC, merged