aws lambda enhanced monitoring
aquasecurity/cloudsploit pull request #1969
Opened 2024-03-26 10:09 UTC by muzzamilinovaqo

2024-03-28 08:02 UTC, fatima99s requested changes

2024-03-28 08:02 UTC, fatima99s commented on plugins/aws/lambda/lambdaEnhancedMonitoring.js
> +                var resource = lambdaFunc.FunctionName;
resource should be the arn . store the function name in a seperate variable for the post call

2024-03-28 08:02 UTC, fatima99s commented on plugins/aws/lambda/lambdaEnhancedMonitoring.js
> +                if (functionInfo && functionInfo.data && functionInfo.data.Configuration &&
check the checks for error and null data

2024-03-28 08:02 UTC, fatima99s commented on plugins/aws/lambda/lambdaEnhancedMonitoring.js
> +    more_info: 'Enhanced monitoring using Amazon CloudWatch Lambda Insights help you to monitor, troubleshoot, and optimize your functions.',
make it more descriptive

2024-04-17 13:49 UTC, fatima99s commented on plugins/aws/lambda/lambdaEnhancedMonitoring.js
> +    title: 'Lambda Enable Enhanced Monitoring',
```suggestion
    title: 'Lambda Enhanced Monitoring Enabled',
```

2024-04-17 13:50 UTC, fatima99s commented on plugins/aws/lambda/lambdaEnhancedMonitoring.js
> +                var functionInfo = helpers.addSource(cache, source, ['lambda', 'getFunction', region, lambdaFunc.FunctionName]);
```suggestion
                var functionInfo = helpers.addSource(cache, source, 
                ['lambda', 'getFunction', region, lambdaFunc.FunctionName]);
```

2024-04-17 13:51 UTC, fatima99s commented on plugins/aws/lambda/lambdaEnhancedMonitoring.js
> +                if (!lambdaFunc.FunctionArn) continue;
```suggestion
                if (!lambdaFunc.FunctionArn || !lambdaFunc.FunctionName) continue;
```

2024-04-17 14:03 UTC, fatima99s requested changes

2024-04-18 18:02 UTC, alphadev4 commented on plugins/aws/lambda/lambdaEnhancedMonitoring.js
> +    description: 'Ensure that AWS Lambda functions enhanced monitoring is enabled.',
```suggestion
    description: 'Ensure that Lambda functions have enhanced monitoring enabled.',
```

2024-04-18 18:44 UTC, alphadev4 commented on plugins/aws/lambda/lambdaEnhancedMonitoring.js
> +                        `Unable to query for Lambda function Information: ${helpers.addError(functionInfo)}`, region,resource);
```suggestion
                        `Unable to query for Lambda function details: ${helpers.addError(functionInfo)}`, region, resource);
```

2024-04-18 19:13 UTC, alphadev4 commented on plugins/aws/lambda/lambdaEnhancedMonitoring.js
> +    link: 'https://docs.aws.amazon.com/lambda/latest/dg/monitoring-insights.html',
```suggestion
    link: 'https://docs.aws.amazon.com/lambda/latest/dg/monitoring-insights.html#monitoring-insights-enabling-console',
```

2024-04-18 19:14 UTC, alphadev4 commented on plugins/aws/lambda/lambdaEnhancedMonitoring.spec.js
> +describe('Lambda Enable Enhanced Monitoring', function () {
```suggestion
describe('Lambda Enhanced Monitoring Enabled', function () {
```

2024-04-18 19:14 UTC, alphadev4 commented on plugins/aws/lambda/lambdaEnhancedMonitoring.spec.js
> +                expect(results[0].message).to.include('Unable to query for Lambda function Information');
```suggestion
                expect(results[0].message).to.include('Unable to get Lambda function details:');
```

2024-04-22 12:40 UTC, alphadev4 commented on plugins/aws/lambda/lambdaEnhancedMonitoring.js
> +                    helpers.addResult(results, 0, 'Lambda functions has enhanced monitoring enabled', region, resource);
```suggestion
                    helpers.addResult(results, 0, 'Lambda function has enhanced monitoring enabled', region, resource);
```

2024-04-22 12:40 UTC, alphadev4 commented on plugins/aws/lambda/lambdaEnhancedMonitoring.spec.js
> +                expect(results[0].message).to.include('Lambda functions has enhanced monitoring enabled');
```suggestion
                expect(results[0].message).to.include('Lambda function has enhanced monitoring enabled');
```

2024-04-22 12:42 UTC, alphadev4 approved these changes

2024-04-22 12:42 UTC, merged