aws route53 in use
aquasecurity/cloudsploit pull request #1972
Opened 2024-03-26 10:25 UTC by muzzamilinovaqo

2024-03-28 08:24 UTC, fatima99s requested changes

2024-03-28 08:24 UTC, fatima99s commented on plugins/aws/route53/route53InUse.js
> +        var region = helpers.defaultRegion(settings);
```suggestion
        var region = helpers.defaultRegion(settings);
        
```

2024-03-28 08:24 UTC, fatima99s commented on plugins/aws/route53/route53InUse.js
> +
```suggestion
```

2024-03-28 08:24 UTC, fatima99s commented on plugins/aws/route53/route53InUse.js
> +    more_info: 'AWS Route 53 allows you to create and manage DNS hosted zones for all your domain names registered with AWS or with other domain registrars.',
```suggestion
    more_info: 'AWS Route 53 simplifies DNS management, ensuring reliable and efficient routing for end users to your website through globally-dispersed DNS servers, enhancing accessibility and performance.',
```

2024-04-22 08:24 UTC, fatima99s commented on plugins/aws/route53/route53InUse.js
> +    more_info: 'AWS Route 53 simplifies DNS management, ensuring reliable and efficient routing for end users to your website through globally-dispersed DNS servers, enhancing accessibility and perfo
```suggestion
    more_info: '
AWS Route 53 simplifies DNS management, ensuring reliable and efficient routing for end users to your website through globally-dispersed DNS servers, enhancing accessibility and performance. It facilitates domain registration, DNS routing, and health checking, allowing seamless management of your web infrastructure.',
```

2024-04-22 08:26 UTC, fatima99s commented on plugins/aws/route53/route53InUse.js
> +    recommended_action: 'Register your domain using Route53 DNS service.',
```suggestion
    recommended_action: 'Register your domain with AWS Route 53 for seamless DNS management.',
```

2024-04-22 09:48 UTC, alphadev4 approved these changes

2024-04-22 13:00 UTC, alphadev4 approved these changes

2024-04-22 13:01 UTC, merged