aws workspace operational state
aquasecurity/cloudsploit pull request #1973
Opened 2024-03-26 11:30 UTC by muzzamilinovaqo

2024-03-28 08:29 UTC, fatima99s requested changes

2024-03-28 08:29 UTC, fatima99s commented on plugins/aws/workspaces/workSpacesOperationalState.js
> +            }
```suggestion
            if (!listWorkspaces)  return rcb();
```

2024-03-28 08:29 UTC, fatima99s commented on plugins/aws/workspaces/workSpacesOperationalState.js
> +    title: 'WorkSpaces Operational State',
```suggestion
    title: 'WorkSpaces Healthy Instances',
```

2024-03-28 08:29 UTC, fatima99s commented on plugins/aws/workspaces/workSpacesOperationalState.js
> +                        'The workspace is not operational', region, resource);
```suggestion
                        'The workspace is in healthy state', region, resource);
```

2024-03-28 08:29 UTC, fatima99s commented on plugins/aws/workspaces/workSpacesOperationalState.js
> +                        'WorkSpace is operational', region, resource);
```suggestion
                        'WorkSpace is not in healthy state', region, resource);
```

2024-04-21 21:20 UTC, alphadev4 commented on plugins/aws/workspaces/workSpacesOperationalState.js
> +    title: 'WorkSpaces Healthy Instances',
can you please make sure that file name is same as title, WorkSpace Healthy Instance looks fine

2024-04-21 21:22 UTC, alphadev4 commented on plugins/aws/workspaces/workSpacesOperationalState.js
> +    link: 'https://docs.aws.amazon.com/workspaces/latest/adminguide/workspace-maintenance.html',
the link doesnt look relevant, maybe this can be used 'https://docs.aws.amazon.com/workspaces/latest/adminguide/cloudwatch-dashboard.html'

2024-04-21 21:30 UTC, alphadev4 requested changes

2024-04-21 21:30 UTC, alphadev4 commented on plugins/aws/workspaces/workSpacesOperationalState.js
> +    description: 'Ensures that the AWS WorkSpaces instances are healthy.',
```suggestion
    description: 'Ensures that the AWS WorkSpace instances are healthy.',
```

2024-04-21 21:30 UTC, alphadev4 commented on plugins/aws/workspaces/workSpacesOperationalState.js
> +    more_info: 'The AWS WorkSpaces service periodically sends status requests to the WorkSpaces instances. An instance is pronounced unhealthy when it fails to respond to these HealthCheck requests.'
```suggestion
    more_info: 'WorkSpace should have healthy and running instances to ensure proper connection. The WorkSpace is marked as Unhealthy if  response isn’t received from the WorkSpace in a timely manner.',
```

2024-04-21 21:30 UTC, alphadev4 commented on plugins/aws/workspaces/workSpacesOperationalState.js
> +                        'The workspace is in healthy state', region, resource);
```suggestion
                        'WorkSpace instance is in healthy state', region, resource);
```

2024-04-21 21:30 UTC, alphadev4 commented on plugins/aws/workspaces/workSpacesOperationalState.js
> +                        'WorkSpace is not in healthy state', region, resource);
```suggestion
                        'WorkSpace instance is not in healthy state', region, resource);
```

2024-04-21 21:30 UTC, alphadev4 commented on plugins/aws/workspaces/workSpacesOperationalState.spec.js
> +                expect(results[0].region).to.include('us-east-1')
add message checks please

2024-04-22 08:17 UTC, alphadev4 commented on plugins/aws/workspaces/workSpacesHealthyInstances.js
> +    description: 'Ensures that the AWS WorkSpaces instance are healthy.',
```suggestion
    description: 'Ensures that the AWS WorkSpace have healthy instances.',
```

2024-04-22 08:18 UTC, alphadev4 commented on plugins/aws/workspaces/workSpacesHealthyInstances.js
> +    more_info: 'WorkSpace should have healthy and running instances to ensure proper connection. The WorkSpace is marked as Unhealthy if  response isn’t received from the WorkSpace in a timely manner
```suggestion
    more_info: 'Amazon WorkSpace should have healthy and running instances to ensure proper connection. The WorkSpace is marked as Unhealthy if  response isn’t received from the WorkSpace in a timely manner.',
```

2024-04-22 08:19 UTC, alphadev4 commented on plugins/aws/workspaces/workSpacesHealthyInstances.js
> +    recommended_action: 'Troubleshoot the workspace when state is unhealthy.',
```suggestion
    recommended_action: 'Troubleshoot and resolve the unhealthy workspace issues.',
```

2024-04-22 13:04 UTC, alphadev4 approved these changes

2024-04-22 13:04 UTC, merged