Azure/Event-Grid-Domain-Diagnostic-Logs
aquasecurity/cloudsploit pull request #1978
Opened 2024-03-27 02:39 UTC by alphadev4

2024-04-01 10:56 UTC, fatima99s approved these changes

2024-04-02 06:41 UTC, alphadev4 commented on plugins/azure/eventGrid/domainDiagnosticLogs.js
> +    description: 'Ensures that Azure Event Grid domains has diagnostic logs enabled.',
```suggestion
    description: 'Ensures that Azure Event Grid domain has diagnostic logs enabled.',
```

2024-04-02 06:42 UTC, alphadev4 commented on plugins/azure/eventGrid/domainDiagnosticLogs.js
> +    more_info: 'Enabling diagnostics logs for Event Grid Domains helps to allow and capture failures and detailed information about events, their sources, and the health of the Event Grid service.Thi
```suggestion
    more_info: 'Enabling diagnostics logs for Event Grid domains helps to capture failures and detailed information about events, their sources, and the health of the Event Grid service.This helps identifying potential security threats, providing essential insights for effective management and security of your environment.',
```

2024-04-02 06:45 UTC, fatima99s approved these changes

2024-04-02 07:46 UTC, mehakseedat63 approved these changes

2024-04-02 07:50 UTC, mehakseedat63 requested changes

2024-04-02 07:50 UTC, mehakseedat63 commented on plugins/azure/eventGrid/domainDiagnosticLogs.js
> +                if (!diagnosticSettings || diagnosticSettings.err || !diagnosticSettings.data) {
should !diagnosticSettings.data produce a fail instead of unknown?

2024-04-02 16:15 UTC, mehakseedat63 approved these changes

2024-04-22 12:53 UTC, merged