aws opensearch audit logs
aquasecurity/cloudsploit pull request #1986
Opened 2024-03-28 08:28 UTC by muzzamilinovaqo

2024-03-28 08:35 UTC, fatima99s requested changes

2024-03-28 08:35 UTC, fatima99s commented on plugins/aws/opensearch/opensearchEnableAuditLogs.js
> +    description: 'Ensures the Audit Logs feature is enabled for all the Amazon OpenSearch domains',
```suggestion
    description: 'Ensures the Audit Logs feature is enabled for all the Amazon OpenSearch domains.',
```

2024-03-28 08:35 UTC, fatima99s commented on plugins/aws/opensearch/opensearchEnableAuditLogs.js
> +                if (!describeDomain ||
```suggestion

                if (!describeDomain ||
```

2024-03-28 08:35 UTC, fatima99s commented on plugins/aws/opensearch/opensearchEnableAuditLogs.js
> +            listDomainNames.data.forEach(function(domain){
```suggestion
            listDomainNames.data.forEach(function(domain){
            const resource = `arn:${awsOrGov}:es:${region}:${accountId}:domain/${domain.DomainName}`;
```

2024-03-28 08:35 UTC, fatima99s commented on plugins/aws/opensearch/opensearchEnableAuditLogs.js
> +                            'Audit Logs feature is enabled for OpenSearch domain', region, domain.DomainName);
```suggestion
                            'Audit Logs feature is enabled for OpenSearch domain', region, resource);
```

2024-03-28 08:35 UTC, fatima99s commented on plugins/aws/opensearch/opensearchEnableAuditLogs.js
> +                            'Audit Logs feature is not enabled for OpenSearch domain', region, domain.DomainName);
```suggestion
                            'Audit Logs feature is not enabled for OpenSearch domain', region, resource);
```

2024-04-17 15:13 UTC, fatima99s requested changes

2024-04-21 21:02 UTC, alphadev4 commented on plugins/aws/opensearch/opensearchEnableAuditLogs.js
> +    description: 'Ensures the Audit Logs feature is enabled for all the Amazon OpenSearch domains.',
```suggestion
    description: 'Ensures the audit logs feature is enabled for OpenSearch domains.',
```

2024-04-21 21:04 UTC, alphadev4 commented on plugins/aws/opensearch/opensearchEnableAuditLogs.js
> +    more_info: 'The Audit Logs feature allows you to keep track of all user activity on your Amazon OpenSearch domains (clusters), including failed login attempts, and which users accessed certain in
```suggestion
    more_info: 'Enabling audit logs feature allows to keep track of all user activity on Amazon OpenSearch domains (clusters), including failed login attempts, and users accessed certain indices, documents, or fields and API requests, enhancing security and compliance monitoring. ',
```

2024-04-21 21:10 UTC, alphadev4 approved these changes

2024-04-22 12:44 UTC, alphadev4 approved these changes

2024-04-22 12:44 UTC, merged