Azure/Batch-Account-CMK-Encrypted
aquasecurity/cloudsploit pull request #1994
Opened 2024-05-09 22:31 UTC by alphadev4

2024-05-19 15:12 UTC, fatima99s commented on plugins/azure/batchAccounts/batchAccountCmkEncrypted.js
> +    recommended_action: 'Modify Batch account add ensure that CMK is encryption enabled.',
```suggestion
    recommended_action: 'Modify Batch account add ensure that CMK encryption enabled.',
```

2024-05-19 18:11 UTC, fatima99s commented on plugins/azure/batchAccounts/batchAccountCmkEncrypted.js
> +    description: 'Ensures that Azure Batch accounts are CMK ecnrypted.',
```suggestion
    description: 'Ensures that Azure Batch accounts are CMK encrypted.',
```

2024-05-20 11:25 UTC, mehakseedat63 requested changes

2024-05-20 11:25 UTC, mehakseedat63 commented on plugins/azure/batchAccounts/batchAccountCmkEncrypted.js
> +    recommended_action: 'Modify Batch account add ensure that CMK is encryption enabled.',
```suggestion
    recommended_action: 'Enable CMK encryption for all Azure Batch accounts..',
```

2024-05-20 11:26 UTC, mehakseedat63 requested changes

2024-05-20 11:26 UTC, mehakseedat63 commented on plugins/azure/batchAccounts/batchAccountCmkEncrypted.js
> +    recommended_action: 'Enable CMK encryption for all Azure Batch accounts..',
```suggestion
    recommended_action: 'Enable CMK encryption for all Azure Batch accounts.',
```

2024-05-20 11:26 UTC, mehakseedat63 approved these changes

2024-05-20 18:35 UTC, merged