docdb deletion protection
aquasecurity/cloudsploit pull request #2002
Opened 2024-05-10 11:39 UTC by muzzamilinovaqo

2024-05-14 17:57 UTC, fatima99s requested changes

2024-05-14 17:57 UTC, fatima99s commented on plugins/aws/documentDB/docdbDeletionProtectionEnabled.js
> +    description: 'Ensure that your Amazon DocumentDB clusters have deletion protection feature enabled.',
```suggestion
    description: 'Ensure that Amazon DocumentDB clusters have deletion protection feature enabled.',
```

2024-05-14 17:57 UTC, fatima99s commented on plugins/aws/documentDB/docdbDeletionProtectionEnabled.js
> +    more_info: 'Enabling deletion protection feature for your Amazon DocumentDB clusters acts as a safety net, preventing accidental deletions and ensuring your data stays secure and accessible at al
```suggestion
    more_info: 'Enabling deletion protection feature for Amazon DocumentDB clusters acts as a safety net, preventing accidental deletions and ensuring that the data stays secure and accessible at all times.',
```

2024-05-14 17:57 UTC, fatima99s commented on plugins/aws/documentDB/docdbDeletionProtectionEnabled.spec.js
> +                expect(results[0].status).to.equal(3);
add the message

2024-05-19 17:22 UTC, alphadev4 commented on plugins/aws/documentDB/docdbDeletionProtectionEnabled.js
> +    more_info: 'Enabling deletion protection feature for Amazon DocumentDB clusters acts as a safety net, preventing accidental deletions and ensuring that the data stays secure and accessible at all
```suggestion
    more_info: 'Enabling deletion protection feature for Amazon DocumentDB clusters acts as a safety net, preventing accidental database deletions or deletion by an unauthorized user.  A Neptune DB cluster can't be deleted while deletion protection is enabled which ensures that the data stays secure and accessible at all times.',
```

2024-05-19 17:22 UTC, alphadev4 commented on plugins/aws/documentDB/docdbDeletionProtectionEnabled.js
> +                let resource = cluster.DBClusterArn;
```suggestion
```

2024-05-19 17:22 UTC, alphadev4 commented on plugins/aws/documentDB/docdbDeletionProtectionEnabled.js
> +                        region, resource);
```suggestion
                        region, cluster.DBClusterArn);
```

2024-05-19 17:23 UTC, alphadev4 commented on plugins/aws/documentDB/docdbDeletionProtectionEnabled.js
> +                        region, resource);
```suggestion
                    helpers.addResult(results, 0, 'DocumentDB cluster has deletion protection enabled', region, resource);
```

2024-05-19 17:23 UTC, alphadev4 commented on plugins/aws/documentDB/docdbDeletionProtectionEnabled.js
> +                        region, resource);
```suggestion
                    helpers.addResult(results, 2,  'DocumentDB cluster does not have deletion protection enabled', region, cluster.DBClusterArn);
```

2024-05-19 17:25 UTC, alphadev4 commented on plugins/aws/documentDB/docdbDeletionProtectionEnabled.js
> +                    helpers.addResult(results, 2,  'DocumentDB cluster does not have deletion protection enabled', region, cluster.DBClusterArn);
```suggestion
                    helpers.addResult(results, 2, 'DocumentDB cluster does not have deletion protection enabled', region, cluster.DBClusterArn);
```

2024-05-19 17:26 UTC, alphadev4 commented on plugins/aws/documentDB/docdbDeletionProtectionEnabled.js
> +    recommended_action: 'Modify DocumentDb cluster and enable deletion protection.',
```suggestion
    more_info: 'Enabling deletion protection feature for Amazon DocumentDB clusters acts as a safety net, preventing accidental database deletions or deletion by an unauthorized user.  A Neptune DB cluster can\'t be deleted while deletion protection is enabled which ensures that the data stays secure and accessible at all times.',
    recommended_action: 'Modify DocumentDb cluster and enable deletion protection.',
```

2024-05-19 17:27 UTC, alphadev4 commented on plugins/aws/documentDB/docdbDeletionProtectionEnabled.js
> +
```suggestion
```

2024-05-19 17:27 UTC, alphadev4 approved these changes

2024-05-19 17:32 UTC, alphadev4 commented on plugins/aws/documentDB/docdbDeletionProtectionEnabled.js
> +    more_info: 'Enabling deletion protection feature for Amazon DocumentDB clusters acts as a safety net, preventing accidental database deletions or deletion by an unauthorized user.  A Neptune DB c
```suggestion
    more_info: 'Enabling deletion protection feature for Amazon DocumentDB clusters acts as a safety net, preventing accidental database deletions or deletion by an unauthorized user. It ensures that the data stays secure and accessible at all times.',
```

2024-05-20 18:09 UTC, merged