aws neptune db deletion protection
aquasecurity/cloudsploit pull request #2003
Opened 2024-05-10 11:41 UTC by muzzamilinovaqo

2024-05-14 18:03 UTC, fatima99s requested changes

2024-05-19 17:35 UTC, alphadev4 commented on plugins/aws/neptune/neptuneDbDeletionProtection.js
> +    more_info: 'Enabling deletion protection for AWS Neptune adds an extra layer of security, preventing accidental deletions and ensuring the continued availability and integrity of your valuable da
```suggestion
    more_info: 'Enabling deletion protection feature for Amazon Neptune adds an extra layer of security, preventing accidental database deletions or deletion by an unauthorized user.  A Neptune DB cluster can\'t be deleted while deletion protection is enabled which ensures continuous availability of data.',
```

2024-05-19 17:35 UTC, alphadev4 commented on plugins/aws/neptune/neptuneDbDeletionProtection.js
> +                let resource = cluster.DBClusterArn;
```suggestion
```

2024-05-19 17:36 UTC, alphadev4 commented on plugins/aws/neptune/neptuneDbDeletionProtection.js
> +                    helpers.addResult(results, 0, 'Neptune database instance has deletion protection enabled', resource, region);
```suggestion
                    helpers.addResult(results, 0, 'Neptune database instance has deletion protection enabled', cluster.DBClusterArn, region); 
```

2024-05-19 17:37 UTC, alphadev4 commented on plugins/aws/neptune/neptuneDbDeletionProtection.js
> +                    helpers.addResult(results, 2, 'Neptune database instance does not have deletion protection enabled', resource, region);
```suggestion
                    helpers.addResult(results, 2, 'Neptune database instance has deletion protection disabled', resource, region);
```

2024-05-19 17:38 UTC, alphadev4 commented on plugins/aws/neptune/neptuneDbDeletionProtection.spec.js
> +                expect(results[0].message).to.include('Neptune database instance does not have deletion protection enabled');
```suggestion
                expect(results[0].message).to.include('Neptune database instance has deletion protection disabled');
```

2024-05-20 18:10 UTC, alphadev4 commented on plugins/aws/neptune/neptuneDbDeletionProtection.js
> +    more_info: 'Enabling deletion protection feature for Amazon Neptune adds an extra layer of security, preventing accidental database deletions or deletion by an unauthorized user.  A Neptune DB cl
```suggestion
    more_info: 'Enabling deletion protection feature for Amazon Neptune adds an extra layer of security, preventing accidental database deletions or deletion by an unauthorized user. A Neptune DB cluster can\'t be deleted while deletion protection is enabled which ensures continuous availability of data.',
```

2024-05-20 18:10 UTC, alphadev4 commented on plugins/aws/neptune/neptuneDbDeletionProtection.js
> +                    helpers.addResult(results, 0, 'Neptune database instance has deletion protection enabled', cluster.DBClusterArn, region);
```suggestion
                    helpers.addResult(results, 0, 'Neptune database instance has deletion protection enabled', region, cluster.DBClusterArn); 
```

2024-05-20 18:10 UTC, alphadev4 commented on plugins/aws/neptune/neptuneDbDeletionProtection.js
> +                    helpers.addResult(results, 2, 'Neptune database instance has deletion protection disabled', cluster.DBClusterArn, region);
```suggestion
                    helpers.addResult(results, 2, 'Neptune database instance has deletion protection disabled', region, cluster.DBClusterArn);
```

2024-05-20 18:13 UTC, alphadev4 approved these changes

2024-05-20 18:15 UTC, merged