aws neptune db multiaz
aquasecurity/cloudsploit pull request #2004
Opened 2024-05-10 11:56 UTC by muzzamilinovaqo

2024-05-14 18:10 UTC, fatima99s requested changes

2024-05-14 18:10 UTC, fatima99s commented on plugins/aws/neptune/neptuneDBMultiAz.js
> +    description: 'Ensure that your AWS Neptune database instances have the multi-az feature enabled.',
```suggestion
    description: 'Ensure that AWS Neptune database instances are created to be cross-AZ for high availability.',
```

2024-05-14 18:10 UTC, fatima99s commented on plugins/aws/neptune/neptuneDBMultiAz.js
> +    more_info: 'Enabling Neptune\'s Multi-AZ feature boosts database reliability by automatically replicating data across multiple availability zones. This ensures continuous availability and minimal
```suggestion
    more_info: 'Enabling Neptune Multi-AZ feature boosts database reliability by automatically replicating data across multiple availability zones. This ensures continuous availability and minimal downtime for graph database deployments.',
```

2024-05-14 18:10 UTC, fatima99s commented on plugins/aws/neptune/neptuneDBMultiAz.js
> +    recommended_action: 'Modify Neptune database instance to multi-az feature.',
```suggestion
    recommended_action: 'Modify Neptune database instance to enable multi-az feature.',
```

2024-05-20 16:58 UTC, alphadev4 commented on plugins/aws/neptune/neptuneDBMultiAz.js
> +    more_info: 'Enabling Neptune Multi-AZ feature boosts database reliability by automatically replicating data across multiple availability zones. This ensures continuous availability and minimal do
```suggestion
    more_info: 'Enabling Multi-AZ feature for Neptune instances boosts database reliability by automatically replicating data across multiple availability zones. This ensures continuous availability and minimal downtime for graph database deployments.',
```

2024-05-20 17:01 UTC, alphadev4 approved these changes

2024-05-20 18:13 UTC, alphadev4 commented on plugins/aws/neptune/neptuneDBMultiAz.js
> +    recommended_action: 'Modify Neptune database instance to enable multi-az feature.',
```suggestion
    recommended_action: 'Modify Neptune database instance to enable multi-AZ feature.',
```

2024-05-20 18:14 UTC, alphadev4 commented on plugins/aws/neptune/neptuneDBMultiAz.js
> +                    helpers.addResult(results, 0, 'Neptune database instance has multi-AZ enabled', resource, region);
```suggestion
                    helpers.addResult(results, 0, 'Neptune database instance has multi-AZ enabled', region, resource); 
```

2024-05-20 18:14 UTC, alphadev4 commented on plugins/aws/neptune/neptuneDBMultiAz.js
> +                    helpers.addResult(results, 2, 'Neptune database instance does not have multi-AZ enabled', resource, region);
```suggestion
                    helpers.addResult(results, 2, 'Neptune database instance does not have multi-AZ enabled', region, resource);
```

2024-05-20 18:20 UTC, merged