docdb has tags
aquasecurity/cloudsploit pull request #2008
Opened 2024-05-10 13:40 UTC by muzzamilinovaqo

2024-05-14 18:12 UTC, fatima99s commented
resolve the confilts

2024-05-14 18:15 UTC, fatima99s requested changes

2024-05-14 18:15 UTC, fatima99s commented on plugins/aws/documentDB/docDbHasTags.js
> +
```suggestion
```

2024-05-14 18:15 UTC, fatima99s commented on plugins/aws/documentDB/docDbHasTags.js
> +            }
```suggestion
            }
            
```

2024-05-14 18:15 UTC, fatima99s commented on plugins/aws/documentDB/docDbHasTags.js
> +            for (let cluster of describeDBClusters.data){
```suggestion
            for (let cluster of describeDBClusters.data) {
```

2024-05-19 17:04 UTC, alphadev4 commented on helpers/aws/api_multipart.js
> +        DocDB: {
cant we use resourceGroupTaggingApi call?

2024-05-19 17:13 UTC, alphadev4 commented on plugins/aws/documentDB/docDbHasTags.js
> +                    helpers.addResult(results, 3, `Unable to get tags information for doc db cluster: ${helpers.addError(getTags)}`, region, resource);
```suggestion
                    helpers.addResult(results, 3, `Unable to get tags for DocumentDB cluster: ${helpers.addError(getTags)}`, region, resource);
```

2024-05-19 17:14 UTC, alphadev4 commented on plugins/aws/documentDB/docDbHasTags.spec.js
> +                expect(results[0].message).to.include('Unable to get tags information for doc db cluster');
```suggestion
                expect(results[0].message).to.include('Unable to get tags for DocumentDB cluster:');
```

2024-05-19 17:15 UTC, alphadev4 approved these changes

2024-05-20 18:24 UTC, merged