aws sqs has tags
aquasecurity/cloudsploit pull request #2009
Opened 2024-05-13 14:24 UTC by muzzamilinovaqo

2024-05-14 18:20 UTC, fatima99s requested changes

2024-05-14 18:20 UTC, fatima99s commented on plugins/aws/sqs/sqsHasTags.js
> +    recommended_action: 'Update Amazon SQS queue and add new tags.',
```suggestion
    recommended_action: 'Update Amazon SQS queue and add tags.',
```

2024-05-14 18:20 UTC, fatima99s commented on plugins/aws/sqs/sqsHasTags.js
> +            helpers.checkTags(cache, 'sqs', arnList, region, results, settings);
```suggestion
            helpers.checkTags(cache, 'SQS queue', arnList, region, results, settings);
```

2024-05-14 18:20 UTC, fatima99s commented on plugins/aws/sqs/sqsHasTags.js
> +    apis: ['SQS:listQueues', 'STS:getCallerIdentity', 'ResourceGroupsTaggingAPI:getResources', 'SQS:listQueueTags'],
```suggestion
    apis: ['SQS:listQueues', 'STS:getCallerIdentity', 'ResourceGroupsTaggingAPI:getResources'],
```

2024-05-14 18:20 UTC, fatima99s commented on plugins/aws/sqs/sqsHasTags.spec.js
> +        //         expect(results[0].region).to.equal('us-east-1');
update the message in spec file and pass check if sqs queue has tags is commented

2024-05-19 16:35 UTC, alphadev4 commented on plugins/aws/sqs/sqsHasTags.js
> +    description: 'Ensures that each Amazon SQS queue has tags associated',
```suggestion
    description: 'Ensures that Amazon SQS queue has tags associated.',
```

2024-05-19 16:36 UTC, alphadev4 commented on plugins/aws/sqs/sqsHasTags.js
> +    title: 'SQS Has Tags',
```suggestion
    title: 'SQS Queue Has Tags',
```

2024-05-19 16:38 UTC, alphadev4 commented on plugins/aws/sqs/sqsHasTags.js
> +    recommended_action: 'Update Amazon SQS queue and add tags.',
```suggestion
    recommended_action: 'Update SQS queue and add tags.',
```

2024-05-19 16:39 UTC, alphadev4 commented on plugins/aws/sqs/sqsHasTags.js
> +                    `Unable to query for Amazon SQS queues: ${helpers.addError(listQueues)}`, region);
```suggestion
                    `Unable to query for SQS queues: ${helpers.addError(listQueues)}`, region);
```

2024-05-19 16:39 UTC, alphadev4 commented on plugins/aws/sqs/sqsHasTags.js
> +                helpers.addResult(results, 0, 'No Amazon SQS queues found', region);
```suggestion
                helpers.addResult(results, 0, 'No SQS queues found', region);
```

2024-05-19 16:40 UTC, alphadev4 commented on plugins/aws/sqs/sqsHasTags.js
> +
```suggestion
```

2024-05-19 16:40 UTC, alphadev4 commented on plugins/aws/sqs/sqsHasTags.js
> +
```suggestion
```

2024-05-19 16:41 UTC, alphadev4 commented on plugins/aws/sqs/sqsHasTags.spec.js
> +                expect(results[0].message).to.include('No Amazon SQS queues found');
```suggestion
                expect(results[0].message).to.include('No SQS queues found');
```

2024-05-19 16:41 UTC, alphadev4 commented on plugins/aws/sqs/sqsHasTags.spec.js
> +                expect(results[0].message).to.include('Unable to query for Amazon SQS queues');
```suggestion
                expect(results[0].message).to.include('Unable to query for SQS queues');
```

2024-05-19 16:41 UTC, alphadev4 approved these changes

2024-05-20 18:29 UTC, alphadev4 approved these changes

2024-05-20 18:29 UTC, merged