Feature/43 | Added AutoScaling Same Az Elb plugin, spec file
aquasecurity/cloudsploit pull request #292
Opened 2020-08-30 23:44 UTC by AkhtarAmir

2020-09-03 16:32 UTC, giorod3 requested changes

2020-09-03 16:32 UTC, giorod3 commented on plugins/aws/autoscaling/sameAzElb.js
> +                            if(elbName in loadBalancers) {
Can you replace this check with `if(loadBalancers[elbName]) {` this technically does the same thing but is more aligned with the codebase

2020-09-03 16:32 UTC, giorod3 commented on plugins/aws/autoscaling/sameAzElb.js
> +                                elbAvailabilityZones.forEach(function(elbAz) {
before looping though elbAvailabilityZones check if it exists and has a length 
Suggestion: `if (elbAvailabilityZones && elbAvailabilityZones.length) {`

2020-09-03 16:32 UTC, giorod3 commented on plugins/aws/autoscaling/sameAzElb.js
> +                                    if(!asgAvailabilityZones.includes(elbAz)) {
same thing here, make sure asgAvailabilityZones exists before doing .includes

2020-09-11 17:04 UTC, matthewdfuller commented on plugins/aws/autoscaling/sameAzElb.js
> +    title: 'Same Availability Zone in ASG and ELB',
```suggestion
    title: 'AutoScaling ELB Same Availability Zone',
```

2020-09-13 21:34 UTC, AkhtarAmir commented on plugins/aws/autoscaling/sameAzElb.js
> +    title: 'Same Availability Zone in ASG and ELB',
Modified

2020-09-18 19:14 UTC, giorod3 approved these changes

2020-09-21 19:15 UTC, merged