Feature/plugin/iam/less restrictive iam role policies
aquasecurity/cloudsploit pull request #293
Opened 2020-09-01 13:07 UTC by jchrisfarris

Adds options to ignore roles for SAML/IDP assumption. Adds option to ignore service:* permissions

These plugins were developed by Trek10 under contract to WarnerMedia for release back into the main CloudSploit Scanning Engine. WarnerMedia expressly authorizes their contribution.

2020-09-01 13:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cloudsploit/scans?pullRequest=293) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/cloudsploit/scans?pullRequest=293) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: hauboldj<br/>:white_check_mark: farina-19<br/>:x: mtskillman<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cloudsploit/scans?pullRequest=293) it.</sub>

2020-09-03 16:39 UTC, giorod3 requested changes

2020-09-03 16:39 UTC, giorod3 commented on plugins/aws/iam/iamRolePolicies.js
> +
can you move this function to our helpers file: https://github.com/cloudsploit/scans/blob/master/helpers/aws/functions.js
and just import the file like this: `var helpers = require('../../../helpers/aws');`

2020-12-10 14:35 UTC, AkhtarAmir commented
Added separate PR for this, can be closed

2021-03-29 17:15 UTC, closed without merging