Feature/959 | Added SSM Agent Auto Update Enabled plugin, spec file
aquasecurity/cloudsploit pull request #308
Opened 2020-09-06 20:51 UTC by AkhtarAmir

2020-09-20 18:27 UTC, giorod3 requested changes

2020-09-20 18:27 UTC, giorod3 commented on plugins/aws/ssm/ssmAgentAutoUpdateEnabled.js
> +                    if (association.Name === 'AWS-UpdateSSMAgent' && association.Targets && association.Targets.length) {
```suggestion
                    if (association.Name && association.Name === 'AWS-UpdateSSMAgent' && association.Targets && association.Targets.length) {
```

2020-09-21 02:57 UTC, giorod3 approved these changes

2020-09-21 19:21 UTC, giorod3 commented on plugins/aws/ssm/ssmAgentAutoUpdateEnabled.js
> +                var resource = instance.InstanceId;
@AkhtarAmir  can you make this an arn

2020-10-05 12:28 UTC, giorod3 approved these changes

2020-10-19 17:17 UTC, matthewdfuller approved these changes

2020-10-19 17:47 UTC, merged