Feature/137 | Added SNS Topic Encrypted plugin, spec file
aquasecurity/cloudsploit pull request #319
Opened 2020-09-12 17:41 UTC by AkhtarAmir

2020-09-21 02:20 UTC, giorod3 requested changes

2020-09-21 02:20 UTC, giorod3 commented on plugins/aws/sns/topicEncrypted.js
> +    recommended_action: 'Enable Server-Side Encryption to protect the conents of SNS topic messages.',
```suggestion
    recommended_action: 'Enable Server-Side Encryption to protect the contents of SNS topic messages.',
```

2020-09-21 02:20 UTC, giorod3 commented on plugins/aws/sns/topicEncrypted.js
> +                }
you have the results flipped. 
```suggestion
                    helpers.addResult(results, 0,
                        'Server-Side Encryption is enabled for SNS topic',
                        region, resource);
                } 
```

2020-09-21 02:20 UTC, giorod3 commented on plugins/aws/sns/topicEncrypted.js
> +                }
```suggestion
                    helpers.addResult(results, 2,
                        'Server-Side Encryption is not enabled for SNS topic',
                        region, resource);
                }
```

2020-10-05 12:34 UTC, giorod3 approved these changes

2020-10-19 17:18 UTC, matthewdfuller approved these changes

2020-10-19 17:47 UTC, merged