feature/24 | Added Redshift Cluster CMK Encrypted plugin, spec file
aquasecurity/cloudsploit pull request #321
Opened 2020-09-13 23:33 UTC by AkhtarAmir

2020-09-21 02:27 UTC, giorod3 commented on plugins/aws/redshift/clusterCmkEncrypted.js
> +    title: 'Redshift Cluster Encrypted With KMS Customer Master Keys',
```suggestion
    title: 'Redshift Cluster CMK Encryption,
```

2020-09-21 02:29 UTC, giorod3 requested changes

2020-09-21 02:29 UTC, giorod3 commented on plugins/aws/redshift/clusterCmkEncrypted.js
> +    recommended_action: 'Update redshift clusters encryption configuration to use KMS CMKs unstead of AWS managed-keys.',
```suggestion
    recommended_action: 'Update redshift clusters encryption configuration to use KMS CMKs instead of AWS managed-keys.',
```

2020-10-05 12:36 UTC, giorod3 approved these changes

2020-10-19 17:21 UTC, matthewdfuller commented on plugins/aws/redshift/redshiftClusterCmkEncrypted.js
> +    recommended_action: 'Update redshift clusters encryption configuration to use KMS CMKs instead of AWS managed-keys.',
```suggestion
    recommended_action: 'Update Redshift clusters encryption configuration to use KMS CMKs instead of AWS managed-keys.',
```

2020-10-19 17:48 UTC, merged