feature/74 | Added EC2 Security Group RFC 1918 plugin, spec file
aquasecurity/cloudsploit pull request #328
Opened 2020-09-17 23:42 UTC by AkhtarAmir

2020-09-21 02:46 UTC, giorod3 requested changes

2020-09-21 02:46 UTC, giorod3 commented on plugins/aws/ec2/securityGroupRfc1918.js
> +    link: 'https://www.cloudconformity.com/knowledge-base/aws/EC2/security-group-rfc1918.html',
Use AWS links only please.

2020-09-21 02:46 UTC, giorod3 commented on plugins/aws/ec2/securityGroupRfc1918.js
> +            default: ['10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16']
change this to be a string

2020-09-21 02:46 UTC, giorod3 commented on plugins/aws/ec2/securityGroupRfc1918.js
> +                            'Security group :' + group.GroupName + ': allows inbound access for these reserved private address: ' + privateCidrsFound.join(', '),
```suggestion
                            'Security group :' + group.GroupName + ': allows inbound access for these reserved private addresses: ' + privateCidrsFound.join(', '), 
```

2020-10-05 12:38 UTC, giorod3 commented on plugins/aws/ec2/securityGroupRfc1918.js
> +    title: 'EC2 Security Group RFC 1918',
```suggestion
    title: 'Open RFC 1918',
```

2020-10-05 12:38 UTC, giorod3 approved these changes

2020-10-19 17:26 UTC, matthewdfuller commented on plugins/aws/ec2/securityGroupRfc1918.js
> +                        'Security group :' + group.GroupName + ': does not have any ip permission', region, resource);
```suggestion
                        'Security group :' + group.GroupName + ': does not have any IP permissions', region, resource);
```

2020-10-19 17:26 UTC, matthewdfuller commented on plugins/aws/ec2/securityGroupRfc1918.js
> +                            'Security group "' + group.GroupName + '" is configured to deny any reserved private address',
```suggestion
                            'Security group "' + group.GroupName + '" is not configured to allow traffic from any reserved private addresses',
```

2020-10-19 17:48 UTC, merged