Feature/115 | Added RDS Encrypted With KMS CMKs plugin, spec file
aquasecurity/cloudsploit pull request #330
Opened 2020-09-19 11:28 UTC by AkhtarAmir

2020-09-21 02:49 UTC, giorod3 requested changes

2020-09-21 02:49 UTC, giorod3 commented on plugins/aws/rds/rdsCmkEncryptionEnabled.spec.js
> +        "DBInstanceArn": "arn:aws:rds:us-east-1:560213429563:db:test-db-115",
replace your account id

2020-09-21 02:49 UTC, giorod3 commented on plugins/aws/rds/rdsCmkEncryptionEnabled.js
> +    title: 'RDS Encrypted With KMS Customer Master Keys',
```suggestion
    title: 'RDS CMK Encryption',
```

2020-10-05 13:07 UTC, giorod3 approved these changes

2020-10-19 17:27 UTC, matthewdfuller approved these changes

2020-10-19 17:49 UTC, merged