Feature/38 | Added AutoScaling ELB Health Check Active plugin, spec file
aquasecurity/cloudsploit pull request #345
Opened 2020-09-26 18:07 UTC by AkhtarAmir

2020-10-05 13:18 UTC, giorod3 approved these changes

2020-10-19 17:32 UTC, matthewdfuller requested changes
Overall, the code is good, but we need to check one extra use case when `LoadBalancerNames` in the response is empty (which indicates the ASG does not have an ELB associated with it).

If `LoadBalancerNames` is not set (or an empty array), then we should mark the ASG as `PASS` with the result `ASG does not use ELBs`.

2020-10-20 15:35 UTC, giorod3 commented
@AkhtarAmir this PR is failing lint, it looks like an indent issue. Can you fix this so I can approve it

2020-10-20 15:37 UTC, giorod3 commented on plugins/aws/autoscaling/elbHealthCheckActive.js
> +                } else {
make an else if to ensure that the user is using elb here instead of inside of the other if statement

2020-10-22 15:38 UTC, giorod3 approved these changes

2020-10-22 17:56 UTC, matthewdfuller approved these changes

2020-10-22 18:32 UTC, merged