Feature/39 | Added AutoScaling Missing Security Groups plugin, spec file
aquasecurity/cloudsploit pull request #349
Opened 2020-09-27 16:17 UTC by AkhtarAmir

2020-10-20 15:45 UTC, giorod3 commented on plugins/aws/autoscaling/asgMissingSecurityGroups.js
> +                            `Auto Scaling launch configuration "${config.LaunchConfigurationName}" refereces these missing EC2 security groups: ${missingSecurityGroups.join(', ')}`,
```suggestion
                            `Auto Scaling launch configuration "${config.LaunchConfigurationName}" references these missing EC2 security groups: ${missingSecurityGroups.join(', ')}`,
```

2020-10-20 15:46 UTC, giorod3 commented on plugins/aws/autoscaling/asgMissingSecurityGroups.js
> +                        `Auto Scaling launch configuration "${config.LaunchConfigurationName}" does not have any security group associated`,
```suggestion
                        `Auto Scaling launch configuration "${config.LaunchConfigurationName}" does not have any security groups associated`,
```

2020-10-20 15:46 UTC, giorod3 approved these changes

2020-10-20 15:47 UTC, giorod3 commented on plugins/aws/autoscaling/asgMissingSecurityGroups.js
> +                            `Auto Scaling launch configuration "${config.LaunchConfigurationName}" does not reference any missing EC2 security group`,
```suggestion
                            `Auto Scaling launch configuration "${config.LaunchConfigurationName}" does not reference any missing EC2 security groups`,
```

2020-10-20 15:47 UTC, giorod3 approved these changes

2020-10-22 18:09 UTC, matthewdfuller requested changes
Might need to update the test for the new pass condition

2020-10-22 18:09 UTC, matthewdfuller commented on plugins/aws/autoscaling/asgMissingSecurityGroups.js
> +                        region, resource);
```suggestion
                    helpers.addResult(results, 0,
                        `Auto Scaling launch configuration "${config.LaunchConfigurationName}" does not have any security groups associated`,
                        region, resource);
```

2020-10-23 15:48 UTC, giorod3 approved these changes

2020-10-26 20:41 UTC, merged