Feature/86 | Added ELB Security Policy plugin, spec file
aquasecurity/cloudsploit pull request #360
Opened 2020-10-04 20:19 UTC by AkhtarAmir

2020-10-20 16:18 UTC, giorod3 approved these changes

2020-11-25 14:40 UTC, giorod3 requested changes
just the one comment

2020-11-25 14:40 UTC, giorod3 commented on plugins/aws/elb/elbSecurityPolicy.js
> +                            if (policyAttrDesc.AttributeName === 'Reference-Security-Policy') {
```suggestion
                            if (policyAttrDesc.AttributeName && policyAttrDesc.AttributeName === 'Reference-Security-Policy') {
```

2021-02-04 17:55 UTC, AkhtarAmir commented
This is a duplicate plugin

2021-02-04 17:55 UTC, closed without merging