feature/AK-55: Added AWS Redshift User Activity Logging Enabled plugin, test cases file
aquasecurity/cloudsploit pull request #380
Opened 2020-10-17 08:58 UTC by AkhtarAmir

2020-11-20 05:11 UTC, dipsubha06 approved these changes

2020-11-24 01:24 UTC, giorod3 commented on plugins/aws/redshift/userActivityLoggingEnabled.js
> +                    if (!groupName.startsWith('default.redshift')) {
check if groupName exists first

2020-11-24 01:25 UTC, giorod3 requested changes
just the one comment

2020-11-25 22:58 UTC, giorod3 approved these changes

2020-11-25 22:58 UTC, merged