feature/AK-57: Added AWS Redshift Allow Version Upgrade plugin, test cases file
aquasecurity/cloudsploit pull request #381
Opened 2020-10-17 09:42 UTC by AkhtarAmir

2020-11-20 14:20 UTC, dipsubha06 approved these changes

2020-11-24 01:23 UTC, giorod3 commented on plugins/aws/redshift/redshiftAllowVersionUpgrade.js
> +                if (cluster.AllowVersionUpgrade && cluster.AllowVersionUpgrade === true) {
the extra check is unnecessary
```suggestion
                if (cluster.AllowVersionUpgrade) {
```

2020-11-24 01:23 UTC, giorod3 requested changes
just the one change

2020-11-24 20:52 UTC, AkhtarAmir commented on plugins/aws/redshift/redshiftAllowVersionUpgrade.js
> +                if (cluster.AllowVersionUpgrade && cluster.AllowVersionUpgrade === true) {
Removed unnecessary check

2020-11-25 22:57 UTC, merged