Requested Plugins Bundle
aquasecurity/cloudsploit pull request #385
Opened 2020-10-19 16:06 UTC by giorod3

Bundle of plugins requested by enterprise user

2020-10-19 16:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=385) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=385) before we can accept your contribution.<br/><hr/>**Gio Rodriguez** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=385) it.</sub>

2020-10-19 18:00 UTC, matthewdfuller requested changes

2020-10-20 16:10 UTC, giorod3 commented on plugins/aws/ec2/allowedCustomPorts.js
> +    title: 'Open Custom Ports',
Allowed Custom Ports

2020-10-20 16:11 UTC, giorod3 commented on plugins/aws/ec2/allowedCustomPorts.js
> +    title: 'Open Custom Ports',
```suggestion
    title: 'Allowed Custom Ports',
```

2020-10-22 18:29 UTC, matthewdfuller requested changes
@giorod3 -For s3 public access block, still loop through every bucket and create a passing result if global access block is set.

2020-10-22 18:29 UTC, matthewdfuller commented on plugins/aws/ec2/allowedCustomPorts.js
> +            description: 'A comma-delimited list of ports that indicates open ports allowed for any connection',
@giorod3 - Add an example value here in the description

2020-10-22 18:29 UTC, matthewdfuller commented on plugins/aws/ec2/allowedCustomPorts.js
> +            default: 'tcp:80,tcp:443'
@giorod3 - And change this to an empty string default

2020-10-22 18:29 UTC, matthewdfuller commented on plugins/aws/ec2/allowedCustomPorts.js
> +
And around here, exit the plugin if settings value is empty string

2020-10-22 18:29 UTC, matthewdfuller commented on plugins/aws/s3/bucketPublicAccessBlock.js
>          };
Add
```
config. check_global_block = (config. check_global_block == 'true');
```

2020-10-22 18:29 UTC, matthewdfuller commented on plugins/aws/s3/bucketPublicAccessBlock.js
> +            default: true
For consistency change to `'true'`

2020-10-26 20:21 UTC, matthewdfuller requested changes
@giorod3 - need to add the check for 'true' vs 'false' to boolean conversion at the top of `run` rather than doing `=== 'true'` later.

2020-10-29 15:18 UTC, merged