feature/AK-34: Added AWS EC2 Open Custom Ports plugin, text cases
aquasecurity/cloudsploit pull request #389
Opened 2020-10-22 10:17 UTC by AkhtarAmir

2020-10-22 17:52 UTC, giorod3 approved these changes

2020-10-22 18:31 UTC, matthewdfuller requested changes
@giorod3 - see comments

2020-10-22 18:31 UTC, matthewdfuller commented on plugins/aws/ec2/openCustomPorts.js
> +            description: 'Comma separated list of ports that should be restricted to be publicly open',
```suggestion
            description: 'Comma separated list of ports that should be restricted and not publicly open',
```

2020-10-22 18:31 UTC, matthewdfuller commented on plugins/aws/ec2/openCustomPorts.js
> +            default: 'tcp:22,tcp:23'
Let's change to empty string

2020-10-22 18:31 UTC, matthewdfuller commented on plugins/aws/ec2/openCustomPorts.js
> +
Exit if settings.restricted_open_ports is empty

2020-10-26 18:50 UTC, giorod3 approved these changes

2020-10-26 20:28 UTC, matthewdfuller commented on plugins/aws/ec2/openCustomPorts.js
> +            description: 'Comma separated list of ports that should be restricted and not publicly open',
```suggestion
            description: 'Comma separated list of ports that should be restricted and not publicly open. Example: tcp:80,tcp:443',
```

2020-10-26 20:37 UTC, merged