feature/change-request: Modified AWS iamRoleLastUsed to skip user defined role paths
aquasecurity/cloudsploit pull request #391
Opened 2020-10-23 07:20 UTC by AkhtarAmir

2020-10-23 15:53 UTC, giorod3 approved these changes

2020-10-26 20:40 UTC, matthewdfuller requested changes

2020-10-26 20:40 UTC, matthewdfuller commented on plugins/aws/iam/iamRoleLastUsed.js
> +            if (!role.RoleName || (role.Path && role.Path.startsWith('/aws-service-role/'))) return cb();
```suggestion
            if (!role.RoleName || (config. skip_aws_service_roles && (role.Path && role.Path.startsWith('/aws-service-role/')))) return cb();
```

2020-10-26 20:40 UTC, matthewdfuller commented on plugins/aws/iam/iamRoleLastUsed.js
>          };
Also add:
```
config. skip_aws_service_roles = (config. skip_aws_service_roles == 'true');
```

2020-10-29 15:08 UTC, merged