feature/ak-68: Added AWS EC2 VPC Endpoint Exposed plugin, test cases
aquasecurity/cloudsploit pull request #397
Opened 2020-10-26 19:21 UTC by AkhtarAmir

2020-11-23 09:27 UTC, dipsubha06 approved these changes

2020-11-24 00:43 UTC, giorod3 requested changes
a couple of syntax issues, one is in the results so I will leave it for you

2020-11-24 00:43 UTC, giorod3 commented on plugins/aws/ec2/vpcEndpointExposed.js
> +    description: 'Ensure Amazon VPC endpoints are not exposed to everyone.',
```suggestion
    description: 'Ensure Amazon VPC endpoints are not publicly exposed',
```

2020-11-24 00:43 UTC, giorod3 commented on plugins/aws/ec2/vpcEndpointExposed.js
> +                        `VPC endpoint ${endpoint.VpcEndpointId} is exposed to everyone`,
```suggestion
                        `VPC endpoint ${endpoint.VpcEndpointId} is publicly exposed`,
```

2020-11-24 22:06 UTC, AkhtarAmir commented on plugins/aws/ec2/vpcEndpointExposed.js
> +    description: 'Ensure Amazon VPC endpoints are not exposed to everyone.',
Updated

2020-11-25 16:15 UTC, giorod3 approved these changes

2020-11-25 22:51 UTC, merged