feature/ak-46: Added AWS ES Access From IP Addresses plugin, test cases
aquasecurity/cloudsploit pull request #400
Opened 2020-10-27 10:16 UTC by AkhtarAmir

2020-11-23 10:11 UTC, dipsubha06 approved these changes

2020-11-24 00:41 UTC, giorod3 requested changes
just the one comment

2020-11-24 00:41 UTC, giorod3 commented on plugins/aws/es/esAccessFromIps.js
> +                    if (statement.Condition && statement.Condition.IpAddress && statement.Condition.IpAddress['aws:SourceIp']) {
check the length before looping through this
```suggestion
                    if (statement.Condition && statement.Condition.IpAddress && statement.Condition.IpAddress['aws:SourceIp'] && statement.Condition.IpAddress['aws:SourceIp'].length) {
```

2020-11-25 16:14 UTC, giorod3 approved these changes

2020-11-25 22:51 UTC, merged