feature/ak-25: Added AWS EBS Snapshot Lifecycle plugin, test cases
aquasecurity/cloudsploit pull request #401
Opened 2020-10-31 09:12 UTC by AkhtarAmir

2020-11-24 00:39 UTC, giorod3 requested changes
just the one comment

2020-11-24 00:39 UTC, giorod3 commented on plugins/aws/ec2/ebsSnapshotLifecycle.js
> +                    getLifecyclePolicy.data.Policy.PolicyDetails.TargetTags) {
you are looping through this without first checking if it has anything in it
```suggestion
                    getLifecyclePolicy.data.Policy.PolicyDetails.TargetTags && getLifecyclePolicy.data.Policy.PolicyDetails.TargetTags.length) {
```

2020-11-24 19:18 UTC, dipsubha06 commented on plugins/aws/ec2/ebsSnapshotLifecycle.js
> +            describeInstances.data.forEach(instance => {
Dont we need to check describeInstances.data.length as we are doing for describeVolumes.data.length?

2020-11-24 19:21 UTC, dipsubha06 requested changes

2020-11-24 19:21 UTC, dipsubha06 commented on plugins/aws/ec2/ebsSnapshotLifecycle.js
> +            describeInstances.data.forEach(instance => {
Dont we need to check describeInstances.data.length as we are doing for describeVolumes.data.length?

2020-11-25 14:33 UTC, dipsubha06 approved these changes

2020-11-25 16:14 UTC, giorod3 approved these changes

2020-11-30 14:29 UTC, merged