Feature/ak-20: Added AWS CloudTrail Delivery Failed plugin, test cases
aquasecurity/cloudsploit pull request #416
Opened 2020-11-17 07:38 UTC by AkhtarAmir

2020-11-24 00:20 UTC, giorod3 requested changes
same comment as the others

2020-11-24 00:20 UTC, giorod3 commented on plugins/aws/cloudtrail/cloudtrailDeliveryFailing.js
> +                if (!trail.TrailARN || trail.S3BucketName == helpers.CLOUDSPLOIT_EVENTS_BUCKET) return cb();
same here as the other PR's

```suggestion
                if (!trail.TrailARN || (trail.S3BucketName && trail.S3BucketName == helpers.CLOUDSPLOIT_EVENTS_BUCKET)) return cb();
```

2020-11-25 04:54 UTC, dipsubha06 approved these changes

2020-11-25 04:56 UTC, dipsubha06 approved these changes

2020-11-25 16:11 UTC, giorod3 approved these changes

2020-11-25 22:41 UTC, merged