Feature/ak-21: Added AWS CloudTrail Global Logging Duplicated plugin, test cases
aquasecurity/cloudsploit pull request #417
Opened 2020-11-17 11:47 UTC by AkhtarAmir

2020-11-24 00:19 UTC, giorod3 requested changes
one comment and its ready to go

2020-11-24 00:19 UTC, giorod3 commented on plugins/aws/cloudtrail/globalLoggingDuplicated.js
> +                if (!trail.TrailARN || trail.S3BucketName == helpers.CLOUDSPLOIT_EVENTS_BUCKET) return;
check if S3BucketName exists first
```suggestion
                if (!trail.TrailARN || (trail.S3BucketName && trail.S3BucketName == helpers.CLOUDSPLOIT_EVENTS_BUCKET)) return;
```

2020-11-25 04:58 UTC, dipsubha06 approved these changes

2020-11-25 16:11 UTC, giorod3 approved these changes

2020-11-30 14:26 UTC, merged