feature/ak-22: Added AWS CloudTrail S3 Bucket plugin, test cases
aquasecurity/cloudsploit pull request #418
Opened 2020-11-17 13:16 UTC by AkhtarAmir

2020-11-24 00:17 UTC, giorod3 requested changes
a couple of comments here

2020-11-24 00:17 UTC, giorod3 commented on plugins/aws/cloudtrail/cloudtrailS3Bucket.js
> +            description: 'Amazon S3 bucket name designated for CloudTrail trains',
```suggestion
            description: 'Amazon S3 bucket name designated for CloudTrail trails',
```

2020-11-24 00:17 UTC, giorod3 commented on plugins/aws/cloudtrail/cloudtrailS3Bucket.js
> +                if (!trail.TrailARN || trail.S3BucketName == helpers.CLOUDSPLOIT_EVENTS_BUCKET) return cb();
check if S3BucketName exists first
```suggestion
                if (!trail.TrailARN || (trail.S3BucketName && trail.S3BucketName == helpers.CLOUDSPLOIT_EVENTS_BUCKET)) return cb();
```

2020-11-24 22:37 UTC, AkhtarAmir commented on plugins/aws/cloudtrail/cloudtrailS3Bucket.js
> +            description: 'Amazon S3 bucket name designated for CloudTrail trains',
sorry about that :D

2020-11-25 05:01 UTC, dipsubha06 approved these changes

2020-11-25 16:10 UTC, giorod3 approved these changes

2020-11-25 22:36 UTC, merged