feature-request: Added AWS Route53 Dangling DNS Records plugin, test cases
aquasecurity/cloudsploit pull request #422
Opened 2020-11-19 11:39 UTC by AkhtarAmir

2020-11-20 23:44 UTC, giorod3 commented on plugins/aws/route53/danglingDnsRecords.js
> +                if (recordSet.Type === 'A' && recordSet.ResourceRecords && recordSet.ResourceRecords.length) {
```suggestion
                if (recordSet.Type && recordSet.Type === 'A' && recordSet.ResourceRecords && recordSet.ResourceRecords.length) {
```

2020-11-20 23:45 UTC, giorod3 requested changes
just one comment and its ready to go

2020-11-24 00:15 UTC, giorod3 approved these changes

2020-11-25 05:14 UTC, dipsubha06 approved these changes

2020-11-25 22:34 UTC, merged