feature/AK-70: Added 'VPC Peering Connections to Accounts Outside AWS…
aquasecurity/cloudsploit pull request #445
Opened 2020-12-07 17:25 UTC by AkhtarAmir

… Organization

2020-12-17 17:20 UTC, dipsubha06 approved these changes

2021-01-20 00:06 UTC, giorod3 commented on plugins/aws/ec2/vpcPeeringConnections.js
> +    title: 'VPC Peering Connections To Accounts Outside AWS Organization',
this title is too long

2021-01-20 03:01 UTC, giorod3 requested changes
other than the title change this looks good

2021-01-20 11:13 UTC, AkhtarAmir commented on plugins/aws/ec2/vpcPeeringConnections.js
> +    title: 'VPC Peering Connections To Accounts Outside AWS Organization',
Changed

2021-01-21 16:42 UTC, giorod3 approved these changes

2021-01-21 16:42 UTC, merged