feature-request/ebs-default-encryption: Added 'EBS Default Encryption Enabled' plugin and test cases
aquasecurity/cloudsploit pull request #448
Opened 2020-12-08 12:16 UTC by AkhtarAmir

2020-12-17 17:49 UTC, dipsubha06 approved these changes

2021-01-20 03:07 UTC, giorod3 requested changes
lets talk about this in the morning

2021-01-20 03:07 UTC, giorod3 commented on helpers/aws/enum.js
> +};
this logic can be added top the plugin since it is only being used once.

2021-01-20 03:07 UTC, giorod3 commented on helpers/aws/functions.js
> +
same here

2021-01-20 03:07 UTC, giorod3 commented on plugins/aws/ec2/ebsDefaultEncryptionEnabled.js
> +    description: 'Ensure the setting for Encryption by default is enabled',
```suggestion
    description: 'Ensure the setting for encryption by default is enabled',
```

2021-01-20 03:09 UTC, giorod3 commented on helpers/aws/enum.js
> +};
I see where you added this for other plugins. lets discuss

2021-01-21 16:51 UTC, giorod3 requested changes
change the map to array and add to index helper. example: encryptionLevel: []

2021-01-25 16:46 UTC, giorod3 approved these changes

2021-01-25 16:48 UTC, merged