Added 'Workspaces IP Access Control' plugin and test cases
aquasecurity/cloudsploit pull request #451
Opened 2020-12-10 11:52 UTC by AkhtarAmir

2020-12-11 10:27 UTC, dipsubha06 approved these changes

2021-01-20 03:53 UTC, giorod3 commented on plugins/aws/workspaces/workspacesIpAccessControl.js
> +    more_info: 'Checking the existence of IP Access control on Workspaces and no open IP to any Workspaces',
```suggestion
    more_info: 'Checking the existence of IP Access control on Workspaces and ensuring that no Workspaces are open',
```

2021-01-20 03:54 UTC, giorod3 commented on plugins/aws/workspaces/workspacesIpAccessControl.js
> +                if (workspaceDirectory.ipGroupIds) {
```suggestion
                if (workspaceDirectory  && workspaceDirectory.ipGroupIds) {
```

2021-01-20 03:54 UTC, giorod3 commented on plugins/aws/workspaces/workspacesIpAccessControl.js
> +                        if (ipGroup.userRules) {
```suggestion
                        if (ipGroup && ipGroup.userRules) {
```

2021-01-20 03:55 UTC, giorod3 requested changes
a few comments here

2021-01-21 16:58 UTC, giorod3 approved these changes

2021-01-21 16:58 UTC, merged