feature/AKD-20: Added 'API Gateway Certificate Rotation' plugin and test cases
aquasecurity/cloudsploit pull request #461
Opened 2020-12-17 20:48 UTC by AkhtarAmir

2020-12-29 06:09 UTC, dipsubha06 approved these changes

2021-01-20 14:08 UTC, giorod3 approved these changes

2021-01-21 17:02 UTC, giorod3 commented on plugins/aws/apigateway/apigatewayCertificateRotation.js
> +            default: 30,
```suggestion
            default: '30',
```

2021-01-21 17:07 UTC, giorod3 requested changes
add logic to convert setting from string to int

2021-01-22 17:25 UTC, giorod3 approved these changes

2021-01-22 17:25 UTC, merged