feature/ak-52: Added 'Lambda Admin Priveleges' plugin and test cases
aquasecurity/cloudsploit pull request #477
Opened 2020-12-26 14:27 UTC by AkhtarAmir

2020-12-28 13:31 UTC, dipsubha06 approved these changes

2021-01-20 15:21 UTC, giorod3 requested changes

2021-01-20 15:21 UTC, giorod3 commented on exports.js
> +        'lambdaAdminPriveleges'         : require(__dirname + '/plugins/aws/lambda/lambdaAdminPriveleges.js'),
privilege is spelled wrong here.

2021-01-20 15:21 UTC, giorod3 commented on plugins/aws/lambda/lambdaAdminPriveleges.js
> +                var adminPriveleged;
misspelling here as well

2021-01-20 15:21 UTC, giorod3 commented on plugins/aws/lambda/lambdaAdminPriveleges.js
> +                        'Function does not have admin priveleges', region, resource);
```suggestion
                        'Function does not have admin privileges', region, resource);
```

2021-01-20 15:21 UTC, giorod3 commented on plugins/aws/lambda/lambdaAdminPriveleges.js
> +                        'Function has admin priveleges', region, resource);
```suggestion
                        'Function has admin privileges', region, resource);
```

2021-01-21 17:14 UTC, giorod3 approved these changes

2021-01-21 17:18 UTC, merged