Feature/AKD-11: Added 'CloudFormation stack SNS notifications' plugin and test cases
aquasecurity/cloudsploit pull request #480
Opened 2021-01-03 00:01 UTC by AkhtarAmir

2021-01-11 05:09 UTC, dipsubha06 approved these changes

2021-01-20 18:40 UTC, giorod3 commented on plugins/aws/cloudformation/stackNotifications.js
> +    more_info: 'AWS CloudFormation stack should have SNS topic associated to ensure stack events monitoring.',
```suggestion
    more_info: 'AWS CloudFormation stacks should have SNS topic associated to ensure stack events monitoring.',
```

2021-01-20 18:40 UTC, giorod3 commented on plugins/aws/cloudformation/stackNotifications.js
> +    recommended_action: 'Associate an Amazon SNS topic to CloudFormation stack',
```suggestion
    recommended_action: 'Associate an Amazon SNS topic to a CloudFormation stack',
```

2021-01-20 18:41 UTC, giorod3 commented on plugins/aws/cloudformation/stackNotifications.js
> +                    helpers.addResult(results, 3, `Unable to query for CloudFormation stack detils: ${helpers.addError(describeStacks)}`,
```suggestion
                    helpers.addResult(results, 3, `Unable to query for CloudFormation stack details: ${helpers.addError(describeStacks)}`,
```

2021-01-20 18:43 UTC, giorod3 commented on plugins/aws/cloudformation/stackNotifications.js
> +            return rcb();
return the callback in the callback of the async function. the way you have it will return while the function still runs

2021-01-20 18:43 UTC, giorod3 requested changes
just one fix here

2021-01-21 17:17 UTC, giorod3 commented on plugins/aws/cloudformation/stackNotifications.js
> +            });
```suggestion
            }, function(err) {
                return rcb();
            });
```

2021-01-21 17:18 UTC, giorod3 commented on plugins/aws/cloudformation/stackNotifications.js
> +            return rcb();
```suggestion
            
```

2021-01-21 17:18 UTC, giorod3 requested changes
just the change to move return to async callback

2021-01-22 17:17 UTC, giorod3 approved these changes

2021-01-29 19:06 UTC, giorod3 approved these changes

2021-01-29 19:06 UTC, merged