Feature/AKD-12: Added 'CloudFormation Drift Detection' plugin and test cases
aquasecurity/cloudsploit pull request #481
Opened 2021-01-03 00:04 UTC by AkhtarAmir

2021-01-11 05:08 UTC, dipsubha06 approved these changes

2021-01-20 18:44 UTC, giorod3 commented on plugins/aws/cloudformation/driftDetection.js
> +    description: 'Ensures that AWS CloudFormation stacks have not been drifted.',
```suggestion
    description: 'Ensures that AWS CloudFormation stacks are not in a drifted state.',
```

2021-01-20 18:45 UTC, giorod3 approved these changes

2021-01-20 18:54 UTC, giorod3 requested changes

2021-01-20 18:54 UTC, giorod3 commented on collectors/aws/collector.js
> -        }
why did you remove this?

2021-01-29 19:09 UTC, giorod3 approved these changes

2021-01-29 19:10 UTC, merged