feature/AKD-33: Added 'VPN Tunnel state' plugin and test cases
aquasecurity/cloudsploit pull request #505
Opened 2021-01-19 08:10 UTC by AkhtarAmir

2021-01-20 19:41 UTC, giorod3 commented on plugins/aws/ec2/vpnTunnelState.js
> +    recommended_action: 'Establish a successfull VPN connection using IKE or IPsec configuration',
```suggestion
    recommended_action: 'Establish a successful VPN connection using IKE or IPsec configuration',
```

2021-01-20 19:46 UTC, giorod3 requested changes
this should be an opt-in type of plugin for customers using Site-to-Site VPN connections.

2021-01-21 16:04 UTC, AkhtarAmir commented
I've added the setting to make this opt-in

2021-01-21 17:46 UTC, giorod3 approved these changes

2021-01-21 18:02 UTC, giorod3 commented on helpers/aws/regions_china.js
> +    glue, regions,
```suggestion
    glue: regions,
```

2021-01-21 18:05 UTC, merged