feature/AKD-107: Added Azure 'Point in Time Restore (PITR) Backup Retention Period' plugin and test cases
aquasecurity/cloudsploit pull request #616
Opened 2021-03-28 01:03 UTC by ali-imran7

2021-03-28 09:47 UTC, AkhtarAmir requested changes

2021-03-28 09:47 UTC, AkhtarAmir commented on plugins/azure/sqldatabases/pitrBackupEnabled.js
> +        }
```suggestion
        pitr_backup_retention_period: {
            name: 'Point in Time Restore Backup Retention Period',
            description: 'Desired number of days for which backups will be retained.',
            regex: '^(3[0-5]|2[0-9]|1[0-9]|[1-9])$',
            default: '7'
        }
```

2021-03-28 09:47 UTC, AkhtarAmir commented on plugins/azure/sqldatabases/pitrBackupEnabled.js
> +            retentionDays: parseInt(settings.ShortTemRetentionDays || this.settings.ShortTemRetentionDays.default)
```suggestion
            retentionDays: parseInt(settings.pitr_backup_retention_period || this.settings.pitr_backup_retention_period.default)
```

2021-03-28 09:47 UTC, AkhtarAmir commented on plugins/azure/sqldatabases/pitrBackupEnabled.js
> +            for (const server of servers.data) {
Loop servers in async.each

2021-03-28 09:47 UTC, AkhtarAmir commented on plugins/azure/sqldatabases/pitrBackupEnabled.js
> +    title: 'Point in Time Restore (PITR) Backup Retention Period',
```suggestion
    title: 'Point in Time Restore (PITR) Backup Retention Period Configured',
```

2021-03-28 09:47 UTC, AkhtarAmir commented on plugins/azure/sqldatabases/pitrBackupEnabled.js
> +    more_info: 'Point-in-time restore is a self-service capability, allowing customers to restore a Basic, Standard or Premium database from these backups to any point within the retention period.',
```suggestion
    more_info: 'Point-in-time restore is a self-service capability, which enabled you to restore a database from backups to any point within the retention period. Point-in-time restore is useful in recovery scenarios, such as incidents caused by errors, incorrectly loaded data, or deletion of crucial data.',
```

2021-04-22 17:47 UTC, AkhtarAmir requested changes

2021-04-22 17:50 UTC, giorod3 approved these changes

2021-04-22 17:50 UTC, giorod3 commented on plugins/azure/sqldatabases/pitrBackupEnabled.js
> +    title: 'Point in Time Restore (PITR) Backup Retention Period Configured',
```suggestion
    title: 'Point in Time Restore Backup Retention',
```

2021-04-23 18:15 UTC, giorod3 approved these changes

2021-04-23 18:15 UTC, merged