feature/AKD-108: Added Azure 'SQL Server Private Endpoints Configured' plugin and test cases
aquasecurity/cloudsploit pull request #617
Opened 2021-03-28 03:40 UTC by ali-imran7

2021-03-28 15:41 UTC, AkhtarAmir requested changes

2021-03-28 15:41 UTC, AkhtarAmir commented on exports.js
> +        'privateEndpointsConfigured'    : require(__dirname + '/plugins/azure/sqlserver/privateEndpointsConfigured.js'),
```suggestion
        'serverPrivateEndpoints'        : require(__dirname + '/plugins/azure/sqlserver/serverPrivateEndpoints.js'), 
```

2021-03-28 15:41 UTC, AkhtarAmir commented on exports.js
> +        'privateEndpointsConfigured'    : require(__dirname + '/plugins/azure/sqlserver/privateEndpointsConfigured.js'),
I like this name better because this is consistent with naming convention. You need to change the name of files as well

2021-03-28 15:41 UTC, AkhtarAmir commented on plugins/azure/sqlserver/privateEndpointsConfigured.js
> +    more_info: 'Azure Private Link enables you to access Azure PaaS Services and Azure hosted customer-owned/partner services over a private endpoint in your virtual network',
```suggestion
    more_info: 'Azure Private Endpoint is a network interface that connects you privately and securely to a service powered by Azure Private Link. Private Endpoint uses a private IP address from your VNet, effectively bringing the service such as Azure SQL Server into your VNet.',
```

2021-03-28 15:41 UTC, AkhtarAmir commented on plugins/azure/sqlserver/privateEndpointsConfigured.js
> +                }
You should always generate 1 result per 1 resource. Also, for the sake of this plugin, I think we should only check for private endpoint, not the public network access. So you can do this:
```suggestion
                if (server.privateEndpointConnections && server.privateEndpointConnections.length > 0) {
                    helpers.addResult(results, 0, 'Private Endpoints are configured for the SQL Server', location, server.id);
                } else {
                    helpers.addResult(results, 2, 'Private Endpoints are not configured for the SQL Server', location, server.id);
                }
```

2021-03-28 15:41 UTC, AkhtarAmir commented on plugins/azure/sqlserver/privateEndpointsConfigured.spec.js
> +                expect(results[1].message).to.include('Public Network Access is disabled for the SQL Server');
You will need to update tests to reflect asked changes

2021-04-22 17:54 UTC, giorod3 commented on plugins/azure/sqlserver/serverPrivateEndpoints.js
> +                if (server.privateEndpointConnections && server.privateEndpointConnections.length > 0) {
```suggestion
                if (server.privateEndpointConnections && server.privateEndpointConnections.length) {
```

2021-04-22 17:56 UTC, giorod3 approved these changes

2021-04-22 17:57 UTC, AkhtarAmir approved these changes

2021-04-22 17:57 UTC, merged