feature/AKD-117: Added Azure 'NSG Flow Logs Retention Period' plugin and test cases
aquasecurity/cloudsploit pull request #618
Opened 2021-03-28 19:38 UTC by ali-imran7

2021-03-29 14:13 UTC, AkhtarAmir requested changes

2021-03-29 14:13 UTC, AkhtarAmir commented on plugins/azure/networkwatchers/nsgFlowLogsRetentionPeriod.js
> +                            `NSG FLow Logs Data retention policy is set to ${retentionDays} of ${config.retentionDays} days desired limit`,
```suggestion
                            `NSG fLow log has retention period set to ${retentionDays} of ${config.retentionDays} days desired limit`,
```

2021-03-29 14:13 UTC, AkhtarAmir commented on plugins/azure/networkwatchers/nsgFlowLogsRetentionPeriod.js
> +                            `NSG FLow Logs Data retention policy is set to ${retentionDays} of ${config.retentionDays} days desired limit`,
```suggestion
                            `NSG flow log has retention period set to ${retentionDays} of ${config.retentionDays} days desired limit`,
```

2021-03-29 14:13 UTC, AkhtarAmir commented on plugins/azure/networkwatchers/nsgFlowLogsRetentionPeriod.js
> +    recommended_action: 'Ensure that Network Security Groups (NSG) flow logs retention period is 90 days or more',
```suggestion
    recommended_action: 'Modify NSG flow logs and set desired value in days for retention period',
```

2021-03-29 14:13 UTC, AkhtarAmir commented on plugins/azure/networkwatchers/nsgFlowLogsRetentionPeriod.js
> +    recommended_action: 'Ensure that Network Security Groups (NSG) flow logs retention period is 90 days or more',
I find it better to give them bit more clarity about recommended action

2021-03-29 14:13 UTC, AkhtarAmir commented on plugins/azure/networkwatchers/nsgFlowLogsRetentionPeriod.js
> +                    }
```suggestion
                    if (flowLog.retentionPolicy && flowLog.retentionPolicy.days) retentionDays = flowLog.retentionPolicy.days;
```

2021-03-29 14:13 UTC, AkhtarAmir commented on plugins/azure/networkwatchers/nsgFlowLogsRetentionPeriod.js
> +                    let retentionDays = 0;
Just to make sure that code doesn't break
```suggestion
                for (const flowLog of flowLogs.data) {
                    if (!flowLog.id) continue;
                    let retentionDays = 0;
```

2021-03-29 14:58 UTC, AkhtarAmir requested changes

2021-03-29 14:58 UTC, AkhtarAmir commented on collectors/azure/collector.js
> +        listAll: {
```suggestion
        list: {
```

2021-04-22 17:58 UTC, AkhtarAmir approved these changes

2021-04-22 17:59 UTC, giorod3 approved these changes

2021-04-22 18:00 UTC, merged