feature/AKD-110: Added Azure 'Auto-Failover Groups Enabled' plugin and test cases
aquasecurity/cloudsploit pull request #636
Opened 2021-04-04 21:44 UTC by ali-imran7

2021-04-05 09:57 UTC, dipsubha06 approved these changes

2021-04-05 10:46 UTC, AkhtarAmir requested changes

2021-04-05 10:46 UTC, AkhtarAmir commented on collectors/azure/collector.js
> +    failOverGroups: {
```suggestion
    failoverGroups: {
```

2021-04-05 10:46 UTC, AkhtarAmir commented on plugins/azure/sqlserver/autoFailoverGroupsEnabled.js
> +    recommended_action: 'Ensure that Auto-Failover Groups are configured for Azure SQL database server',
```suggestion
    recommended_action: 'Ensure that auto-failover groups are configured for Azure SQL database server',
```

2021-04-05 10:46 UTC, AkhtarAmir commented on plugins/azure/sqlserver/autoFailoverGroupsEnabled.js
> +                        'Unable to query for auto-failover groups: ' + helpers.addError(failoverGroups), location);
```suggestion
                        'Unable to query for auto-failover groups: ' + helpers.addError(failoverGroups), location, server.id);
```

2021-04-05 10:46 UTC, AkhtarAmir commented on plugins/azure/sqlserver/autoFailoverGroupsEnabled.js
> +                if (failoverGroups.data.length && failoverGroups.data.length > 0) {
```suggestion
                if (failoverGroups.data.length) {
```

2021-04-22 18:09 UTC, giorod3 approved these changes

2021-06-01 17:06 UTC, giorod3 commented on plugins/azure/sqlserver/autoFailoverGroupsEnabled.js
> +                    return rcb();
```suggestion
                   continue;
```

2021-06-01 17:08 UTC, giorod3 approved these changes

2021-06-01 17:08 UTC, merged