Spec files added
aquasecurity/cloudsploit pull request #646
Opened 2021-04-09 17:24 UTC by umermehmood

2021-04-09 17:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=646) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=646) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=646) it.</sub>

2021-04-12 08:56 UTC, AkhtarAmir requested changes

2021-04-12 08:56 UTC, AkhtarAmir commented on plugins/google/storage/bucketLogging.spec.js
> +var assert = require('assert');
```suggestion
```

2021-04-12 08:56 UTC, AkhtarAmir commented on plugins/google/storage/bucketLogging.spec.js
> +        it('should give empty result if no storage buckets found', function (done) {
```suggestion
        it('should give passing result if no storage buckets found', function (done) {
```

2021-04-12 08:56 UTC, AkhtarAmir commented on plugins/google/storage/bucketVersioning.spec.js
> +var assert = require('assert');
```suggestion
```

2021-04-12 08:56 UTC, AkhtarAmir commented on plugins/google/storage/bucketVersioning.spec.js
> +        it('should give empty result if no storage buckets found', function (done) {
```suggestion
        it('should give passing result if no storage buckets found', function (done) {
```

2021-04-22 18:38 UTC, giorod3 approved these changes

2021-04-22 18:38 UTC, AkhtarAmir approved these changes

2021-04-22 18:38 UTC, merged