Spec files added for VPC plugins
aquasecurity/cloudsploit pull request #652
Opened 2021-04-13 09:08 UTC by umermehmood

2021-04-15 10:44 UTC, AkhtarAmir requested changes

2021-04-15 10:44 UTC, AkhtarAmir commented on plugins/google/vpcnetwork/excessiveFirewallRules.spec.js
> +                      {
indentation seems off

2021-04-15 10:44 UTC, AkhtarAmir commented on plugins/google/vpcnetwork/excessiveFirewallRules.spec.js
> +                      },
Here too

2021-04-15 10:44 UTC, AkhtarAmir commented on plugins/google/vpcnetwork/multipleSubnets.js
> +                if (subnets.length) {
```suggestion
                if (subnets && subnets.length) {
```

2021-04-22 18:51 UTC, giorod3 approved these changes

2021-04-22 18:51 UTC, merged