feature/AKD-135: Added Azure 'Automatic Instance Repair Enabled' plugin and test cases
aquasecurity/cloudsploit pull request #658
Opened 2021-04-18 01:15 UTC by ali-imran7

2021-04-20 05:46 UTC, dipsubha06 approved these changes

2021-04-21 10:49 UTC, AkhtarAmir requested changes

2021-04-21 10:49 UTC, AkhtarAmir commented on exports.js
> +        'autoInstanceRepair'            : require(__dirname + '/plugins/azure/virtualmachines/autoInstanceRepair.js'),
```suggestion
        'autoInstanceRepairsEnabled'    : require(__dirname + '/plugins/azure/virtualmachines/autoInstanceRepairsEnabled.js'),
```

2021-04-21 10:49 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/autoInstanceRepair.js
> +    description: 'Ensures that automatic instance repair is enabled for Azure Virtual ',
```suggestion
    description: 'Ensure that automatic instance repairs is enabled for Azure virtual machine scale sets.',
```

2021-04-21 10:49 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/autoInstanceRepair.js
> +    recommended_action: 'Enable automatic instance repair for Azure virtual machine scale set',
```suggestion
    recommended_action: 'Enable automatic instance repairs for Azure virtual machine scale set',
```

2021-04-21 10:49 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/autoInstanceRepair.js
> +                    helpers.addResult(results, 0, 'Automatic instance repair is enabled for virtual machine scale set', location, scaleSet.id);
```suggestion
                    helpers.addResult(results, 0, 'Automatic instance repairs is enabled for virtual machine scale set', location, scaleSet.id);
```

2021-04-21 10:49 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/autoInstanceRepair.js
> +                    helpers.addResult(results, 2, 'Automatic instance repair is not enabled for virtual machine scale set', location, scaleSet.id);
```suggestion
                    helpers.addResult(results, 2, 'Automatic instance repairs is not enabled for virtual machine scale set', location, scaleSet.id);
```

2021-04-23 18:37 UTC, giorod3 approved these changes

2021-04-23 18:39 UTC, merged