feature/AKD-138: Added Azure 'VM Backups Enabled' plugin and test cases
aquasecurity/cloudsploit pull request #661
Opened 2021-04-18 21:34 UTC by ali-imran7

This PR is similar to #659 so pulled those changes here also to get collector calls and helper changes.

2021-04-21 13:33 UTC, AkhtarAmir requested changes

2021-04-21 13:33 UTC, AkhtarAmir commented on collectors/azure/collector.js
>          }
```suggestion
        },
        listBySubscriptionId: {
            url: 'https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.RecoveryServices/vaults?api-version=2016-06-01'
        }
```

2021-04-21 13:33 UTC, AkhtarAmir commented on collectors/azure/collector.js
> +    },
```suggestion
```

2021-04-21 13:33 UTC, AkhtarAmir commented on helpers/azure/locations.js
> +    recoveryVaults: locations,
```suggestion
```

2021-04-21 13:33 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/dailyBackupRetention.js
> +    description: 'Ensures that VM daily backup retention policy is configured to retain backups for desired number of days',
```suggestion
    description: 'Ensure that VM daily backup retention policy is configured to retain backups for the desired number of days.',
```

2021-04-21 13:33 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/dailyBackupRetention.js
> +        daily_backup_retention_period: {
```suggestion
        vm_daily_backup_retention_period: {
```

2021-04-21 13:33 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/dailyBackupRetention.js
> +            regex: '^([7-9]|1[0-9]|2[0-9]|30)$'
```suggestion
            description: 'Number of days that a VM backup will be retained until it is permanently deleted',
            regex: '^([7-9]|1[0-9]|2[0-9]|30)$',
            default: '30'
```

2021-04-21 13:33 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/dailyBackupRetention.js
> +                helpers.addResult(results, 2, 'No backup recovery vaults found for the virtual machine', location);
```suggestion
                helpers.addResult(results, 2, 'No backup recovery vaults found', location);
```

2021-04-21 13:33 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/dailyBackupRetention.js
> +                if (!backupProtectedItems || backupProtectedItems.err || !backupProtectedItems.data ||
Split these checks

2021-04-21 13:33 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/dailyBackupRetention.js
> +                    for (const vmPolicy of vmPoliciesMap.get(virtualMachine.id.toLowerCase())) {
Get Policy Map first

2021-04-21 13:33 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/vmBackupsEnabled.js
> +                helpers.addResult(results, 2, 'No backup vaults found for the virtual machine', location);
```suggestion
                helpers.addResult(results, 2, 'No backup vaults found', location);
```

2021-04-21 13:33 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/vmBackupsEnabled.js
> +                    helpers.addResult(results, 0, 'Azure virtual machine backups are enabled', location, virtualMachine.id);
```suggestion
                    helpers.addResult(results, 0, 'Azure virtual machine has backups enabled', location, virtualMachine.id);
```

2021-04-21 13:33 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/vmBackupsEnabled.js
> +                    helpers.addResult(results, 2, 'Azure virtual machine backups are not enabled', location, virtualMachine.id);
```suggestion
                    helpers.addResult(results, 2, 'Azure virtual machine does not have backups enabled', location, virtualMachine.id);
```

2021-04-23 19:06 UTC, ali-imran7 commented
Need to update collector API calls to make those specific to vaults.

2021-05-02 09:37 UTC, closed without merging