Added GCP SQL plugins for database flags.
aquasecurity/cloudsploit pull request #664
Opened 2021-04-22 17:44 UTC by umermehmood

2021-04-22 18:01 UTC, dipsubha06 requested changes

2021-04-22 18:01 UTC, dipsubha06 commented on plugins/google/sql/postgresqlLogMinDuration.js
> +                } else if (sqlInstance.instanceType == "READ_REPLICA_INSTANCE") {
Is this else if needed. if so can we have some handling in that case

2021-04-22 18:01 UTC, dipsubha06 commented on plugins/google/sql/postgresqlLogMinDuration.js
> +                            helpers.addResult(results, 0,
from the description of the plugin it is said that the flag should not be enabled. then this should be a failing case if the flag is enabled,right?

2021-04-23 11:02 UTC, AkhtarAmir requested changes

2021-04-23 11:02 UTC, AkhtarAmir commented on plugins/google/sql/postgresqlLogTempFiles.js
> +    title: 'PostgreSQL Log Temp Files Flag Enabled',
```suggestion
    title: 'PostgreSQL Log Temp Files',
```

2021-04-23 18:58 UTC, giorod3 commented on plugins/google/sql/postgresqlLogMinDuration.js
> +    more_info: 'SQL instance for PostgreSQL databases provides log_min_duration_statement flag. It is used to log the duration of every completed statement. We should always disable it as there can b
```suggestion
    more_info: 'SQL instance for PostgreSQL databases provides log_min_duration_statement flag. It is used to log the duration of every completed statement. This should always be disabled as there can be sensitive information as well that should not be recorded in the logs.',
```

2021-04-23 19:00 UTC, giorod3 commented on plugins/google/sql/postgresqlLogMinDuration.js
> +                    helpers.addResult(results, 2,
this should be a pass if there are no database flags

2021-04-23 19:00 UTC, giorod3 requested changes
two comments

2021-05-28 17:58 UTC, giorod3 approved these changes

2021-05-28 17:59 UTC, merged