feature/AKD-190: Added Google BigQuery Dataset All Users Policy plugin and test cases
aquasecurity/cloudsploit pull request #676
Opened 2021-04-29 14:11 UTC by AkhtarAmir

2021-05-28 17:47 UTC, giorod3 commented on helpers/google/index.js
> -        parentParams = {auth: callObj.auth, resource_: LocalGoogleConfig.project};
check this

2021-05-28 17:48 UTC, giorod3 requested changes
everything looks good except the one comment

2021-06-17 11:51 UTC, AkhtarAmir commented on helpers/google/index.js
> -        parentParams = {auth: callObj.auth, resource_: LocalGoogleConfig.project};
fixed

2021-06-30 18:40 UTC, giorod3 commented on plugins/google/bigquery/datasetAllUsersPolicy.js
> +                            if (!rolePermission['role']) continue;
```suggestion
                    for (let rolePermission of dataset.access) {
                        if (!rolePermission['role']) continue;
                        for (let property in rolePermission) {
```

2021-06-30 18:43 UTC, merged