feature/AKD-126: Added Azure 'VM Desired SKU Size' plugin and test cases
aquasecurity/cloudsploit pull request #677
Opened 2021-05-01 21:29 UTC by ali-imran7

2021-05-31 16:57 UTC, AkhtarAmir requested changes

2021-05-31 16:57 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/desiredSkuSize.js
> +    description: 'Ensures that virtual machines is using the desired SKU size.',
```suggestion
    description: 'Ensures that virtual machines are using the desired SKU size.',
```

2021-05-31 16:57 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/desiredSkuSize.js
> +
`if (!config.desiredSkuSize.elngth) return callback(null, results, source);`

2021-05-31 16:57 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/desiredSkuSize.js
> +
This should be an opt-in plugin

2021-05-31 16:57 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/desiredSkuSize.js
> +                }
```suggestion
                } else return scb();
```

2021-05-31 16:57 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/desiredSkuSize.js
> +                let vmSkuSize = '';
```suggestion
                let vmSkuSize;
```

2021-05-31 16:57 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/desiredSkuSize.js
> +            default: 'standard_ds3_v2'
```suggestion
            default: ''
```

2021-05-31 16:57 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/desiredSkuSize.js
> +
Also make this setting a comma-separated list so that they can choose from a list

2021-06-03 17:19 UTC, giorod3 requested changes

2021-06-03 17:19 UTC, giorod3 commented on plugins/azure/virtualmachines/desiredSkuSize.js
> +
opt-in, should callback if not set

2021-06-03 17:19 UTC, giorod3 commented
merge master as well

2021-06-03 17:23 UTC, merged