feature/AKD-138,129,130: Added Azure 'VM Backups Enabled', 'VM DailyBackup Retention Period', 'VM Instant Restore Backup Retention Period' plugin and test cases
aquasecurity/cloudsploit pull request #678
Opened 2021-05-02 09:35 UTC by ali-imran7

2021-05-02 09:39 UTC, ali-imran7 commented
@AkhtarAmir @giorod3 This PR is extension of #661 so pulled those changes here also to get collector calls and helper changes.

2021-05-31 16:43 UTC, AkhtarAmir requested changes

2021-05-31 16:43 UTC, AkhtarAmir commented on exports.js
> +        'dailyBackupRetention'          : require(__dirname + '/plugins/azure/virtualmachines/dailyBackupRetention.js'),
```suggestion
        'vmDailyBackupRetention'          : require(__dirname + '/plugins/azure/virtualmachines/vmDailyBackupRetention.js'),
```

2021-05-31 16:43 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/dailyBackupRetention.js
> +            description: 'Number of days that a VM backup will be retained until it is permanently deleted',
```suggestion
            description: 'Number of days that a VM backup will be retained until it is permanently deleted (7 or above)',
```

2021-05-31 16:43 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/dailyBackupRetention.js
> +                    helpers.addResult(results, 3, 'Unable to query for backup retention policies : ' + helpers.addError(recoveryVaults), location);
```suggestion
                    helpers.addResult(results, 3, 'Unable to query for backup retention policies : ' + helpers.addError(backupProtectedItems), location);
```

2021-05-31 16:43 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/dailyBackupRetention.js
> +                    helpers.addResult(results, 3, 'Unable to query for backup retention policies : ' + helpers.addError(recoveryVaults), location);
```suggestion
                    helpers.addResult(results, 3, 'Unable to query for backup retention policies : ' + helpers.addError(backupPolicies), location);
```

2021-05-31 16:43 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/dailyBackupRetention.js
> +                        vmPoliciesMap.get(bpItem.virtualMachineId.toLowerCase()).push(bpItem.policyId);
Can we do this?
```suggestion
                        vmPoliciesMap.set(bpItem.virtualMachineId.toLowerCase(), [bpItem.policyId]);
```

2021-05-31 16:43 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/dailyBackupRetention.js
> +                            backupPolicy.retentionPolicy.dailySchedule.retentionDuration && backupPolicy.retentionPolicy.dailySchedule.retentionDuration.count > retentionDays) {
```suggestion
                            backupPolicy.retentionPolicy.dailySchedule.retentionDuration && backupPolicy.retentionPolicy.dailySchedule.retentionDuration.count && backupPolicy.retentionPolicy.dailySchedule.retentionDuration.count > retentionDays) {
```

2021-05-31 16:43 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/instantRestoreRetention.js
> +                    helpers.addResult(results, 3, 'Unable to query for backup retention policies : ' + helpers.addError(recoveryVaults), location);
🥇 
```suggestion
                    helpers.addResult(results, 3, 'Unable to query for backup retention policies : ' + helpers.addError(backupProtectedItems), location);
```

2021-05-31 16:43 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/instantRestoreRetention.js
> +                    helpers.addResult(results, 3, 'Unable to query for backup retention policies : ' + helpers.addError(recoveryVaults), location);
```suggestion
                    helpers.addResult(results, 3, 'Unable to query for backup retention policies : ' + helpers.addError(backupPolicies), location);
```

2021-05-31 16:43 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/instantRestoreRetention.js
> +                            helpers.addResult(results, 0, 'No instant restore backup is configured', location, virtualMachine.id);
Never do this in a for loop

2021-05-31 16:43 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/vmBackupsEnabled.js
> +                    helpers.addResult(results, 3, 'Unable to query for backups : ' + helpers.addError(recoveryVaults), location);
```suggestion
                    helpers.addResult(results, 3, 'Unable to query for backups : ' + helpers.addError(backupProtectedItems), location);
```

2021-05-31 16:43 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/vmBackupsEnabled.js
> +                    vmBackupsEnabled = vmPolicies.some(policy => (policy && policy !== ''));
```suggestion
                    vmBackupsEnabled = vmPolicies.some(policy => (policy && policy.length));
```

2021-05-31 16:43 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/vmBackupsEnabled.js
> +                }
Move this outside of for loop

2021-06-03 17:13 UTC, giorod3 commented on plugins/azure/virtualmachines/instantRestoreRetention.js
> +                        helpers.addResult(results, 0, 'No instant restore backup is configured', location, virtualMachine.id);
```suggestion
                        helpers.addResult(results, 2, 'No instant restore backup is configured', location, virtualMachine.id);
```

2021-06-03 17:14 UTC, giorod3 commented on plugins/azure/virtualmachines/instantRestoreRetention.js
> +                        helpers.addResult(results, 2, 'No instant restore backup is configured', location, virtualMachine.id);
changed to 2

2021-06-03 17:28 UTC, merged