feature/AKD-137: Added Azure 'Scale Sets Autoscale Notifications Enabled' plugin and test cases
aquasecurity/cloudsploit pull request #679
Opened 2021-05-02 15:37 UTC by ali-imran7

2021-05-31 16:13 UTC, AkhtarAmir requested changes

2021-05-31 16:13 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/autoscaleNotificationsEnabled.js
> +    recommended_action: 'Ensure that autoscale notifications are enabled for all Virtual Machine Scale Sets.',
```suggestion
    recommended_action: 'Ensure that autoscale notifications are enabled for all Virtual Machine Scale Sets',
```

2021-05-31 16:13 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/autoscaleNotificationsEnabled.js
> +    description: 'Ensures that Virtual Machine scale sets have autoscale notifications enabled',
```suggestion
    description: 'Ensures that Virtual Machine scale sets have autoscale notifications enabled.',
```

2021-05-31 16:13 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/autoscaleNotificationsEnabled.js
> +                    autoScaleNotifications = asMap[virtualMachineScaleSet.id.toLowerCase()].notifications[0];
Shouldn't we loop all notifications?

2021-06-01 17:53 UTC, ali-imran7 commented on plugins/azure/virtualmachines/autoscaleNotificationsEnabled.js
> +                    autoScaleNotifications = asMap[virtualMachineScaleSet.id.toLowerCase()].notifications[0];
lets discuss this

2021-06-03 17:07 UTC, merged