modification: Modified index and engine to accommodate Alibaba cloud
aquasecurity/cloudsploit pull request #682
Opened 2021-05-04 12:44 UTC by AkhtarAmir

2021-05-10 05:37 UTC, dipsubha06 requested changes

2021-05-10 05:37 UTC, dipsubha06 commented on index.js
> +        accessKeyId: config.credentials.aws.access_key_id,
Will this be config.credentials.aws.access_key_id or config.credentials.alibaba.access_key_id?

2021-05-10 14:08 UTC, giorod3 approved these changes

2021-05-14 22:56 UTC, giorod3 commented
@AkhtarAmir I merged the collector PR, I think we can close this

2021-05-26 18:09 UTC, closed without merging