GCP SQL plugin updated for restorable backups.
aquasecurity/cloudsploit pull request #693
Opened 2021-05-09 13:40 UTC by umermehmood

2021-05-28 18:11 UTC, giorod3 commented on plugins/google/sql/dbRestorable.js
> +                        'SQL instance does not have the backup available', region, sqlInstance.name);
```suggestion
                        'SQL instance does not have backups available', region, sqlInstance.name);
```

2021-05-28 18:11 UTC, giorod3 requested changes
just the one comment

2021-06-02 11:55 UTC, AkhtarAmir approved these changes

2021-06-30 18:57 UTC, giorod3 approved these changes

2021-06-30 18:59 UTC, merged