feature/AKD-145: Added 'VM Approved Extensions' plugin and test cases
aquasecurity/cloudsploit pull request #694
Opened 2021-05-09 19:35 UTC by ali-imran7

2021-05-31 13:39 UTC, AkhtarAmir requested changes

2021-05-31 13:39 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/approvedVmExtension.js
> +    more_info: 'Extensions are small applications that provide post-deployment configuration and automation on Azure VMs. VMs installed should be approved by the organization to meet the organization
```suggestion
    more_info: 'Extensions are small applications that provide post-deployment configuration and automation on Azure VMs. Extensions installed should be approved by the organization to meet the organizational security requirements.',
```

2021-05-31 13:39 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/approvedVmExtension.js
> +                        let extensionsList = config.approvedExtensions.split(',');
Move this on top

2021-05-31 13:39 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/approvedVmExtension.js
> +                        let found = extensionsList.some(extension => extension.trim() === virtualMachineExtension.name);
Use find

2021-05-31 13:39 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/approvedVmExtension.js
> +                        if (found) {
Move this check outside foreach loop

2021-06-03 17:03 UTC, giorod3 requested changes

2021-06-03 17:03 UTC, giorod3 commented on plugins/azure/virtualmachines/approvedVmExtension.js
> +
this plugin should be opt-in and skipped here if no setting exists

2021-06-03 17:20 UTC, giorod3 approved these changes

2021-06-03 17:21 UTC, merged