hotfix/vmAvailabilitySetLimit: Fixed bug and added test case
aquasecurity/cloudsploit pull request #696
Opened 2021-05-10 18:34 UTC by ali-imran7

2021-05-31 13:33 UTC, AkhtarAmir requested changes

2021-05-31 13:33 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/vmAvailabilitySetLimit.js
> +                ['resourceGroups', 'list', location]);
Can you add a description why did you changed?

2021-06-01 17:03 UTC, ali-imran7 commented
This PR addresses a bug for this plugin. 
Bug Description : Plugin was generating always passing results
RCA: `availabilitySets:listBySubscription` api call returns 0 for virtual machines count in the availability set. Thats why plugin was always generating passing result.

2021-06-01 18:36 UTC, giorod3 approved these changes

2021-07-30 14:29 UTC, giorod3 approved these changes

2021-07-30 14:29 UTC, merged