feature/AKD-142: Added 'Azure Active Directory (AD) Authentication Enabled' plugin and test cases
aquasecurity/cloudsploit pull request #712
Opened 2021-05-15 23:08 UTC by ali-imran7

2021-05-31 13:23 UTC, AkhtarAmir requested changes

2021-05-31 13:23 UTC, AkhtarAmir commented on exports.js
> +        'adAuthenticationEnabled'       : require(__dirname + '/plugins/azure/virtualmachines/adAuthenticationEnabled.js'),
```suggestion
        'vmAdAuthenticationEnabled'     : require(__dirname + '/plugins/azure/virtualmachines/vmAdAuthenticationEnabled.js'),
```

2021-05-31 13:23 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/adAuthenticationEnabled.js
> +    title: 'Azure Active Directory (AD) Authentication Enabled',
```suggestion
    title: 'VM Active Directory (AD) Authentication Enabled',
```

2021-05-31 13:23 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/adAuthenticationEnabled.js
> +    description: 'Ensures that Azure Active Directory (AD) authentication is enabled of virtual machines.',
```suggestion
    description: 'Ensures that Azure Active Directory (AD) authentication is enabled for virtual machines.',
```

2021-05-31 13:23 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/adAuthenticationEnabled.js
> +                }
Make this one check

2021-05-31 13:23 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/adAuthenticationEnabled.js
> +                        (!windowsImg && virtualMachineExtension.name && virtualMachineExtension.name === 'AADSSHLoginForLinux')));
Make this find or for loop

2021-06-01 16:25 UTC, ali-imran7 commented on plugins/azure/virtualmachines/adAuthenticationEnabled.js
> +                        (!windowsImg && virtualMachineExtension.name && virtualMachineExtension.name === 'AADSSHLoginForLinux')));
Lets discuss this

2021-06-01 18:32 UTC, giorod3 approved these changes

2021-06-01 18:36 UTC, merged