feature/AKD-141: Added Azure 'Virtual Machine Performance Diagnostics Enabled' plugin and test cases
aquasecurity/cloudsploit pull request #713
Opened 2021-05-16 06:23 UTC by ali-imran7

2021-05-31 13:18 UTC, AkhtarAmir requested changes

2021-05-31 13:18 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/performanceDiagnosticsEnabled.js
> +                    windowsImg = true;
We can combine these checks with OR (||) operator

2021-05-31 13:18 UTC, AkhtarAmir commented on plugins/azure/virtualmachines/performanceDiagnosticsEnabled.js
> +                        (virtualMachineExtension.provisioningState && virtualMachineExtension.provisioningState === 'Succeeded')));
Make this for loop or use find

2021-06-01 16:20 UTC, ali-imran7 commented on plugins/azure/virtualmachines/performanceDiagnosticsEnabled.js
> +                        (virtualMachineExtension.provisioningState && virtualMachineExtension.provisioningState === 'Succeeded')));
Lets discuss this

2021-06-01 18:29 UTC, giorod3 approved these changes

2021-06-01 18:32 UTC, merged