Alibaba ram user access keys rotation plugin with spec file
aquasecurity/cloudsploit pull request #722
Opened 2021-05-23 18:47 UTC by umermehmood

2021-05-24 06:46 UTC, AkhtarAmir requested changes

2021-05-24 06:46 UTC, AkhtarAmir commented on collectors/alibaba/collector.js
> +                apiVersion: '2015-05-01'
```suggestion
            },
            ListAccessKeys: {
                reliesOnService: 'ram',
                reliesOnCall: 'ListUsers',
                filterKey: ['UserName'],
                filterValue: ['UserName'],
                apiVersion: '2015-05-01'
```

2021-05-24 06:46 UTC, AkhtarAmir commented on plugins/alibaba/ram/accessKeysRotation.js
> +
Add condition to check UNKNOWN case

2021-05-24 06:46 UTC, AkhtarAmir commented on plugins/alibaba/ram/accessKeysRotation.js
> +            var accessKey = getAccessKey.data.AccessKeys.AccessKey.find(key => key.Status && key.Status == 'Active');
```suggestion
            let accessKey;
            if (getAccessKey.data.AccessKeys && getAccessKey.data.AccessKeys.AccessKey && getAccessKey.data.AccessKeys.AccessKey.length) {
                  accessKey = getAccessKey.data.AccessKeys.AccessKey.find(key => key.Status && key.Status == 'Active');
            }
```

2021-05-24 06:46 UTC, AkhtarAmir commented on plugins/alibaba/ram/accessKeysRotation.js
> +                    'RAM user access keys does not exist ', region, resource);
```suggestion
                    'RAM user does not have any active access keys', region, resource);
```

2021-05-24 06:46 UTC, AkhtarAmir commented on plugins/alibaba/ram/accessKeysRotation.js
> +                        'RAM user access keys are not rotated every 90 days or less ', region, resource);
```suggestion
                        `RAM user access key is ${diffInDays} days old`, region, resource);
```

2021-05-24 06:46 UTC, AkhtarAmir commented on plugins/alibaba/ram/accessKeysRotation.js
> +                        'RAM user access keys are rotated every 90 days or less', region, resource);
```suggestion
                        `RAM user access key is ${diffInDays} days old`, region, resource);
```

2021-05-24 06:46 UTC, AkhtarAmir commented on plugins/alibaba/ram/accessKeysRotation.js
> +            if (accessKey) {
This implementation will only check the first access key. We need to loop all of them and display result for each.

2021-05-26 17:52 UTC, giorod3 approved these changes

2021-05-26 17:59 UTC, giorod3 requested changes
unique results per resource, no duplicates. add setting for rotation length. one result per resource always.

2021-05-28 18:15 UTC, giorod3 commented on plugins/alibaba/ram/accessKeysRotation.js
> +            if (getAccessKey.err || !getAccessKey.data) {
```suggestion
            if (getAccessKey.err || !getAccessKey.data || !Object.keys(getAccessKey.data).length) {
```

2021-05-28 18:16 UTC, giorod3 commented on plugins/alibaba/ram/accessKeysRotation.js
> +                    if (accessKey.Status == 'Active') {
```suggestion
                    if (accessKey.Status && accessKey.Status == 'Active') {
```

2021-05-28 18:17 UTC, giorod3 approved these changes

2021-05-28 18:18 UTC, merged