Alibaba ram user plugin added for block logon with spec file
aquasecurity/cloudsploit pull request #725
Opened 2021-05-23 22:26 UTC by umermehmood

2021-05-24 06:23 UTC, AkhtarAmir requested changes

2021-05-24 06:23 UTC, AkhtarAmir commented on plugins/alibaba/ram/passwordBlockLogon.js
> +    description: 'Ensure that RAM password security settings require logon to be blocked after max login attempts.',
```suggestion
    description: 'Ensure that RAM password security settings require logon to be blocked after maximum of 5 incorrect login attempts.',
```

2021-05-24 06:23 UTC, AkhtarAmir commented on plugins/alibaba/ram/passwordBlockLogon.js
> +        if (getPasswordPolicy.data.MaxLoginAttemps > 0 && getPasswordPolicy.data.MaxLoginAttemps <=5) {
```suggestion
        if (getPasswordPolicy.data.MaxLoginAttemps > 0 && getPasswordPolicy.data.MaxLoginAttemps <= 5) {
```

2021-05-24 06:23 UTC, AkhtarAmir commented on plugins/alibaba/ram/passwordBlockLogon.js
> +    recommended_action: 'Update the password security settings to require logon to be blocked after max login attempts.',
```suggestion
    recommended_action: 'Update the password security settings to require logon to be blocked after maximum of 5 or less incorrect login attempts.',
```

2021-05-26 12:51 UTC, giorod3 approved these changes

2021-05-26 18:04 UTC, giorod3 approved these changes

2021-05-26 18:05 UTC, merged