feature/networkPeering: Added Azure 'Cross Subscription Network Peerings' Plugin and test cases
aquasecurity/cloudsploit pull request #732
Opened 2021-05-27 23:40 UTC by ali-imran7

2021-05-31 11:45 UTC, AkhtarAmir requested changes

2021-05-31 11:45 UTC, AkhtarAmir commented on plugins/azure/virtualnetworks/virtualNetworkPeering.js
> +    title: 'Cross Subscription Network Peering',
```suggestion
    title: 'Virtual Network Peering',
```

2021-05-31 11:45 UTC, AkhtarAmir commented on plugins/azure/virtualnetworks/virtualNetworkPeering.js
> +    description: 'Ensures that Virtual Network is not connected with a virtual network in whitelisted subscription.',
```suggestion
    description: 'Ensures that Virtual Network has peering connection only with a virtual network in whitelisted subscription.',
```

2021-05-31 11:45 UTC, AkhtarAmir commented on plugins/azure/virtualnetworks/virtualNetworkPeering.js
> +    more_info: 'To meet your organization\'s security compliance requirements.',
```suggestion
    more_info: 'Virtual networks should only have peering connections with whitelisted virtual networks to meet your organization\'s security compliance requirements.',
```

2021-05-31 11:45 UTC, AkhtarAmir commented on plugins/azure/virtualnetworks/virtualNetworkPeering.js
> +        }
```suggestion
        whitelisted_peering_subscriptions: {
            name: 'Whitelisted Peering Subscriptions',
            description: 'Subscription Ids for remote virtual networks which should be allowed for peering',
            regex: '/^([a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12},?)+$/',
            default: ''
        }
```

2021-05-31 11:45 UTC, AkhtarAmir commented on plugins/azure/virtualnetworks/virtualNetworkPeering.js
> +                    let deniedSubscriptions = config.subscriptions.split(',');
```suggestion
```

2021-05-31 11:45 UTC, AkhtarAmir commented on plugins/azure/virtualnetworks/virtualNetworkPeering.js
> +                        helpers.addResult(results, 2, 'Virtual network is not connected with a virtual network in whitelisted subscription', location, virtualNetwork.id);
```suggestion
                        helpers.addResult(results, 2, `Vitual network has peering with these unknown subscriptions: ${unknownSubscriptions.join(', ')}`, location, virtualNetwork.id);
```

2021-05-31 11:45 UTC, AkhtarAmir commented on plugins/azure/virtualnetworks/virtualNetworkPeering.js
> +                rcb(null, results, source);
```suggestion
                rcb();
```

2021-06-01 18:10 UTC, giorod3 requested changes
change to opt-in

2021-06-03 17:01 UTC, giorod3 approved these changes

2021-06-03 17:01 UTC, merged