feature/networkPeering: Added Azure 'Managed NAT Gateway In Use' Plugin and test cases
aquasecurity/cloudsploit pull request #734
Opened 2021-05-28 15:03 UTC by ali-imran7

2021-05-31 05:24 UTC, dipsubha06 approved these changes

2021-05-31 11:28 UTC, AkhtarAmir requested changes

2021-05-31 11:28 UTC, AkhtarAmir commented on plugins/azure/virtualnetworks/managedNatGateway.js
> +                        }
You should use find

2021-06-01 17:36 UTC, giorod3 commented on plugins/azure/virtualnetworks/managedNatGateway.js
> +                }
add subscriptionId

2021-06-01 17:40 UTC, giorod3 approved these changes

2021-06-01 17:41 UTC, merged