feature/AKD-188: Added Azure 'Remote Debugging Disabled' Plugin and test cases
aquasecurity/cloudsploit pull request #739
Opened 2021-05-30 06:07 UTC by ali-imran7

2021-05-31 11:08 UTC, AkhtarAmir requested changes

2021-05-31 11:08 UTC, AkhtarAmir commented on plugins/azure/appservice/remoteDebuggingDisabled.js
> +                    }
Check this login in find

2021-05-31 11:08 UTC, AkhtarAmir commented on plugins/azure/appservice/remoteDebuggingDisabled.js
> +                    }
Verify option via API call

2021-06-01 14:42 UTC, ali-imran7 commented on plugins/azure/appservice/remoteDebuggingDisabled.js
> +                    }
Verified the API call as well

2021-06-01 17:25 UTC, giorod3 approved these changes

2021-06-01 17:42 UTC, merged