feature/AKD-189: Added Azure 'Always On Enabled' Plugin and test cases
aquasecurity/cloudsploit pull request #741
Opened 2021-05-30 15:51 UTC by ali-imran7

2021-05-31 10:50 UTC, AkhtarAmir requested changes

2021-05-31 10:50 UTC, AkhtarAmir commented on plugins/azure/appservice/alwaysOnEnabled.js
> +    more_info: 'Keeps the app loaded even when there\'s no traffic. It\'s required for continuous WebJobs or for WebJobs that are triggered using a CRON expression.',
```suggestion
    more_info: 'Always On feature keeps the app loaded even when there\'s no traffic. It\'s required for continuous WebJobs or for WebJobs that are triggered using a CRON expression.',
```

2021-05-31 10:50 UTC, AkhtarAmir commented on plugins/azure/appservice/alwaysOnEnabled.js
> +            );
```suggestion
            const webApps = helpers.addSource(cache, source, ['webApps', 'list', location]);
```

2021-05-31 10:50 UTC, AkhtarAmir commented on plugins/azure/appservice/alwaysOnEnabled.js
> +                if (!configs || configs.err || !configs.data) {
```suggestion
                if (!configs || configs.err || !configs.data || !configs.data.length) {
```

2021-05-31 10:50 UTC, AkhtarAmir commented on plugins/azure/appservice/alwaysOnEnabled.js
> +                }
```suggestion
```

2021-05-31 10:50 UTC, AkhtarAmir commented on plugins/azure/appservice/alwaysOnEnabled.js
> +                    if (config.alwaysOn) {
Check this flag in find

2021-06-01 17:11 UTC, giorod3 commented on plugins/azure/appservice/alwaysOnEnabled.js
> +                if (webApp && webApp.kind === 'functionapp') {
```suggestion
                if (webApp && webApp.kind && webApp.kind === 'functionapp') {
```

2021-06-01 17:18 UTC, giorod3 approved these changes

2021-06-01 17:18 UTC, merged