GCP Shielded vm enabled for compute instances plugin added with spec file
aquasecurity/cloudsploit pull request #745
Opened 2021-05-30 18:11 UTC by umermehmood

2021-06-01 11:57 UTC, AkhtarAmir requested changes

2021-06-01 11:57 UTC, AkhtarAmir commented on plugins/google/compute/shieldedVmEnabled.js
> +    more_info: 'Shielded VM option is provided to defend against the security attacks on the instances.',
```suggestion
    more_info: 'Shielded VM option should be configured to defend against the security attacks on the instances.',
```

2021-06-01 11:57 UTC, AkhtarAmir commented on plugins/google/compute/shieldedVmEnabled.js
> +                    `Shielded VM security is not enabled for the following instances: ${myInstanceStr}`, region);
```suggestion
                helpers.addResult(results, 2,
                    `Shielded VM security is not enabled for the following instances: ${nonShieldedVmInstances.join(', ')}`, region);
```

2021-06-01 11:57 UTC, AkhtarAmir commented on plugins/google/compute/shieldedVmEnabled.js
> +                    `Shielded VM security is enabled for the following instances: ${myInstanceStr}`, region);
```suggestion
                helpers.addResult(results, 0,
                    `Shielded VM security is enabled for the following instances: ${shieldedVmInstances.join(', ')}`, region);
```

2021-06-01 11:57 UTC, AkhtarAmir commented on plugins/google/compute/shieldedVmEnabled.js
> +                    }
```suggestion
                        instance.shieldedInstanceConfig.enableIntegrityMonitoring) shieldedVmInstances.push(instance.id);
                    else nonShieldedVmInstances.push(instance.id);
```

2021-06-02 10:14 UTC, AkhtarAmir approved these changes

2021-06-03 16:48 UTC, giorod3 commented on plugins/google/compute/shieldedVmEnabled.js
> +            });
missing zcb();

2021-06-03 16:50 UTC, giorod3 requested changes
missing callback in the zcb async

2021-06-30 18:48 UTC, giorod3 commented on plugins/google/compute/shieldedVmEnabled.js
> +            rcb();
```suggestion
                }
                rcb();
            });
            
```

2021-06-30 18:49 UTC, giorod3 approved these changes

2021-06-30 18:50 UTC, merged