Alibaba rds public access disabled plugin with spec file
aquasecurity/cloudsploit pull request #747
Opened 2021-05-30 22:13 UTC by umermehmood

2021-05-31 05:27 UTC, dipsubha06 approved these changes

2021-06-01 11:43 UTC, AkhtarAmir requested changes

2021-06-01 11:43 UTC, AkhtarAmir commented on plugins/alibaba/rds/rdsPublicAccess.js
> +    more_info: 'Enabling public access increase chances of data security. Public access should always be disabled.',
```suggestion
    more_info: 'Enabling public access increase chances of data insecurity. Public access should always be disabled and only know IP addresses should be whitelisted.',
```

2021-06-01 11:43 UTC, AkhtarAmir commented on plugins/alibaba/rds/rdsPublicAccess.js
> +    description: 'Ensure that RDS DB instances does not have public access.',
```suggestion
    description: 'Ensure that RDS DB instances are not publicly accessible.',
```

2021-06-01 11:43 UTC, AkhtarAmir commented on plugins/alibaba/rds/rdsPublicAccess.js
> +
Add a setting for whitelisted IP adresses which should be allowed

2021-06-02 10:07 UTC, AkhtarAmir approved these changes

2021-06-03 16:54 UTC, giorod3 approved these changes

2021-06-03 16:54 UTC, merged