Alibaba rds auditing enable plugin added with spec file
aquasecurity/cloudsploit pull request #748
Opened 2021-05-31 00:13 UTC by umermehmood

2021-05-31 05:42 UTC, dipsubha06 approved these changes

2021-06-01 11:26 UTC, AkhtarAmir requested changes

2021-06-01 11:26 UTC, AkhtarAmir commented on plugins/alibaba/rds/rdsAuditingEnabled.js
> +                validInstance = dbEngines.find(engine => instance.Engine && instance.EngineVersion && (instance.Engine.toLowerCase() + ' ' + instance.EngineVersion).includes(engine));
```suggestion
                let instanceEngine = (instance.Engine && instance.EngineVersion) ? `${instance.Engine.toLowerCase()} ${instance.EngineVersion}` : '';
                validInstance = dbEngines.find(engine =>instanceEngine.includes(engine));
```

2021-06-01 11:26 UTC, AkhtarAmir commented on plugins/alibaba/rds/rdsAuditingEnabled.js
> +                if (validInstance) {
Is it supposed to be if(!validInstance) ?

2021-06-02 09:43 UTC, AkhtarAmir approved these changes

2021-06-03 16:54 UTC, giorod3 approved these changes

2021-06-03 16:57 UTC, merged