feature/AKD-181: Added 'SSL Access Only Enabled' plugin and test cases
aquasecurity/cloudsploit pull request #786
Opened 2021-06-30 02:25 UTC by ali-imran7

2021-07-02 12:20 UTC, AkhtarAmir requested changes

2021-07-02 12:20 UTC, AkhtarAmir commented on plugins/azure/redisCache/sslAccessOnlyEnabled.js
> +    description: 'Ensures that SSL Access Only enabled for Azure Cache for Redis.',
```suggestion
    description: 'Ensures that SSL Access Only feature is enabled for Azure Redis Caches.',
```

2021-07-02 12:21 UTC, AkhtarAmir approved these changes

2021-07-07 19:16 UTC, giorod3 approved these changes

2021-07-07 19:16 UTC, merged