Plugin to check for ELB SSL termination
aquasecurity/cloudsploit pull request #788
Opened 2021-06-30 12:45 UTC by UmairAjmal

2021-06-30 14:45 UTC, AkhtarAmir requested changes

2021-06-30 14:45 UTC, AkhtarAmir commented on plugins/aws/elbv2/elbv2SslTermination.js
> +            rcb();
```suggestion
                cb();
            }, function() {
                rcb();
            });
```

2021-06-30 14:45 UTC, AkhtarAmir commented on plugins/aws/elbv2/elbv2SslTermination.js
> +                        helpers.addResult(results, 0,
```suggestion
                    if (listener.Certificates && listener.Certificates.length) {
                        helpers.addResult(results, 0,
```

2021-06-30 14:45 UTC, AkhtarAmir commented on plugins/aws/elbv2/elbv2SslTermination.js
> +                    }
```suggestion
                    } else {
                        helpers.addResult(results, 2,
                            'Elastic Load Balancer does not have SSL Termination configured',
                            region, resource);
                    }
```

2021-06-30 14:45 UTC, AkhtarAmir commented on plugins/aws/elbv2/elbv2SslTermination.js
> +                var describeListeners = helpers.addSource(cache, source,
```suggestion
            async.each(describeLoadBalancers.data, function(elb, cb){
                var resource = elb.LoadBalancerArn;

                var describeListeners = helpers.addSource(cache, source,
```

2021-06-30 14:45 UTC, AkhtarAmir commented on plugins/aws/elbv2/elbv2SslTermination.js
> +
let found = describeListeners.data.Listeners.find(listener => listener.Certificates && listener.Certificates.length);

2021-07-02 10:41 UTC, AkhtarAmir requested changes

2021-07-02 10:41 UTC, AkhtarAmir commented on plugins/aws/elbv2/elbv2SslTermination.js
> +                rcb();
```suggestion
            }, function(){
                rcb();
```

2021-07-07 19:07 UTC, giorod3 commented on plugins/aws/elbv2/elbv2SslTermination.js
> +    description: 'Ensure that Load Balancers has SSL certificate configured for SSL terminations.',
```suggestion
    description: 'Ensure that Load Balancers have SSL certificate configured for SSL terminations.',
```

2021-07-07 19:07 UTC, giorod3 approved these changes

2021-07-07 19:07 UTC, merged