feature/AkD-327: Plugin to check recently active IAM user
aquasecurity/cloudsploit pull request #800
Opened 2021-07-13 13:28 UTC by UmairAjmal

2021-07-15 09:54 UTC, AkhtarAmir requested changes

2021-07-15 09:54 UTC, AkhtarAmir commented on plugins/aws/iam/iamUserInUse.js
> +    description: 'Ensures the IAM user account is being actively used',
```suggestion
    description: 'Ensure that IAM user accounts are being actively used.',
```

2021-07-15 09:54 UTC, AkhtarAmir commented on plugins/aws/iam/iamUserInUse.js
> +    },
```suggestion
```

2021-07-15 09:54 UTC, AkhtarAmir commented on plugins/aws/iam/iamUserInUse.js
> +    _run: function(cache, settings, callback, now) {
Change this to be consistent with newer plugins

2021-07-15 09:54 UTC, AkhtarAmir commented on plugins/aws/iam/iamUserInUse.js
> +                if (user.password_last_used && user.password_last_used !== null && user.password_last_used !== 'no_information') {
```suggestion
                if (user.password_last_used && user.password_last_used !== 'no_information') {
```

2021-07-15 09:54 UTC, AkhtarAmir commented on plugins/aws/iam/iamUserInUse.js
> +                }
```suggestion
                if (user.access_key_1_last_used_date ) accessDates.push(user.access_key_1_last_used_date);

                if (user.access_key_2_last_used_date) accessDates.push(user.access_key_2_last_used_date);
```

2021-07-15 09:54 UTC, AkhtarAmir commented on plugins/aws/iam/iamUserInUse.js
> +
```suggestion
                    var dateToCompare = helpers.mostRecentDate(accessDates);

```

2021-07-15 09:54 UTC, AkhtarAmir commented on plugins/aws/iam/iamUserInUse.js
> +    }
```suggestion
        callback(null, results, source);
    }
```

2021-07-15 09:54 UTC, AkhtarAmir commented on plugins/aws/iam/iamUserInUse.spec.js
> +            iamUserInUse._run(cache, settings, callback, new Date('2021-07-06T15:31:34+00:00'));
Make this dynamic

2021-07-30 13:00 UTC, AkhtarAmir commented on plugins/aws/iam/iamUserInUse.js
> +            helpers.addResult(results, 3, 'Unable to query IAM users');
```suggestion
            helpers.addResult(results, 0, 'No IAM users found', 'global');
```

2021-07-30 14:07 UTC, AkhtarAmir requested changes

2021-07-30 14:07 UTC, AkhtarAmir commented on exports.js
> +        'iamUserInUse'                : require(__dirname + '/plugins/aws/iam/iamUserInUse.js'),
```suggestion
        'iamUserInUse'                  : require(__dirname + '/plugins/aws/iam/iamUserInUse.js'),
```

2021-08-13 16:51 UTC, giorod3 commented on plugins/aws/iam/iamUserInUse.js
> +            description: 'Return a failing result when the IAM user account has been used within this many days',
```suggestion
            description: 'Return a failing result when the IAM user account has not been used within this many days',
```

2021-08-13 16:56 UTC, giorod3 requested changes
review the logic, this should be checking to see if a user is use. it should fail if a user isn't being actively used to prevent lingering users

2021-08-18 10:24 UTC, AkhtarAmir commented on plugins/aws/iam/iamUserInUse.js
> +    recommended_action: 'Delete IAM user accounts which are not being actively used.',
```suggestion
    recommended_action: 'Delete IAM user accounts which are being actively used.',
```

2021-08-18 10:27 UTC, AkhtarAmir requested changes

2021-08-18 10:27 UTC, AkhtarAmir commented on plugins/aws/iam/iamUserInUse.js
> +                }
```suggestion
                    var loginDate = new Date(helpers.mostRecentDate(accessDates));
                    var difference = helpers.daysBetween(loginDate, currentDate);
                    var resultCode = (difference < config.iam_user_account_in_use_days) ? 2: 0;

                    helpers.addResult(results, resultCode,
                        'IAM user was last used ' + difference + ' days ago',
                        'global', user.arn, custom);
                }
```

2021-08-18 10:27 UTC, AkhtarAmir commented on plugins/aws/iam/iamUserInUse.js
> +                if (user.access_key_1_last_used_date) accessDates.push(user.access_key_1_last_used_date);
Check if (user.access_key_1_last_used_date != 'N/A')

2021-08-20 13:25 UTC, AkhtarAmir approved these changes

2021-08-23 16:15 UTC, giorod3 approved these changes

2021-08-23 16:19 UTC, giorod3 approved these changes

2021-08-23 16:19 UTC, merged