Fix condition key name of Amazon SNS topic policies
aquasecurity/cloudsploit pull request #805
Opened 2021-07-15 10:02 UTC by kurochan

Fix condition key case from `AWS:SourceOwner` to `aws:SourceOwner`.

According to the document, there should be start with `aws:` instead of `AWS:`.

https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html
> Global condition keys are condition keys with an aws: prefix. 

https://docs.aws.amazon.com/sns/latest/dg/sns-access-policy-use-cases.html
> The aws:SourceAccount and aws:SourceOwner condition keys are similar in that they both identify a resource owner.

2021-07-15 10:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=805) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=805) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=805) it.</sub>

2021-07-16 02:20 UTC, kurochan commented
Hi @AkhtarAmir, could you review this PR?

2021-08-25 14:46 UTC, AkhtarAmir requested changes

2021-08-25 15:03 UTC, kurochan commented on plugins/aws/sns/topicPolicies.js
> +                            (statement.Condition.StringEquals['aws:SourceOwner'] || !statement.Condition.StringEquals['aws:SourceOwner'] == '*')) ? true : false);
I fixed https://github.com/aquasecurity/cloudsploit/pull/805/commits/43d90e2bb408aaba0107bb7d0d70735ba31f1ad7.

2021-08-31 09:36 UTC, AkhtarAmir commented
Hey @kurochan! we have a change request to add a setting to be able to provide policy conditions just like we do for KMS Key Policy plugin and that has been done and in this PR https://github.com/aquasecurity/cloudsploit/pull/876
Thanks for submitting this anyway

2021-08-31 09:36 UTC, closed without merging