SAAS-2231: Plugin to check usage of specific policy to access AWS Support Center
aquasecurity/cloudsploit pull request #816
Opened 2021-07-26 10:33 UTC by UmairAjmal

2021-08-18 10:01 UTC, AkhtarAmir commented on exports.js
> +        'iamSupportPolicy'                : require(__dirname + '/plugins/aws/iam/iamSupportPolicy.js'),
```suggestion
        'iamSupportPolicy'              : require(__dirname + '/plugins/aws/iam/iamSupportPolicy.js'),
```

2021-08-18 10:02 UTC, AkhtarAmir commented on plugins/aws/iam/iamSupportPolicy.js
> +        var region = helpers.defaultRegion(settings);
```suggestion
        var results = [];
        var source = {};
        var region = helpers.defaultRegion(settings);
```

2021-08-18 10:22 UTC, AkhtarAmir requested changes

2021-08-18 10:22 UTC, AkhtarAmir commented on plugins/aws/iam/iamSupportPolicy.js
> +                }
return callback(null, results, source)

2021-08-18 10:22 UTC, AkhtarAmir commented on plugins/aws/iam/iamSupportPolicy.js
> +                        'No role, user or group attached to the policy', 'global', policy.Arn);
```suggestion
                        'No role, user or group attached to AWSSupportAccess policy', 'global', policy.Arn);
```

2021-08-18 10:22 UTC, AkhtarAmir commented on plugins/aws/iam/iamSupportPolicy.js
> +            ['iam', 'listEntitiesForPolicy', region]);
```suggestion
```

2021-08-18 10:22 UTC, AkhtarAmir commented on plugins/aws/iam/iamSupportPolicy.js
> +            if (listEntitiesForPolicy.err || !listEntitiesForPolicy[policyArn] || !listEntitiesForPolicy[policyArn].data) {
```suggestion
        if (policyArn){
            const listEntitiesForPolicy = helpers.addSource(cache, source,
            ['iam', 'listEntitiesForPolicy', region, policyArn]);
    
            if (!listEntitiesForPolicy || listEntitiesForPolicy.err || !listEntitiesForPolicy.data) {
```

2021-08-18 10:22 UTC, AkhtarAmir commented on plugins/aws/iam/iamSupportPolicy.js
> +                    'Unable to query for IAM entities for policy: ' + helpers.addError(listEntitiesForPolicy));
```suggestion
                    'Unable to query for IAM entities for AWSSupportAccess policy: ' + helpers.addError(listEntitiesForPolicy));
```

2021-08-18 10:22 UTC, AkhtarAmir commented on plugins/aws/iam/iamSupportPolicy.js
> +    }
```suggestion
    if (entities['PolicyGroups']) {
        if (entities.PolicyGroups.length) attachments.push('group'));        
    }
    if ('PolicyRoles' in entities) {
        if (entities.PolicyRoles.length > 0) entities.PolicyRoles.forEach(
            role => attachments.push(`Policy is attached '${role.RoleName}' role`));
    }
    if ('PolicyUsers' in entities) {
        if (entities.PolicyGroups.length > 0) entities.PolicyUsers.forEach(
            user => attachments.push(`Policy is attached '${user.UserName}' user`));
    }
```

2021-08-20 12:33 UTC, AkhtarAmir commented on plugins/aws/iam/iamSupportPolicy.js
> +    settings: {},
```suggestion
```

2021-08-20 12:56 UTC, AkhtarAmir commented on plugins/aws/iam/iamSupportPolicy.js
> +        }
```suggestion
        }
```

2021-08-20 13:13 UTC, AkhtarAmir approved these changes

2021-08-23 16:24 UTC, giorod3 approved these changes

2021-08-23 16:26 UTC, merged