SAAS-2233: Plugin to check access analyzer is enabled
aquasecurity/cloudsploit pull request #817
Opened 2021-07-26 12:45 UTC by UmairAjmal

2021-07-30 12:50 UTC, AkhtarAmir requested changes

2021-07-30 12:50 UTC, AkhtarAmir commented on plugins/aws/accessanalyzer/accessAnalyzerEnabled.js
> +    description: 'Ensure that IAM Access analyzer is enabled for all regions',
```suggestion
    description: 'Ensure that IAM Access analyzer is enabled for all regions.',
```

2021-07-30 12:50 UTC, AkhtarAmir commented on plugins/aws/accessanalyzer/accessAnalyzerEnabled.js
> +    more_info: 'Access Analyzer allow you to determine if an unintended user is allowed, making it easier for administrators to monitor least privileges access. It analyzes only policies that are app
```suggestion
    more_info: 'Access Analyzer allow you to determine if an unintended user is allowed, making it easier for administrators to monitor least privileges access. It analyzes only policies that are applied to resources in the same AWS region.',
```

2021-07-30 12:51 UTC, AkhtarAmir approved these changes

2021-08-13 17:00 UTC, giorod3 approved these changes

2021-08-13 17:00 UTC, merged