SAAS-2062: Plugin to check for outdated Amazon Machine Images
aquasecurity/cloudsploit pull request #819
Opened 2021-07-27 19:37 UTC by UmairAjmal

2021-08-18 09:50 UTC, AkhtarAmir commented on plugins/aws/ec2/outdatedAmi.js
> +
Check if (!config.check_ami_usage) return callback(null, results, source);

2021-08-18 09:59 UTC, AkhtarAmir requested changes

2021-08-18 09:59 UTC, AkhtarAmir commented on plugins/aws/ec2/outdatedAmi.js
> +
Check if (!config.check_ami_usage) return callback(null, results, source);

2021-08-18 09:59 UTC, AkhtarAmir commented on plugins/aws/ec2/outdatedAmi.js
> +
Add launch templates

2021-08-18 09:59 UTC, AkhtarAmir commented on plugins/aws/ec2/outdatedAmi.js
> +                    if (config.check_ami_usage){
remove this check

2021-08-18 09:59 UTC, AkhtarAmir commented on plugins/aws/ec2/outdatedAmi.js
> +            }
Remove this check

2021-08-18 09:59 UTC, AkhtarAmir commented on plugins/aws/ec2/outdatedAmi.js
> +                        if (describeInstances.data.length) {
Change foreach to for loop and break from both loops if usedAmi is true

2021-08-18 09:59 UTC, AkhtarAmir commented on plugins/aws/ec2/outdatedAmi.js
> +                        if (describeLaunchConfigurations.data.length) {
```suggestion
                        if (!usedAmi && describeLaunchConfigurations.data.length) {
```

2021-08-18 09:59 UTC, AkhtarAmir commented on plugins/aws/ec2/outdatedAmi.js
> +
3 cases.
1. inuse + deprecated => fail
2. deprecated + notinuse => pass
3. not deprecated => pass

2021-08-20 14:09 UTC, AkhtarAmir approved these changes

2021-08-23 16:28 UTC, giorod3 commented on plugins/aws/ec2/outdatedAmiInUse.js
> +                                    if (element.ImageId && image.ImageId == element.ImageId) amiInUse = true;
break should be inside the if statement

2021-08-23 16:30 UTC, giorod3 commented on plugins/aws/ec2/outdatedAmiInUse.js
> +                            if (config.ImageId && image.ImageId == config.ImageId) amiInUse = true;
break should be inside the if statement

2021-08-23 16:32 UTC, giorod3 requested changes
just the couple of comments

2021-08-24 16:55 UTC, giorod3 approved these changes

2021-08-24 16:55 UTC, merged