SAAS-2290: Plugin to check AWS ElasticSearch Cluster status
aquasecurity/cloudsploit pull request #837
Opened 2021-08-06 21:03 UTC by UmairAjmal

2021-08-18 09:34 UTC, AkhtarAmir commented on collectors/aws/collector.js
> +                override: true,
add relies on service

2021-08-18 09:44 UTC, AkhtarAmir requested changes

2021-08-18 09:44 UTC, AkhtarAmir commented on collectors/aws/cloudwatch/getEsMetricStatistics.js
> +            'Period': 60,
Update these

2021-08-18 09:44 UTC, AkhtarAmir commented on plugins/aws/es/esClusterStatus.js
> +            async.each(listDomainNames.data, function(domain, dcb){
Add domain.DomainName check

2021-08-18 09:44 UTC, AkhtarAmir commented on plugins/aws/es/esClusterStatus.js
> +                if (!getMetricStats.data.Datapoints.length) return dcb();
Remove this

2021-08-18 09:44 UTC, AkhtarAmir commented on plugins/aws/es/esClusterStatus.js
> +            }
Remove this

2021-08-18 09:44 UTC, AkhtarAmir commented on plugins/aws/es/esClusterStatus.js
> +                if (maximumValue > 1){
Add else case

2021-08-18 09:44 UTC, AkhtarAmir commented on plugins/aws/es/esClusterStatus.js
> +                        `Unable to query for ES domain config: ${helpers.addError(getMetricStats)}`, region);
```suggestion
                        `Unable to query for ES domain metric stats: ${helpers.addError(getMetricStats)}`, region);
```

2021-08-20 13:19 UTC, AkhtarAmir approved these changes

2021-08-20 13:33 UTC, AkhtarAmir approved these changes

2021-08-23 16:34 UTC, giorod3 commented on collectors/aws/cloudwatch/getEsMetricStatistics.js
> +    async.forEach(collection.es.listDomainNames[AWSConfig.region].data, function(domain, cb){
```suggestion
    async.eachLimit(collection.es.listDomainNames[AWSConfig.region].data, 10,  function(domain, cb){        
```

2021-08-23 16:48 UTC, giorod3 requested changes
just the one async limit change

2021-08-23 16:57 UTC, giorod3 approved these changes

2021-08-23 16:58 UTC, merged