Instance Template Machine Types for Google Compute Engine
aquasecurity/cloudsploit pull request #841
Opened 2021-08-09 20:42 UTC by mehakseedat63

2021-08-10 09:23 UTC, AkhtarAmir commented on plugins/google/compute/instanceTemplateMachineTypes.js
> +    description: 'Ensures that Google Cloud Virtual Machine instances are of given types.',
```suggestion
    description: 'Ensure that Cloud VM instance templates are of given types.',
```

2021-08-10 09:31 UTC, AkhtarAmir requested changes

2021-08-10 09:31 UTC, AkhtarAmir commented on plugins/google/compute/instanceTemplateMachineTypes.js
> +    description: 'Ensures that Google Cloud Virtual Machine instances are of given types.',
```suggestion
    description: 'Ensure that Cloud Virtual Machine instance templates are of given types.',
```

2021-08-10 09:31 UTC, AkhtarAmir commented on plugins/google/compute/instanceTemplateMachineTypes.js
> +    more_info: 'Google Cloud Virtual Machine instance should be of the given types to ensure the internal compliance and prevent unexpected billing charges.',
```suggestion
    more_info: 'Virtual Machine instance templates should be of the given types to ensure the internal compliance and prevent unexpected billing charges.',
```

2021-08-10 09:31 UTC, AkhtarAmir commented on plugins/google/compute/instanceTemplateMachineTypes.js
> +    recommended_action: 'Stop the Google Cloud Virtual Machine instance, change the machine type to the desired type  and restart the instance.',
Change this as well

2021-08-10 09:31 UTC, AkhtarAmir commented on plugins/google/compute/instanceTemplateMachineTypes.js
> +        if (!instance_template_machine_types.length) return callback();
Move this to line 25

2021-08-10 09:31 UTC, AkhtarAmir commented on plugins/google/compute/instanceTemplateMachineTypes.js
> +                if (instanceTemplate.properties.machineType && instance_template_machine_types.includes(instanceTemplate.properties.machineType)) {
```suggestion
                if (instanceTemplate.properties && instanceTemplate.properties.machineType && 
                    instance_template_machine_types.includes(instanceTemplate.properties.machineType)) {
```

2021-08-10 09:31 UTC, AkhtarAmir commented on plugins/google/compute/instanceTemplateMachineTypes.js
> +                        'Google Cloud Virtual Machine instance template has the desired machine type', region);
```suggestion
                        'Virtual Machine instance template has desired machine type', region);
```

2021-08-10 09:31 UTC, AkhtarAmir commented on plugins/google/compute/instanceTemplateMachineTypes.js
> +                        'Google Cloud Virtual Machine instance template does not have the desired machine type', region);
```suggestion
                        'Virtual Machine instance template does not have desired machine type', region);
```

2021-08-10 09:31 UTC, AkhtarAmir commented on plugins/google/compute/InstanceTemplateMachineTypes.spec.js
> +                                    "email": "779980017373-compute@developer.gserviceaccount.com",
We never want to make account details public
```suggestion
                                    "email": "111122223333@developer.gserviceaccount.com",
```

2021-08-10 09:31 UTC, AkhtarAmir commented on plugins/google/compute/InstanceTemplateMachineTypes.spec.js
> +                                    "email": "779980017373-compute@developer.gserviceaccount.com",
You can also remove unnecessary data as well. Maybe just keep the data which is needed for plugin

2021-08-10 09:31 UTC, AkhtarAmir commented on plugins/google/compute/InstanceTemplateMachineTypes.spec.js
> +                                    "email": "779980017373-compute@developer.gserviceaccount.com",
```suggestion
                                    "email": "111122223333@developer.gserviceaccount.com",
```

2021-08-10 09:31 UTC, AkhtarAmir commented on plugins/google/compute/InstanceTemplateMachineTypes.spec.js
> +                        "selfLink": "https://www.googleapis.com/compute/v1/projects/akhtar-dev-aqua/global/instanceTemplates/instance-template-1",
```suggestion
```

2021-08-10 09:31 UTC, AkhtarAmir commented on plugins/google/compute/InstanceTemplateMachineTypes.spec.js
> +                        "kind": "compute#instanceTemplate"
```suggestion
                        },
                        "kind": "compute#instanceTemplate"
```

2021-08-10 11:27 UTC, AkhtarAmir commented on plugins/google/compute/instanceTemplateMachineTypes.js
> +    recommended_action: 'Stop the Cloud Virtual Machine instance template, change the machine type to the desired type  and restart the instance template.',
```suggestion
    recommended_action: 'Stop the Cloud Virtual Machine instance template, change the machine type to the desired type and restart the instance template.',
```

2021-08-10 11:27 UTC, AkhtarAmir commented on plugins/google/compute/InstanceTemplateMachineTypes.spec.js
> +        it('should FAIL if VM instance is not of the desired machine type', function (done) {
```suggestion
        it('should FAIL if VM instance template does not have desired machine type', function (done) {
```

2021-08-10 11:27 UTC, AkhtarAmir commented on plugins/google/compute/InstanceTemplateMachineTypes.spec.js
> +        it('should PASS if VM instance is of the desired machine type', function (done) {
```suggestion
        it('should PASS if VM instance template has desired machine type', function (done) {
```

2021-08-10 11:32 UTC, AkhtarAmir commented on plugins/google/compute/instanceTemplateMachineTypes.js
> +    recommended_action: 'Stop the Cloud Virtual Machine instance template, change the machine type to the desired type and restart the instance template.',
```suggestion
    recommended_action: 'Ensure that Virtual Machine instance template are not using undesired machine types.',
```

2021-08-10 11:32 UTC, AkhtarAmir commented on plugins/google/compute/instanceTemplateMachineTypes.js
> +        var instance_template_machine_types = settings.instance_template_machine_types || this.settings.instance_template_machine_types.default;
```suggestion
        var regions = helpers.regions();

        var instance_template_machine_types = settings.instance_template_machine_types || this.settings.instance_template_machine_types.default;
```

2021-08-10 11:34 UTC, AkhtarAmir commented on plugins/google/compute/instanceTemplateMachineTypes.js
> +            ['projects', 'get', 'global']);
```suggestion
        var instance_template_machine_types = settings.instance_template_machine_types || this.settings.instance_template_machine_types.default;

        if (!instance_template_machine_types.length) return callback(null, results, source);

        let projects = helpers.addSource(cache, source,
            ['projects', 'get', 'global']);
```

2021-08-20 17:05 UTC, giorod3 approved these changes

2021-08-20 17:05 UTC, merged