SAAS-2293: Plugin to check Elasticsearch use dedicated master nodes.
aquasecurity/cloudsploit pull request #845
Opened 2021-08-11 18:30 UTC by UmairAjmal

2021-08-18 09:13 UTC, AkhtarAmir commented on plugins/aws/es/esDedicatedMasterEnabled.js
> +                    ['es', 'describeElasticsearchDomain', region, domain.DomainName]);
```suggestion
            listDomainNames.data.forEach(function(domain){
                if (!domain.DomainName) return;
                var describeElasticsearchDomain = helpers.addSource(cache, source,
                    ['es', 'describeElasticsearchDomain', region, domain.DomainName]);
```

2021-08-18 09:14 UTC, AkhtarAmir commented on plugins/aws/es/esDedicatedMasterEnabled.js
> +                    if (localDomain.ElasticsearchClusterConfig &&
```suggestion
                    if (localDomain && localDomain.ElasticsearchClusterConfig &&
```

2021-08-18 09:17 UTC, AkhtarAmir commented on plugins/aws/es/esDedicatedMasterEnabled.js
> +                var describeElasticsearchDomain = helpers.addSource(cache, source,
Create ARN

2021-08-18 09:18 UTC, AkhtarAmir requested changes

2021-08-18 09:18 UTC, AkhtarAmir commented on plugins/aws/es/esDedicatedMasterEnabled.js
> +                var describeElasticsearchDomain = helpers.addSource(cache, source,
Create ARN, include in unknown check and use that ARN in results

2021-08-20 11:59 UTC, AkhtarAmir approved these changes

2021-08-20 12:15 UTC, AkhtarAmir commented on plugins/aws/es/esDedicatedMasterEnabled.js
> +    description: 'Ensure that Amazon Elasticsearch clusters are using dedicated master nodes.',
```suggestion
    description: 'Ensure that Amazon Elasticsearch domains are using dedicated master nodes.',
```

2021-08-20 12:16 UTC, AkhtarAmir approved these changes

2021-08-20 16:55 UTC, giorod3 approved these changes

2021-08-20 16:56 UTC, merged