SAAS-2294: Plugin to check AWS Elasticsearch desired instance types
aquasecurity/cloudsploit pull request #847
Opened 2021-08-12 14:27 UTC by UmairAjmal

2021-08-18 09:02 UTC, AkhtarAmir commented on exports.js
> +        'esDesiredInstanceType'       : require(__dirname + '/plugins/aws/es/esDesiredInstanceType.js'),
```suggestion
        'esDesiredInstanceType'         : require(__dirname + '/plugins/aws/es/esDesiredInstanceType.js'),
```

2021-08-18 09:12 UTC, AkhtarAmir requested changes

2021-08-18 09:12 UTC, AkhtarAmir commented on plugins/aws/es/esDesiredInstanceType.js
> +            description: 'Instance type of ES data instances',
make this data instance

2021-08-18 09:12 UTC, AkhtarAmir commented on plugins/aws/es/esDesiredInstanceType.js
> +                    if (config.InstanceType && !es_desired_instance_type.includes(config.InstanceType)) disallowedInstanceTypes.push(`${config.InstanceType} type for data node`);
Move type for data node to result string.

2021-08-18 09:12 UTC, AkhtarAmir commented on plugins/aws/es/esDesiredInstanceType.js
> +                if (localDomainStatus.ElasticsearchClusterConfig) {
```suggestion
                let disallowedInstanceTypes = [];
                if (describeElasticsearchDomain.data.DomainStatus &&
                    describeElasticsearchDomain.data.DomainStatus;.ElasticsearchClusterConfig) {
```

2021-08-18 09:12 UTC, AkhtarAmir commented on plugins/aws/es/esDesiredInstanceType.js
> +                helpers.addResult(results, 0, 'No ES domains found', region);
Add !domain.DomainName check

2021-08-18 09:12 UTC, AkhtarAmir commented on plugins/aws/es/esDesiredInstanceType.js
> +            default: 't2.small.elasticsearch'
Remove default values

2021-08-20 10:54 UTC, AkhtarAmir commented on plugins/aws/es/esDesiredInstanceType.js
> +            name: 'ES Dedicated Master Instance Type',
```suggestion
            name: 'ES Master Instance Type',
```

2021-08-20 10:55 UTC, AkhtarAmir commented on plugins/aws/es/esDesiredInstanceType.js
> +                if (!domain.DomainName) return;
```suggestion
                if (!domain.DomainName) continue;
```

2021-08-20 11:08 UTC, AkhtarAmir commented on plugins/aws/es/esDesiredInstanceType.js
> +                    return;
```suggestion
                    continue;
```

2021-08-20 11:09 UTC, AkhtarAmir commented on plugins/aws/es/esDesiredInstanceType.js
> +        }, function() {
```suggestion
            rcb();
        }, function() {
```

2021-08-20 12:01 UTC, AkhtarAmir approved these changes

2021-08-20 16:52 UTC, giorod3 approved these changes

2021-08-20 16:52 UTC, merged