SAAS-2297: Plugin to check sender policy framework in use for AWS Route53
aquasecurity/cloudsploit pull request #851
Opened 2021-08-13 16:33 UTC by UmairAjmal

2021-08-18 10:36 UTC, AkhtarAmir requested changes

2021-08-20 10:46 UTC, AkhtarAmir commented on plugins/aws/route53/senderPolicyFwInUse.js
> +
```suggestion
        async.each(listHostedZones.data, function(zone, cb){
            if (!zone.id) return cb();

            var resource = `arn:aws:route53:::${zone.Id}`;

```

2021-08-20 10:48 UTC, AkhtarAmir commented on plugins/aws/route53/senderPolicyFwInUse.js
> +                    `Hosted Zone "${zone.Name}" has these SPF disabled DNS records: ${spfDisabledDnsRecords.join(', ')}`,
```suggestion
                    `Hosted Zone has these SPF disabled DNS records: ${spfDisabledDnsRecords.join(', ')}`,
```

2021-08-20 10:49 UTC, AkhtarAmir commented on plugins/aws/route53/senderPolicyFwInUse.js
> +                    `Hosted Zone "${zone.Name}" has SPF enabled for all DNS records`,
```suggestion
                    'Hosted Zone has SPF enabled for all DNS records',
```

2021-08-20 10:51 UTC, AkhtarAmir commented on plugins/aws/route53/senderPolicyFwInUse.js
> +            if (!zone.id) return cb();
```suggestion
            if (!zone.Id) return cb();
```

2021-08-20 10:52 UTC, AkhtarAmir approved these changes

2021-08-20 16:39 UTC, giorod3 approved these changes

2021-08-20 16:42 UTC, merged