SAAS-2298: Plugin to check sender policy FW record exists in Route 53 DNS records
aquasecurity/cloudsploit pull request #852
Opened 2021-08-15 19:12 UTC by UmairAjmal

2021-08-18 08:26 UTC, AkhtarAmir commented on plugins/aws/route53/senderPolicyFwInUse.js
> +    more_info: 'Implementing SPF records for Route 53 domain names will help in reducing spam and increasing domains trustworthiness by stopping email spoofing.',
```suggestion
    more_info: 'Implementing SPF records for Route53 domain names will help in reducing spam and increasing domains trustworthiness by stopping email spoofing.',
```

2021-08-18 08:32 UTC, AkhtarAmir requested changes

2021-08-18 08:32 UTC, AkhtarAmir commented on plugins/aws/route53/senderPolicyFwInUse.js
> +            var resource = `arn:aws:route53:::${zone.Id}`;
add check if (!zone.id) return cb();

2021-08-18 08:32 UTC, AkhtarAmir commented on plugins/aws/route53/senderPolicyFwInUse.js
> +                if (recordSet.Type && recordSet.Type === 'TXT' && recordSet.ResourceRecords && recordSet.ResourceRecords.length) {
```suggestion
                if (recordSet.Type && recordSet.Type.toUpperCase() === 'TXT' && recordSet.ResourceRecords && recordSet.ResourceRecords.length) {
```

2021-08-18 08:33 UTC, AkhtarAmir commented on plugins/aws/route53/senderPolicyFwInUse.js
> +    title: 'Sender Policy Framework In Use',
```suggestion
    title: 'Sender Policy Framework Record Present',
```

2021-08-18 08:37 UTC, AkhtarAmir requested changes

2021-08-18 08:37 UTC, AkhtarAmir commented on plugins/aws/route53/senderPolicyFwInUse.js
> +    description: 'Ensure that Sender Policy Framework (SPF) is used to stop spammers from spoofing your AWS Route 53 domain.',
Look into description, more_info and link

2021-08-18 08:44 UTC, AkhtarAmir commented on plugins/aws/route53/senderPolicyFwInUse.js
> +    more_info: 'Implementing SPF records for Route53 domain names will help in reducing spam and increasing domains trustworthiness by stopping email spoofing.',
```suggestion
    more_info: 'Implementing SPF records for Route 53 domain names will help in reducing spam and increasing domains trustworthiness by stopping email spoofing.',
```

2021-08-18 10:32 UTC, AkhtarAmir commented on plugins/aws/route53/senderPolicyFwRecordPresent.js
> +            var listResourceRecordSets = helpers.addSource(cache, source,
```suggestion
        async.each(listHostedZones.data, function(zone, cb){
            if (!zone.Id) return cb();

            var resource = `arn:aws:route53:::${zone.Id}`;

            var listResourceRecordSets = helpers.addSource(cache, source,
```

2021-08-18 10:32 UTC, AkhtarAmir approved these changes

2021-08-20 16:37 UTC, giorod3 approved these changes

2021-08-20 16:37 UTC, merged