SAAS-2299: Plugin to check PrivateLink is used in transfer servers
aquasecurity/cloudsploit pull request #853
Opened 2021-08-15 21:12 UTC by UmairAjmal

2021-08-18 08:25 UTC, AkhtarAmir requested changes

2021-08-18 08:25 UTC, AkhtarAmir commented on plugins/aws/transfer/transferPrivateLinkInUse.js
> +    link: 'https://www.cloudconformity.com/knowledge-base/aws/Transfer/end-point-type.html',
Use aws link

2021-08-20 10:45 UTC, AkhtarAmir approved these changes

2021-08-20 16:33 UTC, giorod3 approved these changes

2021-08-20 16:34 UTC, merged