SAAS-2314: Secure Boot Enabled for GKE Cluster Nodes
aquasecurity/cloudsploit pull request #857
Opened 2021-08-16 18:41 UTC by mehakseedat63

2021-08-18 11:19 UTC, AkhtarAmir requested changes

2021-08-18 11:19 UTC, AkhtarAmir commented on plugins/google/kubernetes/secureBootEnabled.js
> +    more_info: 'Secure Boot features protects your cluster nodes from malware and makes sure the system runs only authentic softwares',
```suggestion
    more_info: 'Secure Boot features protect your cluster nodes from malware and makes sure the system runs only authentic software.',
```

2021-08-18 11:19 UTC, AkhtarAmir commented on plugins/google/kubernetes/secureBootEnabled.js
> +    description: 'Ensures all Kubernetes cluster nodes have secure boot feature enabled',
```suggestion
    description: 'Ensures all Kubernetes cluster nodes have secure boot feature enabled.',
```

2021-08-18 11:19 UTC, AkhtarAmir commented on plugins/google/kubernetes/secureBootEnabled.js
> +    recommended_action: 'If you are not using third-party unsigned kernel modules, it is highly recommended to enable Secure Boot for all your GKE cluster nodes',
Change this

2021-08-20 15:04 UTC, AkhtarAmir approved these changes

2021-08-20 16:11 UTC, giorod3 approved these changes

2021-08-20 16:14 UTC, merged