SAAS-2312: Node Encryption Level for  GKE Cluster Nodes
aquasecurity/cloudsploit pull request #858
Opened 2021-08-16 21:48 UTC by mehakseedat63

2021-08-18 11:14 UTC, AkhtarAmir requested changes

2021-08-18 11:14 UTC, AkhtarAmir commented on plugins/google/kubernetes/nodeEncryption.js
> +    recommended_action: 'If you have confidential or sensitive data, it is recommended that you use Customer-Managed Keys to encrypt your GKE cluster nodes',
Change this

2021-08-18 11:14 UTC, AkhtarAmir commented on plugins/google/kubernetes/nodeEncryption.js
> +            default: 'default'
```suggestion
            default: 'cloudcmek'
```

2021-08-20 15:10 UTC, AkhtarAmir approved these changes

2021-08-20 16:08 UTC, giorod3 approved these changes

2021-08-20 16:11 UTC, merged