SAAS-2321: Application Layer Secrets  Encryption Level for GKE Clusters
aquasecurity/cloudsploit pull request #859
Opened 2021-08-16 22:53 UTC by mehakseedat63

2021-08-18 11:06 UTC, AkhtarAmir requested changes

2021-08-18 11:06 UTC, AkhtarAmir commented on plugins/google/kubernetes/clusterEncryption.js
> +                                currentEncryptionLevel = helpers.getProtectionLevel(cryptoKey, helpers.PROTECTION_LEVELS);
remove this check

2021-08-18 11:06 UTC, AkhtarAmir commented on plugins/google/kubernetes/clusterEncryption.js
> +                            helpers.addResult(results, 0,
```suggestion
                        }

                        let currentEncryptionLevelStr = helpers.PROTECTION_LEVELS[currentEncryptionLevel];

                        if (currentEncryptionLevel >= desiredEncryptionLevel) {
                            helpers.addResult(results, 0,
```

2021-08-20 15:01 UTC, AkhtarAmir approved these changes

2021-08-20 16:03 UTC, giorod3 commented on plugins/google/kubernetes/clusterEncryption.js
> +                'cloudhsm: customer managed HSM ecnryption key, external: imported or externally managed key',
```suggestion
                'cloudhsm: customer managed HSM encryption key, external: imported or externally managed key',
```

2021-08-20 16:06 UTC, giorod3 approved these changes

2021-08-20 16:06 UTC, merged