SAAS-2468: Google Compute Engine Instance Maintenance Behavior
aquasecurity/cloudsploit pull request #871
Opened 2021-08-29 22:42 UTC by mehakseedat63

2021-09-13 09:30 UTC, AkhtarAmir requested changes

2021-09-13 09:30 UTC, AkhtarAmir commented on plugins/google/compute/instanceMaintenanceBehavior.js
> +    description: 'Ensure that On Host Maintenance configuration is set to Migrate for VM instances.',
```suggestion
    description: 'Ensure that "On Host Maintenance" configuration is set to Migrate for VM instances.',
```

2021-09-13 09:30 UTC, AkhtarAmir commented on plugins/google/compute/instanceMaintenanceBehavior.js
> +    more_info: "When Google Compute Engine performs regular maintenance of its infrastructure it live migrate your VM instances to other hardware if you configured the instance's availability policy
```suggestion
    more_info: "When Google Compute Engine performs regular maintenance of its infrastructure, it migrates your VM instances to other hardware if you have configured the instance's availability policy to use live migration. This prevents your applications from experiencing disruptions during these events.",
```

2021-09-13 09:34 UTC, AkhtarAmir commented
Can you fix linting issues?

2021-09-14 10:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=871) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=871) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: mehakseedat63<br/>:x: AkhtarAmir<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=871) it.</sub>

2021-09-15 10:55 UTC, AkhtarAmir approved these changes

2021-09-30 10:19 UTC, AkhtarAmir commented on plugins/google/compute/instanceMaintenanceBehavior.js
> +                    if (instance.scheduling && instance.scheduling.onHostMaintenance && instance.scheduling.onHostMaintenance == 'MIGRATE') {
```suggestion
                    if (instance.scheduling && instance.scheduling.onHostMaintenance && instance.scheduling.onHostMaintenance.toUpperCase() == 'MIGRATE') {
```

2021-09-30 10:20 UTC, dipsubha06 approved these changes

2021-09-30 10:21 UTC, merged