SAAS-2470: Google Compute Engine Instance Preemptibility Disabled
aquasecurity/cloudsploit pull request #873
Opened 2021-08-29 22:43 UTC by mehakseedat63

2021-09-13 08:58 UTC, AkhtarAmir requested changes

2021-09-13 08:58 UTC, AkhtarAmir commented on exports.js
> +        'instancePreemptibilityDisabled' : require(__dirname + '/plugins/google/compute/instancePreemptibilityDisabled.js'),
```suggestion
        'instancePreemptibility'        : require(__dirname + '/plugins/google/compute/instancePreemptibility.js'),
```

2021-09-13 08:58 UTC, AkhtarAmir commented on plugins/google/compute/instancePreemptibilityDisabled.js
> +                    }
```suggestion
                    if (instance.scheduling && instance.scheduling.preemptible) {
                        helpers.addResult(results, 2,
                            'VM Instance is preemptible', region, resource);
                    } else {
                        helpers.addResult(results, 0,
                            'VM Instance is not preemptible', region, resource);
                    }
```

2021-09-14 10:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=873) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=873) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=873) it.</sub>

2021-09-15 10:52 UTC, AkhtarAmir approved these changes

2021-09-30 10:16 UTC, dipsubha06 approved these changes

2021-09-30 10:16 UTC, merged