SAAS-2472: Google Compute Engine OS Login 2FA Enabled
aquasecurity/cloudsploit pull request #878
Opened 2021-08-31 22:16 UTC by mehakseedat63

2021-09-13 09:48 UTC, AkhtarAmir requested changes

2021-09-13 09:48 UTC, AkhtarAmir commented on plugins/google/compute/osLogin2FAEnabled.js
> +                    }
```suggestion

                            isEnabled = true;
                        }
                    }

                    if (isEnabled) {
                        helpers.addResult(results, 0,
                            'OS Login 2FA is enabled for the the instance', region, resource);
                    } else {
                        helpers.addResult(results, 2,
                            'OS Login 2FA is not enabled for the the instance', region, resource);
                    }
```

2021-09-13 09:48 UTC, AkhtarAmir commented on plugins/google/compute/osLogin2FAEnabled.js
> +                    if (instance.metadata && instance.metadata.items && instance.metadata.items.length) {
Shouldn't we check enable-os-login-2fa only?

2021-09-14 10:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=878) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=878) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=878) it.</sub>

2021-09-15 10:40 UTC, AkhtarAmir approved these changes

2021-09-30 10:07 UTC, dipsubha06 approved these changes

2021-09-30 10:10 UTC, merged