SAAS-2475: Google Cloud Storage Bucket Lifecycle Configured
aquasecurity/cloudsploit pull request #881
Opened 2021-09-02 18:43 UTC by mehakseedat63

2021-09-13 08:46 UTC, AkhtarAmir requested changes

2021-09-13 08:46 UTC, AkhtarAmir commented on plugins/google/storage/bucketLifecycleConfigured.js
> +                if (bucket.name) {
```suggestion
            buckets.data.forEach(bucket => {
                if (bucket.name) {
```

2021-09-13 08:46 UTC, AkhtarAmir commented on plugins/google/storage/bucketLifecycleConfigured.js
> +                    if (bucket.lifecycle && Object.keys(bucket.lifecycle).length) {
```suggestion
                    if (bucket.lifecycle && bucket.lifecycle.rule && bucket.lifecycle.rule.length) {
```

2021-09-14 10:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=881) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=881) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: mehakseedat63<br/>:x: AkhtarAmir<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=881) it.</sub>

2021-09-30 09:57 UTC, AkhtarAmir commented on plugins/google/storage/bucketLifecycleConfigured.js
> +                        helpers.addResult(results, 0, 'Bucket has lifecycle management configuration.', region, resource);
```suggestion
                        helpers.addResult(results, 0, 'Bucket has lifecycle management configured', region, resource);
```

2021-09-30 09:58 UTC, AkhtarAmir commented on plugins/google/storage/bucketLifecycleConfigured.js
> +                        helpers.addResult(results, 2, 'Bucket has no lifecycle management configuration.', region, resource);
```suggestion
                        helpers.addResult(results, 2, 'Bucket does not have lifecycle management configured', region, resource);
```

2021-09-30 10:00 UTC, AkhtarAmir commented on plugins/google/storage/bucketLifecycleConfigured.spec.js
> +                expect(results[0].message).to.include('Bucket has no lifecycle management configuration');
```suggestion
                expect(results[0].message).to.include('Bucket does not have lifecycle management configured');
```

2021-09-30 10:01 UTC, AkhtarAmir commented on plugins/google/storage/bucketLifecycleConfigured.spec.js
> +                expect(results[0].message).to.include('Bucket has lifecycle management configuration');
```suggestion
                expect(results[0].message).to.include('Bucket has lifecycle management configured');
```

2021-09-30 10:01 UTC, dipsubha06 approved these changes

2021-09-30 10:02 UTC, AkhtarAmir approved these changes

2021-09-30 10:03 UTC, merged