SAAS-2473: Google BigQuery Tables CMK Encrypted
aquasecurity/cloudsploit pull request #883
Opened 2021-09-04 12:42 UTC by mehakseedat63

2021-09-13 10:02 UTC, AkhtarAmir requested changes

2021-09-13 10:02 UTC, AkhtarAmir commented on plugins/google/bigquery/tablesCMKEncrypted.js
> +        desired_encryption_level: {
```suggestion
        bigquery_tables_encryption_protection_level: {
```

2021-09-13 10:02 UTC, AkhtarAmir commented on plugins/google/bigquery/tablesCMKEncrypted.js
> +        let desiredEncryptionLevelStr = settings.desired_encryption_level || this.settings.desired_encryption_level.default;
```suggestion
        let desiredEncryptionLevelStr = settings.bigqury_tables_encryption_protection_level || this.settings.bigqury_tables_encryption_protection_level.default;
```

2021-09-14 10:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=883) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=883) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=883) it.</sub>

2021-09-15 10:39 UTC, AkhtarAmir approved these changes

2021-09-30 09:45 UTC, dipsubha06 commented on plugins/google/bigquery/tablesCMKEncrypted.js
> +    description: 'Ensure that BigQuery dataset tables are encrypted using Customer-Managed Keys (CMKs).',
```suggestion
    description: 'Ensure that BigQuery dataset tables are encrypted using desired encryption protection level',
```

2021-09-30 09:45 UTC, dipsubha06 approved these changes

2021-09-30 09:46 UTC, merged