SAAS-2474: Google Cloud SQL SQL CMK Encryption
aquasecurity/cloudsploit pull request #884
Opened 2021-09-04 13:25 UTC by mehakseedat63

2021-09-13 09:57 UTC, AkhtarAmir requested changes

2021-09-13 09:57 UTC, AkhtarAmir commented on plugins/google/sql/sqlCMKEncryption.js
> +        desired_encryption_level: {
```suggestion
        sql_encryption_protection_level: {
```

2021-09-13 09:57 UTC, AkhtarAmir commented on plugins/google/sql/sqlCMKEncryption.js
> +        let desiredEncryptionLevelStr = settings.desired_encryption_level || this.settings.desired_encryption_level.default;
```suggestion
        let desiredEncryptionLevelStr = settings.sql_encryption_protection_level || this.settings.sql_encryption_protection_level.default;
```

2021-09-13 09:57 UTC, AkhtarAmir commented on plugins/google/sql/sqlCMKEncryption.js
> +                        if (sqlInstance.instanceType && sqlInstance.instanceType.toUpperCase() === 'READ_REPLICA_INSTANCE') return;
```suggestion
                    sqlInstances.data.forEach(sqlInstance => {
                        if (sqlInstance.instanceType && sqlInstance.instanceType.toUpperCase() === 'READ_REPLICA_INSTANCE') return;
```

2021-09-13 09:59 UTC, AkhtarAmir requested changes

2021-09-13 09:59 UTC, AkhtarAmir commented on plugins/google/sql/sqlCMKEncryption.js
> +                    });
```suggestion
                                region, resource);
                        }
                    });
```

2021-09-14 10:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=884) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=884) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=884) it.</sub>

2021-09-15 10:35 UTC, AkhtarAmir approved these changes

2021-09-28 18:07 UTC, giorod3 commented on plugins/google/sql/sqlCMKEncryption.js
> +    description: 'Ensure that Cloud SQL instances are encrypted using Cutomer Managed Keys (CMKs).',
```suggestion
    description: 'Ensure that Cloud SQL instances are encrypted using Customer Managed Keys (CMKs).',
```

2021-09-28 18:07 UTC, giorod3 approved these changes

2021-09-28 18:09 UTC, merged