SAAS-2476: Google Cloud Storage Bucket Encryption
aquasecurity/cloudsploit pull request #885
Opened 2021-09-04 14:37 UTC by mehakseedat63

2021-09-13 09:54 UTC, AkhtarAmir requested changes

2021-09-13 09:54 UTC, AkhtarAmir commented on exports.js
> +        'bucketEncryption'                 : require(__dirname + '/plugins/google/storage/bucketEncryption.js'),
```suggestion
        'bucketEncryption'               : require(__dirname + '/plugins/google/storage/bucketEncryption.js'),
```

2021-09-13 09:54 UTC, AkhtarAmir commented on plugins/google/storage/bucketEncryption.js
> +                            let resource = helpers.createResourceName('b', bucket.name);
```suggestion
                        buckets.data.forEach(bucket => {
                            if (!bucket.name) return;
                            
                            bucketFound = true;
                            let resource = helpers.createResourceName('b', bucket.name);
```

2021-09-13 09:54 UTC, AkhtarAmir commented on plugins/google/storage/bucketEncryption.js
> +                    if (buckets && buckets.data) {
```suggestion
                    }

                    var bucketFound = false;
                    if (buckets && buckets.data) {
```

2021-09-13 09:54 UTC, AkhtarAmir commented on plugins/google/storage/bucketEncryption.js
> +                    }
```suggestion
                    }

                    if (!bucketFound) {
                        helpers.addResult(results, 0, 'No storage buckets found', region);
                    }
```

2021-09-14 10:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=885) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=885) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=885) it.</sub>

2021-09-15 10:32 UTC, AkhtarAmir approved these changes

2021-09-28 18:13 UTC, giorod3 approved these changes

2021-09-28 18:13 UTC, giorod3 approved these changes

2021-09-28 18:14 UTC, merged