SAAS-2594: GCP IAM Service Account Token Creator
aquasecurity/cloudsploit pull request #889
Opened 2021-09-11 21:57 UTC by mehakseedat63

2021-09-13 08:54 UTC, AkhtarAmir requested changes

2021-09-13 08:54 UTC, AkhtarAmir commented on plugins/google/iam/serviceAccountTokenCreator.js
> +                        let resource = helpers.createResourceName('serviceAccountTokenCreator', accountName, project);
```suggestion
                        let memberType = member.startsWith('serviceAccount') ? 'serviceAccounts' : 'users');
                        let resource = helpers.createResourceName(memberType, accountName, project);
```

2021-09-14 10:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=889) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=889) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=889) it.</sub>

2021-09-15 10:33 UTC, AkhtarAmir approved these changes

2021-09-30 09:30 UTC, dipsubha06 commented on plugins/google/iam/serviceAccountTokenCreator.js
> +
```suggestion
```

2021-09-30 09:32 UTC, dipsubha06 approved these changes

2021-09-30 09:32 UTC, merged