SAAS-2595: GCP IAM Member Admin
aquasecurity/cloudsploit pull request #890
Opened 2021-09-11 22:24 UTC by mehakseedat63

2021-09-13 08:36 UTC, AkhtarAmir requested changes

2021-09-13 08:36 UTC, AkhtarAmir commented on plugins/google/iam/memberAdmin.js
> +                        let resource = helpers.createResourceName('serviceAccounts', accountName, project);
Member can be a user or serviceAccount. We should check `memberType = member.startsWith('serviceAccount') ? 'serviceAccounts' : 'users';` and use this type in createResourceName function

2021-09-13 08:36 UTC, AkhtarAmir commented on plugins/google/iam/memberAdmin.js
> +                if (roleBinding.role === 'roles/editor' || roleBinding.role === 'roles/viewer' || roleBinding.role === 'roles/owner') {
```suggestion
                if (roleBinding.role && ['roles/editor', 'roles/viewer', 'roles/owner'].includes(roleBinding.role)) {
```

2021-09-14 10:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=890) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=890) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=890) it.</sub>

2021-09-15 10:33 UTC, AkhtarAmir approved these changes

2021-09-29 10:01 UTC, dipsubha06 approved these changes

2021-09-29 10:01 UTC, merged