SAAS-2597: GCP VPC Network Firewall Logging Metadata
aquasecurity/cloudsploit pull request #892
Opened 2021-09-12 12:05 UTC by mehakseedat63

2021-09-13 08:10 UTC, AkhtarAmir requested changes

2021-09-13 08:10 UTC, AkhtarAmir commented on plugins/google/vpcnetwork/firewallLoggingMetadata.js
> +    more_info: 'You can significantly reduce the size of your log files and optimize storage costs by not including metadata, By default, metadata is included in firewall rule log files.',
```suggestion
    more_info: 'You can significantly reduce the size of your log files and optimize storage costs by not including metadata. By default, metadata is included in firewall rule log files.',
```

2021-09-13 08:10 UTC, AkhtarAmir commented on plugins/google/vpcnetwork/firewallLoggingMetadata.js
> +            }
```suggestion
            if (!firewalls || firewalls.err || !firewalls.data) {
                helpers.addResult(results, 3, 'Unable to query firewall rules', region, null, null, firewalls.err);
                return rcb();
            }
```

2021-09-13 08:10 UTC, AkhtarAmir commented on plugins/google/vpcnetwork/firewallLoggingMetadata.js
> +                    loggedMetadataVPCs.push(firewall.network);
```suggestion
                if (!firewall.disabled && firewall.logConfig && firewall.logConfig.enable && firewall.logConfig.metadata == 'INCLUDE_ALL_METADATA' && firewall.network && !loggedMetadataVPCs.includes(firewall.network)) {
                    loggedMetadataVPCs.push(firewall.network);
```

2021-09-13 08:10 UTC, AkhtarAmir commented on plugins/google/vpcnetwork/firewallLoggingMetadata.js
> +                if (loggedMetadataVPCs.includes(network.selfLink)){
```suggestion
                if (network.selfLink && loggedMetadataVPCs.includes(network.selfLink)){
```

2021-09-13 08:10 UTC, AkhtarAmir commented on plugins/google/vpcnetwork/firewallLoggingMetadata.js
> +    recommended_action: 'Create Cloud DNS Server Policy with logging enabled for VPC Networks',
This doesn't seem right

2021-09-14 10:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=892) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=892) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=892) it.</sub>

2021-09-15 10:15 UTC, AkhtarAmir approved these changes

2021-09-29 09:49 UTC, dipsubha06 approved these changes

2021-09-29 09:49 UTC, merged