SAAS-3063: Added Timestream Databases Encrypted Plugin
aquasecurity/cloudsploit pull request #968
Opened 2021-11-12 13:29 UTC by sadeed12345

2021-11-13 17:36 UTC, sadeed12345 commented on plugins/aws/timestreamwrite/timestreamDatabaseEncrypted.js
> +
```suggestion
```

2021-11-24 08:52 UTC, sadeed12345 commented on plugins/aws/timestreamwrite/timestreamDatabaseEncrypted.spec.js
> +
```suggestion
```

2021-11-24 08:52 UTC, sadeed12345 commented on plugins/aws/timestreamwrite/timestreamDatabaseEncrypted.spec.js
> +
```suggestion
```

2021-11-24 08:53 UTC, sadeed12345 commented on plugins/aws/timestreamwrite/timestreamDatabaseEncrypted.spec.js
> +
```suggestion
```

2021-11-25 08:46 UTC, dipsubha06 commented on plugins/aws/timestreamwrite/timestreamDatabaseEncrypted.js
> +                            region, kmsKeyId);
```suggestion
                            region, database.KmsKeyId);
```

2021-11-25 08:49 UTC, dipsubha06 requested changes

2021-11-25 08:49 UTC, dipsubha06 commented on plugins/aws/timestreamwrite/timestreamDatabaseEncrypted.spec.js
> +            const cache = createCache([listDatabases[0]], listKeys, describeKey[1]);
Here the keys are different in listDatabases[0] and describeKey[1]. Please check.

2021-11-25 08:49 UTC, dipsubha06 commented on plugins/aws/timestreamwrite/timestreamDatabaseEncrypted.spec.js
> +            "KmsKeyId": "arn:aws:kms:us-east-1:000011112222:key/b6d7913b-5604-47c5-8291-8270a1abab58",
The key arn is different than all other arns.

2021-11-26 06:30 UTC, dipsubha06 approved these changes

2021-11-26 09:49 UTC, merged