SAAS-3064: Added ECR Repository Encrypted Plugin
aquasecurity/cloudsploit pull request #970
Opened 2021-11-13 17:18 UTC by sadeed12345

2021-11-22 10:29 UTC, sadeed12345 commented on plugins/aws/ecr/ecrRepositoryEncrypted.spec.js
> +            const cache = createCache(null, null, null, { message: "Unable to list Timestream Databases encryption" });
```suggestion
            const cache = createCache(null, null, null, { message: "Unable to list ECR Repository encryption" });
```

2021-11-24 08:44 UTC, sadeed12345 commented on plugins/aws/ecr/ecrRepositoryEncrypted.js
> +
```suggestion
```

2021-11-25 08:38 UTC, dipsubha06 commented on plugins/aws/ecr/ecrRepositoryEncrypted.js
> +                if (repository.encryptionConfiguration.encryptionType &&
```suggestion
                if ( repository.encryptionConfiguration &&
                repository.encryptionConfiguration.encryptionType &&
```

2021-11-25 08:44 UTC, dipsubha06 requested changes

2021-11-25 08:44 UTC, dipsubha06 commented on plugins/aws/ecr/ecrRepositoryEncrypted.js
> +                        region, resource);
should not we have continue here? If this flow goes below currentEncryptionLevel value wont be set and result can be something unexpected.

2021-11-25 12:56 UTC, AkhtarAmir commented on exports.js
> +        'ecrRepositoryEncrypted'           : require(__dirname + '/plugins/aws/ecr/ecrRepositoryEncrypted.js'),
```suggestion
        'ecrRepositoryEncrypted'         : require(__dirname + '/plugins/aws/ecr/ecrRepositoryEncrypted.js'),
```

2021-11-25 12:56 UTC, AkhtarAmir commented on exports.js
> +        'ecrRepositoryEncrypted'         : require(__dirname + '/plugins/aws/ecr/ecrRepositoryEncrypted.js'),
```suggestion
        'ecrRepositoryEncrypted'        : require(__dirname + '/plugins/aws/ecr/ecrRepositoryEncrypted.js'),
```

2021-11-25 12:57 UTC, AkhtarAmir commented on plugins/aws/ecr/ecrRepositoryEncrypted.js
> +    description: 'Ensures that the ECR Repository is Encrypted',
```suggestion
    description: 'Ensure that the data in ECR repository is encrypted using desired encryption level.',
```

2021-11-25 13:01 UTC, AkhtarAmir commented on plugins/aws/ecr/ecrRepositoryEncrypted.js
> +    more_info: 'Amazon ECR Repository encrypts your data with AWS-manager sse keys by default.' +
```suggestion
    more_info: 'Amazon ECR encrypts your images stored in the repository with AWS-managed KMS keys by default.' +
```

2021-11-25 13:01 UTC, AkhtarAmir commented on plugins/aws/ecr/ecrRepositoryEncrypted.js
> +    description: 'Ensure that the data in ECR repository is encrypted using desired encryption level.',
```suggestion
    description: 'Ensure that the images in ECR repository are encrypted using desired encryption level.',
```

2021-11-25 13:03 UTC, AkhtarAmir commented on plugins/aws/ecr/ecrRepositoryEncrypted.js
> +            description: 'In order (lowest to highest) sse=AWS-managed AES256;awskms=AWS-managed KMS; awscmk=Customer managed KMS; externalcmk=Customer managed externally sourced KMS; cloudhsm=Custom
```suggestion
            description: 'In order (lowest to highest) awskms=AWS-managed KMS; awscmk=Customer managed KMS; externalcmk=Customer managed externally sourced KMS; cloudhsm=Customer managed CloudHSM sourced KMS',
```

2021-11-25 13:04 UTC, AkhtarAmir commented on plugins/aws/ecr/ecrRepositoryEncrypted.js
> +                helpers.addResult(results, 0, 'No ECR Repository  found', region);
```suggestion
                helpers.addResult(results, 0, 'No ECR repositories found', region);
```

2021-11-25 13:04 UTC, AkhtarAmir commented on plugins/aws/ecr/ecrRepositoryEncrypted.js
> +                helpers.addResult(results, 3, `Unable to query ECR Repository: ${helpers.addError(describeRepositories)}`, region);
```suggestion
                helpers.addResult(results, 3, `Unable to query ECR repositories: ${helpers.addError(describeRepositories)}`, region);
```

2021-11-25 13:08 UTC, AkhtarAmir commented on plugins/aws/ecr/ecrRepositoryEncrypted.js
> +    more_info: 'Amazon ECR encrypts your images stored in the repository with AWS-managed KMS keys by default.' +
```suggestion
    more_info: 'By default, Amazon ECR uses server-side encryption with Amazon S3-managed encryption keys which encrypts your data at rest using an AES-256 encryption algorithm.' +
```

2021-11-25 13:09 UTC, AkhtarAmir commented on plugins/aws/ecr/ecrRepositoryEncrypted.js
> +            default: 'awscmk'
```suggestion
            name: 'ECR Repository Encryption',
            description: 'In order (lowest to highest) sse=AES-256; awskms=AWS-managed KMS; awscmk=Customer managed KMS; externalcmk=Customer managed externally sourced KMS; cloudhsm=Customer managed CloudHSM sourced KMS',
            regex: '^(sse|awskms|awscmk|externalcmk|cloudhsm)$',
            default: 'awscmk'
```

2021-11-25 13:10 UTC, AkhtarAmir commented on plugins/aws/ecr/ecrRepositoryEncrypted.js
> +                        continue;
```suggestion
```

2021-11-25 13:16 UTC, AkhtarAmir approved these changes

2021-11-26 06:28 UTC, dipsubha06 approved these changes

2021-11-26 09:45 UTC, merged