SAAS-3071: Added MQ Broker Encrypted Plugin
aquasecurity/cloudsploit pull request #973
Opened 2021-11-15 11:47 UTC by sadeed12345

2021-11-24 08:40 UTC, sadeed12345 commented on plugins/aws/mq/mqBrokerEncrypted.js
> +
```suggestion
```

2021-11-24 08:40 UTC, sadeed12345 commented on plugins/aws/mq/mqBrokerEncrypted.js
> +
```suggestion
```

2021-11-24 08:41 UTC, sadeed12345 commented on plugins/aws/mq/mqBrokerEncrypted.js
> +
```suggestion
```

2021-11-25 08:23 UTC, dipsubha06 requested changes

2021-11-25 08:23 UTC, dipsubha06 commented on plugins/aws/mq/mqBrokerEncrypted.spec.js
> +            const cache = createCache([listBrokers[1]],listKeys, [describeBroker[0]], describeKey[1]);
describeBroker[0] has a different key which is not there in describeKey or listKeys. is this test working as expected if so how?

2021-11-25 12:19 UTC, AkhtarAmir commented on plugins/aws/mq/mqBrokerEncrypted.js
> +            name: 'MQ Broker Encrypted',
```suggestion
            name: 'MQ Broker Target Encryption Level',
```

2021-11-25 12:19 UTC, AkhtarAmir commented on plugins/aws/mq/mqBrokerEncrypted.js
> +
```suggestion
```

2021-11-26 06:25 UTC, dipsubha06 approved these changes

2021-11-26 10:33 UTC, dipsubha06 approved these changes

2021-11-26 10:34 UTC, merged