SAAS-3099: Added AWS WAF plugin
aquasecurity/cloudsploit pull request #989
Opened 2021-11-22 09:32 UTC by m-nouman-suleman

## Task
https://scalock.atlassian.net/jira/software/c/projects/SAAS/boards/151?modal=detail&selectedIssue=SAAS-3099&assignee=60d20746a174630070913561

## Desciption
- Added AWS WAF plugin

2021-11-22 09:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=989) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/cloudsploit?pullRequest=989) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/cloudsploit?pullRequest=989) it.</sub>

2021-11-22 09:40 UTC, AkhtarAmir commented on plugins/aws/elb/elbWafEnabled.js
> +            if (listWebACLs.err || !listWebACLs.data) {
```suggestion
            if (!listWebACLs) return rcb();

            if (listWebACLs.err || !listWebACLs.data) {
```

2021-12-21 13:29 UTC, AkhtarAmir requested changes

2021-12-21 13:29 UTC, AkhtarAmir commented on plugins/aws/waf/wafInUse.js
> +    more_info: 'Using WAF for your web application running in AWS environment against common web-based attacks, SQL injection attacks, DDOS attacks and more.',
```suggestion
    more_info: 'Using WAF for your web application running in AWS environment can help against common web-based attacks, SQL injection attacks, DDOS attacks and more.',
```

2021-12-21 13:29 UTC, AkhtarAmir commented on plugins/aws/waf/wafInUse.js
> +
```suggestion

            callback(null, results, source);
        });
```

2021-12-21 13:29 UTC, AkhtarAmir commented on plugins/aws/waf/wafInUse.js
> +                helpers.addResult(results, 0, 'WAF is enabled');
```suggestion
                helpers.addResult(results, 2, 'WAF is not enabled', 'global');
            } else {
                helpers.addResult(results, 0, 'WAF is enabled', 'global');
```

2021-12-24 13:59 UTC, AkhtarAmir approved these changes

2021-12-27 09:39 UTC, dipsubha06 approved these changes

2021-12-27 09:39 UTC, merged